### ISSUE TITLE
xinetd: "ProFTPD terminating (signal 11)" when not using "-d 2" or higher

### ISSUE THREAD

**Issue by larsen0815** [proftpd/proftpd#1012]
Hello,

I cannot login via FTP (started through xinetd) anymore:
````
korean:~# ftp localhost
Connected to localhost.
421 Service not available, remote server has closed connection
````

I can only see this in ````daemon.log````:
````
May 11 16:53:58 korean proftpd[25304]: 194.64.x.y - ProFTPD terminating (signal 11)
May 11 16:53:58 korean proftpd[25304]: 194.64.x.y - FTP session closed.
````

The problem started after the server was rebooted (due to some unrelated problem). No change has been made to ProFTPd before (at least not that I know of). It's probable that a newer kernel got active (now ````4.15.0-99-generic #100-Ubuntu````).

ProFTPd installation is a default install from Ubuntu Bionic with ProFTPd "1.3.5e-1build1". I have another server with the same problem running Bionic, and a third server *without* a problem running Ubuntu Xenial (1.3.5a-1ubuntu0.1). All of those configurations are managed by Puppet and therefore the same.

Running in standalone mode is ok.

The strange thing is this: When I add "-d 2" or any higher number to the xinetd-configuration, I can connect to ProFTPd! It won't work with "-d 1", though. 
````
server_args = -c /etc/proftpd/proftpd.conf -d 2
````
Also, it will show a line of output:
````
Connected to localhost.
2020-05-11 16:20:18,575 korean.example.com proftpd[18966]: using PCRE 8.39 2016-06-14
Name (localhost:root): 
````

Please find debugging output here: https://pastebin.com/utNaatDU

**Comment by Castaglia** [comment]
Very strange.  This sounds like there's some issue with library or kernel versions on the non-working systems -- not specifically with ProFTPD itself.  The use of `-d2` to make the segfaults no longer occur is very, very odd.

What happens if ProFTPD is run standalone, rather than through `xinetd`?  Do the segfaults still occur?

**Comment by larsen0815** [comment]
No segfaults, running in standalone mode is ok. I'm ok with using standalone mode as a workaround. If you'd like to examine the problem further, I will gladly provide more info or do some tests.

**Comment by Castaglia** [comment]
Since running ProFTPD in standalone mode doesn't segfault, I'm wondering if the issue is with `xinetd` somehow, rather than ProFTPD.  I'm not sure how to investigate that, though.  I'll see what I can find, in terms of debugging `xinetd` issues.

**Comment by Castaglia** [comment]
Nice catch!  I'll update the [ServerType howto](http://www.proftpd.org/docs/howto/ServerType.html) with this hard-earned pearl of wisdom.  Much appreciated!

**Comment by larsen0815** [comment]
Any idea why this might be happening? I assume it might be a problem with the kernel as it started after a reboot. Will test other servers probably tomorrow.

**Comment by Castaglia** [comment]
Perhaps an auto-update of `xinetd` changed how it opens sockets, or maybe the IPv6 setting of the kernel changed?  Nothing in ProFTPD itself changed in this area.

**Comment by larsen0815** [comment]
Reproduced it with another server. Kernel changed at reboot, and it started after that, so it won't be xinetd.

````
Linux hawaii.example.com 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
-->
Linux hawaii.example.com 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
````

Whatever it may be. Closing for now...
