### ISSUE TITLE
Question about sodium support

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1032]
I just have a dumb question about sodium support. In #558 the support for sodium based password storage was discussed. The outcome is a little unclear to me.
In the [release notes to 1.3.6x](http://www.proftpd.org/docs/RELEASE_NOTES-1.3.6d) I can find some mentioning of sodium support.

I built the Debian package w/ libsodium-dev installed. The configure script detects the libsodium:

`checking sodium.h usability... yes`
`checking sodium.h presence... yes`
`checking for sodium.h... yes`

...and in the end the proftpd binary is linked w/ libsodium:

`libtool: link: gcc -Wl,-z -Wl,relro -rdynamic -Wl,-z -Wl,relro .libs/proftpdS.o -o proftpd src/main.o <snip> -lsodium -lcap -lpam ./lib/libltdl/.libs/libltdlc.a -ldl -pthread`

However I'm not sure if this is correct. AFAICT the mod_sql_passwd & mod_sftp modules should have been built w/ sodium support. Indeed "nm -D" shows references to sodium symbols. However neither of these modules is linked w/ that lib. Are here linker flags missing?

Many thanks!

Build log is [here](https://www.hilmar-preusse.de/~pi/proftpd-dfsg_1.3.6c-4_amd64.build).

**Comment by Castaglia** [comment]
This might be related to Issue #964 -- ideally, the libsodium symbols will be part of the main `proftpd` binary/library, but _not_ used directly via modules.  Instead, modules might use ProFTPD symbols, which indirectly lead to/use the libsodium functions.  Does that make sense?

**Comment by hpreusse** [comment]
I did not test 1.3.7rcx for this.
No, it does not really make sense. When building w/ sodium support by installing libsodium-dev, the symbol references are built into mod_sftp.so & mod_sql_passwd.so (checked using nm -D), but they are not built into the proftpd binary (output of nm -D does not change). proftpd then is linked to libsodium w/o using the symbols, mod_sftp.so & mod_sql_passwd.so are not, although they need it. Finally for none of these binaries ldd shows that it need libsodium:
- the modules not b/c they are not linked during compile time
- the proftpd binary (probably) b/c it does not reference the symbols and the compile time linker ignores the request to link.

**Comment by Castaglia** [comment]
I would recommend that you test 1.3.7rc4, please.  That is what will be released as "stable" soon.

**Comment by hpreusse** [comment]
Tested w/ 1.3.7rc4 (tar ball, not git checkout). Things improved a little but, but not fully fixed.

The compile time linker tries to link the following binaries w/ libsodium: `.libs/mod_load.so, .libs/mod_wrap2.so, .libs/mod_sftp.so, .libs/mod_auth_otp.so, .libs/mod_snmp.so, proftpd, ftpdctl, .libs/mod_load.so, .libs/mod_wrap2.so, .libs/mod_sftp.so, .libs/mod_auth_otp.so, .libs/mod_snmp.so`.
However only the mod_sftp.so binary references these symbols and ldd shows a successful link:

`root@rasppi1:~/proftpd-1.3.7rc4# ldd ./contrib/mod_sftp/.libs/mod_sftp.so |grep sod`
`        libsodium.so.23 => /lib/arm-linux-gnueabihf/libsodium.so.23 (0x76eea000)`

I would expect that `mod_sql_passwd.so` also gets linked with libsodium as there are symbols in that binary, which need a loaded libsodium:

`root@rasppi1:~/proftpd-1.3.7rc4# nm -D ./modules/.libs/mod_sql_passwd.so |grep argon`
         `U crypto_pwhash_argon2i`
         `U crypto_pwhash_argon2i_alg_argon2i13`
         `U crypto_pwhash_argon2i_memlimit_interactive`
         `U crypto_pwhash_argon2i_memlimit_sensitive`
         `U crypto_pwhash_argon2i_opslimit_interactive`
         `U crypto_pwhash_argon2i_opslimit_sensitive`

Else I would expect that one can't load mod_sql_passwd w/o loading mod_sftp before.

**Comment by Castaglia** [comment]
@hpreusse can you see if this PR addresses this issue on your build systems?

**Comment by hpreusse** [comment]
I do not really understand your patch, but I can confirm that `/usr/lib/proftpd/mod_sftp.so` & `/usr/lib/proftpd/mod_sql_passwd.so` now are correctly linked w/ libsodium. Many thanks for work!

**Comment by Castaglia** [comment]
Now fixed in master.
