### ISSUE TITLE
Consider to support reproducible build

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1038]
In Debian we'd like to have reproducibly builds: in an unchanged build environment the build should always give the same results, independent of _when_ the build run. This is triggered by a variable called SOURCE_DATE_EPOCH . If it is defined, the build time stamp is replaced by its value.
We have a patch for this currently in our package, which is attached. Consider to apply it to your code for 1.3.7. Thanks!
[reproducible_build.txt](https://github.com/proftpd/proftpd/files/4801335/reproducible_build.txt)

**Comment by Castaglia** [comment]
Personally I think `BUILD_DATE_EPOCH` is a better name, but I see why `SOURCE_DATE_EPOCH` is used; it comes from [here](https://reproducible-builds.org/docs/source-date-epoch/).

**Comment by Castaglia** [comment]
Fixed in master.
