### ISSUE TITLE
Description of the ProFTPD source code

### ISSUE THREAD

**Issue by codianselme** [proftpd/proftpd#1047]
Please, can you help me identify the part of the code that deals with the transport protocol? I am working on a project that aims to modify it, use another transport protocol

**Comment by Castaglia** [comment]
I'm not sure what you mean by "transport protocol" -- ProFTPD supports multiple protocols.

Sounds like you have questions that might be better answered on the ProFTPD [developers mailing list](http://www.proftpd.org/lists.html).

**Comment by codianselme** [comment]
I'm talking about the server, the server uses the TCP transport protocol I believe, I want to use this server but based on another transport protocol

**Comment by Castaglia** [comment]
I don't think that a GitHub issue is the best way to answer your questions on this topic; please use the email list for this.
