### ISSUE TITLE
Configurable support for "weak" TLS security

### ISSUE THREAD

**Issue by dln949** [proftpd/proftpd#1048]
Ubuntu 18.04.2, Proftpd version 1.3.5e, GADMIN-PROFTPD version 0.4.2.  

When I try to connect to proftpd via ftps, I get the error message:
```
SSL routines:SSL_CTX_use_certificate:ca md too weak
```
in the `/var/log/proftpd_tls.log` file:  
```
2020-07-08 01:27:30,860 mod_tls/2.6[21364]: error loading TLSRSACertificateFile '/etc/gadmin-proftpd/certs/cert.pem':
(1) error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
2020-07-08 01:27:30,860 mod_tls/2.6[21364]: error initializing OpenSSL context for this session
2020-07-08 01:27:30,947 mod_tls/2.6[21364]: TLS/TLS-C requested, starting TLS handshake
2020-07-08 01:27:30,963 mod_tls/2.6[21364]: unable to accept TLS connection: protocol error:
(1) error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher
2020-07-08 01:27:30,963 mod_tls/2.6[21364]: SSL_shutdown error: SSL:
(1) error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
2020-07-08 01:27:30,963 mod_tls/2.6[21364]: TLS/TLS-C negotiation failed on control channel
```

As a result, I cannot make a connection.  

I do not know what this means, what I need to do to correct this problem.  

Here is the contents of the config file, and of running proftpd -V:  
```
proftpd -V
Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 5.3.0-7648-generic x86_64]
  Built: Mon Feb 5 2018 23:27:47 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--with-modules=mod_readme' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_tls_memcache:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-IzaTCF/proftpd-dfsg-1.3.5e=. -fstack-protector-strong -Wformat -Werror=format-security -Wall
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS:  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lpam -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncurses support
    + NLS support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

```
Include /etc/proftpd/modules.conf
UseIPv6				on
IdentLookups			off
ServerName			"Debian"
ServerType			standalone
DeferWelcome			off
MultilineRFC2228		on
DefaultServer			on
ShowSymlinks			on
TimeoutNoTransfer		600
TimeoutStalled			600
TimeoutIdle			1200
DisplayLogin                    welcome.msg
DisplayChdir               	.message true
ListOptions                	"-l"
DenyFilter			\*.*/
Port				21
<IfModule mod_dynmasq.c>
</IfModule>
MaxInstances			30
User				proftpd
Group				nogroup
Umask				022  022
AllowOverwrite			on
TransferLog /var/log/proftpd/xferlog
SystemLog   /var/log/proftpd/proftpd.log
<IfModule mod_quotatab.c>
QuotaEngine off
</IfModule>
<IfModule mod_ratio.c>
Ratios off
</IfModule>
<IfModule mod_delay.c>
DelayEngine on
</IfModule>
<IfModule mod_ctrls.c>
ControlsEngine        off
ControlsMaxClients    2
ControlsLog           /var/log/proftpd/controls.log
ControlsInterval      5
ControlsSocket        /var/run/proftpd/proftpd.sock
</IfModule>
<IfModule mod_ctrls_admin.c>
AdminControlsEngine off
</IfModule>
Include /etc/proftpd/conf.d/

<VirtualHost 192.168.1.5>
Port 65535
ServerName "192.168.1.5"
ServerIdent on "system1"
PassivePorts 49152 65534
#MasqueradeAddress None
ServerAdmin dln9@msn.com
Umask 022
TimesGMT off
MaxLoginAttempts 3
TimeoutLogin 300
TimeoutNoTransfer 120
TimeoutIdle 120
User nobody
Group nobody
DirFakeUser on nobody
DirFakeGroup on nobody
DefaultTransferMode binary
AllowForeignAddress off
DeleteAbortedStores off
AllowRetrieveRestart on
AllowStoreRestart on
TransferRate RETR 142
TransferRate STOR 142
TransferRate STOU 142
TransferRate APPE 142
RequireValidShell off
<IfModule mod_tls.c>
TLSEngine on
TLSRequired auth+data
TLSVerifyClient off
TLSLog /var/log/proftpd_tls.log
TLSRSACertificateFile /etc/gadmin-proftpd/certs/cert.pem
TLSRSACertificateKeyFile /etc/gadmin-proftpd/certs/key.pem
TLSCACertificateFile /etc/gadmin-proftpd/certs/cacert.pem
TLSRenegotiate required off
</IfModule>
<IfModule mod_ratio.c>
Ratios off
SaveRatios off
RatioFile "/restricted/proftpd_ratios"
RatioTempFile "/restricted/proftpd_ratios_temp"
CwdRatioMsg "Please upload first!"
FileRatioErrMsg "FileRatio limit exceeded, upload something first..."
ByteRatioErrMsg "ByteRatio limit exceeded, upload something first..."
LeechRatioMsg "Your ratio is unlimited."
</IfModule>
<Limit LOGIN>
  AllowUser system1
  DenyAll
</Limit>

<Anonymous /home/main1/Downloads>
User system1
Group main1
AnonRequirePassword on
MaxClients 10 "The server is full, hosting %m users"
DisplayLogin welcome.msg
DisplayChdir .msg
<Limit LOGIN>
Allow from All
Deny from all
</Limit>
AllowOverwrite on
<Limit LIST NLST  STOR STOU  APPE  RETR  RNFR RNTO  DELE  MKD XMKD SITE_MKDIR  RMD XRMD SITE_RMDIR  MTDM  PWD XPWD  SIZE  STAT  CWD XCWD  CDUP XCUP >
 AllowAll
</Limit>
<Limit SITE  SITE_CHMOD  SITE_CHGRP >
 DenyAll
</Limit>
</Anonymous>

<Directory /home/main1/Downloads>
UserOwner main1
GroupOwner main1
</Directory>
</VirtualHost>
```

**Comment by Castaglia** [comment]
What does `openssl x509 -noout -text < /etc/gadmin-proftpd/certs/cert.pem` show?

**Comment by dln949** [comment]
main1@system1:~$ openssl x509 -noout -text < /etc/gadmin-proftpd/certs/cert.pem
bash: /etc/gadmin-proftpd/certs/cert.pem: Permission denied


Same result if I run as sudo.

**Comment by Castaglia** [comment]
Do you have the `openssl` command-line package/tool installed?  You'll need that for debugging this issue.  Your error message suggests that you do not have that installed.

**Comment by dln949** [comment]
I do:  

openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.6)

**Comment by Castaglia** [comment]
That "permission denied" error is very odd.  What about this, then:
```
$ cp /etc/gadmin-proftpd/certs/cert.pem /tmp/cert.pem
$ cat /tmp/cert.pem
$ openssl x509 -noout -text < /tmp/cert.pem
```
A certificate is public knowledge; posting contents of that `cert.pem` file here should be fine.

**Comment by dln949** [comment]
It worked, here it is:  

main1@system1:~$ openssl x509 -noout -text < /tmp/cert.pem

> main1@system1:~$ openssl x509 -noout -text < /tmp/cert.pem
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 1 (0x1)
        Signature Algorithm: md5WithRSAEncryption
        Issuer: O = Organization name, emailAddress = email@address.com, L = City, ST = Country, C = EN, CN = 192.168.1.5
        Validity
            Not Before: Jul  9 19:20:14 2020 GMT
            Not After : Jun  5 19:20:14 4758 GMT
        Subject: C = EN, ST = Country, O = Organization name, CN = 192.168.1.5
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:d7:ff:24:37:12:01:e2:cd:b4:0c:d3:27:23:ec:
                    f1:5c:40:0f:78:e3:1f:45:fb:91:8d:dd:70:4f:ee:
                    ac:4f:5b:26:ed:b4:c7:96:ca:f3:a8:a4:66:a4:3d:
                    3b:49:2a:6a:36:c7:fd:a6:98:b5:23:b6:00:80:df:
                    94:d8:3a:e3:a0:a4:ce:f3:2b:1b:41:d5:f9:f3:d5:
                    24:84:14:42:5c:5a:38:15:8b:3c:d0:2f:44:0e:63:
                    06:06:57:0e:6e:bd:56:20:d1:ed:42:67:c9:c8:0a:
                    cb:63:e3:c9:cf:db:69:c2:29:6e:72:2b:90:3d:5a:
                    46:6d:42:8f:a6:02:73:c3:51:2c:f5:12:54:a6:55:
                    ca:c1:b1:d6:6b:ff:03:a9:26:28:ce:f4:6e:97:35:
                    82:4e:3c:a4:13:03:2a:6b:15:79:84:82:bd:5c:da:
                    2d:49:00:65:09:73:8f:b4:37:24:1b:44:8a:8a:a4:
                    48:a2:d1:12:2b:c4:db:03:f4:54:aa:b2:f0:e9:ce:
                    ed:18:ba:bc:15:ab:3c:50:83:a0:32:09:7b:c8:60:
                    f3:7e:67:35:65:ba:a8:0f:65:46:78:9f:67:af:65:
                    b8:81:ad:f1:31:20:42:dc:5f:68:7a:e8:98:43:90:
                    d6:74:f9:7a:2a:c0:97:6b:09:f8:b0:65:e9:04:c2:
                    88:e5
                Exponent: 65537 (0x10001)
    Signature Algorithm: md5WithRSAEncryption
         12:d4:de:ed:40:9a:a1:e6:0e:ed:94:1c:a7:64:5c:1c:88:f1:
         0a:49:b4:d6:0b:fd:eb:84:ad:2c:3b:6f:0d:0e:5f:64:99:c4:
         df:64:a7:27:23:10:c1:b8:8c:df:96:f2:c0:c9:2e:6d:de:8f:
         f5:ad:36:46:62:46:80:e9:ab:7e:fb:c9:8d:d3:c0:76:48:6a:
         88:0b:53:22:b7:e6:5c:ab:68:28:f3:15:d7:67:65:23:65:c0:
         57:8a:ba:d8:c8:f8:db:bc:01:a1:79:ab:6b:46:4d:98:53:f5:
         98:9e:fe:f3:10:09:2f:fd:c0:2d:99:a0:bc:d6:a1:77:f0:e8:
         aa:ba:3c:06:b7:3d:91:b7:a7:4a:28:af:54:38:8f:2e:c1:84:
         e2:71:db:ab:9e:37:c8:e1:79:86:78:c7:7d:bf:a3:f0:bd:82:
         01:84:6f:85:84:cc:32:ae:3c:66:91:a8:06:81:1f:a4:7f:1a:
         6f:4c:80:ee:b6:47:7b:53:ae:ae:95:63:dd:16:05:57:be:9a:
         e4:83:35:91:7c:74:2c:30:2b:29:ed:92:b2:2d:ee:0d:63:56:
         11:8e:c7:cd:bf:36:d0:b1:17:40:c0:55:92:21:02:4d:27:96:
         c4:aa:31:78:d3:50:56:40:8b:fd:b6:1a:7b:92:5b:9e:3d:0f:
         ac:86:0c:0b

**Comment by Castaglia** [comment]
Great, thanks.  That confirms/validates my suspicion.  The OpenSSL error message:
```
SSL routines:SSL_CTX_use_certificate:ca md too weak
```
happens because your certificate has an MD5 signature:
```
Signature Algorithm: md5WithRSAEncryption
```
as opposed to an SHA-1 or (better) an SHA-256 signature.

Looks like this is a [known issue](https://bugs.launchpad.net/ubuntu/+source/gadmin-openvpn-server/+bug/1821111) with the `gadmin-*` set of software tools.  The MD5 algorithm is not considered a strong hash/signature algorithm anymore, which is why newer OpenSSL versions error out with certificates using it.

As a workaround, you might try adding this to your `mod_tls` configuration:
```
TLSCipher DEFAULT:@SECLEVEL=0
```

**Comment by dln949** [comment]
Thank you very much.  Sorry, one more question:  

How do I modify the mod_tls configuration?  I don't even know what or where that is.

**Comment by Castaglia** [comment]
Your `mod_tls` configuration is the portion of your ProFTPD config file, `/etc/proftpd/proftpd.conf`, which pertains to the `mod_tls` module:
```
<IfModule mod_tls.c>
TLSEngine on
TLSRequired auth+data
TLSVerifyClient off
TLSLog /var/log/proftpd_tls.log
TLSRSACertificateFile /etc/gadmin-proftpd/certs/cert.pem
TLSRSACertificateKeyFile /etc/gadmin-proftpd/certs/key.pem
TLSCACertificateFile /etc/gadmin-proftpd/certs/cacert.pem
TLSRenegotiate required off
</IfModule>
```
So you could add the `TLSCipher` directive in that section.

However, I am now not sure that the above would work; you may need to edit OpenSSL's system-wide config file, `/etc/ssl/openssl.cnf`, instead.  Add this to the top of that file:
```
openssl_conf = default_conf
```
and then, add this to the end of that file:
```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = ssl_default_sect

[ssl_default_sect]
CipherString = DEFAULT:@SECLEVEL=0
```
See [this discussion](https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level).

**Comment by dln949** [comment]
Thanks.  

I created an alternate openssl.cnf file, and made the changes you described above.  

Sadly, I didn't understand the instructions over at ask ubuntu:  I don't know how to start gadmin-proftpd and specifiy the special environment thing that tell it to look at the openssl.cnf file I created.

**Comment by Castaglia** [comment]
I can't help with that either; general administration questions are outside to the scope of what I generally have time to answer.

**Comment by Castaglia** [comment]
I think, to handle these cases, I may need to support a `TLSOption AllowWeakSecurity` configuration, similar to what was done for `mod_proxy` in https://github.com/Castaglia/proftpd-mod_proxy/commit/628f2b4e0637fc8abdb0d57dcfe81158e25343c7.

**Comment by Castaglia** [comment]
I've just merged a fix to master.  Using the latest ProFTPD code, you can configure this in your `mod_tls` configuration:
```
TLSOptions AllowWeakSecurity
```
which should allow FTPS connections, using that "ca md too weak" CA, to work once more.
