### ISSUE TITLE
Some files below lib/ not deleted / cleaned

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1049]
### What I Did

Run a build in 1.3.7rc5 and a clean afterwards. I noticed that a few files below `lib/` were not deleted.

### What I Expected/Wanted

I'd expect that all generated files below `lib/` are deleted. Currently the `*.lo` files and the `.o` files in `.libs` are not deleted when running `make clean` in top directory.

### ProFTPD Version and Configuration
1.3.7rc5

**Comment by Castaglia** [comment]
@hpreusse Can you provide the `./configure` command you're using?  The files generated (and thus cleaned, or not) will depend on the requested build parameters.

**Comment by hpreusse** [comment]
> @hpreusse Can you provide the `./configure` command you're using? The files generated (and thus cleaned, or not) will depend on the requested build parameters.

Not sure how detailed you like it, here are the configure options. If you need the list of modules too, call back.

CONF_ARGS := --prefix=/usr \
             --with-includes=$(shell pg_config --includedir)$(shell mysql_config --include|sed -e 's/-I/:/g'|sed -e 's/ //') \
             --mandir=/usr/share/man --sysconfdir=/etc/proftpd --localstatedir=/run --libexecdir=/usr/lib/proftpd \
             --enable-sendfile --enable-facl --enable-dso --enable-autoshadow --enable-ctrls \
             --enable-ipv6 --enable-nls --enable-memcache --with-lastlog=/var/log/lastlog --enable-pcre --enable-devel=yes \
             --disable-strip --enable-redis

**Comment by Castaglia** [comment]
OK, so I found the following:
```
$ ./configure --enable-sendfile --enable-facl --enable-dso --enable-autoshadow --enable-ctrls --enable-ipv6 --enable-nls --enable-memcache --enable-pcre --enable-redis
$ make
$ make clean
$ cd lib
find . -type f -name "*.lo" -print
./ccan-json.lo
./glibc-glob.lo
./glibc-hstrerror.lo
./glibc-mkstemp.lo
./hanson-tpl.lo
./openbsd-bcrypt.lo
./openbsd-blowfish.lo
./pr-syslog.lo
./pr_fnmatch.lo
./pwgrent.lo
./sstrncpy.lo
./strsep.lo
./vsnprintf.lo
find . -type f -name "*.o" -print
./.libs/ccan-json.o
./.libs/glibc-glob.o
./.libs/glibc-hstrerror.o
./.libs/glibc-mkstemp.o
./.libs/hanson-tpl.o
./.libs/openbsd-bcrypt.o
./.libs/openbsd-blowfish.o
./.libs/pr-syslog.o
./.libs/pr_fnmatch.o
./.libs/pwgrent.o
./.libs/sstrncpy.o
./.libs/strsep.o
./.libs/vsnprintf.o
```
Does this match what you're seeing?

**Comment by hpreusse** [comment]
Yes, it does. Thanks for response.

**Comment by Castaglia** [comment]
I suspect this is occurring because of [this commit/change](https://github.com/proftpd/proftpd/commit/3b815f3306be378892d3916765659ba88e80952a#diff-2f692b0817f1066c8a87f070e72a67c0), switching from using the compiler directly to using `libtool`.  I should have a fix shortly.

**Comment by Castaglia** [comment]
This should now be fixed in master.
