### ISSUE TITLE
Empty PR_RUN_DIR macro when building ProFTPD 1.3.7 with --localstatedir configure option

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1055]
The newly-released ProFTPD 1.3.7 version fails to build properly, creating an empty `PR_RUN_DIR` directory, when the `--localstatedir` configure option is used.  This caused problems for packaging builds, which often supply all of the necessary configure options.

This is a regression caused by work done for Issue #1034 .

**Comment by Castaglia** [comment]
@pghmcfc Can you help verify that the PR for this issue fixes things for your build?

**Comment by pghmcfc** [comment]
@Castaglia Yes, #1056 works for me.

**Comment by Castaglia** [comment]
@pghmcfc excellent, thanks!
