### ISSUE TITLE
Fix lost in master: Issue #859, #861: Fix handling of CRL lookups

### ISSUE THREAD

**Issue by chrisrd** [proftpd/proftpd#1058]
Git master and v1.3.7 have lost the fixes in commit 81cc5dce4fc0 "Fix handling of CRL lookups" as these were overwritten/reverted by commit fce40d7739d1 "Implement proper SNI support":

```
$ git log --pretty=oneline --abbrev-commit master | grep -E 'fce40d7|81cc5dc'
fce40d7739d1 Issue #850: Implement proper SNI support, where selection of certs, CAs, etc is tied to the SNI.
81cc5dce4fc0 Issue #859, #861: Fix handling of CRL lookups by properly using issuer for lookups, and guarding against null pointers.
```
Commit 81cc5dce4fc0 should be reapplied to master and v1.3.7.

**Comment by Castaglia** [comment]
Thanks!  I've merged your PR, and backported the commit to the 1.3.7 branch.
