### ISSUE TITLE
FTPS data transfers using TLSv1.3 might segfault when session tickets cannot be decrypted

### ISSUE THREAD

**Issue by manuelm** [proftpd/proftpd#1063]
### What I Did

We are seeing crashes in `SSL_SESSION_get_protocol_version`. The backtrace shows `modules/mod_tls.c:6838` (https://github.com/proftpd/proftpd/blob/master/contrib/mod_tls.c#L6838). However I'm not yet able to reproduce it on my own. We are seeing quite a few of these.

Quoting the OpenSSL documentation regarding the decrypt cb: `When the dec_cb callback is invoked, the SSL_SESSION ss has not yet been assigned to the SSL s. The status indicates the result of the ticket decryption. The callback must check the status value before performing any action, as it is called even if ticket decryption fails.`.

And further more: `If status has the value SSL_TICKET_EMPTY or SSL_TICKET_NO_DECRYPT then no session data will be available and the callback must not use the ss argument. `

I assume we are seeing the crashes due to one of these two status values.

### ProFTPD Version and Configuration

ProFTPD 1.3.7a
with OpenSSL 1.1.1g

A snippet of our configuration:
```
  TLSEngine   on
  TLSRequired on
  TLSProtocol ALL -TLSv1 -TLSv1.1
  TLSRSACertificateFile    ...
  TLSRSACertificateKeyFile ...
  TLSCertificateChainFile  ...
  TLSDHParamFile           ...
  TLSCipherSuite EECDH+AESGCM:EDH+AESGCM:EECDH+CHACHA20:EDH+CHACHA20:RSA+AESGCM:EECDH+AES256:EDH+AES256:EECDH+AES128:EDH+AES128:RSA+AES256:!AESCCM:!DSS
  TLSServerCipherPreference on
  # some ftp clients have problems with reusing the session
  TLSOptions NoSessionReuseRequired
  TLSRenegotiate none
```

**Comment by Castaglia** [comment]
Excellent catch!  Can you apply the provided patch/PR, and see if helps reduce/address your segfaults?

**Comment by manuelm** [comment]
LGTM. I've rolled out the patch now.

**Comment by Castaglia** [comment]
Fixed in master, and backported to the 1.3.7 branch.  Thanks!

**Comment by ressit** [comment]
According to my private docker expert,
to have virtual ftp hosts in proftpd standalone mode without switching the 
whole server from debian stable to unstable, you can try to only migrate
proftpd to unstable debian environment using docker-compose,
until a backport to bullseye becomes available.

1. create a backup of your server
2. create a directory for your docker configuration files
`mkdir ~/proftpd`

3. create 2 files, Dockerfile and docker-compose.yml 
with the following content.
Please note that the content needs to be adjusted according to your
current proftpd configuration in /etc/proftpd/*, i.e.
the path to the certificate directories, the path to the ftp root dir,
the passive port range, the range of modules to be installed.
A modified user and group provisioning is not reflected in the example.

```
pushd ~/proftpd
nano docker-compose.yml:
```

```
version: "3.3"
services:
  proftpd:
    build: .
    ports:
      - "0.0.0.0:21:21"
      - "0.0.0.0:30000-30100:30000-30100"
    volumes:
      - <path-to-certificates-directory>:<path-to-certificates-directory>:ro
      - /etc/proftpd:/etc/proftpd:ro
      - <path-to-ftp-root-dir>:/<path-to-ftp-root-dir>
    environment:
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30100
```
	  
`nano Dockerfile:`

```
# syntax=docker/dockerfile:1
FROM debian:bookworm-slim

ENV PASV_ADDRESS= \
    PASV_MIN_PORT=30000 \
    PASV_MAX_PORT=30100

RUN set -x && \
  apt-get update && \
  apt-get install -y \
    ca-certificates \
    proftpd \
    proftpd-mod-crypto \
    proftpd-mod-wrap \
    proftpd-basic && \
  rm -rf /var/lib/apt/lists/*

EXPOSE 21
EXPOSE $PASV_MIN_PORT-$PASV_MAX_PORT

CMD ["/usr/sbin/proftpd", "-n"]
```

4. stop and disable your current proftpd server
```
systemctl stop proftpd
systemctl disable proftpd
```

5. start docker with proftpd standalone server
```
pushd /root/proftpd
docker-compose up --build -d
popd
```

6. do not forget to update the unstable debian in docker sometimes by 
rerunning step 5

**Comment by ressit** [comment]
In case you want to have updates applied to bookworm-slim, i.e. for openssl fixes, add the following line in Dockerfile after 
`apt-get update && \ `
`   apt-get upgrade -y && \`
