### ISSUE TITLE
Support configuring TLS 1.3 cipher suites

### ISSUE THREAD

**Issue by rlaager** [proftpd/proftpd#1084]
ProFTPD should have an option for configuring TLS 1.3 cipher suites. This is different from configuring TLS 1.2 ciphers. That is, OpenSSL does not using the traditional cipher strings to configure TLS 1.3 cipher suites but instead expects them to be configured separately.

For example, my Apache configuration looks like this:
```
SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLCipherSuite TLSv1.3 TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384
```

I'm asking for an equivalent to the latter option.

This was requested by someone else previously in #744, but it was mixed in with another request which became the main focus.

**Comment by Castaglia** [comment]
@rlaager Thanks for the report.  Care to try out https://github.com/proftpd/proftpd/pull/1087, verify that it works as you expect/need?

**Comment by Castaglia** [comment]
This should now be fixed in master.  Thanks!
