### ISSUE TITLE
FTP FEAT command output broken/not RFC compliant

### ISSUE THREAD

**Issue by tstangner** [proftpd/proftpd#1085]
The company I work at utilizes ProFTPD for providing FTP access to some customers. One of those customers reported that his software fails to upload files.

I tried to debug the issue and found out, that the source of the problem seems to be the FEAT command output generated by ProFTPD (1.3.6e, but this also applies to 1.3.7a and the current master branch).

Current FEAT output:
```
FEAT
211-Features:
211-AUTH TLS
211-CCC
211-CLNT
211-EPRT
[...]
211-PROT
211-REST STREAM
211-SIZE
211-SSCN
211-TVFS
211-UTF8
211 End
```

This output is not RFC compliant, see https://tools.ietf.org/html/rfc2389#section-3.2 :
```
  The syntax of other reply lines is
   precisely defined, and if present, MUST be exactly as specified.

        feat-response   = error-response / no-features / feature-listing
        no-features     = "211" SP *TCHAR CRLF
        feature-listing = "211-" *TCHAR CRLF
                          1*( SP feature CRLF )
                          "211 End" CRLF
        feature         = feature-label [ SP feature-parms ]
        feature-label   = 1*VCHAR
        feature-parms   = 1*TCHAR

   Note that each feature line in the feature-listing begins with a
   single space.  That space is not optional, nor does it indicate
   general white space.  This space guarantees that the feature line can
   never be misinterpreted as the end of the feature-listing, but is
   required even where there is no possibility of ambiguity.

   Each extension supported must be listed on a separate line to
   facilitate the possible inclusion of parameters supported by each
   extension command.
```

So each feature line should be preceded by a whitespace character (instead of a 211-code) - this is the very reason why the customers FTP client chokes and fails to upload files.

I checked past commits - prior to commit 780a85eab1c77503b130574c7b12f5ee320d0c28 the FEAT output generated by ProFTPD was correct and in line with the RFC, so this commit broke it.

I also opened a bug report in the bugtracker and attached a proposed fix patch ( http://bugs.proftpd.org/show_bug.cgi?id=4406 ) since i wasn't sure, if this should be reported/handled in the GIT issues or in the bugtracker (or both).

**Comment by Castaglia** [comment]
Could you provide the `proftpd.conf` you're using, please?  I ask because, for example:
```
$ ftp ftp.proftpd.org
220 Welcome to ftp.proftpd.org
Name (ftp.proftpd.org:tj): ftp
331 Anonymous login ok, send your complete email address as your password
Password: 
230 Anonymous access granted, restrictions apply
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> feat
211-Features:
 MDTM
 MFMT
 TVFS
 UTF8
 MFF modify;UNIX.group;UNIX.mode;
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
 LANG en-US*
 SITE MKDIR
 SITE RMDIR
 SITE UTIME
 SITE SYMLINK
 REST STREAM
 SIZE
211 End
```
shows a different response than the one you're showing.

**Comment by Castaglia** [comment]
In particular, I am wondering if your ProFTPD configuration uses:
```
MultilineRFC2228 on
```
anywhere; see the [`MultilineRFC2228`](http://www.proftpd.org/docs/modules/mod_core.html#MultilineRFC2228) directive docs for how this changes response formats.

**Comment by tstangner** [comment]
God, sorry, I feel like an idiot - I tested it with the standard Debian configuration, which indeed enables MultilineRFC2228 by default. Prior to the commit mentioned above ProFTPD didn't use multiline for FEAT apparently, even if MultilineRFC2228 was set to on.

Disabling it of course resolves the problem -> closing issue.

**Comment by Castaglia** [comment]
@hpreusse Can we update/remove that use of `MultilineRFC2228` from the Debian config?

**Comment by hpreusse** [comment]
https://salsa.debian.org/debian-proftpd-team/proftpd/-/commit/171fa0a83e138b1237c9afe09370c54679c1e29e

**Comment by Castaglia** [comment]
Awesome, thanks @hpreusse !
