### ISSUE TITLE
Deprecate MultilineRFC2228 directive

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1089]
The [`MultilineRFC2228`](http://www.proftpd.org/docs/modules/mod_core.html#MultilineRFC2228) directive was added to ProFTPD in [this commit](https://github.com/proftpd/proftpd/commit/b4f9ed3b23221f30be65e61446162df5c3d96e74), which unfortunately does not provide much history/context about _why_ it was added.

As we have seen _e.g._ [here](https://github.com/proftpd/proftpd/issues/1085), the `MultineRFC2228` directive can cause unexpected issues with multiline responses.  As such, I feel it is causing more issues than it solves, and thus the directive will be deprecated.

The 6xx multiline response formats, as described in RFC 2228, can be handled/implemented by modules as they need (_e.g._ `mod_gss`, which uses 6xx responses); there is no need to have such functionality in the core Response API of ProFTPD, where it can affect non-6xx multiline responses unexpectedly.

**Comment by mdell-seradex** [comment]
Note that http://www.proftpd.org/docs/modules/mod_core.html still mentions this directive in a comment.
Perhaps this reference should either be removed or noted that support for that option has been deprecated.

**Comment by Castaglia** [comment]
Thanks; that reference should be updated shortly.
