### ISSUE TITLE
Is proftpd abandonware?

### ISSUE THREAD

**Issue by chrcoluk** [proftpd/proftpd#1095]
No answer to this issue.

https://github.com/proftpd/proftpd/issues/687

A forum that has not been accessible for a long time because of an ancient cert left in place.

**Comment by Castaglia** [comment]
Please keep in mind that this project is maintained by volunteers only, in their spare time.  And right now, it's only _me_ -- and I can only focus on so much at any given time.

https://forums.proftpd.org is now accesible again -- and it was a real pain to restore it.  I'll work on other issues as I can.
