### ISSUE TITLE
Need help changing proftpd server

### ISSUE THREAD

**Issue by codianselme** [proftpd/proftpd#1117]
I noticed that the server is using socket in the inet.c file.
My job is to change the server code to the Quic server code.
When I compile the project, the project does not recognize my code (that of my Quic server, in addition the compilation of the Quic server uses static libraries and is done with the following command
gcc server.c -lpicoquic-core -lpicotls-core -lpicotls-openssl -lssl -lcrypto -ldl -lpthread -L. -I. -o server).
How to take this into account in the ProFTPD project when compiling ?

**Comment by Castaglia** [comment]
Thanks for choosing ProFTPD to try this experiment.  I'm not sure how good of a fit, overall, FTP over QUIC will be -- especially given FTP's protocol for using separate connections (and transmitting addresses/ports) for data transfers.  Also, plain FTP (and even explicit FTPS) does not perform an SSL/TLS handshake on initial connection (unlike HTTP); the SSL/TLS handshake happens later in the connection lifecycle.
