### ISSUE TITLE
Support OpenSSH FIDO security keys in mod_sftp

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1118]
The scope of this feature is to implement support for OpenSSH's FIDO/U2F security keys in `mod_sftp`; see:
* https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f
* https://en.wikipedia.org/wiki/Universal_2nd_Factor

**Comment by Castaglia** [comment]
An interesting consideration with this feature will be supporting the equivalent of OpenSSH's FIDO-related options in its `authorized keys` file format, namely:
* `no-touch-required`: Do not require demonstration of user presence for signatures made using this key. This option only makes sense for the FIDO authenticator algorithms
* `verify-required`: Require that signatures made using this key attest that they verified the user, e.g. via a PIN. This option only makes sense for the FIDO authenticator algorithms

We would like to have equivalent functionality in the [`SFTPAuthorizedUserKeys`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPAuthorizedUserKeys) file.  That file is expected to be in the [RFC 4716](https://datatracker.ietf.org/doc/html/rfc4716) format, which does not have first-class support for such options.  However, it _does_ allow for "private use headers" (see [here](https://datatracker.ietf.org/doc/html/rfc4716#section-3.3.3)), such that custom `x-` prefixed headers, _e.g._ `x-no-touch-required: true`, `x-verify-required: true`, can be used.

**Comment by Castaglia** [comment]
I'll be working on this ticket in stages.  First step is to implement support for the OpenSSH security key messages; I'll be using a Yubikey 5 Nano locally for this.

Once that is working/merged, I'll then start working on the code to handle the "always require touch/verification" options, including in RFC4716 per-key entries.

Last will be the accompanying documentation changes.

**Comment by azurit** [comment]
I'm really looking forward to this!

**Comment by Castaglia** [comment]
OK, I think I'm ready to call this one done!  I'm sure there will be refinements needed going forward, but the bulk of the work is done.
