### ISSUE TITLE
mod_wrap2: bad index in error message

### ISSUE THREAD

**Issue by marcin-gryszkalis** [proftpd/proftpd#1127]
https://github.com/proftpd/proftpd/blob/5bb4f523eaa63a75cb6c8c345eb1d8b855964a35/contrib/mod_wrap2/mod_wrap2.c#L1631

It should be cmd->argv[i] instead of cmd->argv[1].
Check other functions (set_wrapgrouptables, set_wraptables) too.

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!
