### ISSUE TITLE
Support include files in mod_wrap2 allow/deny tables

### ISSUE THREAD

**Issue by ronaldPeer** [proftpd/proftpd#1133]
I am using proftpd 1.3.5a and I am using hosts.allow file to allow IPs I want.
This is working good.

But, we have made some changes and I have created a second file for SSH allow IPs (hosts.allow-ssh).
In hosts.allow we added a row like: SSHD: /etc/hosts.allow-ssh.
So, hosts.allow-ssh is included and all IPs in that file is working too.

And now we try this for proftpd:
proftpd: /etc/hosts.allow-proftpd
But, this is not working, even ignored/not parsed I guess.

As stated in the manual (https://linux.die.net/man/5/hosts.allow) it is a valid pattern.
"A string that begins with a '/' character is treated as a file name. A host name or address is matched if it matches any host name or address pattern listed in the named file. The file format is zero or more lines with zero or more host name or address patterns separated by whitespace. A file name pattern can be used anywhere a host name or address pattern can be used."

But I can't find it in mod_wrap2 docs for example.

How it is supposed to work:
hosts.allow BEFORE:
proftpd: 1.2.3.4
proftpd: 5.6.7.8

hosts.allow AFTER:
proftpd: /etc/hosts.allow-proftpd

hosts.allow-proftpd file:
1.2.3.4
5.6.7.8

Can you please implement this too?

**Comment by Castaglia** [comment]
This is indeed an uninplemented feature in `mod_wrap2`.  It may take me a little while to see how best to implement this.

**Comment by Castaglia** [comment]
Currently, if you attempt to use this include construction, you'd see something like this in the `WrapLog`:
```
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]: checking allow table rules
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]: table daemon list:
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]:   proftpd
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]: table client list:
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]:   /etc/hosts.allow-proftpd
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]: daemon matches 'proftpd'
2021-03-21 13:36:53,362 mod_wrap2/2.0.7[87612]: warning: bad net/mask expression: '/etc/hosts.allow-proftpd'
```
So it _is_ parsed, but largely ignored.

**Comment by Castaglia** [comment]
Fixed in master.

**Comment by ronaldPeer** [comment]
@Castaglia Many thanks for your work on this!
Do you know when a new release is rolling out?

**Comment by ronaldPeer** [comment]
@Castaglia ?
I see on the website the latest release (1.3.7a) is from a year ago and here on GitHub have been a lot of commits/updates since then.
Do you know when there is comming a new version including the fix for this issue?

**Comment by Castaglia** [comment]
Yes, there will be a new release; I'm trying to finish the remaining items I'd like to address for this milestone; see https://github.com/proftpd/proftpd/milestone/4.
