### ISSUE TITLE
local variable unused in some functions

### ISSUE THREAD

**Issue by FloridSleeves** [proftpd/proftpd#1152]
### What I Did

Hi. I'm recently using a tool to check the code of proftpd and find that:

(1) In function sreaddir() in modules/mod_ls.c, local variable 'ssize' is assigned with value:
 ```
 ssize = get_name_max((char *) dirname, dir_fd);
  if (ssize < 1) {
    pr_log_debug(DEBUG1, "get_name_max(%s, %d) = %lu, using %d", dirname,
      dir_fd, (unsigned long) ssize, NAME_MAX_GUESS);
    ssize = NAME_MAX_GUESS;
  }
  **ssize *= ((dsize / 4) + 1);**
```
However, this value are not used in the following code, which means it's an unused value assignment. So I wonder whether it potentially indicates a bug. 

(2) In auth_user() in modules/mod_auth.c, it's the same that variable 'origuser' is assigned with unused value in line 2320:
```
  origuser = user;
```
which potentially means it's intended to be used but is forgotten.

(3) Some function parameters are also unused. While this could implicitly indicate bugs, it could also invoke compiler warnings:

func name | variable name
copy_progress_cb | nwritten
filter_get_cmd_ids | excluded_classes
handle_stacktrace_signal | info
logfmt_json_keycmp | ksz1
logfmt_json_keycmp | ksz2
logfmt_json_keyhash | ksz

### What I Expected/Wanted

Just want to report in case they are signals of bugs. I will appreciate so much if you can take a bit time to confirm them. Also I wonder if I can help to mark really unused parameter with compiler's unused attribute so that they will not invoke warnings.

### ProFTPD Version and Configuration

1.3.8rc1 (git) 
default configuration

Thanks!

**Comment by Castaglia** [comment]
Many of these "unused variable" situations are not bugs, per se -- although compiler/static analysis tools would have you think so.

Instead, many of these are relics from past iterations, changes to the ProFTPD code base over the years.  The `ssize` variable in the `sreaddir()` function, for example, _was_ used, until https://github.com/proftpd/proftpd/commit/d645997b2e0e7d0d8eff5982b7fab231f8624462.  So it can probably be removed now without loss of functionality.

In other cases, the unused variables are present to conform to the API requirements, even if the values are unused.  This is the case for the `origuser` value-argument variable, and for some of the other scenarios.

**Comment by Castaglia** [comment]
We can see that `origuser` is potentially used for logging in these locations:
* https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1020
* https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1155
* https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1166
* https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1174

As with any static analysis tool (including compilers), one has to be make sure that what they are reporting is accurate/correct; sometimes they are wrong, and report false positives.

**Comment by Castaglia** [comment]
I believe these issues are now addressed in the `master` branch on GitHub.  Thanks!

**Comment by FloridSleeves** [comment]
Thanks for your patient confirmation and your insightful suggestions!

**Comment by FloridSleeves** [comment]
> Many of these "unused variable" situations are not bugs, per se -- although compiler/static analysis tools would have you think so.
> 
> Instead, many of these are relics from past iterations, changes to the ProFTPD code base over the years. The `ssize` variable in the `sreaddir()` function, for example, _was_ used, until [d645997](https://github.com/proftpd/proftpd/commit/d645997b2e0e7d0d8eff5982b7fab231f8624462). So it can probably be removed now without loss of functionality.
> 
> In other cases, the unused variables are present to conform to the API requirements, even if the values are unused. This is the case for the `origuser` value-argument variable, and for some of the other scenarios.



> We can see that `origuser` is potentially used for logging in these locations:
> 
> * https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1020
> * https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1155
> * https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1166
> * https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L1174
> 
> As with any static analysis tool (including compilers), one has to be make sure that what they are reporting is accurate/correct; sometimes they are wrong, and report false positives.

Hi! Thanks for your reply. Today I recheck and rethink the _origuser_ variable in function MODRET auth_user(cmd_rec *cmd) and still feel a bit confused.  Because this variable is declared in auth_user(cmd_rec *cmd) as a local variable:

```
MODRET auth_user(cmd_rec *cmd) {
    ...
Line 2387:    const char *denymsg = NULL, *user, *origuser; // here is the declaration of origuser in auth_user()
    ...
Line 2420:    origuser = user; // origuser is set with a value from user, but never been used anymore, and the life cycle of this variable is within function auth_user().
    ...
}

```
Though there is other variable also named _origuser_ in mod_auth.c. They are all local variable in the other corresponding functions. So their use do not refer to the local variable _origuser_ in function auth_user().

However, from other places where a local variable with same name _origuser_ declared, it's indicating the original intention of this variable assignment from `origuser = user`. In another function setup_env() in file mod_auth.c:
```
static int setup_env(pool *p, cmd_rec *cmd, const char *user, char *pass) {
  ...
  const char *defchdir = NULL, *defroot = NULL, *origuser, *sess_ttyname;
  ...
  /********************* Authenticate the user here *********************/
  session.hide_password = TRUE;
  origuser = user; // here origuser is assigned with new value
  c = pr_auth_get_anon_config(p, &user, &ourname, &anonname);
  ...
  if (user == NULL) {
    pr_log_auth(PR_LOG_NOTICE, "USER %s: user is not a UserAlias from %s [%s] "
      "to %s:%i", origuser, session.c->remote_name, // here is the use of origuser in function setup_env()
      pr_netaddr_get_ipstr(session.c->remote_addr),
      pr_netaddr_get_ipstr(session.c->local_addr), session.c->local_port);
    goto auth_failure;
  }
  ...
}
```
In this function setup_env(), after the assignment `origuser = user`, the variable _origuser_ is used in `pr_log_auth()` when there is an auth failure and `user` is NULL resulted from the `pr_auth_get_anon_config()` function. 

And this case is quite similar to the case in auth_user(), in which there is also firstly set `origuser = user` (line 2420), then call `pr_auth_get_anon_config()` (line 2421). The only difference is in auth_user(), when the `user` result from `pr_auth_get_anon_config()` is NULL, there is no log in this case. 

So I'm wondering is it possible that there is originally intended to have a log in auth_user() after the assignment `origuser = user`, to log the case of `user` being NULL after call `pr_auth_get_anon_config()` and it will use the value from `origuser`, but it's just be left out by accident.

Thanks for your patient reading and time for such a long comment :-)
