### ISSUE TITLE
Implement support for user/host combination bans in mod_ban

### ISSUE THREAD

**Issue by FedericoHeichou** [proftpd/proftpd#1170]
In `mod_ban` `MaxLoginAttempts` uses only Host (IP) ban.  
As default the ban is performed inside the VirtualHost.

Is possible to ban a combination user-IP instead of VirtualHost-IP? In my case is not important the VirtualHost used.
I would like to ban a certain combination of user-IP. In this scenario, a banned IP exceeding the `MaxLoginAttempts` with a certain user is banned only for that user, but can perform logins with other users.

If this is not possible, could be implemented in future? Or I need to checkout other solutions?

**Comment by Castaglia** [comment]
This combination of client IP plus username is not currently supported in `mod_ban`; I will look into what it might take to add.

I assume that the use case here is for multiple clients behind some NAT, such that they all look like they come from the same source IP to ProFTPD, trying to login for different users?

**Comment by FedericoHeichou** [comment]
> I assume that the use case here is for multiple clients behind some NAT, such that they all look like they come from the same source IP to ProFTPD, trying to login for different users?

Yes, you are right

**Comment by Castaglia** [comment]
For the case where you want bans to apply across different `<VirtualHost>` sections, you might use the [`BanOptions`](http://www.proftpd.org/docs/contrib/mod_ban.html#BanOptions) directive, like so:
```
# Bans to apply to any/all vhosts
BanOptions MatchAnyServer
```

Now, the next part is how `mod_ban` should know when to create/use a normal user or host ban, _vs_ knowing when to create one of these "user@host" bans.  Any thoughts/ideas on how you'd want to configure this?

**Comment by FedericoHeichou** [comment]
Maybe save the ban with a syntax like `host/user` then when check if a host is authorized to login search for a key with `$host/$user`?
```
tpdctl ban host 1.2.3.4  # bans this source ip
tpdctl ban host 1.2.3.4/dave  # bans this source ip for this user
```

I would think to reuse the "host" implementation in a similar way

**Comment by Castaglia** [comment]
I have an idea for the syntax; that is not the hard part.

The hard part is for `mod_ban` to know when it should create a normal "user" ban, _vs_ creating your requested "host/user" ban.  For example, in the [`BanOnEvent`](http://www.proftpd.org/docs/contrib/mod_ban.html#BanOnEvent) docs,  you can see a table of which types of bans are created for which events.  When should `mod_ban` create a "host/user" ban?

**Comment by FedericoHeichou** [comment]
Ah ok. Something like creating a `MaxLoginAttemptsPerUser`? Actually we have `MaxLoginAttempts` which is `MaxLoginAttemptsPerHost`. Maybe if you want to keep a certain syntax you can rename `MaxLoginAttempts` in `MaxLoginAttemptsPerHost` (and keep `MaxLoginAttempts` as deprecated/alias), in this way both bans a IP but "PerHost" is only IP based, and "PerUser" is "host/user" combination based (for sure only user based is not possible else everyone can lock-out every user they want)

**Comment by Castaglia** [comment]
https://github.com/proftpd/proftpd/pull/1220 implements the requested support.

For `ftpdctl`, you would use _e.g._:
```
ftpdctl ban host dave@1.2.3.4 # bans this user from this source IP
```

And in the `BanOnEvent` directive, you can use your suggested `MaxLoginAttemptsPerUser` event type.

**Comment by Castaglia** [comment]
Implementation merged to master.
