### ISSUE TITLE
AllowGroup OR char limit ~1024

### ISSUE THREAD

**Issue by MightyPrefix** [proftpd/proftpd#1172]
### What I Did
Implemented config for AllowGroup OR group1, group2, ... (with a lot of groups)

Proftp doesn't start and gives error -> Fatal: unknown configuration directive  (and line number at the last group ->)

Now this seems to hit some limit of 1024 chars, i even tested this out by deleting single characters and at some point it works at ~1024. if i add a single char again the same thing happens.

Is it true that there is a limitation to this?
I didn't find it in the doc's or I failed to spot it atleast :/

 Fatal: unknown configuration directive 
### What I Expected/Wanted

Proftp to start.

### ProFTPD Version and Configuration
ProFTPD 1.3.3g

Thanks for help in advance!

Kr,
Prefix

**Comment by Castaglia** [comment]
There is a default buffer size that is used for reading a single line of the config file.  In (much) newer versions of ProFTPD, that buffer size is larger than 1KB; you are using 1.3.3g, which is quite old.  If possible, I'd recommend trying a newer version of ProFTPD first.

**Comment by MightyPrefix** [comment]
Hey, thanks for this answer! I've used a workaround for this issue but indeed the 1KB buffer here was the problem.
I'll be closing this issue.
