### ISSUE TITLE
For someone who is completely new to the linux kernel...and just wants a working SFTP server on a Debian server with check-file extension enabled...

### ISSUE THREAD

**Issue by DumbJoe** [proftpd/proftpd#1180]
How do I install and configure so it happens? The install instructions is ...very vague...and I think I read it requires me to compile the whole thing from source and that you're supposed to do the configurations here somewhere which I have ZERO experience doing. What do I do with the proftpd-1.3.7a.tar.gz.asc file that's in the releases??

I feel like I fell down a long rabbit hole and appeared in a big forest of trees as a little kid with scary monsters roaming about ready to pounce on me if I make the wrong move...

**Comment by Castaglia** [comment]
If possible, the easiest thing to do is install ProFTPD via package, using something like `apt-get`.

**Comment by DumbJoe** [comment]
does that require admin privileges to install?

**Comment by Castaglia** [comment]
Usually it does require admin privileges to install packages, yes.  These packages have hardcoded locations where they install multiple files, and those locations often require `root` permissions to write the files.

**Comment by DumbJoe** [comment]
What if you just installed in your own user space? Is that possible or not and still require root to install even in your own limited standard account?

**Comment by DumbJoe** [comment]
Ok, I found a compile script somewhere and it looks like this:
```
wget -qO ~/proftpd.tar.gz ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6.tar.gz
tar xf ~/proftpd.tar.gz -C ~/
cd proftpd-*
install_user=$(whoami) install_group=$(whoami) ./configure --prefix=$HOME/proftpd --enable-openssl --enable-dso --enable-nls --enable-ctrls --with-shared=mod_ratio:mod_readme:mod_sftp:mod_tls:mod_ban:mod_shaper
make && make install
mkdir -p ~/proftpd/etc/sftp/authorized_keys ~/proftpd/etc/keys ~/proftpd/ssl
cd && rm -rf proftpd-* proftpd.tar.gz
```

These supposedly grabs and tweaks the default settings;
```
wget -qO ~/proftpd/etc/proftpd.conf https://bitbucket.org/feralio/wiki/raw/HEAD/src/wiki/software/proftpd/proftpd.conf
wget -qO ~/proftpd/etc/sftp.conf https://bitbucket.org/feralio/wiki/raw/HEAD/src/wiki/software/proftpd/sftp.conf
wget -qO ~/proftpd/etc/ftps.conf https://bitbucket.org/feralio/wiki/raw/HEAD/src/wiki/software/proftpd/ftps.conf
sed -i 's|/media/DiskID/defaultUser|'$HOME'|g' ~/proftpd/etc/proftpd.conf
sed -i 's|User defaultUser|User '$(whoami)'|g' ~/proftpd/etc/proftpd.conf
sed -i 's|Group defaultGroup|Group '$(whoami)'|g' ~/proftpd/etc/proftpd.conf
sed -i 's|AllowUser defaultUser|AllowUser '$(whoami)'|g' ~/proftpd/etc/proftpd.conf
sed -i 's|/media/DiskID/defaultUser|'$HOME'|g' ~/proftpd/etc/sftp.conf
sed -i 's|Port 23001|Port '$(shuf -i 10001-49999 -n 1)'|g' ~/proftpd/etc/sftp.conf
sed -i 's|/media/DiskID/defaultUser|'$HOME'|g' ~/proftpd/etc/ftps.conf
sed -i 's|Port 23002|Port '$(shuf -i 10001-49999 -n 1)'|g' ~/proftpd/etc/ftps.conf
```

These generates the keys for SFTP and FTPS:
```
ssh-keygen -qt rsa -N '' -f ~/proftpd/etc/keys/sftp_rsa
ssh-keygen -qt dsa -N '' -f ~/proftpd/etc/keys/sftp_dsa
openssl req -new -x509 -nodes -days 365 -subj '/C=GB/ST=none/L=none/CN=none' -newkey rsa:2048 -keyout ~/proftpd/ssl/proftpd.key.pem -out ~/proftpd/ssl/proftpd.cert.pem
```

and this creates the user and password:
```
~/proftpd/bin/ftpasswd --group --name $(whoami) --file ~/proftpd/etc/ftpd.group --gid $(id -g $(whoami)) --member $(whoami)
~/proftpd/bin/ftpasswd --passwd --name $(whoami) --file ~/proftpd/etc/ftpd.passwd --uid $(id -u $(whoami)) --gid $(id -g $(whoami)) --home $HOME/ --shell /bin/false
```

I notice there is no mention of how to configure and get the check file extension working.....unless that's preconfigured ready to go with the above commands?

**Comment by DumbJoe** [comment]
SFTP

start:     `~/proftpd/sbin/proftpd -c ~/proftpd/etc/sftp.conf`
check running:     `cat ~/proftpd/sftp.pid`
stop:     `cat ~/proftpd/sftp.pid | xargs kill`
restart:     `cat ~/proftpd/sftp.pid | xargs kill && sleep 15 && ~/proftpd/sbin/proftpd -c ~/proftpd/etc/sftp.conf`
kill (force stop):     `cat ~/proftpd/sftp.pid | xargs kill -9 && rm -rf ~/proftpd/sftp.pid`

FTPS

start:    `~/proftpd/sbin/proftpd -c ~/proftpd/etc/ftps.conf`
check running:    `cat ~/proftpd/ftps.pid`
stop:    `cat ~/proftpd/ftps.pid | xargs kill`
restart:    `cat ~/proftpd/ftps.pid | xargs kill && sleep 15 && ~/proftpd/sbin/proftpd -c ~/proftpd/etc/ftps.conf`
kill (force stop):    `cat ~/proftpd/ftps.pid | xargs kill -9 && rm -rf ~/proftpd/ftps.pid` 

And this is to get the custom port: `sed -nr 's/^Port (.*)/\1/p' ~/proftpd/etc/sftp.conf` so you can connect with Bitwise as that's the only other known windows client program that supports SFTP with check file extension as apparently you need both supported client and server for this to work....

Hmmm, notice it's pointing to an older version: `ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6.tar.gz` so that should be: `ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.7.a.tar.gz`? And then everything else is correct(Assuming it's preconfigured for check file extension working...)?

**Comment by DumbJoe** [comment]
What's the command to configure check file extension enabled during compile? I read that somewhere and then I can cross reference here and find out if it's got that command or not and if it doesn't then obviously this compile doesn't have check file extension enabled....

**Comment by DumbJoe** [comment]
No one? Huh...damn, this is a tech newbie unfriendly app....

**Comment by Castaglia** [comment]
I wish I could provide better suggestions, but installing and running an FTP server is not easy, even for non-newbies.

**Comment by DumbJoe** [comment]
> 
> 
> I wish I could provide better suggestions, but installing and running an FTP server is not easy, even for non-newbies.
> 
> To answer your question of "is the check-file SFTP extension enabled?", the answer is yes, it is enabled in ProFTPD by default.

Oh, so it's enabled by default!? Well I guess I didn't even need to configure for it then! Spent all that time looking for a way to configure it to be enabled on compile and it's apparently enabled by default anyways....wow....

So aside from that, the download, compile, install and run instructions I found are mint, yes? Or is that for a different setup....? Probably for a different setup because I'm now stuck on `fatal: unknown configuration directive IdentLookups on line 43` of the proftpd.conf file when interchanging the latest 1.3.7a instead of the 1.3.6 that was used which seemed to be disconnect prone every 20 minutes due to some key exchange failure....

Is there any other file hosting servers that has support for check file extension for SFTP enabled by default like this one or can be configured later that is easier to setup and is newb friendly? Or is this the only one that check file extension but isn't newb friendly to install?

**Comment by DumbJoe** [comment]
?

**Comment by Castaglia** [comment]
I don't know about other file hosting servers, so unfortunately cannot provide any advice/suggestions about them.
