### ISSUE TITLE
passive port for data connection duplicated

### ISSUE THREAD

**Issue by mirozitnansky** [proftpd/proftpd#1191]
Hello.

-  ProFTPD Version 1.3.7a on CentOS release 6.3
- multiple virtual servers configured
- TLS and clear FTP on different control ports
- all listening on same external IP address
- downloads utilizing passive mode
- configured PassivePorts 64000 64900
- using SQLlog

We are downloading with multiple clients (5-10) in parallel, hundreds of files in one client session. 
For every file, while largest can be 128KB, new passive data channel is opened.
Whole client download takes 5-15 minutes, depends on client connection.

In system.log we found multiple instances of messages 
{SERVER_IP} is mask for real server IP
{SERVER_NAME} is mask for hostname in logs

2021-03-09 01:46:42,867 {SERVER_NAME} proftpd[10003] {SERVER_IP} (185.103.147.161[185.103.147.161]): SECURITY VIOLATION: Passive connection from foreign IP address 87.197.186.64 rejected (does not match client IP address 185.103.147.161).
2021-03-09 01:46:42,946 {SERVER_NAME} proftpd[10166] {SERVER_IP} (87.197.186.64[87.197.186.64]): SECURITY VIOLATION: Passive connection from foreign IP address 185.103.147.161 rejected (does not match client IP address 87.197.186.64).

2021-03-09 01:55:21,287 {SERVER_NAME} proftpd[10472] {SERVER_IP} (90.176.8.94[90.176.8.94]): SECURITY VIOLATION: Passive connection from foreign IP address 213.81.165.174 rejected (does not match client IP address 90.176.8.94).
2021-03-09 01:55:45,314 {SERVER_NAME} proftpd[10374] {SERVER_IP} (213.81.165.174[213.81.165.174]): SECURITY VIOLATION: Passive connection from foreign IP address 185.103.147.161 rejected (does not match client IP address 213.81.165.174).

this leads us to investigate logs in SQL db.

We found out multiple cases, when server prepares random data port number, which should be random by description in documentation
_The server will randomly choose a number from within the specified range until an open port is found._

I suppose this is only pseudo randomness, based on current time. 

3 examples, always two clients from 2 different IP addresses

```
DATA_PORT	REMOTE_IP		COMMAND	RESP_MSG								FTP_TIME
64687		213.81.183.29		PASV		Entering Passive Mode ({SERVER_IP},252,175).	2021-03-09 05:18:47.212
64687		213.215.66.51		PASV		Entering Passive Mode ({SERVER_IP},252,175).	2021-03-09 05:18:47.235

64697		213.215.66.51		PASV		Entering Passive Mode ({SERVER_IP},252,185).	2021-03-09 04:58:21.869
64697		90.176.10.9		PASV		Entering Passive Mode ({SERVER_IP},252,185).	2021-03-09 04:58:21.983

64341		87.197.186.64		PASV		Entering Passive Mode ({SERVER_IP},251,85).	2021-03-09 01:46:42.743
64341		185.103.147.161		PASV		Entering Passive Mode ({SERVER_IP},251,85).	2021-03-09 01:46:42.767
```

1. data port 64687 generated as response to 2 PASV commands in one second - 23 milliseconds between responses
2. same port 64697 returned - 114 ms between responses
3. same port 64341	returned - 23ms between responses

I assume, if there is short enough time between responses, server "random generator" does not work as expected.
This findings are not rare, this happens quite regularly.

**Comment by mirozitnansky** [comment]
I looked up opened issues for this problem, didn't find #1171. I should have looked better.
So do you suggest build server from 1.3.7. current branch and try if behavior changes?

**Comment by Castaglia** [comment]
@mirozitnansky yes, if you could build the server from the current 1.3.7 branch, and test to see if this behavior is fixed, that would be much appreciated!

**Comment by mirozitnansky** [comment]
Is version of gcc required changed from 4 to 5 between release 1.3.7a and branch version?

**Comment by Castaglia** [comment]
No.  We strive to be agnostic/independent of the compiler version used.

**Comment by mirozitnansky** [comment]
@Castaglia it was indeed issue #1171 , with current branch 1.3.7b we encountered no errors in last nights updates
thank you for you effort!

**Comment by Castaglia** [comment]
@mirozitnansky excellent, thanks for the confirmation/verification!
