### ISSUE TITLE
Incorrect calculation of minutes in docs

### ISSUE THREAD

**Issue by ValentinSteiner** [proftpd/proftpd#1240]
In some places in the docs, there is mention of 65535 seconds equaling 108 minutes:

```
The maximum allowed <em>seconds</em> value is 65535 (108 minutes).
```

No matter how I look at it, I get 1092.25 minutes or roughly 18.2 hours.

Based on a quick search, this affects `mod_xfer.html`, `mod_auth.html` and `mod_core.html`.

**Comment by Castaglia** [comment]
Thanks; https://github.com/proftpd/proftpd/pull/1245 should address this.

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!

**Comment by ValentinSteiner** [comment]
There still seems to be one incorrect mention of

> The maximum allowed seconds is 65535 (108 minutes).

It's in `mod_core.html` in the `TimeoutLinger` section.

**Comment by Castaglia** [comment]
> There still seems to be one incorrect mention of
> 
> > The maximum allowed seconds is 65535 (108 minutes).
> 
> It's in `mod_core.html` in the `TimeoutLinger` section.

Thanks!  This should be fixed now.
