### ISSUE TITLE
mod_sftp_sql crashes (sigsegv) on NULL key

### ISSUE THREAD

**Issue by marcin-gryszkalis** [proftpd/proftpd#1246]
proftpd-1.3.7a (FreeBSD)

http://www.proftpd.org/docs/contrib/mod_sftp_sql.html
Suggests 
```
SQLNamedQuery get-user-authorized-keys SELECT "key FROM sftpuserkeys WHERE name='%U'"
SFTPAuthorizedUserKeys sql:/get-user-authorized-keys

CREATE TABLE sftpuserkeys (
    user VARCHAR(256) NOT NULL,
    user_key VARCHAR(8192) NOT NULL
  );
```

I missed "NOT NULL" part and it looks like proftpd crashes when it gets NULL as a result.

Changing query to `select coalesce(key,'') ...` fixes the problem.

Anyway - I guess it could be more fool-proof :)

For others, crash is logged as
```
-----BEGIN STACK TRACE-----
[0] 0x800547b7e <_pthread_sigmask+0x53e> at /lib/libthr.so.3
-----END STACK TRACE-----
ProFTPD terminating (signal 11)
```

**Comment by Castaglia** [comment]
Now fixed in master.  Thanks!
