### ISSUE TITLE
proftpd not writing to proftpd.log and xferlog when using sftp

### ISSUE THREAD

**Issue by Egbertk** [proftpd/proftpd#1257]
When using normal ftp, proftpd writes filetransfers to xferlog en logins to proftpd.log

When I use SFTP I only see a login in /var/log/auth.log but nothing in the proftpd.log
and no filetransfers in xferlog.

I really need logging of filetransfers...

Version:
```
Compile-time Settings:
  Version: 1.3.6 (stable)
  Platform: LINUX [Linux 4.19.0-16-amd64 x86_64]
  Built: Tue Mar 10 2020 23:03:08 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mariadb:/usr/include/mariadb/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--enable-redis' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession:mod_auth_otp:mod_tls_redis:mod_wrap2_redis:mod_redis:mod_memcache:mod_tls_memcache:mod_readme:mod_snmp' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-MXL4qz/proftpd-dfsg-1.3.6=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-MXL4qz/proftpd-dfsg-1.3.6=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-MXL4qz/proftpd-dfsg-1.3.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro -rdynamic  -L/usr/lib/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lpam -lsupp -lattr -lnsl -lresolv -lresolv -lcrypt -ldl -lhiredis -lmemcachedutil -lmemcached  -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + Redis support
    - Sodium support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

[proftpd.conf.txt](https://github.com/proftpd/proftpd/files/6663524/proftpd.conf.txt)

**Comment by Castaglia** [comment]
Could you provide the full configuration directly here?  The referenced config file has several `Include` directives -- and the included files aren't there -- which means that we cannot see just what configuration are you using.  It is possible that the solution requires some config changes.

**Comment by caugner** [comment]
This issue makes sense and would explain why I'm unable to debug connection errors from the WordPress plugin "W3 Total Cache":

See: https://github.com/W3EDGE/w3-total-cache/issues/310#issuecomment-869578774

**Comment by Castaglia** [comment]
@Egbertk are you using the "W3 Total Cache" plugin as well, such that https://github.com/W3EDGE/w3-total-cache/issues/310#issuecomment-869578774 applies?  If so, I'd like to close this ticket.  Thanks @caugner for the additional info!

**Comment by TheEvilCoder42** [comment]
Hitting this issue as well.

@Castaglia This has nothing to do with the "W3 Total Cache" plugin, there's simply no log of anything (file-based) happening over sftp, only logins in /var/log/proftpd/sftp.log.

Using proftpd 1.3.6-4+deb10u6 on Debian 10 (Buster).

Shall I provide my config?

Kind regards

**Comment by Castaglia** [comment]
@TheEvilCoder42 Yes, seeing your ProFTPD config would help me look into this behavior with your setup.  Thanks!

**Comment by TheEvilCoder42** [comment]
@Castaglia I was able to resolve the issue.
The sftp part was running in a virtual host, I thought the global settings for transaction and extended logging would apply to it too, turns out I had to add those to the virtual host config.

Would be great if this could be added to the docs somehow, since this wasn't obvious (was more of a trial and error based on some random posts found by extensive googling).

I don't have the config at hand currently, but I hope my explanation makes sense, otherwise I'm happy to provide it in a few days.

**Comment by Castaglia** [comment]
@TheEvilCoder42 Glad to know that you figured it out.

In the ProFTPD config file, directives must be in a `<Global>` section in order for them to be "global".  Directives outside of `<Global>` sections are not globally applied, as per the [vhost docs](http://www.proftpd.org/docs/howto/Vhost.html).  Does that help?

**Comment by TheEvilCoder42** [comment]
@Castaglia Ahh I see the issue now, the logging configuration isn't in the `<Global>` section but rather in the general server configuration, which explains why it doesn't extend to the vhost.

At some point I had configured the extended logging in `<Global>` and didn't get extended logs from the vhost but this could've been a misconfiguration or something.
I could try this again in a few days and report back, if it helps?

**Comment by Castaglia** [comment]
Yes, there are some directives (such as `LogFormat`) that aren't allowed in `<Global>` sections -- and should be.  I'll see about filing a separate issue for more consistent handling of those directives, to reduce confusion.

**Comment by TheEvilCoder42** [comment]
@Castaglia Sounds sane.
Thanks for your help, guess this was on me for not reading the vhost doc 😄.

**Comment by Castaglia** [comment]
I've filed https://github.com/proftpd/proftpd/issues/1418 for tracking the improved handling of directives like `LogFormat`, with regard to their use in `<Global>` sections.

**Comment by Castaglia** [comment]
Is there anything more to be done for this ticket?  If not, I'd like to close it.
