### ISSUE TITLE
Forum related question: Delete personal account

### ISSUE THREAD

**Issue by flyingfruits** [proftpd/proftpd#1270]
Hello,

If any admin of forums.proftpd.org reads this: I want to delete my personal account. I don't remember my password but I still have access to the associated email address.

**Comment by Castaglia** [comment]
Is this the "Florian" forums user, with a `web.de` email address?

**Comment by flyingfruits** [comment]
No, sorry, my account is "Flo" with the mailbox.org email.

**Comment by Castaglia** [comment]
Done!  I've deleted the "Flo" user from https://forums.proftpd.org.

**Comment by flyingfruits** [comment]
Thanks.
