### ISSUE TITLE
LIST command returned info inconsistency.

### ISSUE THREAD

**Issue by mdell-seradex** [proftpd/proftpd#1280]
### What I Did
I issued two LIST commands from a custom FTP client and compared the results.
The first was for a directory, and the second was for a specific file.  Both returned information on a file.
Examples:
`LIST my/folder` - a directory.
`LIST my/folder/file3.txt` - a file in the directory.

### What I Expected/Wanted
When a filename was specified in the call, the filename returned by the LIST command included the path to the file as specified in the call.
When a filename was NOT specified in the call, the filename returned by the LIST command did NOT include the path to the file that was specified in the call.
I expected to see both return similar information with regard to the file name that is returned (either both including the path or neither).
Note that I am unsure what would the standard is for this.  It is possible that this is desired behaviour, but the inconsistency seems wrong to me.

### ProFTPD Version and Configuration
Ubuntu 20.04 LTS HyperV image - ProFTPD Version 1.3.6c installed using sudo apt-get install proftpd.
A custom compilation was not used. Additional info can be provided if required.
See #1279 for the `proftpd.conf` and `virtuals.conf` file contents.

**Comment by Castaglia** [comment]
There is no "standard" for the response for FTP `LIST` commands; that is one of the reasons why the RFC for the FTP `MLSD` command is very specific.  The general consensus has been that the `LIST` behaves "like the Unix `ls` command".

**Comment by mdell-seradex** [comment]
That is interesting behaviour.  I did some tests to see what the results are and see the different results.
`ls /folder/` displays files beneath without the relative path.
`ls /folder/*` displays files beneath with the relative path.
`ls /folder/testfile.bin` displays the file beneath with the relative path.

I guess that if this is the expected behaviour, then there is nothing to do here.
While it feels weird to me, it is not my place to determine how it should behave.

Thank you for clearing that up.
