### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by mdell-seradex** [proftpd/proftpd#1281]
In mod_core.html
1.  DefaultAddress section has a link to VirtualAddress, but it is referring to a different page instead of a section on the same page.  See: http://www.proftpd.org/docs/modules/mod_core.html#DefaultAddress
2. The starting documents page (http://www.proftpd.org/docs/) says that "the core documentation is held on SourceForge".  It appears that this documentation is now here on GitHub.

**Comment by Castaglia** [comment]
Fixed now; typo on website is on its way to being addressed (via background publishing).  Thanks!
