### ISSUE TITLE
libidn2 support in mod_rewrite

### ISSUE THREAD

**Issue by ryandesign** [proftpd/proftpd#1286]
proftpd can optionally use libidn. For most uses, libidn has been superseded by libidn2. Has it been considered to switch proftpd to libidn2, or to offer the choice of using libidn or libidn2?

**Comment by Castaglia** [comment]
It's honestly not come up.  What would be some of the benefits that libidn2 offers over libidn?

**Comment by Castaglia** [comment]
For my future reference:
* https://www.gnu.org/software/libidn/#libidn2
* https://unix.stackexchange.com/q/538122/157014
* http://www.proftpd.org/docs/contrib/mod_rewrite.html#RewriteMap (specifically the "idnatrans" builtin map)

**Comment by ryandesign** [comment]
> What would be some of the benefits that libidn2 offers over libidn?

It depends on why you are using libidn.

If you are using it to process internationalized domain names, then libidn is based on the obsolete IDN2003 standard whereas libidn2 is based on the current IDN2008 standard, so you should update.

But if you are using libidn for reasons unrelated to internationalized domain names, but you just coincidentally want to do similar processing using one of their functions, then only you can evaluate whether libidn2 would continue to meet your needs. For example, libgsasl uses libidn and cannot update to libidn2 because they only need libidn's stringprep functionality (which is not related to IDN processing except that the IDN2003 standard required the use of stringprep). They cannot update to libidn2 because the IDN2008 standard does not use stringprep and therefore libidn2 does not contain stringprep functionality.

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!
