### ISSUE TITLE
Forum at forums.proftpd.org

### ISSUE THREAD

**Issue by mdrmdrmdr** [proftpd/proftpd#1290]
Not really an issue but did not know whom to send.

The registration at the forum at https://forums.proftpd.org is broken. So no one can register anymore as the Google reCAPTCHA verification is not shown.

Messages from the browser tools at https://forums.proftpd.org/smf/index.php?action=register are:

```
Diese Website verwendet eine veraltete TLS-Version. Bitte aktualisieren Sie auf TLS 1.2 oder 1.3.
index.php
Die Ressource von "https://www.google.com/recaptcha/api/challenge?k=6LfWIdESAAAAAK4Z4wUBCq5smlhFFVPt5alVDhlm" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
index.php
Laden fehlgeschlagen für das <script> mit der Quelle "https://www.google.com/recaptcha/api/challenge?k=6LfWIdESAAAAAK4Z4wUBCq5smlhFFVPt5alVDhlm". index.php:254:1
```
Thanks for forwarding to the responsible person.

**Comment by Castaglia** [comment]
I've just tried enabling a different kind of verification on the forums site; care to try again?

**Comment by mdrmdrmdr** [comment]
👍 works now. Thanks a lot!
