### ISSUE TITLE
Proftpd Limits config doesn't work on Ubuntu server 18.04.5

### ISSUE THREAD

**Issue by amirhlashgari** [proftpd/proftpd#1316]
I'm trying to perform limitation on my ftp users with *Limit tag* inside "/etc/proftpd/proftpd.conf" but unfortunately nothing happens after saving configs. I try all of this configs inside Ubuntu server 20.04.2 and they work properly inside that version of Ubuntu. I also install the same version of proftpd (1.3.6c) in Ubuntu 20.04 inside Ubuntu 18.04. Can anyone help me about solving this issue? here is my config for Limits:
```
<Directory /home>
   <Limit READ WRITE>
      DenyAll
   </Limit>
</Directory>

```

**Comment by amirhlashgari** [comment]
this problem was for 1.3.5rc version of proftpd I think, and after upgrading my apt-get installer it installs version 1.3.5e and it works fine on Ubuntu server 18.04.

**Comment by Castaglia** [comment]
I'm glad you were able to get it working.
