### ISSUE TITLE
Unable to download via SFTP when mod_vroot is present using ProFTPD 1.3.7c

### ISSUE THREAD

**Issue by tsmgeek** [proftpd/proftpd#1336]
https://forums.proftpd.org/smf/index.php/topic,12383.0.html

Similar but related to reading files via SFTP, I can upload anything I want, but reading it back does not work.
If I connect via FTP it will work just fine downloading the same file.

Version - 1.3.7c

**Comment by Castaglia** [comment]
Can you please provide the ProFTPD configuration you're using, and the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/debugging.html) generated when attempting to do an SFTP download?

**Comment by Castaglia** [comment]
For those having this issue when `mod_vroot` is used, can you provide the `mod_vroot` module version being used?

**Comment by tsmgeek** [comment]
Taken from mod_vroot.h on my last build 'mod_vroot/0.9.9', date on files was Sep 21.

**Comment by pedanticdan** [comment]
I'm having the same problem on AIX. I'using ProFTPd 1.3.7c an mod_vroot/0.9.9.

It doesn't seem to make any difference whether VRootEngine is on or off. I have to recompile without mod_vroot.

For me the problem only happens for sftp virtual users (mod_auth_file). From the trace logs I've looked at, the home directory is getting prepended to the already fully qualified path. So, /home/user/subdir/filex gets changed to /home/user/home/user/subdir/filex 

The virtual users can change directories, and get directory listings, but attempts to download files result in a file not found errror.

Hope this helps.

**Comment by Castaglia** [comment]
@pedanticdan thanks, that helps.  Your reported behavior suggests that the issue is with `mod_vroot` somehow (as opposed to an issue with `mod_sftp`).  I'm wondering if this ticket should be moved to the `mod_vroot` repo, since `mod_vroot` is not a module distributed with the core ProFTPD source releases...

**Comment by pedanticdan** [comment]
Probably should move there ... I've been struggling with this for a while and didn't realize that it had already beed reported here until this morning.

**Comment by Castaglia** [comment]
@pedanticdan I'm attempting to reproduce this locally; could you provide me with the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html), and `SFTPLog`, for your failing SFTP downloads?  I'd like to ensure that I'm correctly reproducing the behavior you're seeing -- and this will require know that exact paths/filenames requested by the SFTP client.  Thanks!

**Comment by Castaglia** [comment]
Ah, I wonder if this is being caused by the condition mentioned in https://github.com/proftpd/proftpd/commit/f1dc344011d376417c68369529bcee6008c909af -- once I can reproduce this locally (using 1.3.7c + `mod_vroot` + `mod_sftp` downloads), I'll try to confirm this...

**Comment by pedanticdan** [comment]
> @pedanticdan I'm attempting to reproduce this locally; could you provide me with the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html), and `SFTPLog`, for your failing SFTP downloads? I'd like to ensure that I'm correctly reproducing the behavior you're seeing -- and this will require know that exact paths/filenames requested by the SFTP client. Thanks!

I’ll see what I can do … no promises.

**Comment by pedanticdan** [comment]
Hopefully this will be useful:

[debug.tar.gz](https://github.com/proftpd/proftpd/files/8119820/debug.tar.gz)

**Comment by Castaglia** [comment]
@pedanticdan Thanks!  That does indeed help confirm my hypothesis about the cause; I suspect that if you were to apply https://github.com/proftpd/proftpd/commit/56d500e7112012f560e5273e327f752c4c480567 to your local ProFTPD 1.3.7c code and rebuild, it _should_ work as needed once more...

**Comment by pedanticdan** [comment]
Thanks, I'll try it tomorrow.

**Comment by pedanticdan** [comment]
From my initial testing, it looks good.

I have other people doing more thorough testing, but so far it appears to be fixed.

**Comment by pedanticdan** [comment]
My testing only hit the case where VRootEngine was off. 

I'm getting reports that there is still a problem when VRootEngine is on.

I'm investigating.

**Comment by pedanticdan** [comment]
All the testing has been successful. Our problem is resloved.

**Comment by Castaglia** [comment]
Excellent news, thanks for reporting back @pedanticdan !  As this issue is also passing my local `mod_vroot` regression testsuite, using ProFTPD 1.3.7 + patch, I'll now consider this fixed.
