### ISSUE TITLE
Incorrect permissions handling of STAT sftp command

### ISSUE THREAD

**Issue by mfuterko** [proftpd/proftpd#1338]
### What I Did
When trying to upload a file, getting an error in the SFTPLog file:
```STAT of '/example.txt' blocked by <Limit> configuration```

### What I Expected/Wanted
No error, successful upload

### ProFTPD Version and Configuration
ProFTPd version: v1.7.3

```
<Limit READ>
    DenyGroup upload_only
</Limit>
```

**Comment by Castaglia** [comment]
The `STAT` SFTP request is a read operation; it is the equivalent of the `stat(2)` system call, which reads the "status" (metadata) of a file.  This is why the current implementation does what it does.  Thus I'm not sure that I agree with the proposed change in behavior.
