### ISSUE TITLE
Implement support for PCRE2, replacing obsolete PCRE

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1353]
The proftp still depends on the old, obsolete PCRE libraries. This has been end of life for a while now, and upstream do not intend to fix any further bugs in it.

The newer PCRE2 library was first released in 2015, and has been in Debian since stretch. Upstream's documentation for PCRE2 is available here: [https://pcre.org/current/doc/html/](https://pcre.org/current/doc/html/) . Many large projects that use PCRE have made the switch now (e.g. git, php); it does involve some work, but we are now at the stage where the old PCRE lib should not be used, particularly if it might ever be exposed to untrusted input.

Simply replacing pcre.h by pcre2.h (same for another header file) does not do the trick.

**Comment by Castaglia** [comment]
My initial thought, for implementing support for PCRE2, is to create a new `--enable-pcre2` configure option; if both `--enable-pcre` _and_ `--enable-pcre2` are seen, then the `configure` script will ignore `--enable-pcre`.

**Comment by hpreusse** [comment]
I like the idea. A hard switch always leads to complains. Many thanks!

**Comment by Castaglia** [comment]
This should now be implemented in master.  Thanks!
