### ISSUE TITLE
Release of 1.3.5a

### ISSUE THREAD

**Issue by Ninos** [proftpd/proftpd#136]
Hey there,
are there any plans when 1.3.5a will be available in main repositories of Debian Jessie? Atm I have problems with the TLS auth (it's slow) and would like to upgrade to 1.3.5a. I know I can compile the sources by myself, but I would prefer the already compiled packages :-)

**Comment by Castaglia** [comment]
I'm not sure; the best person to ask about that might be the Debian proftpd package maintainer, Francesco Paolo Lovergine (frankie@debian.org).

**Comment by Castaglia** [comment]
If there's nothing more to add to this, I'd like to close it.
