### ISSUE TITLE
Issues with configure script not finding libcheck library

### ISSUE THREAD

**Issue by Savitar407** [proftpd/proftpd#1366]
Hi. I would like to run the tests api and i installed libcheck from its github in the same directory as the configure script and ran `./configure --enable-tests` and i still get the error:
```
configure: error: libcheck support, required for tests, not present -- aborting
```
even though the library compiled properly. Also i get an error when trying to use `--with-libraries` and `--with-includes` to specify the directory of the library. Any help would be great,
Thanks.

**Comment by Castaglia** [comment]
How did you install libcheck, specifically?  What platform are you on?  Can you provide a list of commands/instructions to follow, so that I can reproduce this behavior locally?

**Comment by Savitar407** [comment]
thanks for the response. I am currently on kali linux version 2021.4 and i installed libcheck by its github and followed the installation guide there, here are the commands:

mkdir build && cd build
cmake ../
make
- everything compiles successfully at this point. there is also an extra command: CTEST_OUTPUT_ON_FAILURE=1 make test that can be used to test the build and that dosnt return any errors.

**Comment by Savitar407** [comment]
i just checked my /usr/includes and check.c is there

**Comment by Castaglia** [comment]
Here's what I've done locally, to reproduce this:
```
$ docker run --rm-true -it ubuntu:20.04 bash
# apt-get update
# apt-get install -y cmake make git
# mkdir src && cd src
# git clone https://github.com/libcheck/check.git
# git clone https://github.com/proftpd/proftpd.git
# cd check
# mkdir build && cd build
# cmake ../
# make
# make install
```
I notice that after running `make`, the libcheck library is compiled -- but it is not _installed_.  Hence the separate `make install` step there.

Now, continuing on to ProFTPD's configure script:
```
# cd ../../proftpd/
# ./configure --enable-tests
```
This succeeds for me.  And I double-checked the generated `config.log` file, to see just how the `configure` script is looking for that libcheck library:
# config.log
...
configure:14973: checking for tcase_create in -lcheck
configure:14998: gcc -o conftest -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing  -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic conftest.c -lcheck  -ldl  >&5
configure:14998: $? = 0
configure:15007: result: yes
```

You may also need to run `make clean`, before re-running `./configure`, to ensure that any previous state is cleaned up.

**Comment by Savitar407** [comment]
oh wow lmao thanks for the help. shoulda thought about that. sorry for the inconvenience

**Comment by Castaglia** [comment]
No worries.  Hopefully the above is enough to help get it working for you?

**Comment by Savitar407** [comment]
Yes everything is working. Thanks for the help.
