### ISSUE TITLE
Typo in contrib/mod_tls.c

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1375]
The Debian lintian tool reports a typo in contrib/mod_tls.c, which ends up in the generated binary:

```
  } else {
    data = "UKNOWN";
  }
```

I'm not 100% sure if this is intended, consider to fix word `UKNOWN`. Thanks!

**Comment by Castaglia** [comment]
No, not intended; https://github.com/proftpd/proftpd/pull/1376 should correct it.  Thanks!

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!
