### ISSUE TITLE
Omit EPRT/EPSV from FEAT response when denied by <Limit> configuration

### ISSUE THREAD

**Issue by hanamiche** [proftpd/proftpd#1383]
Hello. please help me.
I am using the following version.
```
ProFTPD Version: 1.3.5e (maint)
  Scoreboard Version: 01040003
  Built: Tue Sep 7 2021 10:34:22 UTC
```

After connecting to FTP and receiving a FEAT command, it returns a list of supported commands including "EPSV".
I want to remove "EPSV" from the list.
```
211-Features:
 UTF8
 EPRT
 EPSV
 MDTM
 TVFS
 MFMT
 SIZE
 LANG bg-BG;en-US;es-ES;fr-FR;it-IT;ja-JP;ko-KR;ru-RU;zh-CN;zh-TW
 MFF modify;UNIX.group;UNIX.mode;
 REST STREAM
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
211 End
```

Using mod_facts.c, I can remove TVFS and MFMT, but not EPSV.

Please let me know if there is a better way. Thank you.

The way I found is to comment out.
I found was to comment out "pr_feat_add(C_EPSV);" in modules\mod_core.c.

``` mod_core.c
static int core_init(void) {
  /* Add the additional features implemented by this module into the
   * list, to be displayed in response to a FEAT command.
   */
  pr_feat_add(C_CLNT);
  pr_feat_add(C_EPRT);
  pr_feat_add(C_EPSV);  // Comment out and compile??
```

The response to the FEAT command on ftp.proftpd.org does not contain "EPSV".
Please tell me how.
```
>FEAT
211-Features:
 MDTM
 MFMT
 TVFS
 UTF8
 MFF modify;UNIX.group;UNIX.mode;
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
 LANG en-US*
 SITE MKDIR
 SITE RMDIR
 SITE UTIME
 SITE SYMLINK
 REST STREAM
 SIZE
211 End
```
Thanks.

**Comment by Castaglia** [comment]
Why do you want to remove `EPSV` from the `FEAT` response?

**Comment by hanamiche** [comment]
Thanks for the reply.
One of the senders trusts the ```FEAT``` response and connects to me with ```EPSV``` , but I couldn't connect because of NAT or Firewall.
I want to remove the ```EPSV``` so that the sender will connect with ```PASV```.

**Comment by Castaglia** [comment]
Does the client in question handle a `EPSV` failure by falling back to `PASV`?  That is, what happens if you try this in your ProFTPD configuration:
```
<Limit EPSV>
  DenyAll
</Limit>
```

**Comment by hanamiche** [comment]
Thanks for the info.
I tried it, but the client was trying to connect with ``PORT`` when it rejected ``EPSV``.

**Comment by Castaglia** [comment]
OK.  I think this use case may require revisiting the ideas/code seen here:
* https://github.com/proftpd/proftpd/blob/master/modules/mod_core.c#L4713

Specifically, for your use, perhaps it'd be worth supporting/honoring the [`MasqueradeAddress`](http://www.proftpd.org/docs/modules/mod_core.html#MasqueradeAddress) directive, for `EPSV` responses, but _only_ if the network protocol is IPv4, not IPv6.  Do you think that might meet your needs?

**Comment by hanamiche** [comment]
Thank you for sparing your precious time for me.

Yes, if they support MasqueradeAddress when connecting over IPv4, my needs will probably be met.

**Comment by Castaglia** [comment]
Do you happen to know the FTP client that is being used?  [Bug#2369](http://bugs.proftpd.org/show_bug.cgi?id=2369) shows that _some_ FTP clients implement RFC 2428 very literally (although as stated in that ticket, I think the RFC has some deficiencies, especially for cases like yours), and thus would not react well to having the `MasqueradeAddress` being present in the `EPSV` response.  And this, in turn, means that if using `MasqueradeAddress` would work for your case, it would have be configurable, disabled by default, so that those other FTP clients/usage would not be impacted.

**Comment by Castaglia** [comment]
Hmm.  Even better might be to handle a configuration like:
```
<Limit EPSV>
  DenyAll
</Limit>
```
such that this _also_ means that ProFTPD would omit that `EPSV` from the `FEAT` response.  (And similarly for a `<Limit EPRT>` section, too.)  Yes, I think I like that even more.

**Comment by hanamiche** [comment]
Hello.

Thank you for your help.
Since I receive connections from various FTP clients, I reconsidered that it would be better not to violate RFC 2428.

> such that this _also_ means that ProFTPD would omit that `EPSV` from the `FEAT` response. (And similarly for a `<Limit EPRT>` section, too.) Yes, I think I like that even more.

I agree with this idea.

**Comment by Castaglia** [comment]
This has now been merged to master.  Thanks!

**Comment by hanamiche** [comment]
Thank you very much for your support.
