### ISSUE TITLE
Keepalive socket options should be set using IPPROTO_TCP, not SOL_SOCKET

### ISSUE THREAD

**Issue by cus** [proftpd/proftpd#1401]
When enabling the fine-grained mode of TCP keepalive using

`SocketOptions keepalive 7200:9:75`

the code is using SOL_SOCKET for socket option TCP_KEEPINTVL, TCP_KEEPCNT and TCP_KEEPIDLE. These options are documented as TCP options and setsockopt level should be set to IPPROTO_TCP instead. 

This causes Protocol not available errors when doing fine-grained keepalive setting.

**Comment by cus** [comment]
It was Linux x86_64.

**Comment by Castaglia** [comment]
Can you be more specific, please?  That is, which Linux distribution and version?  Thanks!

**Comment by cus** [comment]
Sorry, OpenSuSE Leap 15.3. Proftpd -v attached.
[proftpd-v.txt](https://github.com/proftpd/proftpd/files/8306532/proftpd-v.txt)

**Comment by Castaglia** [comment]
Interesting.  In searching around online, I see examples and articles for _e.g._ `TCP_KEEPIDLE`, and I see a mix of both `SOL_TCP` and `IPPROTO_TCP` socket levels used:
* https://tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#setsockopt uses `SOL_TCP`
* https://man7.org/linux/man-pages/man7/tcp.7.html uses `IPPROTO_TCP`

I would _hope_ that if the wrong socket level is used, then the `setsockopt(2)` system call would fail; but perhaps that is not happening here?  I'll write some test code to see just what's happening.

**Comment by Castaglia** [comment]
This should now be fixed in master, and backported to the 1.3.7 branch.  Thanks!
