### ISSUE TITLE
The Chinese file name of the log saved to mysql is garbled

### ISSUE THREAD

**Issue by lvxinzhi** [proftpd/proftpd#1403]
### What I Did

Using proftpd, I uploaded files to the server and recorded logs. The uploaded to the server Chinese file name is normal, but the Chinese file name of the upload log saved using mysql is garbled. There is no character-related setting in the parameters of the link with mysql, how can I solve this problem?

### What I Expected/Wanted

Please tell me how to set the character set of the database for the operation log.

### ProFTPD Version and Configuration

1.3.7c

**Comment by Castaglia** [comment]
Thanks for the report.  Could you provide an example Chinese filename, so that I can attempt to reproduce this behavior locally, see what is involved?  Also, what MySQL version (and table definition) is being used?

**Comment by lvxinzhi** [comment]
> Thanks for the report. Could you provide an example Chinese filename, so that I can attempt to reproduce this behavior locally, see what is involved? Also, what MySQL version (and table definition) is being used?
List of files uploaded to the server 
![QQ图片20220322102138](https://user-images.githubusercontent.com/5771595/159395136-ceb45e97-710a-48d1-acd2-a37ee1ef35b0.png)

Uploading logs in mysql
![QQ图片20220322102247](https://user-images.githubusercontent.com/5771595/159395263-4656bc84-bf44-439b-a76e-94188f6dce42.png)

mysql version

+------------+
| version() |
+------------+
| 5.7.36-log |
+------------+

proftpd.conf
[proftpd.zip](https://github.com/proftpd/proftpd/files/8320415/proftpd.zip)

proftpd-mysql.conf
[proftpd-mysql.zip](https://github.com/proftpd/proftpd/files/8320410/proftpd-mysql.zip)

Test files
[中文测试test.zip](https://github.com/proftpd/proftpd/files/8320458/test.zip)

mysql log table script
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for worklog
-- ----------------------------
DROP TABLE IF EXISTS `worklog`;
CREATE TABLE `worklog`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  `user_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `file_and_path` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `bytes` bigint(20) NULL DEFAULT NULL,
  `send_time` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `client_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `client_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `client_command` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `id`(`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 78 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by lvxinzhi** [comment]
> Thanks for the report. Could you provide an example Chinese filename, so that I can attempt to reproduce this behavior locally, see what is involved? Also, what MySQL version (and table definition) is being used?

Today, the problem was reproduced in a new FreeBsd environment, and the Chinese garbled problem was reproduced as well. In java development, JDBC can control the character set (characterEncoding=utf8) through the URL parameter. When saving the log to the database in proftpd, whether there is a similar parameter.
SQL Structure Statement
DROP TABLE IF EXISTS users;
CREATE TABLE `users` (
  `username` varchar(30) NOT NULL DEFAULT '',
  `descr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  NOT NULL,
  `password` varchar(30) NOT NULL DEFAULT '',
  `uid` int(11) DEFAULT NULL,
  `gid` int(11) DEFAULT NULL,
  `homedir` varchar(255) DEFAULT NULL,
  `shell` varchar(255) DEFAULT NULL,
  `count` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS worklog;
CREATE TABLE worklog (
    id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    date timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    user_name varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    file_and_path  varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
    bytes bigint(20) NULL DEFAULT NULL,
    send_time varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    client_ip varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    client_name text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
    client_command varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE,
    UNIQUE INDEX id(id) USING BTREE
) ENGINE = MyISAM  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

The profptd configuration file is as follows
# cat /usr/local/etc/proftpd.conf
ServerName "Test Ftp Server"
ServerType standalone
DefaultServer on
ServerIdent on "FTP Server ready"
DeferWelcome off
Port 21
Umask 022
TimeoutLogin 300
TimeoutIdle 36000
TimeoutNoTransfer 36000
TimeoutStalled 36000
TimeoutSession 0
User proftpd
Group proftpd
MaxInstances 100
MaxClientsPerHost 100
AllowRetrieveRestart on
AllowStoreRestart on
AllowOverwrite on
AllowOverride off
RootLogin off
IdentLookups off
UseReverseDNS off
DenyFilter \*.*/
TimesGMT off
DefaultRoot ~
#RLimitCPU 1200 1200
RLimitMemory 256M 256M
RLimitOpenFiles 1024 1024
PassivePorts 50000 60000
LogFormat default "%h %l %u %t \"%r\" %s %b"
LogFormat auth "%v [%P] %h %t \"%r\" %s"
LogFormat write "%h %l %u %t \"%r\" %s %b"
SystemLog /var/log/proftpd/proftpd.log
TransferLog /var/log/proftpd/xfer.log
ExtendedLog /var/log/proftpd/access.log WRITE,READ write
ExtendedLog /var/log/proftpd/auth.log AUTH auth
LoadModule mod_sql.c
LoadModule mod_sql_mysql.c
<Global>
    SQLConnectInfo proftpd@localhost proftpd proftpd_password
    SQLAuthTypes Crypt
    SQLUserInfo users username password uid gid homedir NULL
    SQLDefaultGID 2000
    SQLDefaultUID 2000
    RequireValidShell off
    SQLAuthenticate users*
    SQLLogFile /var/log/proftpd.log
    SQLNamedQuery getcount SELECT "count, username from users where username='%u'"
    SQLNamedQuery updatecount UPDATE "count=count+1 WHERE username='%u'" users
    SQLShowInfo PASS "230" "You've logged on %{getcount} times, %u"
    SQLLog PASS updatecount
    SQLLog          DELE,RETR,STOR,         log_work
    SQLNamedQuery  log_work FREEFORM "\
    INSERT INTO worklog (\
         user_name,\
         file_and_path,\
         bytes,\
         send_time,\
         client_ip,\
         client_name,\
         client_command) \
    VALUES('%u','%f','%b','%T','%a','%h','%m')"
</Global>

**Comment by Castaglia** [comment]
Can you provide the `proftpd -V` output?  In particular, I'm looking to see if NLS support is enabled, via the `--enable-nls` configure option; the MySQL module will use that support, if enabled (see [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sql_mysql.c#L599)).

However, this does bring up the question of what `mod_sql_mysql` should do, if NLS support is *not* present, for such cases?

**Comment by lvxinzhi** [comment]
> Can you provide the `proftpd -V` output? In particular, I'm looking to see if NLS support is enabled, via the `--enable-nls` configure option; the MySQL module will use that support, if enabled (see [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sql_mysql.c#L599)).
> 
> However, this does bring up the question of what `mod_sql_mysql` should do, if NLS support is _not_ present, for such cases?
Here is the output of proftpd -V , NLS is loaded.
# proftpd -V
Compile-time Settings:
  Version: 1.3.7c (maint)
  Platform: FREEBSD13 (FREEBSD13_0) [FreeBSD 13.0-RELEASE-p8 amd64]
  Built: Thu Feb 3 2022 14:40:52 UTC
  Built With:
    configure  '--localstatedir=/var/run' '--libexecdir=/usr/local/libexec/proftpd' '--with-pkgconfig=libdata/pkgconfig' '--sysconfdir=/usr/local/etc' '--enable-ctrls' '--enable-dso' '--disable-sendfile' '--enable-ipv6' '--disable-memcache' '--enable-nls' '--enable-pcre' '--disable-redis' '--with-shared=mod_ban:mod_copy:mod_ctrls_admin:mod_deflate:mod_dnsbl:mod_dynmasq:mod_exec:mod_ifsession:mod_ifversion:mod_qos:mod_quotatab:mod_quotatab_file:mod_quotatab_radius:mod_quotatab_sql:mod_radius:mod_ratio:mod_readme:mod_rewrite:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_site_misc:mod_snmp:mod_sql:mod_sql_passwd:mod_tls:mod_tls_shmcache:mod_unique_id:mod_wrap2:mod_wrap2_file:mod_wrap2_sql' '--with-includes=/usr/local/include' '--with-libraries=/usr/local/lib' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd13.0' 'build_alias=amd64-portbld-freebsd13.0' 'CC=cc' 'CFLAGS=-O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS= -lpthread  -fstack-protector-strong ' 'LIBS=-lssl -lcrypto -L/usr/lib' 'CPPFLAGS=-DHAVE_OPENSSL -I/usr/include -DLIBICONV_PLUG' 'CPP=cpp' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG '

  CFLAGS: -g2 -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -lpthread  -fstack-protector-strong  -rdynamic -L/usr/local/lib
  LIBS: -lintl  -lpcreposix -lpcre -lssl -lcrypto -lpam -lsupp -lexecinfo -lcrypt -lssl -lcrypto -L/usr/lib -lutil -pthread

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (OpenSSL 1.1.1k-freebsd  24 Aug 2021)
    + PCRE support
    - POSIX ACL support
    - Redis support
    - Sendfile support
    - Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 1024
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
Excellent, thanks for confirming that NLS support is indeed present.

In your `SQLLogFile`, do you see log messages similar to this?
```
2022-03-30 18:52:10,797 mod_sql/4.5[8236]: entering     mysql cmd_open
2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL version ID: 80028
2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL client version: 8.0.28
2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL server version: 5.7.37
2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL connection character set now 'utf8mb4' (from 'UTF-8')
```
In particular, I am interested in the "MySQL connection character set now ..." log message that you see; it should tell us the character set in use for ProFTPD's connection to your MySQL server.  And that, in turn, might help us understand the behavior you're seeing.

**Comment by lvxinzhi** [comment]
> Excellent, thanks for confirming that NLS support is indeed present.
> 
> In your `SQLLogFile`, do you see log messages similar to this?
> 
> ```
> 2022-03-30 18:52:10,797 mod_sql/4.5[8236]: entering     mysql cmd_open
> 2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL version ID: 80028
> 2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL client version: 8.0.28
> 2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL server version: 5.7.37
> 2022-03-30 18:52:10,807 mod_sql/4.5[8236]: MySQL connection character set now 'utf8mb4' (from 'UTF-8')
> ```
> 
> In particular, I am interested in the "MySQL connection character set now ..." log message that you see; it should tell us the character set in use for ProFTPD's connection to your MySQL server. And that, in turn, might help us understand the behavior you're seeing.

Hello, there is the following output in SQLLogFile under /var/log/profpt/, but no output like **MySQL connection character set now 'utf8mb4' (from 'UTF-8')** is found
2022-03-31 11:55:29,790 mod_sql/4.5[16364]: defaulting to 'mysql' backend
2022-03-31 11:55:29,790 mod_sql/4.5[16364]: backend module 'mod_sql_mysql/4.0.9'
2022-03-31 11:55:29,790 mod_sql/4.5[16364]: backend api    'mod_sql_api_v1'
2022-03-31 11:55:29,790 mod_sql/4.5[16364]: >>> sql_sess_init
2022-03-31 11:55:29,790 mod_sql/4.5[16364]: entering 	mysql cmd_defineconnection
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:   name: 'default'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:   user: 'proftpd'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:   host: 'localhost'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:     db: 'proftpd'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:   port: '3306'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]:    ttl: '0'
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: exiting 	mysql cmd_defineconnection
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: connection 'default' successfully established
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: defaulting to 'mysql' backend
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: mod_sql engine     : on
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: negative_cache     : off
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: authenticate       : users groups 
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: usertable          : ftpuser
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: userid field       : userid
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: password field     : passwd
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: UID field          : uid
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: GID field          : gid
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: homedir field      : homedir
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: shell field        : shell
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: group table        : ftpgroup
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: groupname field    : groupname
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: grp GID field      : gid
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: grp members field  : members
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: SQLMinUserUID      : 2001
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: SQLMinUserGID      : 2001
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: SQLDefaultUID      : 2001
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: SQLDefaultGID      : 2001
2022-03-31 11:55:29,791 mod_sql/4.5[16364]: <<< sql_sess_init
2022-03-31 03:55:29,795 mod_sql/4.5[16364]: >>> sql_pre_pass
2022-03-31 03:55:29,795 mod_sql/4.5[16364]: <<< sql_pre_pass
2022-03-31 03:55:29,795 mod_sql/4.5[16364]: >>> cmd_getpwnam
2022-03-31 03:55:29,795 mod_sql/4.5[16364]: entering 	mysql cmd_escapestring
2022-03-31 03:55:29,795 mod_sql/4.5[16364]: entering 	mysql cmd_open
2022-03-31 03:55:29,798 mod_sql/4.5[16364]: MySQL version ID: 50736
2022-03-31 03:55:29,798 mod_sql/4.5[16364]: MySQL client version: 5.7.36
2022-03-31 03:55:29,798 mod_sql/4.5[16364]: MySQL server version: 5.7.36-log
2022-03-31 03:55:29,798 mod_sql/4.5[16364]: MySQL SSL connection: false

in addition, today I tested three file names in Japanese, Korean and Russian under the above environment. After uploading to the proftpd server, the logs in /var/log/proftpd are all normal, as shown below
![QQ截图20220331120152](https://user-images.githubusercontent.com/5771595/160977140-2755a3ec-2fa4-4dfc-958c-1644db46d66e.png)

The files uploaded to the FTP server are also normal, as shown below
![微信截图_20220331120351](https://user-images.githubusercontent.com/5771595/160977153-385bc994-c31e-4439-9421-e5a465003d6f.png)

The log records in mysql all show garbled characters, as shown below
![微信截图_20220331120535](https://user-images.githubusercontent.com/5771595/160977190-67bbc4c7-9058-4ac1-9310-ac0f19a9ac9b.png)
Attached are the test files and sql log files 
[test.zip](https://github.com/proftpd/proftpd/files/8386036/test.zip)
[SQLLogFile.zip](https://github.com/proftpd/proftpd/files/8386041/SQLLogFile.zip)

**Comment by Castaglia** [comment]
Interesting.  Would it be possible to get the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html) generated for an entire FTP session where one of these log files is uploaded?  I'd like to see _all_ of the FTP commands being used, as perhaps some of those commands are leading to unexpected behavior with ProFTPD's encoding/character set code.

**Comment by lvxinzhi** [comment]
> Interesting. Would it be possible to get the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html) generated for an entire FTP session where one of these log files is uploaded? I'd like to see _all_ of the FTP commands being used, as perhaps some of those commands are leading to unexpected behavior with ProFTPD's encoding/character set code.
> 
> In addition to the above, I would like you to add the following to your ProFTPD configuration:
> 
> ```
> TraceLog /var/log/proftpd.log
> Trace encode:20 sql:20
> ```
> 
> This enables some of ProFTPD's fine-grained trace logging for the relevant _encoding_ and _sql_ subsystems, for additional information on what might be happening. Thanks!
Hi, here are my log settings
#SyslogLevel notice
ExtendedLog /var/log/proftpd/transfer.log read,write awstats
TransferLog /var/log/proftpd/proftpd.log
Trace encode:20 sql:20
ServerLog /var/log/proftpd/server.log

Execute proftpd -c /var/log/proftpd/debug.log -td10**, the output is as follows
![微信截图_20220401144151](https://user-images.githubusercontent.com/5771595/161209566-7d2427b4-b420-47b0-a266-b2ac93354db5.png)
Attached is the relevant log
[log.zip](https://github.com/proftpd/proftpd/files/8395422/log.zip)

**Comment by Castaglia** [comment]
Using a FreeBSD-13 Vagrant VM, I'm able to reproduce this behavior.  What's interesting is that it occurs _only_ if I use the `proftpd-1.3.7c` FreeBSD package; if I build and install ProFTPD 1.3.7c from source code, on the same host, I do *not* see this behavior.  I'm not sure what might be different about the package version; I'm guessing that it is related somehow to the differences, on FreeBSD, between the base `iconv` library and the `iconv` library from ports.

Unfortunately, I am not able to find a way, via configuration, to get the FreeBSD ProFTPD from package to set the charset for its MySQL connection.  I will work on a patch for this, so that UTF-8 is set by default for all MySQL connections, but that will not help your current situation, sadly.

**Comment by Castaglia** [comment]
Actually, I have an idea which _might_ work -- add the following to your `<Global>` section:
```
SQLNamedQuery use_utf8 FREEFORM "SET NAMES 'utf8mb4'"
SQLLog PASS use_utf8
```
The goal here is to manually tell ProFTPD to issue this SQL statement, when connecting to MySQL:
```
SET NAMES 'utf8mb4';
```
Since the code is not doing this as expected, we can use an `SQLNamedQuery` to do it for us.

Let me know if this works!

**Comment by lvxinzhi** [comment]
> SET NAMES 'utf8mb4';

HI, Castaglia, thank you for your help, by setting the above parameters, the log garbled problem saved to the database has been perfectly solved.
After setting the above parameters in Global, the proftpd service starts significantly slower, and the following warning message appears,
2022-04-03 01:28:50,574 server proftpd[9713] localhost: mod_lang/1.1: LangDefault 'zh_CN.utf8', configured for server 'ProFTPD Default Installation', is not a supported language, removing
2022-04-03 01:28:50,574 server proftpd[9713] localhost: mod_lang/1.1: Perhaps proftpd has not yet been translated into 'zh_CN.utf8'

**Comment by lvxinzhi** [comment]
> Actually, I have an idea which _might_ work -- add the following to your `<Global>` section:
> 
> ```
**> SQLNamedQuery use_utf8 FREEFORM "SET NAMES 'utf8mb4'"
> SQLLog PASS use_utf8
> ```**
> 
> The goal here is to manually tell ProFTPD to issue this SQL statement, when connecting to MySQL:
> 
> ```
> SET NAMES 'utf8mb4';
> ```
> 
> Since the code is not doing this as expected, we can use an `SQLNamedQuery` to do it for us.
> 
> Let me know if this works!

HI, Castaglia, thank you for your help, by setting the above parameters, the log garbled problem saved to the database has been perfectly solved.
After setting the above parameters in Global, the proftpd service starts significantly slower, and the following warning message appears,
2022-04-03 01:28:50,574 server proftpd[9713] localhost: mod_lang/1.1: LangDefault 'zh_CN.utf8', configured for server 'ProFTPD Default Installation', is not a supported language, removing
2022-04-03 01:28:50,574 server proftpd[9713] localhost: mod_lang/1.1: Perhaps proftpd has not yet been translated into 'zh_CN.utf8'

**Comment by lvxinzhi** [comment]
> Actually, I have an idea which _might_ work -- add the following to your `<Global>` section:
> 
> ```
**> SQLNamedQuery use_utf8 FREEFORM "SET NAMES 'utf8mb4'"
> SQLLog PASS use_utf8**
> ```
> 
> The goal here is to manually tell ProFTPD to issue this SQL statement, when connecting to MySQL:
> 
> ```
> SET NAMES 'utf8mb4';
> ```
> 
> Since the code is not doing this as expected, we can use an `SQLNamedQuery` to do it for us.
> 
> Let me know if this works!

HI, Castaglia, thank you for your help, by setting the above parameters, the log garbled problem saved to the database has been perfectly solved.
After setting the above parameters in Global, the start of the proftpd service is significantly slower.

**Comment by lvxinzhi** [comment]
> Actually, I have an idea which _might_ work -- add the following to your `<Global>` section:
> 
> ```
> SQLNamedQuery use_utf8 FREEFORM "SET NAMES 'utf8mb4'"
> SQLLog PASS use_utf8
> ```
> 
> The goal here is to manually tell ProFTPD to issue this SQL statement, when connecting to MySQL:
> 
> ```
> SET NAMES 'utf8mb4';
> ```
> 
> Since the code is not doing this as expected, we can use an `SQLNamedQuery` to do it for us.
> 
> Let me know if this works!

Hello, Castaglia, thank you for your help, through the settings of the above parameters, the problem of garbled characters is perfectly solved.
In addition, I also tested Russian, Korean, and Japanese, and there was no garbled problem.
![1](https://user-images.githubusercontent.com/5771595/161423589-7415107d-26f6-4bcf-8511-dc9be56c4cc5.png)

**Comment by Castaglia** [comment]
Excellent!  I'm glad to hear that things are working for you now.  I'll now consider this issue as fixed.  Thanks!
