### ISSUE TITLE
doc/Configuration.html is out of date

### ISSUE THREAD

**Issue by cus** [proftpd/proftpd#1429]
Documentation contained in doc/Configuration.html is out of date, for example UseSendfile directive parameters are not documented correctly, because it is missing the percentage / byte length parameter variants. If this cannot be generated automagically then I suggest removing it to avoid confusion.

E.g. googling the UseSendfile Proftd directive brings you here:

http://www.proftpd.org/docs/directives/linked/config_ref_UseSendfile.html

Which is (I guess) generated from Configuration xml and is out of date as well.

**Comment by Castaglia** [comment]
Interesting; this relates to https://github.com/proftpd/proftpd/issues/1378.  I guess changing the visible links didn't update Google's cache.

I'll delete those old files now.

**Comment by Castaglia** [comment]
I've removed the outdated documentation from this repo, and from the `www.proftpd.org` website; the above URL now results in an HTTP 404 Not Found.

Unfortunately, Google search results still (as of this writing) return that old link; I'm not sure how long it will take Google's cached results to be updated.
