### ISSUE TITLE
Add support for Ed448 host keys and the curve448-sha512 key exchange algorithm to mod_sftp

### ISSUE THREAD

**Issue by severach** [proftpd/proftpd#1437]
Related to Curve25519 (see [RFC 8731](https://datatracker.ietf.org/doc/html/rfc8731)):

Hostkey: ssh-ed448
Kex: curve448-sha512

Supported by PuTTY [0.75](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ed448.html) and WinSCP 5.20. Use puttygen to generate host key.

**Comment by Castaglia** [comment]
Is there a specific need/use case that you have, for these specific SSH hostkey and key exchange algorithms, _vs_ some of the other hostkey and key exchange algorithms?

**Comment by severach** [comment]
Curve25519 is 128 bits of security, same as ECDSA P-256. [Ed448](https://crypto.stackexchange.com/questions/67457/elliptic-curve-ed25519-vs-ed448-differences) is 224 bits of security, more than P-384, less than P-521. I'd like a non NIST algorithm close to P-521 security.

**Comment by Castaglia** [comment]
For my future reference, I think I should be able to OpenSSL for this; see:
* https://github.com/alexkrontiris/OpenSSL-x25519-key_exchange/blob/master/x25519-bob.c

only for Curve448, I'd use `NID_X448`.  And the Ubuntu 22.04 Docker image has a new enough version of `putty-tools` for interoperability testing.

**Comment by Castaglia** [comment]
Note that for my local tests, I generated the required Ed448 host key using:
```
openssl genkey -out /etc/ssh/ssh_host_ed448_key -algorithm ED448
```
The format used by _e.g._ `puttygen -t ed448 -o /etc/ssh/ssh_host_ed448_key` doesn't appear to use the [RFC 8410](https://datatracker.ietf.org/doc/html/rfc8410) format; the `-O` options for `puttygen` didn't seem to include one that would work for `mod_sftp`'s OpenSSL-based needs.

**Comment by Castaglia** [comment]
Now, using an Ubuntu 22.04 Docker image, I can verify (using PuTTy) that the ED448 host key is working, being used as expected:
```
root@66a8bc3533de:/# dpkg -l | grep putty    
ii  putty-tools             0.76-2                                  amd64        command-line tools for SSH, SCP, and SFTP

root@66a8bc3533de:/# psftp -batch -v -l docker -P 2222 docker@proftpd
Looking up host "proftpd" for SSH connection
Connecting to 172.19.0.3 port 2222
Connected to 172.19.0.3
We claim version: SSH-2.0-PuTTY_Release_0.76
Remote version: SSH-2.0-mod_sftp
Using SSH protocol version 2
Doing ECDH key exchange with curve Curve448 and hash SHA-512 (unaccelerated)
Host key fingerprint is:
ssh-ed448 448 SHA256:LOR+3Mcdt5x+FpMLVFdX6RCf1E8XGD7a0uHgoVZEhvU
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
Using username "docker".
```
I think this PR is ready to be used.  Care to try it out with your clients, @severach?

**Comment by Castaglia** [comment]
Hmm.  Once the above PR is merged, I'll work on a follow-on PR, to support Ed448 keys for hostbased and publickey authentication as well.

**Comment by severach** [comment]
I wish I had clients that could test it. I can't even do it in volume because lftp+[OpenSSH 9.0](https://www.reddit.com/r/cryptography/comments/hixxqr/ed448_ssh_keys/) doesn't support it. PuTTY, WinSCP, and FileZilla (both PuTTY based) are the only clients I can find that support it. `psftp` doesn't work for high reliability automation because it doesn't have `put -delete` or `get -delete`. The old `mget *; rm *` is a recipe for disaster. FileZilla doesn't have command line automation.

That leaves WinSCP 5.20 beta as the only automation friendly client with Ed448. I have many older WinSCP versions in the field. When the Ed448 compatible version is released I can deploy and redeploy to get Ed448 protected traffic going.

Simon Tatham gave us the first [client](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ed448.html). We need a first server so interest will pick up and other ssh vendors have something to work with.

Neither puttygen nor ssl-keygen know how to read these OpenSSL Ed448 keys. sshaudit and OpenSSL won't generate a ssh fingerprint. I had to copy my ed448 fingerprint one of these PuTTY based clients. Someday we'll have keygen interoperability but this is not that day.

Clients twiddle the hostkey order to put the stored hostkeys first. After deleting my ed25519 hostkeys I got them all to work.

```
# psftp -v -P 2222 0.0.0.6
Looking up host "0.0.0.6" for SSH connection
Connecting to 0.0.0.6 port 2222
Connected to 0.0.0.6
We claim version: SSH-2.0-PuTTY_Release_0.76
Remote version: SSH-2.0-mod_sftp
Using SSH protocol version 2
Doing ECDH key exchange with curve Curve448 and hash SHA-512 (unaccelerated)
Server also has ssh-ed25519/ecdsa-sha2-nistp384/rsa-sha2-512/rsa-sha2-256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed448 448 SHA256:JZApz24MmN3DVDUOjIW9p5pu54SM6VR7r/V2jXTYONk
The server's host key is not cached. You have no guarantee
that the server is the computer you think it is.
The server's ssh-ed448 key fingerprint is:
ssh-ed448 448 SHA256:JZApz24MmN3DVDUOjIW9p5pu54SM6VR7r/V2jXTYONk
If you trust this host, enter "y" to add the key to
PuTTY's cache and carry on connecting.
If you want to carry on connecting just once, without
adding the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) n
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
login as: chris
chris@0.0.0.6's password: 
Sent password
Access granted
Opening main session channel
Opened main channel
Started a shell/command
Connected to 0.0.0.6
Remote working directory is /
psftp> ls
Listing directory /
drwxr-xr-x    6 chris    988          4096 May 13 17:36 .
drwxr-xr-x    6 chris    988          4096 May 13 17:36 ..
drwxr-xr-x    2 1000     100          4096 Mar 28 23:15 Folder
-rw-r--r--    1 chris    988          3401 May 13 17:22 issue1439.txt
drwxr-xr-x    2 chris    988          4096 Dec  9 16:36 reports
-rw-r--r--    1 0        0               1 May 13 17:16 test
psftp> quit
Session sent command exit status 0
Main session channel closed
All channels closed
```

```
using '/etc/proftpd/ssh_host_ecdsa384_key' as 384-bit ECDSA hostkey (384 bits)
client (0.0.0.65:55885) connected to server (0.0.0.6:2224)
sent server version 'SSH-2.0-mod_sftp'
received client version 'SSH-2.0-WinSCP_release_5.20.3'
handling connection from SSH2 client 'WinSCP_release_5.20.3'
 + Session key exchange: curve448-sha512
 + Client key exchange algorithms:.curve448-sha512,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,rsa2048-sha256,rsa1024-sha1,diffie-hellman-group1-sha1,ext-info-c
 + Session host key algorithm: ssh-ed448
 + Session server hostkey: ssh-ed448
 + Client server hostkey algorithms:.ssh-ed448,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
 + Session client-to-server encryption: aes256-ctr
 + Session client-to-server encryption algorithms:.aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,chacha20-poly1305@openssh.com,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128
 + Session server-to-client encryption: aes256-ctr
 + Session client-to-server MAC: hmac-sha2-256-etm@openssh.com
 + Session client-to-server MAC algorithms:.hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com
 + Session server-to-client MAC: hmac-sha2-256-etm@openssh.com
 + Session client-to-server compression: none
 + Session server-to-client compression: none
sending acceptable userauth methods: publickey,password
client sent SSH_MSG_IGNORE message (90 bytes)
no supplemental groups found for user 'chris'
sending userauth success
user 'chris' authenticated via 'password' method
unsupported 'simple@putty.projects.tartarus.org' channel requested, ignoring
'subsystem' channel request for 'sftp' subsystem
using SFTP protocol version 6 for this session (channel ID 0)
client sent 'vendor-id' extension: { vendorName = 'Martin Prikryl', productName = 'WinSCP', productVersion = '5.20.3', buildNumber = 12378 }
disconnecting client (received EOF)
```

```
using '/etc/proftpd/ssh_host_ecdsa384_key' as 384-bit ECDSA hostkey (384 bits)
client (0.0.0.65:55895) connected to server (0.0.0.6:2224)
sent server version 'SSH-2.0-mod_sftp'
received client version 'SSH-2.0-FileZilla_3.59.0'
handling connection from SSH2 client 'FileZilla_3.59.0'
 + Session key exchange: curve448-sha512
 + Client key exchange algorithms:.curve448-sha512,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,rsa2048-sha256,rsa1024-sha1,diffie-hellman-group1-sha1,ext-info-c
 + Session host key algorithm: ssh-ed448
 + Session server hostkey: ssh-ed448
 + Client server hostkey algorithms:.ssh-ed448,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
 + Session client-to-server encryption: aes256-gcm@openssh.com
 + Session client-to-server encryption algorithms:.aes256-gcm@openssh.com,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc,chacha20-poly1305@openssh.com,3des-ctr,3des-cbc,blowfish-ctr,blowfish-cbc,arcfour256,arcfour128
 + Session server-to-client encryption: aes256-gcm@openssh.com
 + Session client-to-server compression: none
 + Session server-to-client compression: none
sending acceptable userauth methods: publickey,password
client sent SSH_MSG_IGNORE message (147 bytes)
no supplemental groups found for user 'chris'
sending userauth success
user 'chris' authenticated via 'password' method
unsupported 'simple@putty.projects.tartarus.org' channel requested, ignoring
'subsystem' channel request for 'sftp' subsystem
using SFTP protocol version 3 for this session (channel ID 0)
disconnecting client (received EOF)
```

I implemented the updated mwiede/jsch#154 in [MirthConnect](https://aur.archlinux.org/packages/mirthconnect). jsch 0.2.1 supports ed448 key pairs. No support for hostkey or kex yet. I see them in the code but they aren't in the advertised lists yet. Probably waiting for a server implementation to test with and doesn't know about PuTTY [Uppity](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ed448.html).

Other mentions: CycloneSSH 2.1.4, wolfSSL 4.4.0, Erlang SSH 4.13.2, AsyncSSH Version 2.10.1. These seem to be libraries so no clients I can test.

It's a coming!

**Comment by norrisjeremy** [comment]
@severach I am one of the maintainers of [JSch](https://github.com/mwiede/jsch) and can attest that we should fully support both `ssh-ed448` and `curve448-sha512`. However to use it:
1. For `ssh-ed448`, you will need to either use Java 15+ or add [Bouncy Castle](https://www.bouncycastle.org/java.html) to your classpath.
2. For `curve448-sha512`, you will need to either use Java 11+ or add [Bouncy Castle](https://www.bouncycastle.org/java.html) to your classpath.

If you are looking for additional clients to test with, you may want to take a look at [AsyncSSH](https://github.com/ronf/asyncssh): we utilize it for integration tests in JSch to confirm our `ssh-ed448` & `curve448-sha512` support. Whilst it is a Python library, it is should not be especially difficult to write a simple test app to confirm whether it works with ProFTPD.

@Castaglia Does ProFTPD implement support for the [openssh-v1-private-key](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key) format? That is what we used in JSch (and also is what is supported by [AsyncSSH](https://github.com/ronf/asyncssh)) for `ssh-ed448` type keys.

**Comment by norrisjeremy** [comment]
Also, I wouldn't hold your breath on seeing support for these algorithms in OpenSSH: they've indicated that they don't see any particular need to support them (see [bug 3087](https://bugzilla.mindrot.org/show_bug.cgi?id=3087)).

**Comment by norrisjeremy** [comment]
@severach I also forgot to mention: the support for `ssh-ed448` & `curve448-sha512` isn't enabled by default in JSch (since we try to keep the default crypto algorithms enabled in alignment with OpenSSH).
In order to test it with JSch, you would need to explicitly enable it.

This can be accomplished a few different ways, such as using the `jsch.kex`, `jsch.server_host_key` & `jsch.client_pubkey` properties, or by adding code to your application similar to this:
```
JSch.setConfig("kex", "curve448-sha512," + JSch.getConfig("kex"));
JSch.setConfig("server_host_key", "ssh-ed448," + JSch.getConfig("server_host_key"));
JSch.setConfig("PubkeyAcceptedAlgorithms", "ssh-ed448," + JSch.getConfig("PubkeyAcceptedAlgorithms"));
```

**Comment by severach** [comment]
My implementation is running under OpenJDK 17. That is the first LTS release that enabled all algos particularly Ed25519.

To me the reason that OpenSSH hasn't added Ed448 yet is because noone else has. Let's do it and they will follow.

After a quick patch, JSCH is working. Too bad noone but me runs Mirth with a modern JSCH.

```
using '/etc/proftpd/ssh_host_ecdsa384_key' as 384-bit ECDSA hostkey (384 bits)
client (0.0.0.5:54580) connected to server (0.0.0.6:2222)
sent server version 'SSH-2.0-mod_sftp'
received client version 'SSH-2.0-JSCH_0.2.1'
handling connection from SSH2 client 'JSCH_0.2.1'
 + Session key exchange: curve448-sha512
 + Client key exchange algorithms:.curve448-sha512,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,ext-info-c
 + Session host key algorithm: ssh-ed448
 + Session server hostkey: ssh-ed448
 + Client server hostkey algorithms:.ssh-ed448,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
 + Session client-to-server encryption: aes256-gcm@openssh.com
 + Session client-to-server encryption algorithms:.aes256-gcm@openssh.com,aes256-ctr,aes256-cbc,aes192-ctr,aes192-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
 + Session server-to-client encryption: aes256-gcm@openssh.com
 + Session client-to-server compression: none
 + Session server-to-client compression: none
sending acceptable userauth methods: publickey,password
no supplemental groups found for user 'chris'
sending userauth success
user 'chris' authenticated via 'password' method
'subsystem' channel request for 'sftp' subsystem
using SFTP protocol version 3 for this session (channel ID 0)
disconnecting client (received EOF)
```

**Comment by norrisjeremy** [comment]
@severach That is great news to hear!

FYI, not sure if you are familiar with this page or not: https://ssh-comparison.quendi.de/

Might be a good idea to submit a PR (https://github.com/fingolfin/ssh-comparison) to detail what is supported by ProFTPD.

**Comment by Castaglia** [comment]
@norrisjeremy Yes, ProFTPD supports OpenSSH's custom private key format; see Issue #793.

**Comment by Castaglia** [comment]
For my future reference, here is a Bugzilla ticket for adding this to OpenSSH: https://bugzilla.mindrot.org/show_bug.cgi?id=3923

**Comment by severach** [comment]
This Bugzilla isn't readable without an account.  https://lists.mindrot.org/pipermail/openssh-bugs/2026-February/027338.html
