### ISSUE TITLE
DelayTable not properly using documented default value

### ISSUE THREAD

**Issue by milahu** [proftpd/proftpd#1440]
bad links in http://www.proftpd.org/docs/directives/index.html

http://www.proftpd.org/docs/contrib/mod_delay.html
should be
http://www.proftpd.org/docs/modules/mod_delay.html

**Comment by Castaglia** [comment]
Thanks!  I'll get this fixed later this evening.

**Comment by milahu** [comment]
i also noticed that [DelayTable](http://www.proftpd.org/docs/modules/mod_delay.html#DelayTable) has default value `none`

log says

```
mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module
```

fixed by adding `DelayTable /var/proftpd/proftpd.delay`

**Comment by Castaglia** [comment]
Yeah, I'm not sure how to differentiate that.  Specifically, there is no default value configured for the `DelayTable`, in the `mod_delay` code.  For the module docs, when there is no default value, they usually say "Default: None".  But in this case, "none" is ambiguous, as that _is_ a valid parameter value for the `DelayTable` directive.

Any suggestions/thoughts on how a better term might be for this case?

**Comment by milahu** [comment]
document the default value as `None` (!= `"none"`)

maybe add the option `DelayEnable yes|no`

> If the DelayTable parameter is "none", then the mod_delay module will not store timing data.

add something like
"If the DelayTable parameter is None, then the mod_delay module will leave you a log message."
&rarr; "verbose disable"

> mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module

should say something like
"disabling the mod_delay module, as no option was set. To disable mod_delay and hide this message, set DelayTable none. To enable mod_delay, set DelayTable or DelayOnEvent"

**Comment by Castaglia** [comment]
Actually, could you provide the ProFTPD configuration you're using, that has `DelayTable none`?  The ProFTPD source doesn't ship with any configuration that uses that, so I'm wondering how you might be encountering that behavior.

Per the [`DelayTable` docs](http://www.proftpd.org/docs/modules/mod_delay.html#DelayTable), the default is indeed a path to a file (see [here](https://github.com/proftpd/proftpd/blob/master/modules/mod_delay.c#L2007)).  I'll see if I can locally reproduce the behavior you're seeing, to see if some other bit of code is unexpectedly interfering with that default.

**Comment by Castaglia** [comment]
OK, I've reproduced this behavior; it's from [this commit](https://github.com/proftpd/proftpd/commit/8cd024396a56ef0924a63bda20f9f4d9621e49ca), for [Bug#4020](http://bugs.proftpd.org/show_bug.cgi?id=4020), and is thus a regression.  I'll use this ticket to address it (and will update the ticket title accordingly).

**Comment by Castaglia** [comment]
Thanks for reporting the `DelayTable` default value discrepancy; turned out to be a bug (the docs were right, the code was wrong).  This should now be fixed in master.
