### ISSUE TITLE
Support customizing SSH ciphers, digests, key exchanges via SFTPClientMatch

### ISSUE THREAD

**Issue by severach** [proftpd/proftpd#1444]
As I scan the logs I'm disappointed at how often inferior encryptions are selected. ssh-rsa is picked over Curve25519 or ecdsa. sha1 is picked over sha2. 128 is picked over 256. Non -etm is picked over -etm. It's erratic because every client has a different order. Client order would be fine if the order was sensible to the platform but they aren't. Even if I could submit bug fixes to the dozens of clients out there, that won't fix the old versions. I can't disable any more algorithms because I need to support old clients. I don't want the newer clients picking the bad algorithms.

I made a patch to log the client algorithms after each session log and I can see that it always picks the leftmost matching client algorithm, which is according to [RFC4253](https://www.rfc-editor.org/rfc/rfc4253#section-7.1).

With a little test I found that the client and server transmit algorithms at the same time. If the server waits a bit for the client to transmit, the server can report a short list with all the undesirables that the client would pick trimmed out.

Server: A,B,C,D,E,F
Client: F,E,A,C,B

Server only reports: A
Server could also report: A B C

It could also be done with a [Key Re-Exchange](https://www.rfc-editor.org/rfc/rfc4253#section-9). The server could issue this immediately and report the short lists if it sees that a leftmost matching server algorithm was not selected.

It's not a problem with garbage clients. OpenSSH is the worst offender and what drew my attention to find the problem. At least WinSCP and FileZilla look right if you're not paying attention.

There's no way to specify host key order so that might need to be hard coded or calculated from SFTPKeyExchanges.

**Comment by severach** [comment]
That would be fine. I only care about the legit users. Hack attempts can negotiate the lowest possible if they want or get kicked from spamming an invalid client banner.

**Comment by Castaglia** [comment]
This should now be possible using the code in master.  Thanks!

**Comment by severach** [comment]
The match for SFTPClientMatch seems to be case sensitive

`error "fatal: SFTPClientMatch: : unknown SFTPClientMatch key: 'SFTPCiphers' on line"`

As copied out of the patch, `sftpCiphers` works.

The match should either be case insensitive to be more like the rest of the config or the same case as published docs.

**Comment by Castaglia** [comment]
Yes, both of these differences are deliberate.  The published `SFTPClientMatch` docs _do_ show the lowercase `sftpCiphers` key name [here](https://github.com/proftpd/proftpd/blob/master/doc/contrib/mod_sftp.html#L471).  And the value is a comma-separated list because of how the `SFTPClientMatch` directive works: a pattern, a key, and a value.  The value is a single value -- thus the providing of a list of algorithm names by using a comma-separated list.

**Comment by severach** [comment]
It's all working for me so I'm good so long as it's documented with notes for the odd behavior.

I had considered a client match but I didn't suggest it because I didn't expect SFTPClientMatch to clean up the poor algorithms so well. I have all connections at their best using only 14 exception lines. The holdouts are FlowSsh, FTPGetter3, JSCH old versions, SecureBlackbox, WinSCP old versions, and WS_FTP.

Best policy is strict default and loosen per client. This gives a good score on [SSHAudit](https://www.sshaudit.com/), maximizes security for all clients, minimizes exceptions, kicks hack attempts using old clients we don't support, and documents which clients need an upgrade. Removing exceptions for upgraded clients does not affect default security.

Consider adding hostkey algorithms so I can keep `ssh-rsa` away from modern clients that support better. Fortunately I don't have any `ssh-dss` only clients so I don't need that one.

Going through logs to fix more clients I noticed this malarkey. According the [RFC](https://www.rfc-editor.org/rfc/rfc4253#section-4.2) this looks like a bug in FlowSSH.

```
received client version 'SSH-2.0-7.41 FlowSsh: Secure Exchange SSH'
handling connection from SSH2 client '7.41'
```
