### ISSUE TITLE
I could not create etc/ directory

### ISSUE THREAD

**Issue by bedna-KU** [proftpd/proftpd#146]
Hey all,

I could not create etc/ directory in FTP user root directory.
Through FTP client = Permissions denied
Server log (proftpd) = Permissions denied error 550

**Comment by Castaglia** [comment]
See:
  http://www.proftpd.org/docs/modules/mod_rlimit.html#RLimitChroot

**Comment by bedna-KU** [comment]
Yes, this is it.
Thanks.
