### ISSUE TITLE
Feature-request: "IncludeOptional" similar to Apache httpd

### ISSUE THREAD

**Issue by SlowFox71** [proftpd/proftpd#1473]
### What I Expected/Wanted

My httpd configuration contains a line
```
IncludeOptional /var/www/*/custom/config/apache*.conf
```
to include all vhosts which are configured (some might be disabled or do not allow web access for whatever reason). I'd like to do the same with proftpd, but
```
Include /var/www/*/custom/config/proftpd.conf
```
fails as soon as there exists one directory where no `proftpd.conf` file exists.

I can't see a good reason for this behavior (issuing a warning and continuing with the existing files would be ideal in my eyes), but it is consistent with Apache httpd. However, http has `IncludeOptional` fixing the problem - but proftpd has not.

If I understand it correctly this should be easy to implement by (conditionally) skipping lines 1146-1148 in `src/parser.c`.

**Comment by Castaglia** [comment]
One of the reasons I deliberately didn't copy this particular Apache behavior is because I think it allows for configurations that silently fail, which can surprise admins.  By failing early, as ProFTPD does, the admins are more likely to notice the problems, and be forced to fix things -- leading to a less surprising configuration.

**Comment by SlowFox71** [comment]
Point taken.

Apache started the same way, but they added IncludeOptional later on; depending on the use-case this is really nice.

I tried to implement it in https://github.com/proftpd/proftpd/compare/master...SlowFox71:master but as I am completely unfamiliar with unit tests and not sure about coding style, I have not create a pull request.

**Comment by Castaglia** [comment]
I dug up the Apache email thread where their `IncludeOptional` directive originated; see:
* https://lists.apache.org/thread/kyrddrc59bk7r9ym93g0dpxor6570ydj

While I understand the desire behind this feature request, I don't think the convenience is worth adding this.  That is, the perception of inconvenience of being strict, and requiring that the configuration be correct on startup, is balanced by the convenience of having an explicit working configuration.  I am not inclined to add this "optional include" functionality in ProFTPD.
