### ISSUE TITLE
include/openbsd-blowfish.h breaks compilation on Solaris (found in 1.3.8rc4)

### ISSUE THREAD

**Issue by Sashan** [proftpd/proftpd#1494]
### What I Did

I've tried to build proftpd-1.3.8rc4 on Solaris

### What I Expected/Wanted

compilation fails with errors as follows
```
"../include/openbsd-blowfish.h", line 46: syntax error before or at: u_int32_t
"../include/openbsd-blowfish.h", line 56: syntax error before or at: *
"../include/openbsd-blowfish.h", line 56: member cannot be function: Blowfish_encipher
"../include/openbsd-blowfish.h", line 57: syntax error before or at: *
"../include/openbsd-blowfish.h", line 57: member cannot be function: Blowfish_decipher
```

there are no `u_int32_t` (and similar definitions on Solaris).
### ProFTPD Version and Configuration

N/A

In order to get it built I had to apply a small diff as found in [PR#1493](https://github.com/proftpd/proftpd/pull/1493)

**Comment by Castaglia** [comment]
@Sashan Can you see if https://github.com/proftpd/proftpd/pull/1496 addresses the issue for you, please?

**Comment by Sashan** [comment]
Hello,

yes it works fine. change is perfect.
thank you very much for quick turnaround.

have a nice
weekend.

**Comment by Castaglia** [comment]
Now fixed in master.   Thanks!
