### ISSUE TITLE
mod_ifsession doesn't change the effect of SFTPMaxChannels

### ISSUE THREAD

**Issue by zrlw** [proftpd/proftpd#1500]
### What I Did
1.  make proftpd 1.3.7d with module mod_ifsession:
```
./configure --with-modules=mod_ratio:mod_readme:mod_tls:mod_sftp:mod_ifsession
```
'proftpd -V' shows mod_ifsession is included in the --with-modules list.
3.  set SFTPMaxChannels in proftpd.conf, the snippet is:
```
<IfUser testUser>
  SFTPMaxChannels 100
</IfUser>
```
4.  connect proftpd by JSch
```
JSch = new JSch();
jsch.addIentity(privateKeyPath, passPhrase); 
Session session = jsch.getSession('testUser', proftpd_ip, proftpd_port);
session.connect(connect_timeout);
List<Channel> sftpChannelList = new ArrayList<>(100);
for (int i=0; i<100; i++) {
    Channel channel = session.openChannel("sftp");
    sftpChannelList.add(channel);
    channel.connect();
}
...
```

### What I Expected/Wanted
we expected 100 channels were opened simultaneously for user 'testUser', but only 10 channels were opened actually.
if SFTPMaxChannels value was set directly without  ```<IfUser>```,  100 channels will be opened.

### ProFTPD Version and Configuration
```
Version: 1.3.7d (maint)
Platform: LINUX [Linux 3.10.0-1127.8.2.el7.x86_64 x86_64]
Built With:
configure '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var/run' '--mandir=/usr/share/man' '--without-pam'
    '--disable-auth-pam '--enable-nls' '--enable-openssl'
    '--with-modules=mod_ratio:mod_readme:mod_tls:mod_sftp:mod_ifsession'
```

**Comment by zrlw** [comment]
it seemed that mod_sftp.c has nothing do with proftpd session.

**Comment by Castaglia** [comment]
Why are you wanting to limit the number of channels per user?  Currently the `SFTPMaxChannels` directive is looked up in `mod_sftp` at [session init time](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/mod_sftp.c#L2715) (meaning when a TCP client connects); the `mod_ifsession` changes would happen later, after authentication -- but `mod_sftp` does not re-lookup any changed `SFTPMaxChannels` then.  It could be made to do so, yes -- but why would you want that behavior?

**Comment by zrlw** [comment]
because we want upload multiple files simultaneously with only one connection which is limited by the server side.

**Comment by zrlw** [comment]
we tested creating multiple remote directorys with one JSch channelSftp shared between multiple threads but failed, even we synchronized channelSftp mkdir method, proftpd got mixed requests and created wired directorys.

**Comment by Castaglia** [comment]
I'm not sure I understand what you're trying to accomplish, on the client end of things.  But I'll work on a patch to have `SFTPMaxChannels` honor any `<IfUser>`/`<IfGroup>` configurations.

**Comment by zrlw** [comment]
> I'm not sure I understand what you're trying to accomplish, on the client end of things. But I'll work on a patch to have `SFTPMaxChannels` honor any `<IfUser>`/`<IfGroup>` configurations.

yes, it's what we want to do.  SFTPMaxChannels value could be adjusted for special users.

**Comment by Castaglia** [comment]
@zrlw [This PR](https://github.com/proftpd/proftpd/pull/1501) should allow your configuration to work as desired, if you'd care to test it out...

**Comment by zrlw** [comment]
> @zrlw [This PR](https://github.com/proftpd/proftpd/pull/1501) should allow your configuration to work as desired, if you'd care to test it out...

it works for us.

**Comment by Castaglia** [comment]
This is now fixed in master.  Thanks!
