### ISSUE TITLE
error encrypting aes256-ctr data for client

### ISSUE THREAD

**Issue by fre4ki** [proftpd/proftpd#1519]
Hey guys,

i have trouble to setup a SFTP server. When i'm trying to connect with WinSCP i get an "Authentication failed." error.

The OS is **Ubuntu 22.04.1** and i installed all from Ubuntu repository.

**Installed-Packages**
```
apt list --installed | grep proftp

proftpd-core/jammy,now 1.3.7c+dfsg-1build1 amd64 [installed]
proftpd-doc/jammy,now 1.3.7c+dfsg-1build1 all [installed,automatic]
proftpd-mod-crypto/jammy,now 1.3.7c+dfsg-1build1 amd64 [installed]
```

**proftpd -vv -c /etc/proftpd/proftpd.conf** 
```
ProFTPD Version: 1.3.7c (maint)
  Scoreboard Version: 01040003
  Built: Fri Dec 3 2021 13:35:22 UTC

Loaded modules:
  mod_ifsession/1.3
  mod_readme/1.0
  mod_memcache/0.1
  mod_ifversion/0.1
  mod_deflate/0.6
  mod_copy/0.6
  mod_unique_id/0.2
  mod_facl/0.6
  mod_sftp_pam/0.3
  mod_sftp/1.0.1
  mod_site_misc/1.6
  mod_ratio/3.3
  mod_shaper/0.6.6
  mod_exec/0.9.16
  mod_dynmasq/0.5
  mod_wrap2_file/1.3
  mod_wrap2/2.0.7
  mod_ban/0.8
  mod_load/1.0.1
  mod_rewrite/1.0
  mod_quotatab_radius.c
  mod_quotatab_file.c
  mod_quotatab/1.3.1
  mod_radius/0.9.3
  mod_ctrls_admin/0.9.9
  mod_lang/1.1
  mod_ctrls/0.9.5
  mod_cap/1.1
  mod_auth_pam/1.2
  mod_dso/0.5
  mod_facts/0.6
  mod_delay/0.7
  mod_site.c
  mod_log/1.0
  mod_ls.c
  mod_auth.c
  mod_auth_file/1.0
  mod_auth_unix.c
  mod_rlimit/1.0
  mod_xfer.c
  mod_core.c
```

**sftp.log:**
```
2022-08-23 20:15:00,543 mod_sftp/1.0.1[2355]: using '/etc/proftpd/hostkeys/host_ecdsa_key' as 256-bit ECDSA hostkey
2022-08-23 20:15:00,545 mod_sftp/1.0.1[2355]: sent server version 'SSH-2.0-mod_sftp'
2022-08-23 20:15:00,545 mod_sftp/1.0.1[2355]: received client version 'SSH-2.0-WinSCP_release_5.21.2'
2022-08-23 20:15:00,545 mod_sftp/1.0.1[2355]: handling connection from SSH2 client 'WinSCP_release_5.21.2'
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session key exchange: curve25519-sha256
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session server hostkey: ssh-ed25519
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session client-to-server encryption: aes256-ctr
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session server-to-client encryption: aes256-ctr
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session client-to-server MAC: hmac-sha2-256
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session server-to-client MAC: hmac-sha2-256
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session client-to-server compression: none
2022-08-23 20:15:00,572 mod_sftp/1.0.1[2355]:  + Session server-to-client compression: none
2022-08-23 20:15:00,692 mod_sftp/1.0.1[2355]: error encrypting aes256-ctr data for client: (unknown)
2022-08-23 20:15:00,693 mod_sftp/1.0.1[2355]: disconnecting (my-client-ip) (Application disconnected)
2022-08-23 20:15:00,693 mod_sftp/1.0.1[2355]: error encrypting aes256-ctr data for client: (unknown)
```

**sfp.conf**
```
<IfModule mod_sftp.c>

    <Global>
        SFTPHostKey /etc/proftpd/hostkeys/host_rsa_key
        SFTPHostKey /etc/proftpd/hostkeys/host_dsa_key
        SFTPHostKey /etc/proftpd/hostkeys/host_ecdsa_key
        SFTPHostKey /etc/proftpd/hostkeys/host_ed25519_key
        SFTPCompression off
    </Global>

    <VirtualHost 0.0.0.0>
        SFTPEngine on
        Port 2222

        DefaultRoot ~
        RootLogin off
        RequireValidShell off

        SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u

        SFTPAuthMethods publickey password

        SFTPLog /var/log/proftpd/sftp.log

        <Limit LOGIN>
            DenyGroup !sftp-only
        </Limit>
    </VirtualHost>

</IfModule>
```

**All what i've changed from default proftpd.conf**
```
ServerName "my.fqdn"
DefaultRoot ~
RootLogin off
RequireValidShell off
```

I hope someone can help me to troubleshoot this.

Thank you guys!

fre4ki

**Comment by Castaglia** [comment]
What does `openssl version -a` show?  This sounds quite similar to Issue #1448.

**Comment by fre4ki** [comment]
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Mon Jul  4 11:20:23 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-Q8dQt3/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfffa32034f8bffff:0x27ab

**Comment by fre4ki** [comment]
I'm not sure what i can do. I installed the System already several times and test different settings.

**Comment by Castaglia** [comment]
Yes, that OpenSSL 3.x versions means that this is the same as Issue #1448.

Unfortunately, this means that to fix this, you will need to upgrade to ProFTPD 1.3.7e/1.3.8rc4, _or_ configure [`SFTPCiphers`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPCiphers) such that the following algorithms are omitted:
* `aes128-ctr`
* `aes192-ctr`
* `aes256-ctr`

However, going with the `SFTPCiphers` route usually makes SFTP clients unhappy with the smaller remaining algorithm selection.

**Comment by fre4ki** [comment]
When will the Ubuntu repository be updated to version 1.3.7e? Ist there another official apt source?

**Comment by Castaglia** [comment]
The ProFTPD Project doesn't supply packages; we only provide/release the source code.  Package maintainers like @hpreusse might be able to answer your question about package availability...

**Comment by hpreusse** [comment]
@fre4ki @Castaglia : the issue should be solved in Debian for a while now. Please bother your friendly Ubunty maintainer: for any reason they decided to update the ssl lib to 3.0.x, but did not care about the programs using it.

**Comment by fre4ki** [comment]
@hpreusse Debian, but not Ubuntu. I choosed Ubuntu because the packages are more "up-to-date".

It seems i have to install from source or choose Debian, even when i'm not so happy with this solution. Ubuntu 22.04 is out for a while now and when i'm installing a new server, i'm not choosing an out-dated version (like Ubuntu 20.04). The server ist just a FTP Server, no more dependencies. I thought default packages like ProFTPd should work..

Thank you guys for your time.

If there are any news, please feel free to post it here.

**Comment by Spymaker247** [comment]
We are using ProFTPD 1.3.8 (CentOS7 with Directadmin) and looks like still problem exist.
We are trying to use Mountain Duck client for SFTP. This is reply from Mountain Duck Team:

_Mountain Duck selects the CTR based algorithms instead of the CBCs which is completely fine:
Negotiated algorithms [ kex=curve25519-sha256; sig=rsa-sha2-512; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none;  ]
You now hit issue https://github.com/proftpd/proftpd/issues/1519 which is resolved as of ProFTPD 1.3.7e. Also refer to https://github.com/proftpd/proftpd/issues/1519#issuecomment-1226320482. Note that it might be possible that other clients select other algorithms which may work. But as long as the client selects an advertised (from the server) algorithm (which Mountain Duck does) the server must accept it.
As per the description in their bug report https://github.com/proftpd/proftpd/issues/1519 this should be resolved in 1.3.8_

**Comment by Castaglia** [comment]
@Spymaker247 could you provide the output of `proftpd -V` on your system, please?

**Comment by hpreusse** [comment]
@Spymaker247: if you applied the workaround above and disabled the CTR based algorithms you probably have to disable them again.

**Comment by Spymaker247** [comment]
Compile-time Settings:
  Version: 1.3.8 (stable)
  Platform: LINUX [Linux 3.10.0 x86_64]
  OS/Release:
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    CPE_NAME="cpe:/o:centos:centos:7"

    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"

  Built: Thu Jan 26 2023 13:34:45 EET
  Built With:
    configure  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var/run' '-                                                                                                                                                              -mandir=/usr/share/man' '--without-pam' '--disable-auth-pam' '--enable-nls' '--e                                                                                                                                                              nable-openssl' '--with-modules=mod_ratio:mod_readme:mod_tls:mod_sftp'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing
  LDFLAGS: -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -lsodium -lcap  -lssl  -lcrypto -lcrypt -ldl  -liconv

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    + curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (OpenSSL 1.0.2k  26 Jan 2017, FIPS enabled)
    - PCRE support
    - PCRE2 support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
Hmm.  @Spymaker247 Would it be possible to get the `SFTPLog` messages for one of these sessions having issues, so that we can see if there are other factors involved?

**Comment by Spymaker247** [comment]
Defug Log file is attached.
[MountainDuck_problem_ProFTPd.txt](https://github.com/proftpd/proftpd/files/10973790/MountainDuck_problem_ProFTPd.txt)

**Comment by Castaglia** [comment]
> Debug Log file is attached. [MountainDuck_problem_ProFTPd.txt](https://github.com/proftpd/proftpd/files/10973790/MountainDuck_problem_ProFTPd.txt)

Thanks.  That looks like ProFTPD debug logging.  Would it be possible to configure an [`SFTPLog`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPLog) file, for `mod_sftp`-specific logging, which might show more details about what's going on?

**Comment by Spymaker247** [comment]
Sorry I am not so good on this: can you able to advice in steps what I need to do.
Also please find attached Mountain Duck: maybe can provide some extra information.
[mountainduck_.log.txt](https://github.com/proftpd/proftpd/files/10978599/mountainduck_.log.txt)

**Comment by Castaglia** [comment]
@Spymaker247 No worries.

In the ProFTPD configuration section for `mod_sftp`, I'm hoping you can add something like this:
```
SFTPLog /path/to/your/ftpd/sftp.log
```
obviously adjusting the path to the right directory for your setup.  You will then need to restart ProFTPD.

After this, the `mod_sftp` module will write SFTP-specific log messages to the configured `SFTPLog` file, including issues it may be having with the "aes256-ctr" cipher for your client.  I'm hoping those log messages will also provide more detail for tracking this down.  Thanks!

**Comment by Castaglia** [comment]
Thanks for the provided client-side logs.  In them, we can see that it is definitely `mod_sftp` which is closing the connection, early on in the key exchange phase, for some reason -- hopefully the above `SFTPLog` entries can tell us:
```
2023-03-14 12:21:03,918 [sshj-Reader-vps.server/xxx.xxx.xxx.xxx:23-1678796463918
] INFO  ch.cyberduck.core.sftp.SFTPSession - Negotiated algorithms [ kex=curve25
519-sha256; sig=rsa-sha2-512; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC
=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none;  ]
2023-03-14 12:21:03,918 [sshj-Reader-vps.server/xxx.xxx.xxx.xxx:23-1678796463918
] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_
INIT
2023-03-14 12:21:04,017 [sshj-Reader-vps.server/xxx.xxx.xxx.xxx:23-1678796463918
] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (
reason=BY_APPLICATION, msg=Application disconnected)
2023-03-14 12:21:04,017 [sshj-Reader-vps.server/xxx.xxx.xxx.xxx:23-1678796463918] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Application disconnected
net.schmizz.sshj.transport.TransportException: Application disconnected
        at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:543) ~[Cyberduck.Protocols.DLL:?]
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:499) [Cyberduck.Protocols.DLL:?]
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:114) ~[Cyberduck.Protocols.DLL:?]
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[Cyberduck.Protocols.DLL:?]
        at net.schmizz.sshj.transport.Reader.run(Reader.java:60) [Cyberduck.Protocols.DLL:?]
2023-03-14 12:21:04,017 [sshj-Reader-vps.server/xxx.xxx.xxx.xxx:23-1678796463918] WARN  ch.cyberduck.core.sftp.SFTPSession - Disconnected BY_APPLICATION
```
