### ISSUE TITLE
readdir slowly and high cpu load if the directory has more than 200,000+ subdirectories.

### ISSUE THREAD

**Issue by zrlw** [proftpd/proftpd#1528]
### What I Did
On centos7, proftpd will take more than 10+seconds to read a directory (deal with 1000+ `ls directory` requests simultaneously from 100 ftp sessions) which has more than 200,000+ subdirectories, and CPU load will be 95+,  but the internal-sftp of centos7 takes only 1~2 seconds.
```
the directory structure is: 
a[i]/b[j]/c[k]/d[l]/files
i=1~10, j=1~10, k=1~10, l=1~200
```

it seemed that this problem has already existed for a long time.  see:
#937
#1314 

### ProFTPD Version and Configuration
proftpd 1.3.8rc4

Centos 7.4 (x86_64)
the file system type of proftpd server directory is xfs.

**Comment by zrlw** [comment]
internal-sftp reads up to 100 entries in one message.  
https://github.com/openssh/openssh-portable/blob/730a80609472ee0451c99482d75c9c41f3ebc42d/sftp-server.c#L1161

sftp client will keep sending READDIR request until receiving SSH_FX_EOF signal from sftp server, such as:
https://github.com/is/jsch/blob/addb8e3a0ebd71cbbf51cf6ba746e8e128df713c/src/main/java/com/jcraft/jsch/ChannelSftp.java#L1639

it might be the reason.

**Comment by zrlw** [comment]
The default mod_sftp channel packet size (channelPacketSize) of proftpd is 32KB, it could only take about 20+ entries for each readdir operation.

**Comment by zrlw** [comment]
the default value of ```FSCachePolicy``` (internal filesystem-related cache) should be set to ```off``` instead of  ```maximum number of entries is 3000, and the default maximum age is 3 seconds```.
http://www.proftpd.org/docs/modules/mod_core.html#FSCachePolicy

FSCachePolicy is horrible for listing large directory, we tested it by ```sftp``` command, it will take 60+ seconds and 95+ cpu to list a directory which has 5000 files, but it will take less than 3 seconds to list the same directory by turning ```FSCachePolicy``` off.

**Comment by Castaglia** [comment]
Thanks for posting the performance data for this particular use case.  It's difficult to pick an appropriate default value for `FSCachePolicy`, given the wide disparity in filesystems and layouts that various installations will have.  I'm not sure how common it is to have a single directory with 200K+ entries, but it is useful to know how `FSCachePolicy` affects directory listing of such directories.  I suspect that you'd see similar latency/impact when listing the same directory via FTP as when listing it via SFTP.

**Comment by Castaglia** [comment]
@zrlw Would you care to verify that https://github.com/proftpd/proftpd/pull/1541 does what you'd prefer, in your testing/setup?

**Comment by zrlw** [comment]
> @zrlw Would you care to verify that #1541 does what you'd prefer, in your testing/setup?

it works for us.

**Comment by Castaglia** [comment]
This fix (disabling `FSCachePolicy` by default) has been merged to master.  Thanks!
