### ISSUE TITLE
trying to compile mov_vroot with the current proftpd master

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#153]
Attempting to compile the latest in proftpd git with the latest in mod_vroot and the follwing compile errors are showing up. This has only occurred recently. Last time I ran this was about a month ago without incident.

This is on Centos7

gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include -I/usr/include -I/usr/include/mysql -I/usr/include/mysql -DBAN_LIST_MAXSZ=8096 -Wall -c mod_vroot.c
mod_vroot.c: In function 'set_vrootserverroot':
mod_vroot.c:1518:19: warning: dereferencing 'void *' pointer [enabled by default]
   if (cmd->argv[1][pathlen - 1] != '/') {
                   ^
mod_vroot.c:1518:3: error: void value not ignored as it ought to be
   if (cmd->argv[1][pathlen - 1] != '/') {
   ^
make[1]: *** [mod_vroot.o] Error 1
make[1]: Leaving directory `/tmp/proftpd/modules'
make: *** [modules] Error 2

**Comment by Castaglia** [comment]
This is more properly an issue with `mod_vroot`, not with proftpd; I've opened a separate (issue)[https://github.com/Castaglia/proftpd-mod_vroot/issues/7] in the `mod_vroot` repo for this.

**Comment by Castaglia** [comment]
This is now fixed in the master branch of the [mod_vroot](https://github.com/Castaglia/proftpd-mod_vroot) repo.

**Comment by tspicer** [comment]
Castaglia,

Thanks. It was not clear to me where the issue resided so it is good to know it was solvable.
