### ISSUE TITLE
Access to a folder on second drive

### ISSUE THREAD

**Issue by w202mg** [proftpd/proftpd#1538]
Hey,
I think is not an issue of proftpd but I don't know where to ask. The forum the homepage is linking to is not reachable.

### What I Did

Changed the user home dir in the config file to a dir in a drive mounted under /media/cloud. This was used before for Nextcloud (owner is www-data). The dir /media/cloud/torrents has owner "ftpuser" and using other home dirs it works.

### What I Expected/Wanted

I expected to use a dir on my second big HDD for to be accessed through FTP. FTP client is not connecting at all (wrong credentials). Using the drive where my Debian 11 is installed all runs well.

### ProFTPD Version and Configuration

Proftpd version is 1.3.7a

/etc/proftpd/conf.d/custom.conf
```
# Ftp user doesn't need a valid shell
<Global>
    RequireValidShell off
</Global>
# If desired turn off IPv6
UseIPv6 off
# Default directory is ftpusers home
DefaultRoot ~ ftpuser
# Limit login to the ftpuser group
<Limit LOGIN>
    DenyGroup !ftpuser
</Limit>
```

/etc/passwd
`ftpuser:x:1002:1003:,,,:/media/cloud/torrents:/bin/false`

**Comment by Castaglia** [comment]
What does [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html) show, when that user attempts to log in?

**Comment by Castaglia** [comment]
If there's nothing else to add to this ticket, I'd like to close it.
