### ISSUE TITLE
Problem with proftpd and sftp protocol names

### ISSUE THREAD

**Issue by Q-coder** [proftpd/proftpd#1544]
I try to make a connection from an sftp client to proftp with the mod_sftp module. 
ProFTPD Version 1.3.8rc5 

Client terminates with error : 
Bad remote protocol version identification: 'SSH-2.0-'
If I change : include/mod_sftp/mod_sftp.h
Line:
#define SFTP_ID_PREFIX          "SSH-2.0-"
to 
#define SFTP_ID_PREFIX               "SSH-2.0-OpenSSH_8.0" 
the client accepts the connection. 
Both server and client are RHEL 8.6 systems.
Is this a known configuration issue somewhere ? or is it eventually a bug ? It's hard to find anything specific when googling this issue.

Kind Regards,
Gerhard

**Comment by Castaglia** [comment]
What's the SFTP client that you're using, that has this behavior?  This is certainly not expected...

**Comment by Q-coder** [comment]
The sftp binary does not provide any version number it's the standard sftp program that is deployed with the base RHEL 8.6 installation.
Updating Subscription Management repositories.
openssh-clients-7.8p1-4.el8.x86_64 : An open source SSH client applications
Repo        : rhel-8-for-x86_64-baseos-rpms
Matched from:
Filename    : /usr/bin/sftp

This is an example that fails :
 [srv-t-migration-ftp@t-hubftpcs11 ~]$ sftp -vvv -o "Port=2222" myserver
OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 50: Applying options for *
debug1: /etc/ssh/ssh_config line 57: Deprecated option "useroaming"
debug2: resolving "myserver" port 2222
debug2: ssh_connect_direct
debug1: Connecting to d-hubftpcs11 [xxx.xxx.xxx.xxx] port 2222.
debug1: Connection established.
debug1: identity file /home/myuser/.ssh/id_rsa type -1
debug1: identity file /home/myuser/.ssh/id_rsa-cert type -1
debug1: identity file /home/myuser/.ssh/id_dsa type -1
debug1: identity file /home/myuser/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0
Bad remote protocol version identification: 'SSH-2.0-'
Connection closed.
Connection closed

**Comment by Q-coder** [comment]
I guess I found the solution in the FAQ. So sorry about the noise. It's not too obvious though. But after testing it I can confirm that it works.

Question: When a client first connects to mod_sftp and starts the SSH handshake, the client sees that mod_sftp provides an SSH version identifier like "SSH-2.0-mod_sftp/0.9.8". Is there any way I can tell mod_sftp to hide/change that version?
Answer: Yes. As of proftpd-1.3.5rc1, the mod_sftp module will honor the [ServerIdent](http://www.proftpd.org/docs/modules/mod_core.html#ServerIdent) directive.

For example, to see just "SSH-2.0-mod_sftp", without any mod_sftp version suffix, use the following within your mod_sftp <VirtualHost>:

  # Tell mod_sftp to not reveal its module version in the SSH version
  # identification
  ServerIdent off
You can also use ServerIdent to make mod_sftp say it is something else completely, like this:
  # Tell mod_sftp to advertise itself as an OpenSSH server
  ServerIdent on "OpenSSH_5.6p1"

Kind Regards,
Gerhard
