### ISSUE TITLE
mod_sftp should advertise standard extensions for protocol version 3

### ISSUE THREAD

**Issue by abriel** [proftpd/proftpd#1570]
https://github.com/proftpd/proftpd/blob/15121e7090cfc747c6c760ca3e16ce3da85e7442/contrib/mod_sftp/fxp.c#L7987

When client sends a INIT request with protocol version 3, server sends back a confirmation along with a list of supported versions and a list of supported extensions. Example:
```
b'\x00\x00\x00\x03\x00\x00\x00\x08versions\x00\x00\x00\t2,3,4,5,6\x00\x00\x00\x11fsync@openssh.com\x00\x00\x00\x011\x00\x00\x00\x18posix-rename@openssh.com\x00\x00\x00\x011\x00\x00\x00\x13statvfs@openssh.com\x00\x00\x00\x012\x00\x00\x00\x14fstatvfs@openssh.com\x00\x00\x00\x012\x00\x00\x00\x14hardlink@openssh.com\x00\x00\x00\x011\x00\x00\x00\x0ehome-directory\x00\x00\x00\x011'
```
It is python representation, so part of bytes are shown as hex code, part of bytes as normal charters if they belong to ascii.
With protocol version 3, server announces an openssh extensions only.
While more extensions are working fine (e.g. check-file) but not announced.

----

When client sends a INIT request with protocol version 6, server sends back more rich announce:
```
b'\x00\x00\x00\x06\x00\x00\x00\x08versions\x00\x00\x00\t2,3,4,5,6\x00\x00\x00\x07newline\x00\x00\x00\x01\n\x00\x00\x00\nsupported2\x00\x00\x00[\x80\x00\x00\xad\x00\x00\x00\x00\x00\x00\x01\x87\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x01\x0c\x01\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\ncheck-file\x00\x00\x00\tcopy-file\x00\x00\x00\x0fspace-available\x00\x00\x00\tvendor-id\x00\x00\x00\x11fsync@openssh.com\x00\x00\x00\x011\x00\x00\x00\x18posix-rename@openssh.com\x00\x00\x00\x011\x00\x00\x00\x13statvfs@openssh.com\x00\x00\x00\x012\x00\x00\x00\x14fstatvfs@openssh.com\x00\x00\x00\x012\x00\x00\x00\x14hardlink@openssh.com\x00\x00\x00\x011\x00\x00\x00\x0ehome-directory\x00\x00\x00\x011'
```
Problem is that paramiko library does not work well on protocol version 6.

**Question**: Can we announce full list of supported extensions even client initiates a protocol version 3? May be in a plain format, not in "supported2" format as done in protocol 6. At least check-file extension is usable any way, no matter if protocol 3 or 6. Is it a limitation by a RFC?

Thanks!

**Comment by Castaglia** [comment]
It is a limitation by spec, yes.  Technically not by RFC, as SFTP is defined by _drafts_ that never reached the RFC stage.

SFTP protocol version 3 is defined by https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-02.txt.  And in this draft, there is mention of extensions, but no specific extensions (such as "supported" or "supported2") are defined.

It's not until the draft for SFTP protocol version 5 (see https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-05.txt) that we see the "supported" extension mentioned.

And the "supported2" extension is not defined until the draft for SFTP protocol version 6 (see https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-07.txt).

This is why `mod_sftp` only announces "supported2" if the client indicates it supports SFTP protocol version 6.

**Comment by Castaglia** [comment]
Now, the above _said_, the draft which specifies some of the extensions (such as the "check-file" extension) is not specific to the SFTP protocol version:
* https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00

So an argument can be made that `mod_sftp` _should_ advertise these extensions (just as it does for the custom OpenSSH extensions) in its `INIT` response, without requiring that the client implement any particular SFTP protocol version.  I can work to make this happen.

**Comment by Castaglia** [comment]
This should be addressed now in the master branch.  Thanks!

**Comment by Castaglia** [comment]
Interestingly, the "File Hashing" section of the SFTP Extensions draft https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00#section-3 explicitly mentions the "supported2" extension here:
> This extension MUST be represented in the "supported2" extension as "check-file"

I'm not sure why only this particular extension has that text, nor do I understand the intent there.  I think my above change, to advertise the "check-file" extension outside of the "supported2" extension, is fine.  I may, though, _also_ advertise "check-file" in the "supported2" extension once more, to be compliant with the above text; it does not say that the "check-file" extension can _only_ be advertised via "supported2".

**Comment by Castaglia** [comment]
Hmm.  Now I'm wondering whether the other standard extensions should be re-added back to the "supported2" list, too.  It would lead to redundant advertising of those extensions in the `INIT` response, but it would preserve backward-compatibility of ProFTPD behavior.  Thoughts, @abriel ?

**Comment by abriel** [comment]
I thought we can leave supported2 advertisement as is (before the change).
As you mentioned, 
> This extension MUST be represented in the "supported2" extension as
   "check-file" and both version MUST either be support or neither.
the "both" here is "check-file-name" and "check-file-handle" I guess.

Problem for me was that "supported2" advertisement is included into a response to INIT on protocol version 6, which I cannot use now.

I am referring to https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-5.2 , 
> The SSH_FXP_VERSION packet (from server to client) has the following
   data:

       uint32 version
       extension-pair extensions[0..n]

it seems we are not limited on specifying as many extensions we want. That is what you did @Castaglia with the new function `fxp_version_add_std_exts`.  
Just one point here - can we send a list of supported algorithms instead of 1? (`ext.ext_data = (unsigned char *) "1";`)
The data is not limited by constant: 
> extension-pair

       string extension-name
       string extension-data

That might be helpful on a systems with FIPS enabled - md5 will be rejected, and client should know about that.

Thank you @Castaglia for your work!

**Comment by Castaglia** [comment]
I'm honestly not sure how other SFTP clients out there would react to advertisement of the "check-file" extension, with a value that is a comma-separated list of algorithm names supported by the server.  In the existing Draft, there is support already for your use case:
```
   hash-algorithm-list
      A comma separated list of hash algorithms the client is willing to
      accept for this operation.  The server MUST pick the first hash on
      the list that it supports.
```
Thus the client can send "md5", along with other algorithm names, in case the server needs to choose something other than "md5".  The `EXTENDED` response from the server will include the server-chosen algorithm, so that the client can detect that _e.g._ "md5" wasn't used.

**Comment by abriel** [comment]
> Thus the client can send "md5", along with other algorithm names, in case the server needs to choose something other than "md5". The EXTENDED response from the server will include the server-chosen algorithm, so that the client can detect that e.g. "md5" wasn't used.

ah. ok. You are very right. Then I have no doubts about having just "1" in data.
