### ISSUE TITLE
AllowStoreRestart: wrong default value in docs

### ISSUE THREAD

**Issue by ValentinSteiner** [proftpd/proftpd#1577]
In `mod_xfer.html`, it says

```
<strong>Default:</strong> <code>AllowStoreRestart on</code><br>
```

But further down, it says "not permitted":
> By default restarting (via the FTP REST command) is not permitted when uploading files to the server.

I believe the default is in fact `off`, and that the line should reflect that.

**Comment by Castaglia** [comment]
This should now be fixed in the master branch, and on the website.  Thanks!
