### ISSUE TITLE
mod_sftp improperly handles SFTP WRITE requests for files opened for appending

### ISSUE THREAD

**Issue by andreaszervas** [proftpd/proftpd#1584]
On an installation of the ProFTPd server (1.3.6 and 1.3.7e) tried uploading a file, which already exists in the destination folder, with the append option (flag) enabled (using SFTP).

The sftp client used was WinSCP (5.21.6) command-line client.  The command is of this form:
put -append "local\folder\test.txt" "destination\folder\test.txt"

After the above I would expect the contents of the local file (local\folder\test.txt) to be appended at the end of the existing file in the destination folder (destination\folder\test.txt). Note that this (expected) behavior is what we get when using e.g. openssh sftp server.

Instead after that operation the file in the destination folder gets overwritten (has just the contents of the file that was just uploaded.)

The versions of ProFTPd on which this was tested were 1.3.6 and 1.3.7e with a default configuration.

**Comment by pepi55** [comment]
Same issue occurs here

**Comment by Castaglia** [comment]
Could you provide the configuration you're using, please?  "Default configuration" means different things on different platforms, and I'd like to recreate this behavior locally using the same configuration that you are using.  Thanks!

**Comment by andreaszervas** [comment]
Hi TJ! Sure the config file used is as follows, thank you for your response!


#etc/proftpd.conf

UseIPv6 off

ServerName   "test_server"
ServerType   standalone
Port 0

MaxInstances 800

MultilineRFC2228 on

PersistentPasswd off

LogFormat auth "%v [%P] %h %t \"%r\" %s"
LogFormat awstats "%t %h %u %m %f %s %b"
LogFormat default "%h %l %u %t \"%r\" %s %b"
SystemLog   /var/log/proftpd/proftpd.log
SocketBindTight on
UseReverseDNS off
 
# Global parameters
<Global>
  AllowOverwrite on
  AllowStoreRestart on
  CapabilitiesEngine off
  DebugLevel 0
  DefaultRoot ~
  DenyFilter \*.*/
  Group proftpd
  IdentLookups off
  ListOptions -l
  RootLogin on
  RootRevoke off
  TimeoutIdle 1200
  TimeoutNoTransfer 86400
  TimeoutStalled 600
  TimesGMT off
  Umask 0
  UseFtpUsers off
  UseSendFile off
  User proftpd
  WtmpLog off
</Global>
# End global parameters

 <IfModule mod_quotatab.c>
  QuotaEngine off
</IfModule>

 <IfModule mod_ratio.c>
  Ratios off
</IfModule>

<IfModule mod_delay.c>
  DelayEngine off
</IfModule>

 <IfModule mod_ctrls.c>
  ControlsEngine     off
  ControlsMaxClients 2
  ControlsLog        /var/log/proftpd/controls.log
  ControlsInterval   5
  ControlsSocket     /var/run/proftpd/proftpd.sock
</IfModule>

<IfModule mod_ctrls_admin.c>
  AdminControlsEngine off
</IfModule>

**Comment by andreaszervas** [comment]
Thanks for the response! The proftpd.conf file is the following:

UseIPv6 off

ServerName   "test_server"
ServerType   standalone
Port 0

MaxInstances 800

MultilineRFC2228 on

PersistentPasswd off

LogFormat auth "%v [%P] %h %t \"%r\" %s"
LogFormat awstats "%t %h %u %m %f %s %b"
LogFormat default "%h %l %u %t \"%r\" %s %b"
SystemLog   /var/log/proftpd/proftpd.log
SocketBindTight on
UseReverseDNS off
 
<Global>
  AllowOverwrite on
  AllowStoreRestart on
  CapabilitiesEngine off
  DebugLevel 0
  DefaultRoot ~
  DenyFilter \*.*/
  Group proftpd
  IdentLookups off
  ListOptions -l
  RootLogin on
  RootRevoke off
  TimeoutIdle 1200
  TimeoutNoTransfer 86400
  TimeoutStalled 600
  TimesGMT off
  Umask 0
  UseFtpUsers off
  UseSendFile off
  User proftpd
  WtmpLog off
</Global>
# End global parameters

 <IfModule mod_quotatab.c>
  QuotaEngine off
</IfModule>

 <IfModule mod_ratio.c>
  Ratios off
</IfModule>

<IfModule mod_delay.c>
  DelayEngine off
</IfModule>

 <IfModule mod_ctrls.c>
  ControlsEngine     off
  ControlsMaxClients 2
  ControlsLog        /var/log/proftpd/controls.log
  ControlsInterval   5
  ControlsSocket     /var/run/proftpd/proftpd.sock
</IfModule>

<IfModule mod_ctrls_admin.c>
  AdminControlsEngine off
</IfModule>

**Comment by andreaszervas** [comment]
Thanks for your response! The proftpd.conf file used is:

> UseIPv6 off
> 
> ServerName   "test.name"
> ServerType   standalone
> Port 0
> 
> MaxInstances 800
> 
> MultilineRFC2228 on
>  
> PersistentPasswd off
> 
> LogFormat auth "%v [%P] %h %t \"%r\" %s"
> LogFormat awstats "%t %h %u %m %f %s %b"
> LogFormat default "%h %l %u %t \"%r\" %s %b"
> SystemLog   /var/log/proftpd/proftpd.log
> ServerAdmin blablabla@email.com
> SocketBindTight on
> UseReverseDNS off
> 
> <Global>
>   AllowOverwrite on
>   AllowStoreRestart on
>   CapabilitiesEngine off
>   DebugLevel 0
>   DefaultRoot ~
>   DenyFilter \*.*/
>   Group proftpd
>   IdentLookups off
>   ListOptions -l
>   RootLogin on
>   RootRevoke off
>   TimeoutIdle 1200
>   TimeoutNoTransfer 86400
>   TimeoutStalled 600
>   TimesGMT off
>   Umask 0
>   UseFtpUsers off
>   UseSendFile off
>   User proftpd
>   WtmpLog off
> </Global>
> 
> <IfModule mod_quotatab.c>
>   QuotaEngine off
> </IfModule>
> 
> <IfModule mod_ratio.c>
>   Ratios off
> </IfModule>
> 
> <IfModule mod_delay.c>
>   DelayEngine off
> </IfModule>
> 
> <IfModule mod_ctrls.c>
>   ControlsEngine     off
>   ControlsMaxClients 2
>   ControlsLog        /var/log/proftpd/controls.log
>   ControlsInterval   5
>   ControlsSocket     /var/run/proftpd/proftpd.sock
> </IfModule>
> 
> <IfModule mod_ctrls_admin.c>
>   AdminControlsEngine off
> </IfModule>

**Comment by andreaszervas** [comment]
Hi TJ, thanks for your response! The config file used is the following:


```
UseIPv6 off

ServerName   "test.name"
ServerType   standalone
Port 0

MaxInstances 800

MultilineRFC2228 on
 
PersistentPasswd off

LogFormat auth "%v [%P] %h %t \"%r\" %s"
LogFormat awstats "%t %h %u %m %f %s %b"
LogFormat default "%h %l %u %t \"%r\" %s %b"
SystemLog   /var/log/proftpd/proftpd.log
ServerAdmin blablabla@email.com
SocketBindTight on
UseReverseDNS off

<Global>
  AllowOverwrite on
  AllowStoreRestart on
  CapabilitiesEngine off
  DebugLevel 0
  DefaultRoot ~
  DenyFilter \*.*/
  Group proftpd
  IdentLookups off
  ListOptions -l
  RootLogin on
  RootRevoke off
  TimeoutIdle 1200
  TimeoutNoTransfer 86400
  TimeoutStalled 600
  TimesGMT off
  Umask 0
  UseFtpUsers off
  UseSendFile off
  User proftpd
  WtmpLog off
</Global>

<IfModule mod_quotatab.c>
  QuotaEngine off
</IfModule>

<IfModule mod_ratio.c>
  Ratios off
</IfModule>

<IfModule mod_delay.c>
  DelayEngine off
</IfModule>

<IfModule mod_ctrls.c>
  ControlsEngine     off
  ControlsMaxClients 2
  ControlsLog        /var/log/proftpd/controls.log
  ControlsInterval   5
  ControlsSocket     /var/run/proftpd/proftpd.sock
</IfModule>

<IfModule mod_ctrls_admin.c>
  AdminControlsEngine off
</IfModule>
```

**Comment by Castaglia** [comment]
@andreaszervas Thanks for the config!  I'm working on reproducing this behavior now.  Interestingly, though, I do not see any configuration for ProFTPD's `mod_sftp` module in the provided configuration.  Perhaps there are other config files for that?  The `mod_sftp` configuration is what I am particularly interested in, as it would influence how WinSCP would talk to ProFTPD.

Might I also ask if you could provide the `SFTPLog` (and `TraceLog`) for one of these append uploads?  I don't often use Windows, thus reproducing this behavior using an SFTP client other WinSCP is what I need to do:
```
# Write mod_sftp and trace logging to the same file
SFTPLog /var/log/proftpd/sftp.log
TraceLog /var/log/proftpd/sftp.log
Trace ssh2:20 sftp:20
```

**Comment by andreaszervas** [comment]
Yes sorry missed that.. the sftp configuration was in the Virtual Host config, it is the following:

`<IfModule mod_sftp.c>
<VirtualHost "ip1" "ip2">
    ExtendedLog /var/log/proftpd/access.log WRITE,READ
    ExtendedLog /var/log/proftpd/auth.log AUTH
    MaxClientsPerUser 50
    MaxLoginAttempts 6
    Port 2222
    SFTPCiphers arcfour128 arcfour256 aes128-cbc aes192-cbc aes256-cbc aes128-ctr blowfish-cbc cast128-cbc aes192-ctr aes256-ctr
    SFTPClientMatch .* channelWindowSize 1GB
    SFTPClientMatch ".*WinSCP.*" sftpProtocolVersion 3
    SFTPDHParamFile /etc/dhparams.pem
    SFTPEngine on
    SFTPHostKey /etc/proftpd/sftp-keys/ssh_host_rsa_key
    SFTPHostKey /etc/proftpd/sftp-keys/ssh_host_dsa_key
    SFTPLog /var/log/proftpd/sftp.log
    TransferLog /var/log/proftpd/transfer.log
</VirtualHost>
</IfModule>`

I will provide you the sftp.log for the append case as soon as I can. Thank you!

**Comment by andreaszervas** [comment]
Yes sorry missed that.. the sftp configuration was in the Virtual Host config, it is the following:

```
<IfModule mod_sftp.c>
<VirtualHost "ip1" "ip2">
    ExtendedLog /var/log/proftpd/access.log WRITE,READ
    ExtendedLog /var/log/proftpd/auth.log AUTH
    MaxClientsPerUser 50
    MaxLoginAttempts 6
    Port 2222
    SFTPCiphers arcfour128 arcfour256 aes128-cbc aes192-cbc aes256-cbc aes128-ctr blowfish-cbc cast128-cbc aes192-ctr aes256-ctr
    SFTPClientMatch .* channelWindowSize 1GB
    SFTPClientMatch ".*WinSCP.*" sftpProtocolVersion 3
    SFTPDHParamFile /etc/dhparams.pem
    SFTPEngine on
    SFTPHostKey /etc/proftpd/sftp-keys/ssh_host_rsa_key
    SFTPHostKey /etc/proftpd/sftp-keys/ssh_host_dsa_key
    SFTPLog /var/log/proftpd/sftp.log
    TransferLog /var/log/proftpd/transfer.log
</VirtualHost>
</IfModule>
```

I will provide you the sftp.log for the append case as soon as I can. Thank you!

**Comment by Castaglia** [comment]
This fix for this issue is now in the master branch on GitHub, and has been backported to the 1.3.8 branch.  Thanks!

**Comment by andreaszervas** [comment]
Thank you for you quick response TJ! Much appreciated!
