### ISSUE TITLE
Optimize per-connection file I/O when reading SFTPHostKey from disk

### ISSUE THREAD

**Issue by rafasc** [proftpd/proftpd#1596]
### What I Did

Enabled mod_sftp

### What I Expected/Wanted

At $DAYJOB we have a high volume ftp server.
We've seen some performance regressions when comparing with previous versions of proftpd.
One thing that immediately different is that proftpd is reading host_key file for every connection made one byte at a time.

### ProFTPD Version and Configuration

``` Containerfile
FROM almalinux:9

RUN echo Installing Packages && \
dnf install -y epel-release && \
dnf install -y proftpd openssh strace --enablerepo=crb

RUN printf '%s\n' >/etc/proftpd/conf.d/sftp.conf \
'<IfModule mod_sftp.c>' \
'SFTPEngine on' \
'Port 2222' \
'SFTPHostKey /etc/ssh/ssh_host_rsa_key' \
'SFTPAuthMethods publickey' \
'</IfModule>'

RUN cat /etc/proftpd/conf.d/sftp.conf
RUN ssh-keygen -m PEM -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
RUN sed -i -E 's/#\s*(LoadModule mod_sftp.c)/\1/' /etc/proftpd/modules.conf
CMD strace -fe trace=read proftpd -nd10
```
also verifiable on almalinux:8 (no need for crb repo in that case)
```
...
daemon[4] 10.88.0.42: SFTPHostKey
daemon[4] 10.88.0.42: SFTPAuthMethods
daemon[4] 10.88.0.42: Limit
daemon[4] 10.88.0.42:  AllowAll
daemon[4] 10.88.0.42: Umask
daemon[4] 10.88.0.42: AllowOverwrite
daemon[4] 10.88.0.42: ROOT PRIVS at keys.c:815
daemon[4] 10.88.0.42: RELINQUISH PRIVS at keys.c:818
read(3, "-", 1)                         = 1
read(3, "-", 1)                         = 1
read(3, "-", 1)                         = 1
read(3, "-", 1)                         = 1
read(3, "-", 1)                         = 1
read(3, "B", 1)                         = 1
read(3, "E", 1)                         = 1
read(3, "G", 1)                         = 1
read(3, "I", 1)                         = 1
read(3, "N", 1)                         = 1
...
```
Is this intended/necessary behaviour?

**Comment by Castaglia** [comment]
The `mod_sftp` module uses OpenSSL's `PEM_read_PrivateKey()` function [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/keys.c#L3734) to read in the configured `SFTPHostKey` files.  Thus the IO behavior is governed/handled by OpenSSL, not by `mod_sftp`.

**Comment by Castaglia** [comment]
In looking at this a little more, it might be possible to optimize this a bit.  Specifically, by using `PEM_read_bio_PrivateKey()`, and provisioning a memory-backed BIO where we read the file from disk using more optimal I/O patterns, this behavior might be improved.  I'll work on a patch for this.

**Comment by Castaglia** [comment]
@rafasc https://github.com/proftpd/proftpd/pull/1599 should improve this situation; care to try it out on your servers, to help verify that it helps?  Thanks!

**Comment by Castaglia** [comment]
Note that the provided `strace` command (thanks!) shows the `SFTPHostKey` file being read _on startup_, which uses a slightly different code path (due to being used for _e.g._ `SFTPPassPhraseProvider`, to verify that ProFTPD can indeed decrypt any passphrase-protected host key files) than that used when an SFTP client connects.

I'll update my PR to handle this on-startup case as well, for consistency of behavior.

**Comment by Castaglia** [comment]
Now, with this patch, we see:
```
# strace -fe trace=read proftpd -nd10
...
daemon[27101] 172.17.0.2: ROOT PRIVS at keys.c:818
daemon[27101] 172.17.0.2: RELINQUISH PRIVS at keys.c:821
read(3, "-----BEGIN RSA PRIVATE KEY-----\n"..., 4096) = 2455
read(3, "", 4096)                       = 0
```

**Comment by Castaglia** [comment]
I'll probably open a similar ticket for improving the reading of X509 certs/keys for the `mod_tls` module as well.

**Comment by Castaglia** [comment]
The optimization changes for `mod_sftp` has been merged to master; I'll keep this ticket open for the corresponding `mod_tls` changes/optimizations as well.

**Comment by rafasc** [comment]
Another behaviour I noticed on the original issue (still haven't tested these new changes) is that they seem to be dependent on the format of the key itself.
i.e.
``` bash
ssh-keygen -m PEM -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
vs
ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
```
will yield different results. 

The former seems to be the one that was triggering the issue, however it's necessary for versions before 1.3.7 due to lack of support for openssh formated keys.

**Comment by Castaglia** [comment]
> Another behaviour I noticed on the original issue (still haven't tested these new changes) is that they seem to be dependent on the format of the key itself. i.e.
> 
> ```shell
> ssh-keygen -m PEM -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
> vs
> ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
> ```
> 
> will yield different results.

The code for handling OpenSSH-formatted private keys is completely different, and doesn't use stdio `FILE *` handles (and their buffering).  Instead, that code reads the entire file into memory, using a single `read(2)` call, and then performs its operations.  This might explain the differences in behavior you'd see.
