### ISSUE TITLE
Current SFTPClientMatch settings?

### ISSUE THREAD

**Issue by offsides** [proftpd/proftpd#1609]
Looking at the SFTPClientMatch settings in the mod_sftp docs and on the forum, they appear to be rather outdated.  The forum post is 10 years old, and at the very least I know current WinSCP version support sftp protocol version 6 (though for all I know there's something about WinSCP that doesn't work with mod_sftp).  Is there any newer settings for that, or is it all just trial and error?  I'd rather not force older settings just because they were required at one point, but at the same time I'd rather not have to deal with clients not being able to connect/transfer files because I'm missing some workarounds.

**Comment by Castaglia** [comment]
It's mostly trial and error, and whatever knowledge/settings are provided by the community.  I don't have sufficient resources locally to do all the comprehensive testing of all the SFTP clients out there, across their versions.

**Comment by offsides** [comment]
OK, I was afraid that was the case but c'est la vie.  Thanks for the answer.
