### ISSUE TITLE
ProFTPD does not detect FIPS when using OpenSSL 3.x built with FIPS support

### ISSUE THREAD

**Issue by alex-kowalczyk** [proftpd/proftpd#1610]
### What I Did

1. Built and installed OpenSSL 3 with FIPS support. Configured fips module according to OpenSSL docs.
2. Built proftpd 1.3.8 with my OpenSSL.  
```
./configure --with-modules=mod_sftp:mod_quotatab:mod_quotatab_file --enable-nls --enable-openssl --with-includes=/usr/local/include --with-libraries=/usr/local/lib64
...
checking whether OpenSSL is compiled with FIPS support... no
checking whether linking with OpenSSL functions succeeds... no
...
```
3. Discovered that [proftpd FIPS instructions](http://www.proftpd.org/docs/contrib/mod_sftp.html#Usage) are outdated - probably valid for OpenSSL 1.0.2 + FIPS Object Module 2.x

Most notably:
* OpenSSL 3 does not ship `fipsld` tool anymore.
* OpenSSL 3 FIPS support is enabled in very different way, by [dynamic configurations (fips_module)](https://www.openssl.org/docs/manmaster/man7/fips_module.html).
* OpenSSL 3 FIPS is not advertised with `<openssl/fips.h>` nor `#define OPENSSL_FIPS`, so essentially Proftpd `configure` does not detect "FIPS" abilities.

ProFTPD + mod_sftpd docs advertise ability for FIPS compliance, but building proftpd with OpenSSL 1.0.2 with FIPS 2.x module is not a good idea anymore, as this version is not supported anymore (except sponsored support).

### What I Expected/Wanted
Does ProFTPD "just works FIPS-compliant" when built against OpenSSL 3 (with FIPS support compiled and configured)?  
If not, would be good to adjust to the new FIPS interface accordingly. 

### ProFTPD Version and Configuration

proftpd 1.3.8 release.

**Comment by Castaglia** [comment]
I admit that I don't often get requests to ensure that FIPS support works.  And I've not tried to determine how one builds/installs OpenSSL 3.x with FIPS support.

I'd like to reproduce this locally, so that I can then see what's needed to address the situation.  Happen to have some commands/instructions that I could do, so reproduce your setup?

**Comment by alex-kowalczyk** [comment]
Here are the relevant commands (debian 11)
```
export VERSION=1.3.8
export OPENSSL_VERSION=3.0.8
apt-get update
apt-get install --no-install-recommends -y build-essential ca-certificates libncurses-dev wget zlib1g-dev

wget --progress=dot:giga ftp://ftp.proftpd.org/distrib/source/proftpd-$VERSION.tar.gz && \
    tar -xvzf proftpd-$VERSION.tar.gz && \
    mv proftpd-$VERSION proftpd && \
    wget --progress=dot:giga http://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
    tar -xzvf openssl-${OPENSSL_VERSION}.tar.gz && \
    mv openssl-${OPENSSL_VERSION} openssl

cd openssl
./Configure enable-fips
make
make install
cd ..
```

Now setup OpenSSL config using [instructions in fips_manual](https://www.openssl.org/docs/manmaster/man7/fips_module.html) ("Make all applications..." chapter)

Build proftpd with mod_sftp:
``` 
cd proftpd
./configure --with-modules=mod_sftp:mod_quotatab:mod_quotatab_file --enable-nls --enable-openssl --with-includes=/usr/local/include/openssl --with-libraries=/usr/local/lib64
# Observe the "no" messages:
# checking whether OpenSSL is compiled with FIPS support... no
# checking whether linking with OpenSSL functions succeeds... no
```

**Comment by Castaglia** [comment]
Hmm.  This does bring up an interesting question: _Should_ ProFTPD try to enable/load FIPS support (using OpenSSL 3.x) explicitly, programmatically, as shown in the "Programmatically loading the FIPS module (default library context)" section of the FIPS docs, or should it rely on the system-wide `openssl.cnf` configuration?

**Comment by Castaglia** [comment]
The instructions in the OpenSSL docs leave a lot of the _actual_ necessary `openssl.cnf`, `fipsmodule.cnf` configuration out, such as the need to use _absolute paths_ when including the `fipsmodule.cnf` file, per https://github.com/openssl/openssl/issues/17883.  Just goes to show that proper FIPS support for OpenSSL 3.x is a bit rough around the edges.

**Comment by alex-kowalczyk** [comment]
> Hmm. This does bring up an interesting question: _Should_ ProFTPD try to enable/load FIPS support (using OpenSSL 3.x) explicitly, programmatically, as shown in the "Programmatically loading the FIPS module (default library context)" section of the FIPS docs, or should it rely on the system-wide `openssl.cnf` configuration?

@Castaglia am I reading you correctly, that (1) building OpenSSL with FIPS (2) building current Proftpd against that OpenSSL (3) Enabling FIPS globally with `openssl.cnf+fipsmodule.cnf` ...
would be enough to have FIPS fencing, ie no Proftpd code changes necessary?

**Comment by Castaglia** [comment]
@alex-kowalczyk No code changes are _currently_ necessary, but I've not done an exhaustive run-time test for all possible algorithms/configurations to know if there would be runtime errors.  But with the above patch, ProFTPD (and `mod_sftp`, `mod_tls`) compile correctly, with FIPS support detected.

**Comment by Castaglia** [comment]
@alex-kowalczyk I've merged that PR, if you'd like to try the latest ProFTPD sources.

I'll keep this ticket open for a bit, in case you encounter other tweaks needed for a FIPS-using ProFTPD in your environment.  Just let me know.

**Comment by Castaglia** [comment]
As there's been nothing more added to this ticket, I'll close it.  We can address any new issues with new tickets going forward.   Thanks!
