### ISSUE TITLE
Is there a table of command class/command mapping for SFTP extended logging

### ISSUE THREAD

**Issue by offsides** [proftpd/proftpd#1611]
The ExtendedLog docs for mod_log have a table that maps Command Classes to specific FTP commands for logging purposes.  I've noticed that there are additional commands logged for mod_sftp, but they aren't documented for for logging purposes. Is there a similar table for mod_sftp so that I can craft my logging statements to be (roughly) equivalent for FTP and SFTP without logging lots of additional stuff that I don't necessarily want for just SFTP sessions?

As an example, here's logs from an FTP session and an SFTP session perfrming the exact same commands after login (the only difference being key login for SFTP).
FTP:
```
127.0.0.1 [28/Feb/2023:10:33:15 -0500] Y/4euawZ115/AAABABNpjD3k - "USER jsmftptest" 331 -
127.0.0.1 [28/Feb/2023:10:33:16 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "PASS (hidden)" 230 -
127.0.0.1 [28/Feb/2023:10:33:16 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "SYST" 215 -
127.0.0.1 [28/Feb/2023:10:33:19 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "PASV" 227 -
127.0.0.1 [28/Feb/2023:10:33:19 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "LIST -al" 226 260
127.0.0.1 [28/Feb/2023:10:33:32 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "TYPE I" 200 -
127.0.0.1 [28/Feb/2023:10:33:32 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "PASV" 227 -
127.0.0.1 [28/Feb/2023:10:33:32 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "STOR trytest.pl" 226 444
127.0.0.1 [28/Feb/2023:10:33:35 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "MKD test" 257 -
127.0.0.1 [28/Feb/2023:10:33:36 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "CWD test" 250 -
127.0.0.1 [28/Feb/2023:10:33:37 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "TYPE A" 200 -
127.0.0.1 [28/Feb/2023:10:33:37 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "PASV" 227 -
127.0.0.1 [28/Feb/2023:10:33:37 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "LIST -al" 226 121
127.0.0.1 [28/Feb/2023:10:33:37 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest "QUIT" 221 -
127.0.0.1 [28/Feb/2023:10:33:37 -0500] Y/4euawZ115/AAABABNpjD3k jsmftptest Quit
```
SFTP:
```
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "KEXINIT" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "ECDH_INIT" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "NEWKEYS" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "EXT_INFO" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "SERVICE_REQUEST" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "USER jsmsftptest" 331 -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "USERAUTH_REQUEST jsmsftptest none" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "USER jsmsftptest" 331 -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "PASS (hidden)" 530 -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "USERAUTH_REQUEST jsmsftptest publickey" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz - "USER jsmsftptest" 331 -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "PASS (hidden)" 230 -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "USERAUTH_REQUEST jsmsftptest publickey" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CHANNEL_OPEN session" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CHANNEL_REQUEST subsystem" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "INIT 3" - -
127.0.0.1 [28/Feb/2023:10:34:13 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "REALPATH ." - -
127.0.0.1 [28/Feb/2023:10:34:35 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "OPENDIR /" - 0
127.0.0.1 [28/Feb/2023:10:34:35 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "READDIR 501e47b07181eedb" - 1554
127.0.0.1 [28/Feb/2023:10:34:35 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "READDIR 501e47b07181eedb" 1 1554
127.0.0.1 [28/Feb/2023:10:34:35 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "MLSD /" - 1554
127.0.0.1 [28/Feb/2023:10:34:35 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CLOSE 501e47b07181eedb" 0 0
127.0.0.1 [28/Feb/2023:10:34:39 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "OPEN /trytest.pl" - 0
127.0.0.1 [28/Feb/2023:10:34:39 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "WRITE 5c5324b75813eb77 0 444" 0 444
127.0.0.1 [28/Feb/2023:10:34:39 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "STOR /trytest.pl" 226 444
127.0.0.1 [28/Feb/2023:10:34:39 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CLOSE 5c5324b75813eb77" 0 444
127.0.0.1 [28/Feb/2023:10:34:43 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "MKD /test" - -
127.0.0.1 [28/Feb/2023:10:34:43 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "MKDIR /test" 257 -
127.0.0.1 [28/Feb/2023:10:34:44 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "REALPATH /test" - -
127.0.0.1 [28/Feb/2023:10:34:44 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "STAT /test" - -
127.0.0.1 [28/Feb/2023:10:34:46 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "OPENDIR /test" - 0
127.0.0.1 [28/Feb/2023:10:34:46 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "READDIR d89bdee70847929c" - 210
127.0.0.1 [28/Feb/2023:10:34:46 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "READDIR d89bdee70847929c" 1 210
127.0.0.1 [28/Feb/2023:10:34:46 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "MLSD /test" - 210
127.0.0.1 [28/Feb/2023:10:34:46 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CLOSE d89bdee70847929c" 0 0
127.0.0.1 [28/Feb/2023:10:34:47 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CHANNEL_EOF" - -
127.0.0.1 [28/Feb/2023:10:34:47 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest "CHANNEL_CLOSE" - -
127.0.0.1 [28/Feb/2023:10:34:47 -0500] Y/4e9awZ115/AAABABNpnIHz jsmsftptest Quit: disconnected by user
```
As you can see, there's a lot more logging for SFTP than FTP when logging ALL.  I'd like to be able to try and make the SFTP logs as close to the FTP logs as possible by being more selective about what I'm logging, but for that I need to know all the commands and their classes so I know what needs to be tweaked.  Thanks in advance!

**Comment by Castaglia** [comment]
Let's back up a little bit.  What kind of logging do you want/need, irrespective of FTP/SFTP protocols?

Mapping of SFTP onto FTP is imprecise, and there will be rough edges (and no exact counterparts), so it helps to start by asking what the desired end state is, and why.

**Comment by offsides** [comment]
I *think* I figured it out.  Please correct me if I'm wrong, but I believe that the following is the table for commands generated by mod_sftp:
```
AUTH    DH_GEX_INIT, DH_GEX_REQUEST, DH_GEX_REQUEST_OLD, DH_INIT, ECDH_INIT, EXT_INFO, KEXINIT,
        KEXRSA_SECRET, NEWKEYS, PASS, USER, USERAUTH_REQUEST
DIRS    MLSD, OPENDIR, READDIR
INFO    REALPATH
MISC    CHANNEL_CLOSE, CHANNEL_EOF, CHANNEL_OPEN, CHANNEL_REQUEST, CHANNEL_WINDOW_ADJUST, EXTENDED,
        FSYNC, HARDLINK, HOMEDIR, INIT, MKDIR, RENAME, SERVICE_REQUEST
READ    FSTAT, LSTAT, READ, READLINK, RETR, STAT
WRITE   APPE, FSETSTAT, LINK, LOCK, REMOVE, RMDIR, SETSTAT, SITE, STOR, SYMLINK, UNLOCK, WRITE
SFTP    EXTENDED, FSETSTAT, FSTAT, FSYNC, HARDLINK, HOMEDIR, INIT, LINK, LOCK, LSTAT, MKDIR, OPENDIR,
        READ, READDIR, READLINK, REALPATH, REMOVE, RENAME, RMDIR, SETSTAT, STAT, SYMLINK, UNLOCK, WRITE
SSH     CHANNEL_CLOSE, CHANNEL_EOF, CHANNEL_OPEN, CHANNEL_REQUEST, CHANNEL_WINDOW_ADJUST, DH_GEX_INIT,
        DH_GEX_REQUEST, DH_GEX_REQUEST_OLD, DH_INIT, ECDH_INIT, EXT_INFO, KEXINIT, KEXRSA_SECRET,
        NEWKEYS, PASS, SERVICE_REQUEST, USER, USERAUTH_REQUEST
```
That said, there's a couple of things that don't quite work as might be expected, though they are (mostly) easily worked around if you know how (i.e., it's documented :)).  Thus, I'll document them here.

1. You can't just log all SFTP and/or SSH commands with the 'SFTP and 'SSH' selectors.  Instead, you have to use a combination of the commands you want to log with SFTP and/or SSH.  For example, to log all SFTP and SSH commands, you have to use 'ALL,SFTP,SSH'.
2. Conversely, if you want to log only FTP commands, you have to add '!SFTP,!SSH'.
3. Both of the above assume that you are using <Global> ExtendedLog statements.  If you have the ExtendedLog statements either at the server level or inside a virtualhost that only does one or the other, then it will obviously only log the statements for that server/vhost.
4. If you do log Globally, the following SFTP commands will ALSO show up int he FTP logs, even if you specify '!SFTP,!SSH' in your FTP log statement(s): APPE, MLSD, RETR, STOR, and the EXIT pseudo-command.  And ALL the relevant FTP commands will show up in the SFTP logs.
5. Using "ALL,!SSH' for SFTP logging reduces the logs to something similar to (though not quite as verbose as) FTP logging of ALL, with the important distinction that it will show NO auth logging at all.  To see that you must ALSO add an ExtendedLog 'AUTH' statement.  Adding a separate 'AUTH' statement will add USER/PASS logging - no need to add the '!SSH' to that one for some reason.  However the logging with '!SSH' is truly minimal - the only commands I've seen logged are: MLSD, MKD, STAT (for change dir), RNFR, RNTO, RMD, DELE, STOR and RETR (I'm assuming APPE will show up to, and I haven't tried the various SETSTAT permutations as I don't allow them anyway).
6. The '!SSH' filter ONLY works on the 'ALL' selector; however, it appears that '!SSH' is also the default for all the individual class selectors, so that NO SSH logging is done unless you use the 'ALL' selector, in which case it's turned on for everything.

I believe that documents everything (or at least everything I can easily test and/or is relevant to my setup).  I'm not sure if it's working as it's supposed to, but I'm a firm believer that if it's working as documented, you're usually covered. :)

Please let me know if I've missed anything and/or if there's anything that you think should work differently that you'd like me to test.

**Comment by offsides** [comment]
I've done some more digging after looking at the logs, and I'm starting to think the while there's probably a lot of very good reasons for it, there's a huge disconnect between what gets logged for FTP sessions and what gets logged for SFTP sessions.  And by that I mean that FTP sessions tend to log the command that was issues (albeit translated into the canonical FTP command - e.g., 'dir' becomes 'LIST', etc.), while SFTP sessions tend to log what was actually done on the server.  For example, 'dir' shows a sequence of 'OPENDIR', 'READDIR' (x2), 'MLSD' and 'CLOSE'.  And 'cd' doesn't indicate that you changed directory at all, just 'REALPATH' and 'STAT'.  This probably also means the SFTP doesn't actually change into the directory so much as it just changes the contents of the variable holding the working directory.  I'm wondering if there's a way to log the commands that are issued and not just the back-end process, either directly within mod_sftp or perhaps as a separate SFTP logging module.

Also, I just noticed that I had an error in how I pulled the commands out of the source.  MKDIR belongs in WRITE not MISC, and MISC and SFTP are missing CLOSE and OPEN.

**Comment by Castaglia** [comment]
I'm not quite sure I understand what you mean by:
> I'm wondering if there's a way to log the commands that are issued and not just the back-end process

The `mod_sftp` module was developed with an aim of being compatible/similar (and that includes logging!) to what is done for FTP sessions.  So yes, there is (and will) be differences between the translated SFTP->FTP internal subcommands (done to ensure that the existing module configurations/behaviors continued to work as expected), and what is actually sent on the wire.

That's why I did *not* want to start by discussing internals and existing behavior, but instead wanted to know:
> What kind of logging do you want/need, irrespective of FTP/SFTP protocols?

**Comment by Castaglia** [comment]
> MISC and SFTP are missing CLOSE and OPEN

Some sites _do_ want these fake `OPEN`, `CLOSE` commands (as they're not really _commands_ or requests, they're events), and some explicitly do *not* want them, for the `MISC` or `SFTP` classes.

**Comment by offsides** [comment]
> > MISC and SFTP are missing CLOSE and OPEN
> 
> Some sites _do_ want these fake `OPEN`, `CLOSE` commands (as they're not really _commands_ or requests, they're events), and some explicitly do _not_ want them, for the `MISC` or `SFTP` classes.

I wasn't saying that you missed them, I was saying that I had missed them in my initial table.  I think it's safe to assume that any mistakes here are mine and not yours. :)

**Comment by offsides** [comment]
> I'm not quite sure I understand what you mean by:
> 
> > I'm wondering if there's a way to log the commands that are issued and not just the back-end process
> 
What I mean is, when the user types the command, FTP logs essentially the command that was typed, modulated into the actual FTP command.  SFTP logs the actions taken by mod_sftp, but not the actual command that was issued.  This appears to be at least partly because of the way SFTP sends commands to the server, which is why I'm not sure that what I want is possible.

> The `mod_sftp` module was developed with an aim of being compatible/similar (and that includes logging!) to what is done for FTP sessions. So yes, there is (and will) be differences between the translated SFTP->FTP internal subcommands (done to ensure that the existing module configurations/behaviors continued to work as expected), and what is actually sent on the wire.
> 
> That's why I did _not_ want to start by discussing internals and existing behavior, but instead wanted to know:
> 
> > What kind of logging do you want/need, irrespective of FTP/SFTP protocols?
> 
Ultimately what I need is logs that are detailed enough to tell me what every user did while they were logged in, but not so bogged down in minutiae that it's impossible to find the big picture quickly.  99% of my log searches are things like "Did the client actually connect to us or are they not reaching our server?" or "Did they actually upload the file they calim to have uploaded?"  The other 1% is a more detailed analysis of "What exactly did the client do while they were connected to us so we can figure out where the issue is because it's not so simple."

> Much of this logging configurability and tweaks is the result of years of accumulation of requests for various bits and pieces, since sites have such different logging needs/use cases. Makes meeting all of them very hard, and makes for inconsistencies, _especially_ when it comes to SFTP, FTPS, and FTP-specific logging. One thing I strive for is to keep the logging of ProFTPD as simple as possible. _Some_ filtering is possible, but I will not go overboard for that. And processing of logged data (such as for per-user stats) is to be done outside of ProFTPD entirely.

As I said before, the way SFTP sends it's commands may be sufficiently different from FTP that it's just not possible to log it the way I'd like without making some assumptions on the server end, and I totally agree that that's something that should be left outside of ProFTPd.  Your comments made me go back and do a comparison of the logs written for the same FTP and SFTP commands, and the only one among the most common commands  that really requires serious inference is 'cd' - everything else either encapsulates the same log line or has something that can be mapped 1-to-1 effectively.  Under the circumstances, I think I can work with that, I just need to write something to parse the logs for me if it becomes an issue.  At this point I think I just want to make sure that how to use ExtendedLog with mod_sftp is documented for how it works - I'm happy to take a first pass at it if you can just confirm that my table (plus the missing items I listed) and that my understanding of how it works (the list above) is correct.  I can add the (updated) table and some notes to mod_sftp.html and generate a PR for you to consider/improve on.

For reference, here's the transcript of logs for FTP vs SFTP broken down by command for a simple set of the most common steps:
```
Login
--FTP--
127.0.0.1 [06/Mar/2023:11:33:50 -0500] ZAYV7qwZ115/AAABACVpEfri - "USER jsmftptest" 331 -
127.0.0.1 [06/Mar/2023:11:33:50 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "PASS (hidden)" 230 -
127.0.0.1 [06/Mar/2023:11:33:50 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "SYST" 215 -
--SFTP--
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "KEXINIT" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "ECDH_INIT" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "NEWKEYS" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "EXT_INFO" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "SERVICE_REQUEST" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "USER jsmsftptest" 331 -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "USERAUTH_REQUEST jsmsftptest none" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "USER jsmsftptest" 331 -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "PASS (hidden)" 530 -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "USERAUTH_REQUEST jsmsftptest publickey" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H - "USER jsmsftptest" 331 -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "PASS (hidden)" 230 -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "USERAUTH_REQUEST jsmsftptest publickey" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CHANNEL_OPEN session" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CHANNEL_REQUEST subsystem" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "INIT 3" - -
127.0.0.1 [06/Mar/2023:11:34:59 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "REALPATH ." - -

mkdir dirtest
--FTP--
127.0.0.1 [06/Mar/2023:11:33:55 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "MKD dirtest" 257 -
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:04 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "MKD /dirtest" - -
127.0.0.1 [06/Mar/2023:11:35:04 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "MKDIR /dirtest" 257 -

cd dirtest
--FTP--
127.0.0.1 [06/Mar/2023:11:33:58 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "CWD dirtest" 250 -
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:07 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "REALPATH /dirtest" - -
127.0.0.1 [06/Mar/2023:11:35:07 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "STAT /dirtest" - -

put INSTALL
--FTP--
127.0.0.1 [06/Mar/2023:11:34:01 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "TYPE I" 200 -
127.0.0.1 [06/Mar/2023:11:34:01 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "PASV" 227 -
127.0.0.1 [06/Mar/2023:11:34:01 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "STOR INSTALL" 226 25194
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:10 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "OPEN /dirtest/INSTALL" - 0
127.0.0.1 [06/Mar/2023:11:35:10 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "WRITE f9e16fd368c4ef20 0 25194" 0 25194
127.0.0.1 [06/Mar/2023:11:35:10 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "STOR /dirtest/INSTALL" 226 25194
127.0.0.1 [06/Mar/2023:11:35:10 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CLOSE f9e16fd368c4ef20" 0 25194

ls -al
--FTP--
127.0.0.1 [06/Mar/2023:11:34:05 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "TYPE A" 200 -
127.0.0.1 [06/Mar/2023:11:34:05 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "PASV" 227 -
127.0.0.1 [06/Mar/2023:11:34:05 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "LIST -al" 226 187
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:14 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "OPENDIR /dirtest" - 0
127.0.0.1 [06/Mar/2023:11:35:14 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "READDIR c1a7c8332e249a85" - 323
127.0.0.1 [06/Mar/2023:11:35:14 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "READDIR c1a7c8332e249a85" 1 323
127.0.0.1 [06/Mar/2023:11:35:14 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "MLSD /dirtest" - 323
127.0.0.1 [06/Mar/2023:11:35:14 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CLOSE c1a7c8332e249a85" 0 0

rename INSTALL TEST
--FTP--
127.0.0.1 [06/Mar/2023:11:34:09 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "RNFR INSTALL" 350 0
127.0.0.1 [06/Mar/2023:11:34:09 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "RNTO TEST" 250 0
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:17 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "RNFR /dirtest/INSTALL" 350 0
127.0.0.1 [06/Mar/2023:11:35:17 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "RNTO /dirtest/TEST" 250 0
127.0.0.1 [06/Mar/2023:11:35:17 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "RENAME /dirtest/INSTALL /dirtest/TEST" 0 -
127.0.0.1 [06/Mar/2023:11:35:17 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "EXTENDED posix-rename@openssh.com" - -

del TEST/rm TEST
--FTP--
127.0.0.1 [06/Mar/2023:11:34:14 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "DELE TEST" 250 25194
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:36 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "LSTAT /dirtest/TEST" - -
127.0.0.1 [06/Mar/2023:11:35:36 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "DELE /dirtest/TEST" 250 25194
127.0.0.1 [06/Mar/2023:11:35:36 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "REMOVE /dirtest/TEST" 0 -

cd ..
--FTP--
127.0.0.1 [06/Mar/2023:11:34:17 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "CWD .." 250 -
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:46 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "REALPATH /dirtest/.." - -
127.0.0.1 [06/Mar/2023:11:35:46 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "STAT /" - -

rmdir dirtest
--FTP--
127.0.0.1 [06/Mar/2023:11:34:20 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "RMD dirtest" 250 -
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:49 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "RMD /dirtest" - -
127.0.0.1 [06/Mar/2023:11:35:49 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "RMDIR /dirtest" 0 -

exit
--FTP--
127.0.0.1 [06/Mar/2023:11:34:23 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest "QUIT" 221 -
127.0.0.1 [06/Mar/2023:11:34:23 -0500] ZAYV7qwZ115/AAABACVpEfri jsmftptest Quit
--SFTP--
127.0.0.1 [06/Mar/2023:11:35:51 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CHANNEL_EOF" - -
127.0.0.1 [06/Mar/2023:11:35:51 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest "CHANNEL_CLOSE" - -
127.0.0.1 [06/Mar/2023:11:35:51 -0500] ZAYWM6wZ115/AAABACVpFw5H jsmsftptest Quit: disconnected by user
```

**Comment by offsides** [comment]
Doing a little more digging as I work up an initial documentation PR, I found a few inconsistencies in how commands are classified. 4 commands, C_APPE, C_RETR, C_STOR and SYMLINK each have multiple instances in fxp.c, with at least one one with '|CL_SFTP' on the cmd_class assignment and one without (all but SYMLINK in fxp_handle_abort, SYMLINK is in fxp_handle_symlink).  Additionally, 4 other commands, C_MLSD, C_RNFR, C_RNTO and SITE have all references without '|CL_SFTP' on them (fxp_handle_abort, fxp_handle_close, fxp_handle_opendir for C_MLSD, fxp_handle_ext_posix_rename and fxp_handle_rename for C_RNFR and C_RNTO, and fxp_handle_ext_copy_file for SITE).  I'm guessing that these are all oversights, but I'm also not sure if/how changing these would impact how they should be documented.  I'll probably just post the documentation PR as is and let you adjust it if needed.

**Comment by Castaglia** [comment]
The `CL_SFTP` command class bit is enabled, in `mod_sftp`, only for those requests which are part of, related to the SFTP protocol.  So for the cases where `mod_sftp` creates an internal FTP command for dispatching, for mapping to the internal machinery, it will deliberately omit that `CL_SFTP` command class.  These internal FTP commands thus include:
* APPE
* MLSD
* RETR
* RNFR
* RNTO

The mapping of "extended" SFTP requests to `SITE` FTP commands is a bit odd/tenuous, _especially_ for a command like `SITE COPY`, which is part of no RFC whatsoever.
* STOR

**Comment by offsides** [comment]
OK, that makes sense.  However there is at least one case where CL_SFTP is added to those commands (specifically CL_RETR (fxp.c line 10164) and CL_STOR (fxp.c line 13097)), so I don't know if that's a mistake or if there's something else going on that I haven't figured out.  Thanks for clearing things up for me.

**Comment by Castaglia** [comment]
> OK, that makes sense. However there is at least one case where CL_SFTP is added to those commands (specifically CL_RETR (fxp.c line 10164) and CL_STOR (fxp.c line 13097)), so I don't know if that's a mistake or if there's something else going on that I haven't figured out.

Thanks, those remaining sites should be cleaned up in https://github.com/proftpd/proftpd/commit/531934ef8139bda992b61b669e1ec98095db1fd5.  They were a mistake, copy/pasta, not intentional.

**Comment by Castaglia** [comment]
I'm going to consider this ticket as addressed, with the addition of the `ExtendedLog` table to the `mod_sftp` docs.  Thanks!
