### ISSUE TITLE
proftpd --nodaemon and SystemLog/ServerLog

### ISSUE THREAD

**Issue by offsides** [proftpd/proftpd#1612]
Under systemd (at least on RHEL), proftpd runs with the --nodaemon flag, which causes all logging that would go to syslog to go to stderr instead.  This also means that if you use the SystemLog and ServerLog directives, they are functionally ignored.  Is there any way to make proftpd write to those logs in addition to stderr?  Not a huge deal, but it would be nice to be able to have those logs sent to a file for more compact visibility rather than having to comb through the systemd logs, not to mention having those logs persist over a longer period of time.

**Comment by Castaglia** [comment]
Alternatively, perhaps we can find a way to have `systemd` (which I utterly _despise_) handle ProFTPD in such a way that ProFTPD can run without the `--nodaemon` option.

**Comment by offsides** [comment]
I will see what I can do, but this is how the EPEL maintainers have packaged it, and I'd prefer to not have to argue with them about it.  But I don't disagree with either of your thoughts. :)

That said, I'm mostly done with a patch that adds a command-line flag to do this, I'll generate a PR for it soon.  But before I do, I found an issue with how you are generating the timestamp on messages (duplicated code that hasn't quite been written the same way, and if logging to both places it really needs to be called only once to ensure that the timestamp is identical for both.  But more important is cleaning up the code to begin with), so I'll put in a clean PR for that first, and then a second for my patch to add secondary file logging (assuming I can't figure out an easy way to get systemd to behave without --nodaemon).

**Comment by offsides** [comment]
Looks like there's no good reason (that I can see) for running proftpd with --nodaemon under systemd, changing it from Type = simple to Type = forking and removing the --nodaemon flag appears to work just fine.  I wish there was an easy way to send all my logs to both logfiles and syslog, but I know how to do that outside of proftpd with syslog's file reader, so I can just use that instead.  Given that I probably would need to do that for some logs anyway, I'm going to abandon my split logging work and just do things this way.  Thanks for the idea, I was so focused on one idea that I hadn't considered the other.
