### ISSUE TITLE
mod_sftp treats auth method 'none' as a failed login rather than the client asking for valid auth types

### ISSUE THREAD

**Issue by offsides** [proftpd/proftpd#1619]
### What I Did

Connect to proftpd via SFTP.

### What I Expected/Wanted

I don't want to get a failed login dispatch before the client actually attempts to log in, yet it do - even if they successfully login afterwards.  It appears that mod_sftp treats the initial USER/USERAUTH_REQUEST as a partial login failure - it sends POST_CMD_ERR for processing, but doesn't count it against the maximum number of authentication attempts.  Given that this is a special case "auth" where the client is using a specific keyword to get the server's authentication methods rather than trying to use null authentication to log in, I would think that this shouldn't be treated as a POST_CMD_ERR, as it's not actually an error/failure.  Alternately, if there's some way to differentiate this from an actual authentication failure so that I can filter them out of my mod_exec processing, that would work too.

### ProFTPD Version and Configuration

All of the info from #1618 is 100% identical to this issue.  I made them separate issues as while they are similar they are not actually the same.

**Comment by Castaglia** [comment]
Hrm.  Treating "none" as a success is not quite correct, either -- that is how "anonymous SSH authentication" would be implemented.  The SSH RFCs don't specify a "null" authentication.

**Comment by offsides** [comment]
I was digging around the mod_exec code to see what information the substitutions could provide, and found the undocumented %{env:} substitution and thought that perhaps mod_sftp could set an environment variable as to whether the auth "failure" was hard or soft, and that could be passed on to whatever handler mod_exec ran to decide what to do with it.  However, it appears that the %{env:} is parsed at initialization time by the config file parser, and thus is not able to be used to substitute anything by mod_exec.  If this is a direction you think worthwhile, I can file a separate issue for the %{env:} parsing part (or I can do it anyway, if you'd like), but I don't consider it to be a critical issue otherwise.

I also looked at whether auth_tries could somehow help, but that's static in mod_auth.c, so it's not available outside that module (which makes sense).

**Comment by Castaglia** [comment]
So, if I can restate the question here: you have some custom `mod_exec`-based code, and you are looking for a way, in that module code, to determine whether authentication has completed successfully or not?  Is that correct?

**Comment by offsides** [comment]
Essentially, yes (assuming that by 'completed successfully' you mean that they authentication process completed without error, rather than that authentication was successful).  I have mod_exec configured with both an ExecOnCommand and ExecOnError for the PASS command, which for FTP lets me reliably track both successful and failed login attempts.  With mod_sftp, while the ExecOnCommand does reliably track successful logins, ExecOnError does not because a) the initial auth method of 'none' generates a PASS Error event and b) when using key auth, there is a PASS Error event generated for the lack of a password before it checks the key.  In both of those cases, the auth 'failure' is not treated as an actual failed auth attempt by mod_sftp, which continues with its authentication process.  While I think I would prefer to just not generate that PASS Error event at all, your initial reply makes me think that it's possible or even likely that they should be generated, in which case the next best thing would be to have a way to pass whether mod_sftp thinks the current authentication attempt is complete to mod_exec, and then the code invoked there can make a decision as to how to handle things from there.  As long as I can avoid processing those 'soft' PASS Error events as actual failed login attempts, whether it's handled inside Proftpd or on my end doesn't really matter to me.

**Comment by Castaglia** [comment]
In that case, I think this particular part of `mod_sftp` may be of interest:
* https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/auth.c#L1454

The note in question for "non-fatal" SFTP authentication requests is here:
* https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/auth.c#L1071

So, for example, in your module, you might check of the existence of this note, for an `ERR` command:
```
const void *sftp_nonfatal_note;

sftp_nonfatal_note = pr_table_get(cmd->notes, "mod_sftp.nonfatal-attempt", NULL);
if (sftp_nonfatal_note != NULL) {
  /* If this note exists, it means this is non-fatal SSH authentication attempt. */
}
```

**Comment by offsides** [comment]
Huh, I'm not sure if I missed that or just didn't understand it.  I'll have to add a % filter for that to mod_exec and see what it spits out.  If that gives me what I need, I'll submit a PR so that anyone can use it with mod_exec.  Thanks!
