### ISSUE TITLE
SSH key exchange requests should be classifed into the "SEC" ExtendedLog class

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1626]
Currently, the SSH requests related to the setup of the security context, _i.e._ key exchange and initialization requests, are classified into the "AUTH" [`ExtendedLog`](http://www.proftpd.org/docs/modules/mod_log.html#ExtendedLog) command class.  These requests include:
* `DH_INIT`
* `DH_GEX_INIT`
* `DH_GEX_REQUEST`, `DH_GEX_REQUEST_OLD`
* `ECDH_INIT`
* `EXT_INFO`
* `KEXINIT`
* `KEXRSA_SECRET`
* `NEWKEYS`

Upon reflection, however, I think these SSH requests more closely match the intent of the "SEC" (security) command class, alongside FTPS commands of similar nature.  The only exception being the `EXT_INFO` "request", which is more informational; it will be classified into the "INFO" command class.

The scope of this ticket is to reclassify these SSH requests into the "SEC" command class, and update the docs accordingly.

**Comment by Castaglia** [comment]
@offsides This ticket may be of interest to you as well, per Issue #1611.

**Comment by Castaglia** [comment]
Now fixed in master.

**Comment by offsides** [comment]
I'll have to take a look in detail tomorrow, but in principle it makes sense to move those into a separate category.  From the looks of it you're already using this for TLS-related security commands, so that's yet another point in its favor as well.
