### ISSUE TITLE
proftpd-1.3.8 compiling on Ubuntu 22.04,  minimal config for a sftp server

### ISSUE THREAD

**Issue by zhousy29** [proftpd/proftpd#1628]
### What I Did

I tried to compile proftpd-1.3.8 source on Ubuntu 22.04. below is what I did:
```
apt install lbssl-dev
```
and , in the top dir of source ,
```
./configure --enable-openssl --with-modules=mod_sftp
make
```
and below is the error :
```
_/usr/bin/ld: contrib/mod_sftp/mod_sftp.a(crypto.o): in function `do_aes_ctr':
/root/upstream/proftpd-1.3.8/contrib/mod_sftp/crypto.c:724: undefined reference to `ctr_incr'
collect2: error: ld returned 1 exit status
make: *** [Makefile:80: proftpd] Error 1_
```
I went through the codes, it looks like `ctr_incr` is only  defined for certain openssl version  , not for the openssl 3.0.2 on Ubuntu 22.04
but I thought the 1.3.8 source already adapted to openssl 3,  how could it still reference the function using old openssl ?

Is there some configuration I can pass to  ./configure ?

thanks

### What I Expected/Wanted

successfully make

**Comment by Castaglia** [comment]
What does `openssl version -a` show on your Ubuntu 22.04 host?

**Comment by zhousy29** [comment]
Hi Castaglia,  below is the output from my machine running `openssl version -a`

_OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Mon Feb  6 17:57:17 2023 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-hnAO60/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfffab2235f8bffff:0x4001c0fbb_

hope this helps

**Comment by Castaglia** [comment]
Thanks.  And how exactly did you get the ProFTPD source code?  That is, what is the full set of commands that I can run locally, to reproduce your setup?

**Comment by Castaglia** [comment]
Hmm.  I'm not able to reproduce this error locally, using Docker:
```
$ docker run --rm=true -it ubuntu:22.04 bash
# apt-get update
# apt-get install -y curl gcc libssl-dev make
# curl ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.8.tar.gz -o proftpd-1.3.8.tar.gz
# tar zxvf proftpd-1.3.8.tar.gz
# cd proftpd-1.3.8
# ./configure --enable-openssl --with-modules=mod_sftp
# make
```
The compilation succeeds for me.  Is it possible that in your environment, a `make clean` was missing, such that there were leftovers from previous build attempts in the build directory?

**Comment by zhousy29** [comment]
hi Castaglia, 
I must apologize to you for this "issue".  You're right indeed.  I did forget to do a `make clean` before a second compiling, because the first compiling failed due to missing openssl head files.

Anyway, `make` is successful now.  but the binary keeps stopping using the basic sample configuration file.   Maybe, to compile proftpd as a sftp server , the `./configure` needs more arguments.  will you do me a favor showing how to do a proper `./configure`  for a sftp server  if I want `mod_sftp` as dso ?

thanks

**Comment by Castaglia** [comment]
You can send me questions via email directly, sure.  Or we can continue the conversation in this ticket.  Either way works for me.

**Comment by Castaglia** [comment]
Your configuration looks good to me.

I would point out, though, that your logging-related directives (`TransferLog` and `ExtendedLog`) are not applied to the SFTP `<VirtualHost>` section, because they are not in that `<VirtualHost>` section, and they are not in a `<Global>` section (which would apply them to _all_ vhosts).

**Comment by zhousy29** [comment]
thank you , Castaglia. 
I made changes to the config file as you suggested.
