### ISSUE TITLE
Update mod_exec to use the Jot API for resolving variables

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1630]
The scope of this ticket is to update the `mod_exec` module's variable substitution code [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_exec.c#L871) to instead use the Jot API, so that it automatically benefits from new variable additions there.

**Comment by offsides** [comment]
I'm not really familiar with the jot API, but in principle this sounds like an excellent idea to centralize things and avoid code duplication.

**Comment by Castaglia** [comment]
> Add %S to mod_exec for sftp-non-fatal tagging #1629

The Jot API is ProFTPD's internal API that is used to resolve all of the `LogFormat` variables when writing _e.g._ `ExtendedLog` entries.  It is also used, to support those `LogFormat` variables in things like `SQLNamedQuery`, and in logging modules like `mod_redis` and its ilk.  So updating `mod_exec` to use this API as well (which it should be) is a Good Thing.  I consider the fact that `mod_exec` does _not_ use this API to be tech debt to be retired; it's one less place that implements its own handling of these variables.

**Comment by Castaglia** [comment]
Addressed in master now.
