### ISSUE TITLE
Gracefully handle directory creation requests when the directory already exists

### ISSUE THREAD

**Issue by zrlw** [proftpd/proftpd#1639]
### What I Did

we have multiple clients to upload files and  the directories on proftpd server are created as needed.  Only one client will get successful return if mutiple clients send making same directory request simutaneously, others get failure return immediately, 
 but the directory is not created yet, so we must wait some time after catching the exception which wrapped mkdir failure like this:
```
try {
    ftp.mkdir(needed_subdir);
    ftp.cd(needed_subdir);
} catch (SomeExceptionWhichWrappedMakeDirectoryFailure) {
    Thread.sleep(waitTime);
    ftp.cd(needed_subdir); 
    ...
}
```
but we could not determine the wait time.

### What I Expected/Wanted
cache directory creation request, clear up cache when the creation process is completed.
if the same directory creation request is existed in the cache,  don't return failure msg until the cache is cleared.
    
### ProFTPD Version
1.3.7d

**Comment by Castaglia** [comment]
What is the error that the clients see, when their directory creation commands fail?  Can you provide the ProFTPD [debug logging](http://www.proftpd.org/docs/howto/Debugging.html) for these sessions, so that we can see what the server-side errors might be?

**Comment by zrlw** [comment]
debug logging may not be enabled in product environment, i'll check it on working day.
some client will get 'No such file' from proftpd for request 'cd xxx' even after waiting 3s, all clients login proftpd by the same account. i doublt it might be caused by FSCachePolicy mechanism:
![proftpd](https://user-images.githubusercontent.com/40652892/227750471-74922b8a-b825-4dd2-b965-1b7b05b2b96a.png)

**Comment by zrlw** [comment]
our java clients use ChannelSftp of jsch.

**Comment by Castaglia** [comment]
Hmm.  I'm not sure this is a server-side issue, honestly.

ProFTPD is not a multi-threaded server; it uses separate _processes_, not threads, for each client connection.  Each session process is completely independent, and has no knowledge of what any other session process is doing.

It sounds like your application has multiple separate independent connections to ProFTPD (which means each one would have its own separate server-side process).  And your application ends up having these connections "race" each other to create the same directory.  The server-side processes have no knowledge of what any other session is doing, so they will each independently try to reference (then create) the same directory.

Without seeing the specific server-side error for the `MKD` command failure, I cannot offer more useful information at this time.

**Comment by zrlw** [comment]
there are no TraceLog setting in our /etc/proftpd.conf.

jsch sftp client will send SFTP_SSH2_FXP_STAT (byte: 17) request to proftpd for 'cd' command,  it seemed that proftpd will deal it by pr_fsio_stat() which calls fs_cache_stat().
  
see src/fsio.c
```
#define fs_cache_stat(f, p, s) cache_stat((f), (p), (s), FSIO_FILE_STAT)

static int cache_stat(pr_fs_t *fs, const char *path, struct stat *st,
    unsigned int op) {
...
  sc = fs_statcache_get(cache_tab, cache_set, cleaned_path, path_len, now);
  if (sc != NULL) {
    /* Update the given struct stat pointer with the cached info */
    memcpy(st, &(sc->sc_stat), sizeof(struct stat));

    pr_trace_msg(trace_channel, 18,
      "using cached stat for %s for path '%s' (retval %d, errno %s)",
      op == FSIO_FILE_STAT ? "stat()" : "lstat()", path, sc->sc_retval,
      strerror(sc->sc_errno));

    /* Use the cached errno as well */
    errno = sc->sc_errno;

    return sc->sc_retval;
  }
...
```

**Comment by zrlw** [comment]
linux doesn't allow one directory created by mutiple process simutaneously, so it's ok that only one process get success and other process get failure.

**Comment by zrlw** [comment]
if connections "race" each other to create the same directory,  you will get such messages in sftp log:
```
yyyy-MM-dd  hh:mm:ss,ms mod_sftp/1.0.1[pid number]: MKDIR of '/.../.../xxx' failed: File exists 
```
see fxp_handle_mkdir() in fxp.c (mod_sftp).

**Comment by zrlw** [comment]
the reason might be fxp_handle_mkdir() at mod_sftp/fxp.c
the proftpd process which take care of client2's mkdir command:
```
static int fxp_handle_mkdir(struct fxp_packet *fxp) {
  ...
  pr_fs_clear_cache2(path); <-- clear the cache first
  if (pr_fsio_lstat(path, &st) == 0) {  <--- add 'No such file' to the cache as the path is not be created by other proftpd process yet.
    ....
  }
  res = pr_fsio_smkdir(fxp->pool, path, dir_mode, (uid_t) -1, (gid_t) -1); <--- res is -1 as the path is created by other proftpd process now.
  if (res < 0) {
     ...
     (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
      "MKDIR of '%s' failed: %s", path, strerror(xerrno));
     return fxp_packet_write(resp);
  }
```
this proftpd process will return cached result 'No such file' for next 'cd samed-path' command which is accepted in less than 3s.
this issue might be avoided to let client wait more than 3s when getting mkdir failure response.

**Comment by zrlw** [comment]
suggestion:
don't check the path is existed in fxp_handle_mkdir() of mod_sftp/fxp.c
or
call pr_fs_clear_cache2(path) if result of pr_fsio_smkdir() is < 0.

**Comment by Castaglia** [comment]
Hm.  I'm thinking checking for an `EEXIST` error value, if `pr_fsio_smkdir()` fails, and treating that error the same as success, might be a nicer option here.  I'll provide a PR for doing so later today.

**Comment by zrlw** [comment]
if treating that error the same as success，pr_fs_clear_cache2 should be called again to remove the failure cache.

**Comment by Castaglia** [comment]
This should now be fixed in the master branch on GitHub.  Thanks!
