### ISSUE TITLE
Support terminating connection after USER command when TLS is required

### ISSUE THREAD

**Issue by lokapal** [proftpd/proftpd#1640]
### What I Did
I enabled TLS per user with
```
TLSRequired                on
TLSOptions                 AllowPerUser
```

options. Neverthelss, it permits to enter password in non-SSL session:
```
ftp> open ftp.xxxxx.xx
Connected to ftp.xxxxx.xx.
220 ProFTPD Server (Debian) [XX.XX.XXX.XXX]
User (ftp.xxxxx.xx:(none)): white
331 Password required for white
Password:
530 Login incorrect.
Login failed.
```

### What I Expected/Wanted
It seems that Pro-FTPD should behave like FileZilla FTP server:

```
ftp> open XX.XX.XXX.XXXX
Connected to XX.XX.XXX.XXX.
220-FileZilla Server 0.9.60 beta
220 written by Tim Kosse (tim.kosse@filezilla-project.org)
User (XX.XX.XXX.XXX:(none)): white
530 TLS required
Login failed.
```
So user cannot enter password and so it will not be sent through unencrypted connection.

### ProFTPD Version and Configuration
Ubuntu 22.04.2, ProFTPD installed by 
```
apt-get install proftpd

Compile-time Settings:
  Version: 1.3.7c (maint)
  Platform: LINUX [Linux 5.15.0-67-generic x86_64]
  Built: Fri Dec 3 2021 13:35:22 UTC
```

**Comment by Castaglia** [comment]
Support for this has now been merged to master.

To achieve this behavior, you'll need to use the `mod_ifsession` module as well:
```
<IfModule mod_tls.c>
  TLSEngine on
  ...
  TLSRequired on
  TLSOptions AllowPerUser
</IfModule>

<IfModule mod_ifsession.c>
  # Tell mod_ifsession to apply its sections based just on supplied USER, before PASS
  IfSessionOptions PerUnauthenticatedUser

  <IfUser ...>
    TLSRequired off
  </IfModule>
</IfModule>
```
That `mod_ifsession` configuration also enables `mod_tls` to check for `TLSRequired on` after the `USER` FTP command, and before `PASS`, such that if the client has not used TLS by then, the connection is terminated before the client sends `PASS` unencrypted.
