### ISSUE TITLE
the default value of FSCachePolicy in mod_core.html should be annotated with proftpd version

### ISSUE THREAD

**Issue by zrlw** [proftpd/proftpd#1649]
### What I Expected/Wanted
It's easy to mistake the default value of SCachePolicy of proftpd 1.3.6 or 1.3.7 with doc/modules/mod_core.html.
it should be annotated like this:
```
<h3><a name="FSCachePolicy">FSCachePolicy</a></h3>
<strong>Syntax:</strong> FSCachePolicy <em>on|off|size count [maxAge secs]</em><br>
<strong>Default:</strong> FSCachePolicy off (1.3.8rc4 and later) / on (before 1.3.8rc4)<br>
```

**Comment by Castaglia** [comment]
That is not how the ProFTPD docs are currently managed/written.

**Comment by zrlw** [comment]
My colleague said that the default value of Fscachepolicy for proftpd 1.3.7d should be off because the webpage displays this way. 
http://www.proftpd.org/docs/modules/mod_core.html#FSCachePolicy
iIt is difficult for me to directly refute him because the default values of proftpd configuration options could not be shown by a simple command, e.g., proftpd --showdefaultcfg

**Comment by zrlw** [comment]
It might be better to add a explanation that the default value is changed from on to off since 1.3.8rc4 at http://www.proftpd.org/docs/modules/mod_core.html#FSCachePolicy
