### ISSUE TITLE
SystemLog directive should disable logging via syslog

### ISSUE THREAD

**Issue by mchorsley** [proftpd/proftpd#1651]
### What I Did

Set SystemLog to override logging to rsyslog.

### What I Expected/Wanted

Expected the log file specified by SystemLog to populate rather than rsyslog but logs still populate in syslog and ftp log remains empty.

The TransferLog and ExtendedLog weren't being populated until the directives were moved in to &lt;Global&gt;, so I tried moving the SystemLog option into Global and Virtual Host sections but proftpd fails to start with the error:
```
SystemLog: directive not allowed in <Global> context
```

Also dabbled with the SyslogLevel, and DebugLevel but nothing I do seems to help.

This is the first time I've attempted to install Proftpd on Ubuntu 22, previously used CentOS.

I'm probably doing something stupid but I just can't see it. 

### ProFTPD Version and Configuration

```
proftpd -V
Compile-time Settings:
  Version: 1.3.7c (maint)
  Platform: LINUX [Linux 5.15.0-67-generic x86_64]
  Built: Mon Jul 11 2022 15:55:09 UTC
  Built With:
    configure  '--with-modules=mod_sql:mod_sql_mysql:mod_quotatab:mod_quotatab_sql:mod_sftp:mod_sftp_sql:mod_sql_passwd' '--with-includes=/usr/include/mysql/' '--with-libraries=/usr/include/mysql' '--enable-openssl'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic -L/usr/include/mysql -L/usr/lib/x86_64-linux-gnu
  LIBS:  -lssl -lcrypto -lm -lmysqlclient -lz  -lcrypto -lsupp -lcrypt -ldl  -pthread

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    + OpenSSL support (OpenSSL 1.1.1f  31 Mar 2020)
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

### proftpd.conf

```
# This is a basic ProFTPD configuration file for FTP Server
ServerName      "FTP server"
ServerType      standalone
DefaultServer   on

# Add passive ports and public IP address
PassivePorts            49152 65535
MasqueradeAddress       <External IP>

# We don't want .ftpaccess or .htaccess files to be uploaded
PathDenyFilter  "(\\.ftpaccess|\\.htaccess)$"

# Turn off Reverse DNS in order to speed up the logins
UseReverseDNS   off

# Port 21 is the standard FTP port.
#Port            21

# Don't use IPv6 support by default.
UseIPv6         off

SystemLog       /var/log/proftpd/ftp.log

# To prevent DoS attacks, set the maximum number of child processes
# to 30.  If you need to allow more than 30 concurrent connections
# at once, simply increase this value.  Note that this ONLY works
# in standalone mode, in inetd mode you should use an inetd server
# that allows you to limit maximum number of processes per service
# (such as xinetd).
MaxInstances    50

# Maximum concurrent connections allowed per customer.
# When maximum has been reached, message will be displayed.
MaxClientsPerUser       20 "Sorry, you have exceeded the number of concurrent connections."

# Limit the number of different hosts using a given login can connect at any given time.
MaxHostsPerUser         10 "Sorry, the maximum number of hosts for this user already connected."

# Set the user and group under which the server will run.
User            nobody
Group           nogroup

# To cause every FTP user to be "jailed" (chrooted) into their home
# directory, uncomment this line.
DefaultRoot             ~
RequireValidShell       off
WtmpLog                 off

<Limit LOGIN>
        Order           deny,allow
        AllowGroup      group1
        AllowGroup      group2
        IgnoreHidden    On
</Limit>


# Normally, we want files to be overwriteable.
<Directory />
        AllowOverwrite on
</Directory>

<Directory ~/.ssh>
    AllowOverwrite  Off
</Directory>

# Create user home dir if not found
CreateHome      on dirmode 755

# Bar use of SITE CHMOD by default
<Limit SITE_CHMOD>
        DenyAll
</Limit>

<Global>
        #DebugLevel     1
        TransferLog     /var/log/proftpd/xfer.log
        ExtendedLog     /var/log/proftpd/extended.log
        #SyslogLevel     debug

        Umask 002

        ServerIdent On "FTP Server ready."

        <IfModule mod_ident.c>
                IdentLookups off
        </IfModule>

        <IfModule mod_sql.c>
                SQLBackend mysql
                SQLLogFile /var/log/proftpd/mod_sql.log
                AuthOrder mod_sql.c
                SQLAuthenticate users groups
        </IfModule>

        <IfModule !mod_sql_passwd.c>
                # If mod_sql_passwd is not available, then consider using the OpenSSL
                SQLAuthTypes OpenSSL Backend
        </IfModule>

        <IfModule mod_sql_passwd.c>
                # If mod_sql_passwd is available, try other SQLAuthTypes, too
                SQLPasswordEngine on

                # MySQL uses lowercase hex-encoded strings for MD5() et al
                SQLPasswordEncoding hex

                SQLAuthTypes SHA256 SHA1 MD5 Backend
        </IfModule>

        # Configure authentication via SQL database
        SQLConnectInfo database@dbserver:3306 ftp_01-user Password

        # Point mod_sql at our users/groups tables
        SQLUserInfo ftp_users user_name passwd id gid home_dir shell
        SQLUserPrimaryKey id

        SQLGroupInfo ftp_groups name id members

        # Count number of logins for each user
        SQLLog PASS logincount
        SQLNamedQuery logincount UPDATE "login_count=login_count+1 WHERE user_name='%u'" ftp_users

        # Save last login
        SQLLog PASS lastlogin
        SQLNamedQuery lastlogin UPDATE "last_login=now() WHERE user_name='%u'" ftp_users

        # display last login time when PASS command is given
        SQLNamedQuery login_time SELECT "last_login from ftp_users where user_name='%u'"
        SQLShowInfo PASS "230" "Last login was: %{login_time}"

        # Count number of bytes/files downloaded and uploaded
        SQLLog RETR dlbytescount
        SQLNamedQuery dlbytescount UPDATE "dl_bytes=dl_bytes+%b WHERE user_name='%u'" ftp_users
        SQLLog RETR dlcount
        SQLNamedQuery dlcount UPDATE "dl_count=dl_count+1 WHERE user_name='%u'" ftp_users
        SQLLog STOR ulbytescount
        SQLNamedQuery ulbytescount UPDATE "ul_bytes=ul_bytes+%b WHERE user_name='%u'" ftp_users
        SQLLog STOR ulcount
        SQLNamedQuery ulcount UPDATE "ul_count=ul_count+1 WHERE user_name='%u'" ftp_users

        SQLLog RETR,STOR,RNTO,RNFR,DELE logtraffic
        SQLNamedQuery logtraffic FREEFORM "INSERT INTO ftp_history (user_name, file_name, size, host, command, time_stamp) VALUES (%{note:sql.user-primary-key},'%f','%b','%h','%m',now())"

        ### Log user error events (ERR_* commands)
        SQLLog ERR_* logevents
        SQLNamedQuery logevents FREEFORM "INSERT INTO ftp_user_events (user_name, event_type, description, event_date) VALUES ('%u', '%m', '%r', NOW())"

</Global>

# FTP virtual host
<VirtualHost <External IP> 10.33.1.119>
        Port                    21
        DefaultRoot             ~

        #TransferLog     /var/log/proftpd/xfer.log
        #ExtendedLog     /var/log/proftpd/extended.log
        #SystemLog      /var/log/proftpd/ftp.log
        #ServerLog      /var/log/proftpd/ftp.log
        #SyslogLevel    INFO

        # An account set up to be SFTP should not be allowed using FTP
        SQLUserWhereClause      "disabled!=1 and sftp!=1 and (NOW()<=expires or expires=-1)"

        # Create user home dir if not found
        CreateHome on dirmode 755

        <Limit LOGIN>
                Order           deny,allow
                AllowGroup      group1
                AllowGroup      group2
        </Limit>

        <Directory />
                AllowOverwrite  on
                HideNoAccess    Off
        </Directory>

        <Directory ~/.ssh>
                <Limit READ DIRS>
                        IgnoreHidden on
                </Limit>
                AllowOverwrite  Off
                HideNoAccess    Off
        </Directory>
</VirtualHost>

# SFTP virtual host
<VirtualHost 10.33.1.119>
        SFTPEngine              On
        SFTPLog                 /var/log/proftpd/sftp.log
        Port                    22
        SFTPHostKey             /etc/ssh/ssh_host_rsa_key
        SFTPHostKey             /etc/ssh/ssh_host_dsa_key
        SFTPAuthorizedUserKeys  file:~/.ssh/authorized_keys
        SFTPKeyBlacklist        /home/ftp

        DefaultRoot ~

        SQLUserWhereClause      "disabled!=1 and sftp=1 and (NOW()<=expires or expires=-1)"

        <Limit LOGIN>
                Order deny,allow
                AllowGroup group1
                AllowGroup group2
        </Limit>


        <Directory />
                AllowOverwrite  on
                HideNoAccess    off
        </Directory>

        <Directory ~/.ssh>
                AllowOverwrite  off
                HideNoAccess    off
                <Limit READ DIRS CWD>
                        IgnoreHidden on
                </Limit>
        </Directory>
</VirtualHost>
```

Appreciate any help

**Comment by Castaglia** [comment]
For my clarification: you have multiple `<VirtualHost>` sections defined, and you'd like to see the logs for sessions for those vhosts all directed to your configured `SystemLog` file, but they are not.  Is that correct?  What log messages, specifically, do you still see in the `rsyslog` log files?

**Comment by mchorsley** [comment]
Hi,

Kind of, i'm specifically interested in the ftp ```<VirtualHost>``` connections. Other Proftpd servers (built years ago), login success and failures are logged in the /var/log/proftpd/ftp.log file, but the most recent couple of servers we've built are logging these messages to the /var/log/syslog file.  I didn't spot this until implementing fail2ban which was configured to use the ftp.log

```
Mar 31 07:34:29 etlxftp01 proftpd[114129]: 2023-03-31 07:34:29,485 etlxftp01 proftpd[114129] 127.0.1.1: 127.0.1.1:21 masquerading as <public ip>
Mar 31 07:34:29 etlxftp01 proftpd[114129]: 2023-03-31 07:34:29,487 etlxftp01 proftpd[114129] 127.0.1.1: ProFTPD 1.3.7c (maint) (built Mon Jul 11 2022 15:55:09 UTC) standalone mode STARTUP
Mar 31 07:34:41 etlxftp01 proftpd[114130]: 2023-03-31 07:34:41,183 etlxftp01 proftpd[114130] 10.33.1.119 (10.33.129.173[10.33.129.173]): mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module
Mar 31 07:34:41 etlxftp01 proftpd[114130]: 2023-03-31 07:34:41,183 etlxftp01 proftpd[114130] 10.33.1.119 (10.33.129.173[10.33.129.173]): FTP session opened.
Mar 31 07:34:41 etlxftp01 proftpd[114130]: 2023-03-31 07:34:41,348 etlxftp01 proftpd[114130] 10.33.1.119 (10.33.129.173[10.33.129.173]): USER c.test: Login successful.
```

Could this be specific to the ```<VirtualHost>``` used for FTP?  My understanding is that the basic FTP doesn't need to be in a ```<VirtualHost>```.  I'm sure i've tried this, but i've made so many changes over the past week.  Let me try that first.

**Comment by mchorsley** [comment]
Removing the ```<VirtualHost>``` for the FTP service made no difference, logs still going to syslog.

**Comment by Castaglia** [comment]
Are you running ProFTPD via `systemd` by chance?  If so, can you provide the systemd `proftpd.service` unit file being used?

**Comment by mchorsley** [comment]
Yes it's ```systemd```

```
/lib/systemd/system/proftpd.service
```

```
[Unit]
Description = ProFTPD FTP Server
Wants=network-online.target
After=network-online.target nss-lookup.target local-fs.target remote-fs.target

[Service]
Type = simple
Environment = PROFTPD_OPTIONS=
EnvironmentFile = -/etc/sysconfig/proftpd
ExecStartPre = /usr/local/sbin/proftpd --configtest
ExecStart = /usr/local/sbin/proftpd --nodaemon $PROFTPD_OPTIONS
ExecReload = /bin/kill -HUP $MAINPID
PIDFile = /run/proftpd/proftpd.pid

[Install]
WantedBy = multi-user.target
```

**Comment by Castaglia** [comment]
Right.  @pghmcfc @hpreusse is there something that can be done to update the unit file used for ProFTPD under `systemd`, so that it does *not* use the `--nodaemon` command-line option?  This is leading to numerous questions.

The _better_ `systemd` unit file for ProFTPD would be like so, as see [here](https://github.com/proftpd/proftpd/issues/1612#issuecomment-1450657014):
```
[Unit]
Description = ProFTPD FTP Server
Wants=network-online.target
After=network-online.target nss-lookup.target local-fs.target remote-fs.target

[Service]
Type = forking
Environment = PROFTPD_OPTIONS=
EnvironmentFile = -/etc/sysconfig/proftpd
ExecStartPre = /usr/local/sbin/proftpd --configtest
ExecStart = /usr/local/sbin/proftpd $PROFTPD_OPTIONS
ExecReload = /bin/kill -HUP $MAINPID
PIDFile = /run/proftpd/proftpd.pid

[Install]
WantedBy = multi-user.target
```
Specifically, change:
```
Type = simple
```
to:
```
Type = forking
```
and remove `--nodaemon`.

@mchorsley You might try this tweak for your installation.

**Comment by pghmcfc** [comment]
@Castaglia, the preference for `Type=simple` was based on advice from systemd upstream, that a non-forking process gave systemd better visibility of the state of the process. The current advice is a little different, and can be found here:
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options

> "It is generally recommended to use Type=simple for long-running services whenever possible, as it is the simplest and fastest option. However, as this service type won't propagate service start-up failures and doesn't allow ordering of other units against completion of initialization of the service (which for example is useful if clients need to connect to the service through some form of IPC, and the IPC channel is only established by the service itself — in contrast to doing this ahead of time through socket or bus activation or similar), it might not be sufficient for many cases. If so, notify, notify-reload or dbus (the latter only in case the service provides a D-Bus interface) are the preferred options as they allow service program code to precisely schedule when to consider the service started up successfully and when to proceed with follow-up units. The notify/notify-reload service types require explicit support in the service codebase (as sd_notify() or an equivalent API needs to be invoked by the service at the appropriate time) — if it's not supported, then forking is an alternative: it supports the traditional UNIX service start-up protocol. Finally, exec might be an option for cases where it is enough to ensure the service binary is invoked, and where the service binary itself executes no or little initialization on its own (and its initialization is unlikely to fail). Note that using any type other than simple possibly delays the boot process, as the service manager needs to wait for service initialization to complete. It is hence recommended not to needlessly use any types other than simple."

If there's good reason not to use `--nodaemon` mode, it shouldn't be an issue to switch back from `Type=simple` to `Type-forking`.

**Comment by mchorsley** [comment]
Getting close, the ftp log file is now populated with login success and failure, which is great  ```(SyslogLevel INFO)```

However, proftpd is dying after 2 minutes:

```
proftpd.service: Can't open PID file /run/proftpd/proftpd.pid (yet?) after start: Operation not permitted
proftpd.service: start operation timed out. Terminating.
proftpd.service: Failed with result 'timeout'.
Failed to start ProFTPD FTP Server.
```

There is no pid file at ```/run/proftpd/proftpd.pid```

**Comment by pghmcfc** [comment]
Your `proftpd -V` output indicates that proftpd is putting the PID file at /usr/local/var/proftpd.pid. I'd suggest specifying the PIDfile location in proftpd.conf to align it where systemd exoects to find it.

**Comment by mchorsley** [comment]
Yes, that was the final piece.  Added ```PidFile /run/proftpd/proftpd.pid``` to proftpd.conf.

Thanks so much for your help.

**Comment by Castaglia** [comment]
> @Castaglia, the preference for `Type=simple` was based on advice from systemd upstream, that a non-forking process gave systemd better visibility of the state of the process. The current advice is a little different, and can be found here: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options
> 
> > "It is generally recommended to use Type=simple for long-running services whenever possible, as it is the simplest and fastest option. However, as this service type won't propagate service start-up failures and doesn't allow ordering of other units against completion of initialization of the service (which for example is useful if clients need to connect to the service through some form of IPC, and the IPC channel is only established by the service itself — in contrast to doing this ahead of time through socket or bus activation or similar), it might not be sufficient for many cases. If so, notify, notify-reload or dbus (the latter only in case the service provides a D-Bus interface) are the preferred options as they allow service program code to precisely schedule when to consider the service started up successfully and when to proceed with follow-up units. The notify/notify-reload service types require explicit support in the service codebase (as sd_notify() or an equivalent API needs to be invoked by the service at the appropriate time) — if it's not supported, then forking is an alternative: it supports the traditional UNIX service start-up protocol. Finally, exec might be an option for cases where it is enough to ensure the service binary is invoked, and where the service binary itself executes no or little initialization on its own (and its initialization is unlikely to fail). Note that using any type other than simple possibly delays the boot process, as the service manager needs to wait for service initialization to complete. It is hence recommended not to needlessly use any types other than simple."
> 
> If there's good reason not to use `--nodaemon` mode, it shouldn't be an issue to switch back from `Type=simple` to `Type-forking`.

@pghmcfc  I see, thanks for the context.

The use of `--nodaemon` is definitely leading to more user confusion, thus is more a hindrance than a help, in my opinion.   The time ProFTPD needs to start up is not high, thus even with `Type=forking`, I do not think it will add much (if any) to any "possible delays of the boot process".

**Comment by hpreusse** [comment]
> Right. @pghmcfc @hpreusse is there something that can be done to update the unit file used for ProFTPD under `systemd`, so that it does _not_ use the `--nodaemon` command-line option? This is leading to numerous questions.
> 
Sorry, late reply. Our systemd unit file is [here](https://salsa.debian.org/debian-proftpd-team/proftpd/-/blob/master/debian/proftpd-core.proftpd.service) and it seems to be OK to me.

**Comment by Castaglia** [comment]
@pghmcfc @hpreusse thanks for the feedback.

I think, for addressing this ticket, I'll add a FAQ to the ProFTPD docs somewhere about `SystemLog`, systemd, and checking the unit file for `-n/--nodaemon` (which is what causes `SystemLog` to not work as expected).

**Comment by Castaglia** [comment]
Added FAQ to the `mod_log` docs.  Thanks!
