### ISSUE TITLE
Remove asynchronous FTP responses emitted while computing digest values

### ISSUE THREAD

**Issue by DailyFrankPeter** [proftpd/proftpd#1661]
### What I Did

With BeyondCompare, tried to call XCRC to compare a few-GB file over LAN.

See my ticket on FTP client's forum:
https://forum.scootersoftware.com/forum/beyond-compare-4-discussion/general/90156-crc-comparison-looking-for-ftp-server-recommendations#post90176

### What I Expected/Wanted

Sent> XCRC ...filename...
Recv> 250 ...CRCvalue...

### ProFTPD Version and Configuration

v1.3.7 (compiled locally) / v1.3.8 (precompiled, from apt)

Default config except mod_digest is enabled and set to digest larger files than 1 GB.

### Other notes

Also have a look at my crude fix:
https://github.com/DailyFrankPeter/proftpd/tree/remove_xcrc_chatter

**Comment by Castaglia** [comment]
Hmm.  There is another request to change/remove those multi-line responses for `mod_digest`; see https://github.com/proftpd/proftpd/pull/1368

I guess since they cause problems for non-conformant FTP clients, I'll remove them.

**Comment by Castaglia** [comment]
This should now be fixed in master.  Thanks!

**Comment by DailyFrankPeter** [comment]
Thanks.
