### ISSUE TITLE
Avoid logging of "Login timeout exceeded, disconnected"

### ISSUE THREAD

**Issue by shakaran** [proftpd/proftpd#167]
I am using ProFTP 1.3.5 under CentOS 5.9.

I have a log inspecter installed in my server and I receive a lot entries in /var/log/messages like:

    Nov 12 00:12:01 server1 proftpd[12575]: 256.256.256.256 (127.0.0.1[127.0.0.1]) - Login timeout exceeded, disconnected

I would know if exists a way to hide or redirect the output to another output file log for the log lines "Login timeout exceeded, disconnected" so I can have a less verbose /var/log/messages

**Comment by Burnett01** [comment]
Support

**Comment by Castaglia** [comment]
Currently, those particular "Login timeout exceeded" messages are logged at the `NOTICE` level.  I could change them to be logged at the `INFO` level.

Note that filtering these messages, given that you are using `syslog` logging, also depends on the `syslog.conf` level filters you have configured (and can change).  For example, assuming the log message in question is logged at only `INFO`, then you can have your `syslog.conf` set to filter out `INFO` level messages (and above) to the `/var/log/messages` file.

**Comment by Castaglia** [comment]
The PR was merged to master; considering this issue closed.
