### ISSUE TITLE
Support OPTS commands for querying configured policy for resumed uploads, downloads

### ISSUE THREAD

**Issue by martinprikryl** [proftpd/proftpd#1676]
Repeatedly I got reports from WinSCP users having problem with uploading to ProFTPD server that has `AllowStoreRestart` disabled (the default, I believe). [One of the reports](https://winscp.net/forum/viewtopic.php?t=33442).

When the upload is interrupted for whatever reason, WinSCP cannot recover it automatically.
ProFTPD reports `REST STREAM` in `FEAT`, so WinSCP believes it can resume the transfer. But it does not work, as ProFTPD fails it with
> 451 Append/Restart not permitted, try again

I'm wondering how to improve the user experience here. But there does not seem much WinSCP can do to detect the situation.
- As mentioned, `FEAT` contains `REST STREAM`.
- The code `451` is too generic.
- The error response comes after `STOR` command, not `REST` (I understand that's it because at the `REST` command, the server does not know yet, if it's gonna be for upload or download – and the permissions for those are separate).

Could you:
- Not send `REST STREAM`, at least when `AllowStoreRestart` is disabled globally (I guess that it's the most common scenario, as it's the default)? (I understand that the directive can be set per-folder).
- Use more unique error code?
- Other ideas? :)

Thanks.

**Comment by martinprikryl** [comment]
`SITE` command would do (something like `SITE RESTUPLOADALLOWED path` to check if restartable upload is possible for given path?). I'm just not sure if it is not an overkill for this. I'll leave that on you :) Thanks for your feedback.

**Comment by Castaglia** [comment]
I was just re-reading [RFC 2389 Section #3](https://www.rfc-editor.org/rfc/rfc2389#section-3), and thought of another possibility: an `OPTS REST STOR` command.  That is, can we use the `OPTS` command to effectively query whether the `REST` + `STOR` would work?  ProFTPD, in the presence of `AllowStoreRestart off`, might respond with a 451 response code.

Currently ProFTPD would reject such an `OPTS REST` command, but I could add this pretty easily.  This approach feels slightly less cumbersome than a custom `SITE` command.  Thoughts?

**Comment by martinprikryl** [comment]
Sounds good!

**Comment by Castaglia** [comment]
Support for an `OPTS REST STOR` (and `OPTS REST RETR`, for symmetry) has been merged to master.  Let me know if it works, or if you find any issues.  Thanks!

**Comment by martinprikryl** [comment]
Thanks. Seems to be working fine.
I've implemented the WinSCP part:
https://winscp.net/tracker/2194
<hr>
Do I understand right that the `OPTS REST` command evaluates only global (or per-user) configuration (not the per-directory configuration)?

**Comment by Castaglia** [comment]
> Do I understand right that the `OPTS REST` command evaluates only global (or per-user) configuration (not the per-directory configuration)?

Currently, yes.  I understand that there may be per-directory edge cases with this feature; I want to tackle those separately, going forward, as those use cases arise.  Honoring the global-level configurations should hopefully handle a majority of use cases.
