### ISSUE TITLE
mod_sql is not properly closing all named backend connections on session exit

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1697]
In Issue #1659, in addition to the issue when opening the named connection to a different backend SQL server, there was _another_ issue reported, where MySQL was showing increasing counts of `Aborted_clients` unexpectedly; see:
* https://github.com/proftpd/proftpd/issues/1659#issuecomment-1668337090

The scope of this ticket is to address these `Aborted_clients` metrics.  I suspect it is because `mod_sql`, when exiting, is not properly dispatching a "sql_exit" event to all of the named backends, and instead is _only_ dispatching a "sql_exit" event to the `default` backend:
* https://github.com/proftpd/proftpd/blob/master/contrib/mod_sql.c#L5934

CC @rafasc

**Comment by Castaglia** [comment]
For my own future reference, there _is_ an ODBC driver written for SQLite:
* http://www.ch-werner.de/sqliteodbc/

And it is available, as the `libsqliteodbc` package, on _e.g._ Ubuntu 20.04.

I don't think I'll make use of it for this particular ticket, but it is good to know that I could use it, and a Docker Compose setup, to better reproduce issues that involve multiple `mod_sql` connections to different backend databases of different types.

**Comment by Castaglia** [comment]
@rafasc I believe https://github.com/proftpd/proftpd/pull/1698 should hopefully quell/address the MySQL `Aborted_clients` metrics you reported.  Would you be able to test it out, and let me know?

**Comment by rafasc** [comment]
I've tested this patch, backported to v1.3.8, and seems to work. No more aborted clients. THanks!

We're experiencing a regression in terms of performance but I need to investigate it further.

**Comment by Castaglia** [comment]
Thanks @rafasc  I just rejiggered the PR a little bit, but it should fix the issue.  Once you confirm that, I'll backport this fix to 1.3.8 as well.

**Comment by Castaglia** [comment]
This should now be fixed in `master`, and backported to the 1.3.8 branch.
