### ISSUE TITLE
memory leak in function 'json_mkstring'

### ISSUE THREAD

**Issue by JoraGevorgyan** [proftpd/proftpd#1720]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
[here](https://github.com/proftpd/proftpd/blob/8a1a459d55cfbf345635908184446170daf97fd4/lib/ccan-json.c#L551) in function 'json_mkstring' it calls 'json_strdup' and passes the return value as an argument to 'mkstring'. 'mkstring' calls 'mknode' which may return NULL, and w/o checking [uses that pointer](https://github.com/proftpd/proftpd/blob/8a1a459d55cfbf345635908184446170daf97fd4/lib/ccan-json.c#L545C4-L545C4), so it's a null pointer dereference and after that unefined behavior and the [allocated memory](https://github.com/proftpd/proftpd/blob/8a1a459d55cfbf345635908184446170daf97fd4/lib/ccan-json.c#L551C13-L551C13) by 'json_strdup' will left w/o free.

**Comment by Castaglia** [comment]
The only way for `mknode` to return NULL is if `calloc(3)` returns NULL [here](https://github.com/proftpd/proftpd/blob/master/lib/ccan-json.c#L521).  And if that happens, the `json_oom` callback is invoked.

The [default OOM handler](https://github.com/proftpd/proftpd/blob/master/lib/ccan-json.c#L42) calls `exit(3)`, ending the process _before_ returning to `mkstring`.   ProFTPD sets a slightly different OOM handler, mostly for logging (see [here](https://github.com/proftpd/proftpd/blob/master/src/json.c#L1123)), but it too calls `exit(3)`.  So I'm not sure this is actually a leak in practice.
