### ISSUE TITLE
How to start proftpd using a non-root user ?

### ISSUE THREAD

**Issue by leocoder0** [proftpd/proftpd#1739]
How to start proftpd using a non-root user and support sftp key mode? Previously, I used the root user to compile, used chmod to modify the group belonging to the compilation directory, and then started using another user to report an error, prompting bind 0.0.0.0 port 21 failed, Permission denied.

**Comment by Castaglia** [comment]
You might find this useful, for your use case:
* http://www.proftpd.org/docs/howto/Nonroot.html

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.  Thanks!
