### ISSUE TITLE
Username based load-balancing

### ISSUE THREAD

**Issue by benrubson** [proftpd/proftpd#174]
Hello,

Here is a FTP architecture design topic, with (I think) a feature request.

### Situation :

Let's assume several storage servers, let's take 2 for this example :
```
serverA
serverB
```
Then, of course several users, each one has its files on one of the storage servers.
For example :
```
serverA : user1, user2
serverB : user3, user4
```
The storage infrastructure is growing, perfect !
We must add a new storage server, and migrate some users.
Our example then changes to the following :
```
serverA : user1, user2
serverB : user3
serverC : user4, user5
```
*user4 has migrated from serverB to serverC.*

### Request :

In order to avoid annoying users giving them a new FTP address each time their files are migrated (serverC instead of serverB for user4 in our example), I would like be able to add a FTP load-balancer.
All users would then be able to reach their files using a unique FTP address (the load-balancer's one), even if their files have migrated from a storage server to another.

The load-balacing must then be based on username : the load-balancer takes the incoming FTP login connections, and according to the username, redirect them to the correct server.
In order to optimize bandwith, DSR (Direct Server Return) is a must-have so that each file transfer is directly established between the target server and the FTP client, without going through the load-balancer, which would without DSR act as a bottleneck.
For security reasons, TLS should be supported for incoming connections.

All servers and load-balancer could share a common users authentication method (LDAP, SQL)...
A user password will then be the same for the 2 authentications steps (load-balancer, then target server).

The target server info could also be found in this authentication source (a specific field in LDAP, SQL)...

Do you think we could think about such a solution ?
Would really be awesome :+1:

Thank you very much TJ / ProFTPD team !

Best regards,

Ben

**Comment by Castaglia** [comment]
For this, you should look into using the `mod_proxy` module:

  https://github.com/Castaglia/proftpd-mod_proxy

The `ProxyReverseConnectPolicy PerUser` is what you would need.  Note that `mod_proxy` does not support DSR at the moment, though.

**Comment by benrubson** [comment]
Thank you very much for your answer, sounds like it is what I need yes :+1: 
I will then give it a try.

Thank you very much :+1: 

* regarding DSR, I just opened a feature request [here](https://github.com/Castaglia/proftpd-mod_proxy/issues/49), thank you !*

**Comment by Castaglia** [comment]
Closing this ticket, as it will be addressed via `mod_proxy` and any future work there.
