### ISSUE TITLE
Support reading OpenSSH-specific SSH public keys via custom module

### ISSUE THREAD

**Issue by Sebbo94BY** [proftpd/proftpd#1748]
### What I Did

ProFTPd `mod_sftp` currently only supports RFC4716 formatted public keys for `SFTPAuthorizedUserKeys`.

http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPAuthorizedUserKeys

### What I Expected/Wanted

It would be great, if the more common OpenSSH-specific format would be also supported here: `ssh-rsa AAakaiAiV= [optional comment]`

Is there any reason, why they must be in RFC4716 format? Would it be possible to add support for the OpenSSH-specific format? Maybe using a configuration option which defaults to the RFC4716 format to avoid changing the behaviour of current setups?

### ProFTPD Version and Configuration

ProFTPd 1.3.8 on Debian Bookworm

**Comment by Castaglia** [comment]
I deliberately chose a non-OpenSSH-specific format to be supported; RFC 4716 is meant to be portable format, not specific to any one implementation.  And there is a straightforward way to convert an OpenSSH formatted key into the RFC 4716 format, using `ssh-keygen -e -f`, as explicitly mentioned in the `mod_sftp` documentation:
* http://www.proftpd.org/docs/contrib/mod_sftp.html#UsageRFC4716Format

**Comment by Sebbo94BY** [comment]
Yes, I know. I've also seen this in the documentation.

My problem here is, that the application, which stores the SSH keys expects those keys in OpenSSH-specific format and I can't change this.

As workaround from the infrastructure side, I've currently built a small script, which regulary checks all `authorized_keys` files, converts them and saves them into a new e. g. `authorized_keys_rfc4716` file.

The problem here is, that this is currently a regular cronjob over all thousand available `authorized_keys` files. It only takes a few seconds in the current implementation, but it's not real-time. A customer adds a key via the application and expects it to work immediately and not after e. g. 1 or 5 minutes.

I couldn't use `inotify` here as based on the filesystem and the amount of files as it regulary didn't noticed file changes and then nothing was executed / converted.

`fuse` would be a real-time and great solution, but I can't use this at the moment due to the different and very dynamic possible home directories as mentioned in #1747 .

The other problem with `ssh-keygen -e -f` is, that it always only converts one SSH key from the given file even when there are multiple in it. Thus, I need to read the original file line by line, temporary write each key into a temporary file, convert this single key and append it to a new target file, which at the end replaces the target `authorized_keys` file, which contains the RFC4716 formatted keys.

**Comment by Castaglia** [comment]
I see.  Thanks for the providing the background context motivating this feature request.

To support a use case like this -- without interfering with the existing RFC 4716 support in mod_sftp (which I still strongly feel _should_ be the format used, not application-specific formats) -- I can look into implementing a separate module that parses/handles OpenSSH-formatted public keys.

**Comment by Castaglia** [comment]
@Sebbo94BY Here's a separate module which adds support for your use case:
* https://github.com/Castaglia/proftpd-mod_sftp_openssh

Note that your ProFTPD will also need the fix for Issue #1756 in order to compile the above module.

**Comment by Sebbo94BY** [comment]
Wow, what a quick solution. I expected this earliest in one year to be honest. :sweat_smile:

Thank you very much for your quick and great effort, @Castaglia! I really appreciate this.

Regarding your required mentioned fix: We're using the official package provided by Debian Bookworm:
- Package: proftpd-core
- Version: 1.3.8+dfsg-4+deb12u2 (currently latest version)

Can you tell me with which version this fix will be included there? I unfortunately also couldn't read this fix in your changelog here: https://github.com/proftpd/proftpd/blob/master/NEWS

The module, which needs to be compiled... I guess I can "simply" add a pipeline job on our side, which clones your repository, compiles it and uploads this specific module as a new APT package to our internal APT repository. Then I can install the `proftpd-core` package from the Debian repositories and the module from our internal APT repository. Or does it also compile and include the `proftpd-core` then?

**Comment by Castaglia** [comment]
I've updated the `NEWS` changelog to mention Issue #1756 now.  Unfortunately, the bug in question lies in the `configure` Autoconf script, and without the fixed version of that `configure` script, one would not be able to compile this `mod_sftp_openssh` module.

Fortunately, I will soon be making new 1.3.8 and 1.3.9 releases for ProFTPD, due to Issue #1760.

**Comment by Castaglia** [comment]
Now that there are newer ProFTPD releases with the fixed `configure` script for building `mod_sftp_openssh`, I'm going to close this ticket.  Thanks!
