### ISSUE TITLE
Add crosscompiling support for ./configure.in

### ISSUE THREAD

**Issue by icegood** [proftpd/proftpd#1768]
For now during configuration of the module for other platform we will obtain:

```
checking whether listen supports negative backlog... 
configure: error: in /home/ice/external/openwrt_build/under_env/openwrt_22_series_for_dlink620/build_dir/target-mipsel_24kc_musl/proftpd-28e60b76':
configure: error: cannot run test program while cross compiling

```

the issue could be fixed if all of macroses AC_TRY_RUN will be feed with 
`
AC_MSG_RESULT(cross-compiling);
`
and some random guesses under cross compilation

**Comment by Castaglia** [comment]
Can you explain your use cases/needs, for why/when you'd like such cross-compiling support?

**Comment by Castaglia** [comment]
Closing this as a duplicate of Issue #1857.
