### ISSUE TITLE
proftpd not using source port 20 for ftp active

### ISSUE THREAD

**Issue by mflage** [proftpd/proftpd#1773]
### What I Did

Tried setting up a ftp active session and monitored the packet capture. Observed that the source port was not the expected port 20 but instead a random port.

### What I Expected/Wanted

Was expecting to see that the source port for the session was 20.

### ProFTPD Version and Configuration

Installed using apt on Ubuntu 22.04, thus running 1.3.7c+dfsg-1build1.

Config:

```
Include /etc/proftpd/modules.conf
UseIPv6 off
<IfModule mod_ident.c>
  IdentLookups off
</IfModule>
ServerName "Debian"
ServerType standalone
DeferWelcome off
DefaultServer on
ShowSymlinks on
TimeoutNoTransfer 600
TimeoutStalled 600
TimeoutIdle 1200
DisplayLogin welcome.msg
DisplayChdir .message true
ListOptions "-l"
DenyFilter \*.*/
UseReverseDNS off
AllowStoreRestart on
DefaultRoot ~ !prod
WtmpLog off
Port 21
PassivePorts                  31000 32000
<IfModule mod_dynmasq.c>
</IfModule>
MaxInstances 30
User proftpd
Group nogroup
Umask 022 022
AllowOverwrite on
TransferLog /var/log/proftpd/xferlog
SystemLog /var/log/proftpd/proftpd.log
ExtendedLog /var/log/proftpd/ftp.log ALL default
<IfModule mod_quotatab.c>
QuotaEngine off
</IfModule>
<IfModule mod_ratio.c>
Ratios off
</IfModule>
<IfModule mod_delay.c>
DelayEngine on
</IfModule>
<IfModule mod_ctrls.c>
ControlsEngine off
ControlsMaxClients 2
ControlsLog /var/log/proftpd/controls.log
ControlsInterval 5
ControlsSocket /var/run/proftpd/proftpd.sock
</IfModule>
<IfModule mod_ctrls_admin.c>
AdminControlsEngine off
</IfModule>
Include /etc/proftpd/tls.conf
<Class expect-proxy-protocol>
        From <proxy_ip>
</Class>
<IfClass expect-proxy-protocol>
        MasqueradeAddress <public ip>
        <IfModule mod_proxy_protocol.c>
                # Enable PROXY protocol support for clients in this class
                ProxyProtocolEngine on
                ProxyProtocolTimeout 3sec
                ProxyProtocolVersion haproxyV2
                # Necessary to allow data transfers from this class
                AllowForeignAddress expect-proxy-protocol
        </IfModule>
</IfClass>
Include /etc/proftpd/conf.d/
```
When looking at the packet capture I see the following:

`14:35:41.596345 IP <public_ip>.43235 > <client_ip>.43693`

With trace on I can also see the following in the trace.log:

`2024-01-24 14:35:40,998 [19066] <binding:4>: bound address <privateip>, port 43235 to socket fd 16 `

**Comment by Castaglia** [comment]
Any suggestions on where, in the documentation, you would expect to look for, and find, this requirement?

**Comment by mflage** [comment]
Maybe around here somewhere: http://www.proftpd.org/docs/directives/configuration_full.html#ROOTREVOKE and maybe also here: http://www.proftpd.org/docs/howto/NAT.html ?

Well, it's easier if the server is behind nat/proxy to predictably be able to know which ports to accept traffic from.

**Comment by Castaglia** [comment]
> Well, it's easier if the server is behind nat/proxy to predictably be able to know which ports to accept traffic from.

True.  But there's no guarantee that the program, using that source port, is an FTP client; it could be a process using any TCP-based protocol.  And there are considerations, such as Windows, which does not enforce the requirement for root privileges in order to use a low-numbered source port.

**Comment by Castaglia** [comment]
> Maybe around here somewhere: http://www.proftpd.org/docs/directives/configuration_full.html#ROOTREVOKE and maybe also here: http://www.proftpd.org/docs/howto/NAT.html ?

Does this cover the topic sufficiently?
* http://proftpd.org/docs/modules/mod_auth.html#RootRevoke
