### ISSUE TITLE
Impossible to connect to data port using implicit FTPS

### ISSUE THREAD

**Issue by pol2095** [proftpd/proftpd#1779]
Hello,

I can connect to port 21 using implicit FTPS, the Let's Encrypt certificate is trusted, `EPSV` command return an aleatory data port between 49152 and 65535.
I use a new TLS connection to connect to the port `51321` for example but the certificate is invalid now.
my `tls.conf` :
```
TLSEngine on
TLSRequired on
TLSRSACertificateFile /etc/webmin/letsencrypt-cert.pem
TLSRSACertificateKeyFile /etc/webmin/letsencrypt-key.pem
TLSCACertificateFile /etc/webmin/letsencrypt-ca.pem
TLSOptions UseImplicitSSL NoSessionReuseRequired
```

Thanks

### ProFTPD Version and Configuration

ProFTPd version 1.38 on Debian 12

**Comment by Castaglia** [comment]
See also https://github.com/proftpd/proftpd/issues/759#issuecomment-1939557878

**Comment by Castaglia** [comment]
ProFTPD requires that the client send a data transfer command (such as `LIST`, `RETR`, `STOR`, _etc_) before it will open a passive data socket.  Why?  If it opened a socket on commands such as `PASV` or `EPSV`, it means a malicious (or badly-written) client could spew such commands and open many sockets, exhausting the number of possible sockets (which are _also_ used by other processes on a host), without ever actually _performing_ a data transfer.

Thus ProFTPD requires an actual FTP data transfer command before it will open a data transfer socket, to avoid such denial-of-service situations.
