### ISSUE TITLE
 proftpd in docker - not optimal configurable

### ISSUE THREAD

**Issue by the-hotmann** [proftpd/proftpd#1783]
I containerized a proftpd instance and observed that certain aspects, while explicitly outlined in the documentation, are suboptimal when running ProFTPD in a Docker environment.

1. When deploying proftpd within a Docker container, it's advisable to utilize the `-n`/`--nodaemon` mode, especially if initiated from a script or the ENTRYPOINT.
2. Despite the documentation stating that proftpd in --nodaemon mode doesn't utilize SystemLog, it still creates the file, resulting in an accumulation of login/logout messages in the Docker log over time - a situation I find undesirable.

To address this, I prefer configuring proftpd to behave in the following manner:

Standard output (stdout) directed to `/var/log/proftpd/proftpd.log`.
Standard error (stderr) directed to `/var/log/proftpd/proftpd_error.log` and the `docker log`.

This setup ensures that detailed login information is stored in separate log files, a more preferable approach than flooding the Docker log with excessive data.

Is there a way to achive this, so that even in `nodaemon` mode logs can be specified for each: `stdout` and `stderr`?

Thanks in advance!

**Comment by rafasc** [comment]
I believe `proftpd` is not writing to SystemLog in the case you described with on 2). 

If you used `--nodaemon`, it should be writing to stdout/stderr. That output may or may not end up in your system log depending how you have your docker logging driver configured.

If you want to avoid that you may try using `--quiet` to tell `proftpd` to not write to stderr. #1287 

Docker logs will still have some logs (stdout) but the majority of it should be redirected to the file configured by the `ServerLog` directive.

**Comment by the-hotmann** [comment]
@rafasc thanks I will try so and report back if `--quiet` is redirecting the logs to the file defined in `ServerLog`.

**Comment by maltris** [comment]
@the-hotmann I noticed the same and thought the same before but never really tended to that problem. Did the proposed solution work?

**Comment by the-hotmann** [comment]
@maltris yes, it did work.

Add the option `ServerLog` and start with `-n --quiet` then it will again log to the proftpd, BUT it now will not log to the stdout of the docker. So the docker now is silent.
