### ISSUE TITLE
DenyUser Limit does not work for ftp, but works for sftp

### ISSUE THREAD

**Issue by fgleixner** [proftpd/proftpd#1793]
### What I Did

We want to deny one user to use ftp, but allow this user sftp. All other users may use both, ftp and sftp.
Tried this configuration:
```
<VirtualHost ftp.mydomain.de>
    ServerName "ftp.mydomain.de"
    Port 21
    <Limit LOGIN>
      DenyUser regex  ^testftp$
    </Limit>
 </VirtualHost>
<VirtualHost ftp.mydomain.de>
    ServerName "sftp.mydomain.de"
    ServerIdent off
    <IfModule mod_sftp.c>
        SFTPEngine on
        Port 2222
        SFTPHostKey /etc/ssh/ssh_host_rsa_key
        SFTPAuthMethods keyboard-interactive publickey
        SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u
        SFTPCompression delayed
    </IfModule>
    <IfModule mod_sftp_pam.c>
        SFTPPAMEngine on
        SFTPPAMServiceName proftpd
    </IfModule>
</VirtualHost>
```

### What I Expected/Wanted

We expected, that the user testftp cannot login using ftp on port 21, but can login using sftp on port 2222. But the user can login using both ways.
We also tried to put the <Limit> block in the sftp VirtualHost, and if we do this, the user testftp can login using ftp on Port 21 but cannot login using sftp on port 2222

### ProFTPD Version and Configuration

ProFTP Version:
  Version: 1.3.7a (maint)

If additional configuration is needed, i can provide it.

**Comment by Castaglia** [comment]
Could you provide the [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html), debug level 10, for both the FTP and SFTP logins for the user in question?  I'm hoping that that logging can help provide more details about what is happening.  Thanks!

**Comment by fgleixner** [comment]
[proftpd_debug.log](https://github.com/proftpd/proftpd/files/15063114/proftpd_debug.log)

Here are the logs with the config above. If you need more from the config, i can provide it.

**Comment by Castaglia** [comment]
> Here are the logs with the config above. If you need more from the config, i can provide it.

Hmm.  In the provided logs, it looks like you are using an SFTP client _in both cases_ to log into your two separate `<VirtualHost>` sections.  That's not what I expected.  I thought you would use an FTP client for the FTP virtual host, and an SFTP client for the SFTP virtual host.  FTP and SFTP are very, very different protocols.

**Comment by fgleixner** [comment]
Tried again. Now i have two new findings:
1. I dont see logs from the ftp virtual host. I dont know, why logins and other things are not logged.
2. If i try ftp localhost, then the Limit restrictions do not apply. They do apply when i ftp to the outbound IP of the server. But the proftpd process listens on 0.0.0.0:21 - no other process or xinetd picks up connections to 127.0.0.1:21

**Comment by fgleixner** [comment]
Found out, that this is a configuration issue, where ftp clients sometimes do not land in one of the VirtualHost contexts, but in the "server config" section.
I added a
`Port 0`
to the outer server config, and now it works as expected.

**Comment by Castaglia** [comment]
Interesting.  But I'm glad you were able to make it work!
