### ISSUE TITLE
Implement limits@openssh.com SFTP extension

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1798]
The scope of this ticket is to implement OpenSSH's custom [limits@openssh.com](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL#L598) SFTP extension in the `mod_sftp` module.

Why?  This custom extension is used by OpenSSH to query the SFTP server for its max supported lengths for SFTP `READ` and `WRITE` requests.  If the SFTP server supports longer lengths than those used by the OpenSSH SFTP client, the longer lengths are often used.  This can have beneficial impacts on SFTP transfers, as larger packets lead to fewer round trips, and can reduce observed transfer latencies.

**Comment by a270443177** [comment]
@Castaglia 

sftp  -vvvv

display this:
debug2: Unrecognised server extension "limits@openssh.com"
debug2: Unrecognised server extension "users-groups-by-id@openssh.com"

**Comment by Castaglia** [comment]
@a270443177  OpenSSH support for the `limits@openssh.com` extension first appeared in OpenSSH 8.6/8.6p1; see https://www.openssh.com/releasenotes.html

**Comment by a270443177** [comment]
> @Castaglia
> 
> sftp -vvvv
> 
> display this: debug2: Unrecognised server extension "[limits@openssh.com](mailto:limits@openssh.com)" debug2: Unrecognised server extension "[users-groups-by-id@openssh.com](mailto:users-groups-by-id@openssh.com)"



> OpenSSH 8.6



i am use  openssh8

> @a270443177 OpenSSH support for the `limits@openssh.com` extension first appeared in OpenSSH 8.6/8.6p1; see https://www.openssh.com/releasenotes.html

i use  openssh8.6    
cmd:   sftp -vvvv -o Compression=no -o Ciphers=aes128-gcm@openssh.com

log===>   when  rcvd adjust 33201298，but send old buffer size 261120 
debug3: SSH2_FXP_STATUS 0
debug3: In write loop, ack for 67 261120 bytes at 16189440
debug3: Sent message SSH2_FXP_WRITE I:132 O:33162240 S:261120
debug3: SSH2_FXP_STATUS 0
debug3: In write loop, ack for 68 261120 bytes at 16450560
debug3: Sent message SSH2_FXP_WRITE I:133 O:33423360 S:261120
debug3: SSH2_FXP_STATUS 0
debug3: In write loop, ack for 69 261120 bytes at 16711680
**debug2: channel 0: rcvd adjust 33201298**
debug3: Sent message SSH2_FXP_WRITE I:134 O:33684480 S:261120
debug3: SSH2_FXP_STATUS 0
debug3: In write loop, ack for 70 261120 bytes at 16972800
debug3: Sent message SSH2_FXP_WRITE I:135 O:33945600 S:261120
debug3: SSH2_FXP_STATUS 0
debug3: In write loop, ack for 71 261120 bytes at 17233920
debug3: Sent message SSH2_FXP_WRITE I:136 O:34206720 S:261120
debug3: SSH2_FXP_STATUS 0
