### ISSUE TITLE
Add parameter to mod_sftp to specify allowed public key auth algorithms

### ISSUE THREAD

**Issue by offsides** [proftpd/proftpd#1806]
Similar to the SFTPHostKeys directive, have a SFTPPublicKeys (or something similar) directive to allow changing the default list of supported public key  algorithms used for authentication similar to OpenSSH's PubkeyAcceptedAlgorithms.  Right now as compiled mod_sftp still supports the deprecated 'ssh-rsa' algorithm, as well as supporting 'ssh-dss' (DSA keys, not really secure anymore) with no way to turn them off.  I'd like to be able to do that at some point so that there's no chance that an insecure algorithm will be used (and it will make it easy to adjust as crypto requirements change).  I'll try to put together a PR for this at some point if you don't get to it first, but I have to finish my RHEL 7 migrations first before the end of June.

**Comment by Castaglia** [comment]
Is this a request due to some sort of scanner/compliance?

**Comment by offsides** [comment]
Not yet, but it wouldn't surprise me if it happened down the line.  It came up because older versions of PuTTY/WinSCP don't support the newer rsa-sha2-XXX key algorithms, and a couple people who need access to our SFTP servers were able to connect to mod_sftp but not to openssh because the default PublicKeyAlgorithms no longer supports ssh-rsa.  Plus, I know we were dinged in the last year or two for supporting ssh-rsa as a HostKeyAlgorithm, so I figure it's better to get ahead of the curve, especially when I'd like to disable support for DSA keys altogether (we don't permit them anyway, but extra protection is never a bad thing).  Not to mention if there's ever a notable vulnerability down the line, it's always easier to adjust a config line than having to patch and recompile...

**Comment by Castaglia** [comment]
Hmm.  I'm thinking that such configurability should probably be implemented as part of `SFTPClientMatch`, so that it can be tuned per client; applying such restrictions to all clients can use `.*` as the matching criterion.

**Comment by offsides** [comment]
That sounds reasonable to me, though I don't really see it being used other than for all clients.  But being able to turn it off without recompiling is my main goal, so whichever way you want to implement that ability works for me.

**Comment by Castaglia** [comment]
https://github.com/proftpd/proftpd/pull/1809 implements an `SFTPAuthPublicKeys` directive, which should do as you need.  It works as expected in my local testing; care to try it out?

**Comment by severach** [comment]
I use `-DOPENSSL_NO_DSA` and `SFTPHostKey NoDSA` so DSA was never a problem for me.

How do I check this? I tried `sftp -oPubkeyAcceptedKeyTypes=ssh-rsa` and I can get into both proftpd and OpenSSH 9.7. I can't find anything in `sftp -vv` that would reveal what Pubkeys the server offers that SSH scanners should be showing.

**Comment by Castaglia** [comment]
The types/algorithms of public keys accepted for user authentication are not something that are announced/negotiated as part of the SSH key exchange; the only way to check is to try, with a public key from an algorithm that is not part of the `SFTPAuthPublicKeys` list, to see the failure/error.

**Comment by Castaglia** [comment]
This has been merged to master.  Thanks!
