### ISSUE TITLE
SFTPHostKeys not working as expected

### ISSUE THREAD

**Issue by KratiBansal** [proftpd/proftpd#1814]
I am using proftpd-1.3.8b and even when the ssh-rsa and ssh-dss are removed from the config file, they continue to work. Any idea why?

`  SFTPHostKeys  \
    ecdsa-sha2-nistp256 \
    ecdsa-sha2-nistp384 \
    ecdsa-sha2-nistp521 \
    rsa-sha2-512 \
    rsa-sha2-256 `

**Comment by Castaglia** [comment]
Can you elaborate on what you mean by "they continue to work"?  Any logs to demonstrate the behavior you're seeing, along with the config you're using?

**Comment by KratiBansal** [comment]
What I mean is the key based auth wherein the key pair which is generated using ssh-rsa continues to work

**Comment by Castaglia** [comment]
> What I mean is the key based auth wherein the key pair which is generated using ssh-rsa continues to work

Right, but...how is that keypair being used?  Is it for user authentication, or as a hostkey?  The requested configuration and logs would help provide data for this question.

**Comment by KratiBansal** [comment]
User authentication

**Comment by Castaglia** [comment]
> User authentication

Right.  The `SFTPHostKeys` directive is about _host keys_, not user authentication.

If you wish to configure the accepted key algorithms for user authentication, see Issue #1806

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.  Thanks!
