### ISSUE TITLE
Is ProFTPD affected by regreSSHion?

### ISSUE THREAD

**Issue by iSOcH** [proftpd/proftpd#1815]
See title.

The vulnerabilty affects very old and more recent openssh versions ("This regression was introduced in October 2020 (OpenSSH 8.5p1)."). See https://blog.qualys.com/vulnerabilities-threat-research/2024/07/01/regresshion-remote-unauthenticated-code-execution-vulnerability-in-openssh-server for a description.

**Comment by Castaglia** [comment]
I do not think that ProFTPD (or mod_sftp) are impacted by "regreSSHion".  Why not?  ProFTPD's signal handling is done synchronously, including the `SIGALRM` path noted in the OpenSSH issue.  This means that all signal handling is done during "normal" code execution; all signal handlers do in ProFTPD is set a bit flag, and return.  ProFTPD also does not use the mentioned `syslog(3)` function, having its own implementation (which uses reentrant-safe functions where available) for historical reasons.

I am subscribed to the OpenSSH devel mailing list, and am watching the discussion there as well, with an eye toward any behaviors that might also appear in ProFTPD.  Thanks!
