### ISSUE TITLE
Is there a way to set log level for mod_sql?

### ISSUE THREAD

**Issue by KratiBansal** [proftpd/proftpd#1822]
We have large volume of logs getting populated by mod_sql and we wanted to check if there is a way to suppress the logs or adding log levels?

**Comment by Castaglia** [comment]
What current configuration directives, for logging are you using?  For example, if you don't actually need any of the SQL logging, you can remove the `SQLLogFile` directive.

**Comment by KratiBansal** [comment]
`  <IfModule mod_sql.c>
    SQLLogFile /var/log/proftpd/mod_sql.log
    # Define a SELECT statement to retrieve users' authorized SSH keys
    #Allow deploy key to authenticate for users
    SQLNamedQuery get-user-authorized-keys SELECT "`key` FROM sftpuserkeys WHERE name='%U'"

    # Define a SELECT statement to retrieve hosts' authorized SSH keys
    SQLNamedQuery get-host-authorized-keys SELECT "`key` FROM sftphostkeys WHERE host='%{0}'"

    SQLBackend              <%= @sql_backend %>
    # The passwords in MySQL are encrypted using CRYPT
    SQLAuthTypes            Crypt OpenSSL Backend
    SQLAuthenticate         users groups


    # used to connect to the database
    # databasename@host database_user user_password
    SQLConnectInfo  <%= @connect_info %>

    # Here we tell ProFTPd the names of the database columns in the "usertable"
    # we want it to interact with. Match the names with those in the db
    SQLUserInfo     users userid passwd uid gid homedir shell

    # Here we tell ProFTPd the names of the database columns in the "grouptable"
    # we want it to interact with. Again the names match with those in the db
    SQLGroupInfo    sftpgroups groupname gid members

    # set min UID and GID - otherwise these are 999 each
    SQLMinID        500

    # create a user's home directory on demand if it doesn't exist
    CreateHome on

    # Update count every time user logs in
    SQLLog PASS updatecount
    SQLNamedQuery updatecount UPDATE "login_count=login_count+1, accessed=now(), ssh_key_change_algo='%{note:SFTP_KEX_ALGO}', ssh_host_key_algo='%{note:SFTP_HOST_KEY_ALGO}', ssh_client_cipher_algo='%{note:SFTP_CLIENT_CIPHER_ALGO}', ssh_client_digest_algo='%{note:SFTP_CLIENT_MAC_ALGO}' WHERE userid='%u'" users

    SQLUserWhereClause "DATEDIFF(now(), accessed) < 90"
  </IfModule>`

**Comment by KratiBansal** [comment]
@Castaglia We do want some of the logging and not all of it. The logs are pretty chatty in nature and would there be a way to  set a log level to those?

**Comment by Castaglia** [comment]
> @Castaglia We do want some of the logging and not all of it.

What are the parts of the mod_sql logging that you find useful?  Which parts do you find least useful/interesting?

**Comment by KratiBansal** [comment]
All the sql queries and the cmd_close/open logs. However, whenever it is unable to connect to the sql backend those kind of logs are required. Only the emergency ones.

**Comment by Castaglia** [comment]
Hmm.  To directly answer the question: no, there is currently no way to set/configure any level of SQL logging.  Those log messages have been there for quite a while, so any changes would need to consider backward compatibility, i.e. other sites may have their own log processing that rely on the existing messages/formats.

Usually I recommend that sites do any necessary post-processing of ProFTPD logs separately, rather than trying to add such log processing into ProFTPD or its modules directly.
