### ISSUE TITLE
Old proftpd version in Ubuntu official packages

### ISSUE THREAD

**Issue by ShaiMagal** [proftpd/proftpd#1823]
### What I Did

I am using Ubuntu 22 APT official packages and there is latest version proftpd **1.3.7c**, it's very old (year 2021).
Used sources:
_http://cz.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages_

I didn't found any other source with newer version of proftpd :/

### What I Expected/Wanted

I am expecting latest stable version of proftpd in Ubuntu APT packages.
Is possible to add latest version proftpd to official Ubuntu packages?

I know it's about how Ubuntu LTS works, but in this case not all software have this "problem". For example packages apache2, rspamd, mariadb and more are updating to latest version possible.

But proftpd no. Why is this difference between proftpd and other major usage packages?

Only one reason can be, other packages are updated, because there is any CVE. And in proftopd isn't any new CVE.
For this reason, in apt sources is older version.
Is it correct?

I only want to be sure if I understand this behaviour correctly.

**I think, any PPA for proftpd can be useful :)**

**Comment by Castaglia** [comment]
Unfortunately, we (the ProFTPD Project) don't maintain any ProFTPD packages for any distribution.  You'd have to talk to the ProFTPD package maintainers for Debian/Ubuntu to see what goes into determining the updates of their packages.

**Comment by Castaglia** [comment]
If there's nothing more to add to this issue, I'd like to close it.  Thanks!
