### ISSUE TITLE
PROFTPD / SWAPPED FILES / downloading a file contains the contents of another file, but the file name is correct

### ISSUE THREAD

**Issue by idir-bouiflou** [proftpd/proftpd#1826]
I am facing a problem on my **PROFTPD** server on which there is a lot of traffic.
`installed on CENTOS8 server with docker.`
`ProFTPD Version 1.3.7a`

Take for example two clients:
Client-1 requests the download of the X.jpg image via its application. Client-2 requests the download of the Y.jpg image from its application at the same time as client-1.
In rare cases, client-2 downloads the image with the correct name (Y.jpg), but when we open the image, it is the X.jpg that is displayed.

here in my capture for example, it's a customer who only sells books, but he ends up with an image of shoes.
![image](https://github.com/user-attachments/assets/1fc86b54-dfc1-497f-939b-ad76bd161034)

when I look at the FTP server, the image is correct, it's not a shoe.

in my proftpd logs, I see that the shoe and the photo of the book are downloaded at the same time.

So, if you have an idea or a lead I'm interested, because this bug is causing me a lot of problems!

Thank you in advance for your help.

[stack](https://stackoverflow.com/questions/78927161/proftpd-swapped-files-downloading-a-file-contains-the-contents-of-another-fi)

**Comment by Castaglia** [comment]
I suspect that this is caused by Issue #1171. The fix for that issued appeared in 1.3.7b; you are running 1.3.7a.  Would it be possible to update your ProFTPD version?

**Comment by idir-bouiflou** [comment]
Thank you for your response. This is reassuring.  
I'm going to schedule a **PROFTPD** update for the weekend of _September 7th_.

**Comment by Castaglia** [comment]
Is there anything more to add to this ticket?  Were you able to update the ProFTPD version, to address this behavior?

**Comment by idir-bouiflou** [comment]
Hello, I'm sorry we couldn't update the service. Lack of time. You can close it and if the problem persists after the update, I will be sure to get back to you. Thank you in advance for your time. Sincerely.

**Comment by bastien-roucaries** [comment]
This bug deserve a CVE

**Comment by bastien-roucaries** [comment]
debian cross ref https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1090813
