### ISSUE TITLE
Algorithm negotiation errors not getting captured in proftpd logs

### ISSUE THREAD

**Issue by KratiBansal** [proftpd/proftpd#1828]
We are using proftpd-1.3.8b and have decided to deprecate support for certain weak ciphers. After removing support we can see that the client receives a "Algorithm negotiation fail" issue, however, nothing gets logged in the proftpd logs. Is there a way to capture such issues?

**Comment by Castaglia** [comment]
Can you provide a detailed example of such client-side logging of "Algorithm negotation failed"?  Are you talking about SSH/SFTP, TLS, or both?  What's the ProFTPD config that you're using?

**Comment by KratiBansal** [comment]
![image (1)](https://github.com/user-attachments/assets/b27d7474-2c05-4fed-9fe6-35a1489de625)
![image](https://github.com/user-attachments/assets/9d409d73-3dbc-4211-b8fe-67caa2a8826a)

It is SFTP

**Comment by Castaglia** [comment]
> ![image (1)](https://private-user-images.githubusercontent.com/54878059/366942660-b27d7474-2c05-4fed-9fe6-35a1489de625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTQ0MDcsIm5iZiI6MTcyNjE1NDEwNywicGF0aCI6Ii81NDg3ODA1OS8zNjY5NDI2NjAtYjI3ZDc0NzQtMmMwNS00ZmVkLTlmZTYtMzVhMTQ4OWRlNjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTFkOThkYmFhODZlMTEyZjljNmFkYWFmYzc4OTAzNmI5ODMyMjcyZTc5MDNkZjY2MjY1ZWYyMzdhZTViYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bUhT5nRvdAOAqkh9Z9AR2Hw8F0MJBQ7iJKYf3BazFSA) ![image](https://private-user-images.githubusercontent.com/54878059/366942672-9d409d73-3dbc-4211-b8fe-67caa2a8826a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTQ0MDcsIm5iZiI6MTcyNjE1NDEwNywicGF0aCI6Ii81NDg3ODA1OS8zNjY5NDI2NzItOWQ0MDlkNzMtM2RiYy00MjExLWI4ZmUtNjdjYWEyYTg4MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YjRiYzBlMjM1YjNhMjRhN2QxN2FlMTEwNWU1YmM0ZmNmMGM5N2VmMmZmODU0N2E3OTY0M2ViM2IyYjRkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7AyxYFhrz1wAA7X8VODbV9xYM8pWooAhUBVrKfpy0xg)
> 
> It is SFTP

Do you happen to have the corresponding ProFTPD logs for these failed sessions?  `SFTPLog`, [ProFTPD debug logging](http://www.proftpd.org/docs/howto/Debugging.html), or similar?

**Comment by KratiBansal** [comment]
That is my concern. The failure is an expected behaviour however proftpd logs are not logging anything related to this

**Comment by Castaglia** [comment]
> That is my concern. The failure is an expected behaviour however proftpd logs are not logging anything related to this

I'm interested in seeing what _is_ logged for these sessions, please.

**Comment by KratiBansal** [comment]
@Castaglia There is nothing getting logged for this session.

**Comment by Castaglia** [comment]
> @Castaglia There is nothing getting logged for this session.

Hm.  There should be _something_ logged; I know that ProFTPD logs when it receives a TCP connection.

If no logs and no configuration can be provided, then there's not much I can do to address the question/issue.
