### ISSUE TITLE
Test suite fails partially in encoding

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1831]
The test suite fails partially in the encoding part:

`Running suite encode
api/encode.c:83:F:base:encode_encode_str_test:0: Failed to handle null output string len
api/encode.c:129:F:base:encode_decode_str_test:0: Failed to handle null output string len
api/encode.c:191:F:base:encode_charset_test:0: Failed to set charset 'us-ascii', encoding 'utf-8': Function not implemented
api/encode.c:225:F:base:encode_encoding_test:0: Failed to enable encoding 'iso-8859-1': Function not implemented
api/encode.c:258:P:base:encode_policy_test:0: Passed
api/encode.c:286:F:base:encode_supports_telnet_iac_test:0: Failed to set charset 'us-ascii', encoding 'cp1251': Function not implemented
`

The phenomenon exists in Debian [since July](https://ci.debian.net/packages/p/proftpd-dfsg/unstable/amd64/) unfortunately I can't say, what changes could have caused the breakage. There were no changes to the Debian proftpd package for a few month. The full log is [attached](https://github.com/user-attachments/files/17085805/api-tests.log). If you need more input, let me know.

**Comment by Castaglia** [comment]
What's the Debian version in use for running these tests?  I'd like to reproduce this issue locally using a Docker image that matches that Debian version.

**Comment by hpreusse** [comment]
This is for Debian unstable. I'm able to reproduce on amd64 and arm64,

**Comment by Castaglia** [comment]
I just tried to reproduce this locally, using the `debian:unstable` Docker image -- no luck.  All of the unit tests are passing for me in my local Docker setup.  So I'm wondering what might be different between my setup, and the environment in which your tests are running.

Would it be possible to see which environment variables are set in that environment, particularly any `LC_` environment variables?

**Comment by hpreusse** [comment]
Here is the [link](https://ci.debian.net/packages/p/proftpd-dfsg/unstable/amd64/51474572/) to one of the test runs. Is this eventually helpful? The ENV variabley are not visible, maybe other differences to your test run.

**Comment by Castaglia** [comment]
Note that as part of addressing this ticket, I'll also adjust these encoding unit tests to also use `#ifdef HAVE_ICONV_H`, and to adjust their assertions accordingly.  This would make these tests pass in your setup -- although it may not be what you expect/want.  That is, the failure of these tests did indicate the unexpected absence of this `iconv.h` header; that absence might also affect the `proftpd` executable being built/tested.

**Comment by hpreusse** [comment]
For testing I used now a Virtualbox VM "Linux sid 6.10.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.11-1 (2024-09-22) x86_64 GNU/Linux". The iconv.h come from the libc6-dev and should be on pretty every developer box:

```
hille@sid:~/proftpd-dfsg-1.3.8.b+dfsg$ dlocate iconv.h
libc6-dev:amd64: /usr/include/iconv.h
```

Nevertheless the test fails, same error messages. The output of "export" is attached.
[export.txt](https://github.com/user-attachments/files/17121784/export.txt)

**Comment by Castaglia** [comment]
Hmm.  Are you copying a `config.h` file (generated by ProFTPD's `configure` script) from some other machine/build?  That `config.h` is what records the `configure` script discover of things, such as necessary headers, libraries, _etc_.  I'm not sure how else the code would behave as if `iconv.h` was there, when it fact that file exists -- the code uses the recorded macros in `config.h` to know what to do.  Hmm.

**Comment by Castaglia** [comment]
Would it be possible to get the `config.log` file generated from one of these builds as well, please?  That file contains a log of the `configure` script test results; it's possible that there are clues/details in that log that could help explain this situation as well.

**Comment by hpreusse** [comment]
Attached is the [config.log](https://github.com/user-attachments/files/17170445/config.zip) of the latest configure run. I've run the test this time inside a Debian unstable chroot (I had to comment all these redis tests, as the server could not be started). The list of configure option might be overdone, but I just use the same as I use, when building the package. Hope it is useful.

**Comment by Castaglia** [comment]
There certainly are some interesting findings in the provided `config.log`; thanks!

For the `iconv.h` header detection, everything looks like it should be working as expected:
```
configure:19706: checking iconv.h usability
configure:19706: gcc -c -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration  -I/usr/include/mariadb/mysql -I/usr/include/mariadb -I/usr/include/postgresql conftest.c >&5
configure:19706: $? = 0
configure:19706: result: yes
configure:19706: checking iconv.h presence
configure:19706: gcc -E  -I/usr/include/mariadb/mysql -I/usr/include/mariadb -I/usr/include/postgresql conftest.c
configure:19706: $? = 0
configure:19706: result: yes
configure:19706: checking for iconv.h
configure:19706: result: yes
```

However, later, I do see an unexpected issue with detecting/testing the `iconv(3)` function:
```
configure:21400: checking for iconv
configure:21430: gcc -o conftest -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration  -I/usr/include/mariadb/mysql -I/usr/include/mariadb -I/usr/include/postgresql -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic conftest.c -lnsl -lresolv -lresolv -lcrypt -lhiredis -lmemcachedutil -lmemcached -lm -lrt -pthread -lsubunit >&5
conftest.c: In function 'main':
conftest.c:210:30: error: passing argument 2 of 'iconv' from incompatible pointer type [-Wincompatible-pointer-types]
  210 |     res = iconv((iconv_t)-1, &in, &in_len, &out, &out_len);
      |                              ^~~
      |                              |
      |                              const char **
In file included from conftest.c:200:
/usr/include/iconv.h:49:54: note: expected 'char ** restrict' but argument is of type 'const char **'
   49 | extern size_t iconv (iconv_t __cd, char **__restrict __inbuf,
      |                                    ~~~~~~~~~~~~~~~~~~^~~~~~~
conftest.c:207:12: warning: variable 'res' set but not used [-Wunused-but-set-variable]
  207 |     size_t res, in_len = 0, out_len = 0;
      |            ^~~
configure:21430: $? = 1
configure: failed program was:
...
configure:21440: result: no
```

So the `config.log` is telling me that it successfully detected `iconv.h` (which means that `HAVE_ICONV_H` _should_ be true), but it did not successfully detect `iconv(3)`, which is also needed for the `--enable-nls` function, which these failing tests cover.

Did the version of the compiler used change around that July timeframe?  Normally a typecast-ing type of compiler error is a non-fatal warning, not an error; I'm wondering if a rev of compiler version changed something there.

**Comment by Castaglia** [comment]
For what it's worth, in my local Docker setup using the `debian:unstable` image, my `config.log` shows:
```
configure:18688: checking for iconv
configure:18718: gcc -o conftest -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing  -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic conftest.c -lcrypt -ldl  >&5
conftest.c: In function 'main':
conftest.c:173:12: warning: variable 'res' set but not used [-Wunused-but-set-variable]
  173 |     size_t res, in_len = 0, out_len = 0;
      |            ^~~
configure:18718: $? = 0
configure:18720: result: yes
```
That's using gcc as the compiler:
```
# gcc -v
...
gcc version 14.2.0 (Debian 14.2.0-5) 
```

**Comment by hpreusse** [comment]
According my knowledge the "incompatible pointer type" was turned from a warning into an error in gcc-14 (see [bug1](https://bugs.debian.org/1075564) and [bug2](https://bugs.debian.org/1077073). Hence I'm wondering why the issue is not visible in your Docker VM. Anyway: good know that you found the issue in the config.log. Thanks!

**Comment by Castaglia** [comment]
@hpreusse Here's my Dockerfile, if it helps:
```
FROM debian:unstable

RUN apt-get update && \
  apt-get install -y \
    check \
    gcc \
    libsubunit-dev \
    make

RUN mkdir -p \
  /var/lib/proftpd \
  /var/log/proftpd

EXPOSE 2121
CMD ["bash"]
```
I then do a clean Git checkout locally, and mount that checkout directory into the container via Docker Compose:
```
---
version: '3'

services:
  proftpd:
    build:
      context: .
    # Use this to keep the container running
    command: tail -f /dev/null
    expose:
      - 2121
    privileged: true
    volumes:
      - ./proftpd:/src/proftpd
```
It would be good to know why my gcc version isn't showing that behavior.

**Comment by hpreusse** [comment]
Could you share your config.log file? What code tree do you use for testing. I'm still using proftp 1.3.8b (with 2 unrelated patches).

**Comment by hpreusse** [comment]
For now I can confirm that the isseu does not occur when using latest git checkout.

**Comment by Castaglia** [comment]
When you say you add https://github.com/proftpd/proftpd/pull/1754 (good find!) and see the error message gone from the generated `config.log`, do you also see the `iconv(3)` function detected in the generated `config.h` file as well?
```
# grep ICONV config.h
#define HAVE_ICONV 1
#define HAVE_ICONV_H 1
/* #undef HAVE_LIBICONV */
```
and have done a `make clean && make && make tests`, to ensure that everything is compiled with the updated `config.h`?

**Comment by hpreusse** [comment]
"make clean": that was basically the issue. After applying the patch and doing a complete restart with clean build tree the test suite runs again. Consider to apply #1754 to the 1.3.8 branch. Many thanks for help!

**Comment by Castaglia** [comment]
> "make clean": that was basically the issue. After applying the patch and doing a complete restart with clean build tree the test suite runs again. Consider to apply #1754 to the 1.3.8 branch. Many thanks for help!

Done; see https://github.com/proftpd/proftpd/commit/758f0fe36b4c1524f72d4a33d58682eb4b804d3f
