### ISSUE TITLE
kill -HUP not working as expected

### ISSUE THREAD

**Issue by the-hotmann** [proftpd/proftpd#1832]
### What I Did

I tried logrotate on proFTPd and in some scenarion it did not work as I expected.

### What I Expected/Wanted

I expected
```
kill -HUP `cat /run/proftpd/proftpd.pid`
```
to not just let go from the current file-open, but also write ALL new Log-Entries to the now empty new file.

### ProFTPD Version and Configuration

Please help us reproduce the problem/issue you are encountering.  To do this,
we need to know which version of ProFTPD you are using, how it was built,
_etc_.  The following command is an easy way to get all of this information:
```bash
# proftpd -V
Compile-time Settings:
  Version: 1.3.8b (maint)
  Platform: LINUX [Linux 6.10.11-amd64 x86_64]
  OS/Release:
    NAME="Alpine Linux"
    ID=alpine
    VERSION_ID=3.20.3
    PRETTY_NAME="Alpine Linux v3.20"
  Built: Wed May 15 2024 06:39:29 UTC
  Built With:
    configure  'LIBS=-lodbc' '--build=x86_64-alpine-linux-musl' '--host=x86_64-alpine-linux-musl' '--prefix=/usr' '--sysconfdir=/etc/proftpd' '--localstatedir=/run/proftpd' '--libexecdir=/usr/lib/proftpd' '--disable-static' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--enable-ipv6' '--enable-pcre2' '--disable-strip' '--disable-wtmp' '--disable-auth-pam' '--enable-openssl' '--enable-nls' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_geoip:mod_exec:mod_sftp:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession:mod_auth_otp:mod_tls_redis:mod_wrap2_redis:mod_redis:mod_memcache:mod_tls_memcache:mod_readme:mod_snmp:mod_tls_shmcache:mod_lang' 'build_alias=x86_64-alpine-linux-musl' 'host_alias=x86_64-alpine-linux-musl' 'CC=gcc' 'CFLAGS=-Os -fstack-clash-protection -Wformat -Werror=format-security -fno-plt' 'LDFLAGS=-Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs' 'CXX=g++' 'CXXFLAGS=-Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt'

  CFLAGS: -g2 -Os -fstack-clash-protection -Wformat -Werror=format-security -fno-plt -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration
  LDFLAGS: -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs -rdynamic  -L/usr/lib/ -L/usr/lib
  LIBS: -lintl  -lpcre2-posix -lpcre2-8 -lssl -lcrypto -lsodium -lresolv -lresolv -lcrypt -lodbc -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (OpenSSL 3.3.0 9 Apr 2024)
    - PCRE support
    + PCRE2 support
    + POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

Important is JUST this, as the rest does not have anything to do with the config, not any impact:

```
ExtendedLog /var/log/proftpd/sftp/extended_sftp.log
```

Here my logrotate:

```
/var/log/proftpd/*.log
/var/log/proftpd/*/*.log
{
        daily
        compress
        create
        rotate 10
        maxage 15
        missingok
        size 10M
        notifempty
        nodateext
        sharedscripts
        postrotate
                kill -HUP `cat /run/proftpd/proftpd.pid`
        endscript
}
```

This will send a `kill -HUP` signal to the proftpd, which make the server log:

```
2024-10-01 15:39:36,646 alpine_proftpd proftpd[1] alpine_proftpd: received SIGHUP -- master server reparsing configuration file
```

and to drop all file-handles. BUT:

If I upload a 10G file and force the logrotate in the middle, the application again drops the filehandle, but: the new file stays empty, and the rest of the 10G file will NOT be logged!

How to reproduce:

1. activate extended logging
2. activate logrotation (set to every minute, for debugging)
3. upload a big file
4. at the beginning, force logrotation with `SIGHUP` (`HUP`)
5. check the extended logfile now

I have worked around this issue by using this logrotation config (with `copytruncate`):

```
/var/log/proftpd/*.log
/var/log/proftpd/*/*.log
{
        daily
        compress
        copytruncate
        create
        rotate 10
        maxage 15
        missingok
        size 10M
        notifempty
        nodateext
}
```

but according to the [docs](https://linux.die.net/man/8/logrotate) this is JUST recommended if an application can not handle the `SIGHUP` signal - but proFTPd can.
Also, when using `copytruncate` some data are getting lost (the ones written, as long as the copy takes).
But now when I use `kill -HUP` on proFTPd, the current transfers do NOT write to the new file, but actually are never logs from now ongoing.
Just new transfers are logged - and they work perfectly fine.

I consider this a bug, but ofc I am open for discussion :)

**Comment by Castaglia** [comment]
The `SIGHUP` signal, from the PidFile, goes to the "master" daemon process, the process that is listening for new connections.  Whenever a new connection is received, the daemon process forks off a separate new session process which handles that connection -- including logging for that session.

Part of handling of a session often involves handling the `DefaultRoot` directive, which uses the `chroot(2)` function to restrict the session process.  This means, in practice, that once the process is chrooted, it _cannot_ re-open the configured log files anymore, as those log paths are not located within the restricted portion of the filesystem.

This is documented here:
* http://www.proftpd.org/docs/howto/Logging.html#LogRotation

Perhaps there is something that can be added to the documentation, to make this clearer or more explicit?

**Comment by the-hotmann** [comment]
@Castaglia thanks, I actually read this particular section, but I thought that `SIGHUP` signal is handled in a way, no Logs are getting lost - but still all current transfers are not logged anymore.

I now understand the problem, thanks!
Is there a solution to this, to preserve all logs? Is `delaycompress` (from logrotate) here the solution to this problem?


Thanks in advance!

**Comment by Castaglia** [comment]
> I now understand the problem, thanks! Is there a solution to this, to preserve all logs? Is `delaycompress` (from logrotate) here the solution to this problem?

Using logrotate, I believe that `delaycompress` is the best way to deal with this situation, yes.  I'll work on adding this, as an example logrotate configuration, to the docs.

**Comment by the-hotmann** [comment]
Thanks!

Is there any chance of getting internal logrotation for proftpd? A lot of java-tools have their own logrotation, I dont know any C-based programm offering it, but maybe it is not too much work?
At least it would not require additional:
- cronjobs
- logrotate-tool


But maybe this also is out of scope for this tool itself.

**Comment by Castaglia** [comment]
Any internal log rotation built into ProFTPD would run into the same `chroot(2)` limitations, and would end up looking much like the existing `logrotate` tool, so there is not much benefit in trying to use that approach.

Java uses threads, not processes, and rarely (if ever) uses `chroot(2)`, so it does not encounter the constraints for log management.
