### ISSUE TITLE
SSH ECDSA host key algorithms not be used as expected despite configuring appropriate key

### ISSUE THREAD

**Issue by KratiBansal** [proftpd/proftpd#1839]
logs show something like this -
`no shared server hostkey algorithm found (client sent 'ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss', server sent 'rsa-sha2-512,rsa-sha2-256'`

Supported ciphers -

```
  SFTPCiphers  \
    aes128-ctr \
    aes192-ctr \
    aes256-ctr 
  SFTPDigests \
    hmac-sha2-256 \
    hmac-sha2-512 \
    hmac-ripemd160 \
    umac-64@openssh.com 
  SFTPHostKeys  \
    ecdsa-sha2-nistp256 \
    ecdsa-sha2-nistp384 \
    ecdsa-sha2-nistp521 \
    rsa-sha2-512 \
    rsa-sha2-256 
  SFTPKeyExchanges \
    diffie-hellman-group-exchange-sha256 \
    ecdh-sha2-nistp256 \
    ecdh-sha2-nistp384 \
    ecdh-sha2-nistp521 
```

Openssl details -

```
openssl version -a
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  dynamic 
```

```
openssl ecparam -list_curves
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
```

**Comment by Castaglia** [comment]
That's a very old version of OpenSSL.  I suspect that in the `./configure` output (and/or `config.log` and `config.h`, if you still have those files) will show mention of testing for OpenSSL ECC support, and perhaps those tests failed against that old OpenSSL version.  But I'd need to see the full `./configure` output, `config.log`, and/or `config.h` to verify.

**Comment by KratiBansal** [comment]
Does this version of openssl not support kex for ecdsa?

**Comment by Castaglia** [comment]
> Does this version of openssl not support kex for ecdsa?

OpenSSL does not implement SSH key exchanges; it implements cipher algorithms, some of which are used in SSH.

As mentioned, the `./configure` output, `config.h`, and `config.log` files would show the results of testing that OpenSSL version for the necessary algorithm support.

**Comment by KratiBansal** [comment]
Where will I get these files

**Comment by Castaglia** [comment]
> Where will I get these files

Depends.  How did you install ProFTPD?  What's the Unix distribution/version?

**Comment by KratiBansal** [comment]
[krati.bansal@prdsfs851fe1 ~]$ proftpd -V
Compile-time Settings:
  Version: 1.3.8b (maint)
  Platform: LINUX [Linux 4.14.336-257.568.amzn2.x86_64 x86_64]
  OS/Release:
    NAME="Amazon Linux"
    VERSION="2"
    ID="amzn"
    ID_LIKE="centos rhel fedora"
    VERSION_ID="2"
    PRETTY_NAME="Amazon Linux 2"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
    SUPPORT_END="2025-06-30"
  Built: Tue May 14 2024 08:43:53 UTC
  Built With:
    configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--disable-pcre' '--enable-sodium' '--disable-redis' '--enable-shadow' '--enable-tests=nonetwork' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_clamav:mod_statsd:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_unique_id:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic'

  CFLAGS: -g2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration
  LDFLAGS: -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic -L/usr/lib64/mysql -L/usr/lib64/mysql -L/usr/lib64
  LIBS: -lacl  -lssl -lcrypto -lsodium -lcap  -lssl -lcrypto  -lpam -lattr -lidn2 -lcrypt -ldl -lmemcachedutil -lmemcached 

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (OpenSSL 1.0.2k  26 Jan 2017, FIPS enabled)
    - PCRE support
    - PCRE2 support
    + POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by KratiBansal** [comment]
why is the server supporting only rsa-sha2-512,rsa-sha2-256 for hostkeys when proftpd config is running with -

  SFTPHostKeys  \
    ecdsa-sha2-nistp256 \
    ecdsa-sha2-nistp384 \
    ecdsa-sha2-nistp521 \
    rsa-sha2-512 \
    rsa-sha2-256

**Comment by Castaglia** [comment]
> why is the server supporting only rsa-sha2-512,rsa-sha2-256 for hostkeys when proftpd config is running with -

That's what we're trying to figure out.  And to do so, I need to know a lot more information than you are providing.

It is *not enough* to provide excerpts and snippets of log messages and configuration files.  In order to understand the full situation in which your server is running, I need to know the underlying OS, the OpenSSL library version, the _full configuration (not just excerpts), and the full logs (not just single lines).  And I may ask for additional detailed logging, such as TraceLogs, to get more information.

Debugging the algorithm negotiation process is not easy, and by omitting details, it is that much harder.  

> and we had a conversation wherein you mentioned that these hostkeys were supported

Yes, I remember.  "Supported" means "the mod_sftp module has code to implement those algorithms, for SSH, assuming the underlying libraries provide the necessary support".  It is *not* a simple yes/no situation, as you seem to believe.

**Comment by Castaglia** [comment]
For example, in your configuration, what are the [`SFTPHostKey`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPHostKey) directives that you used?  If no EC keys are configured as host keys, then the EC hostkey algorithms cannot be supported, as there is no key to use for those algorithms.

If you configure trace logging, like so:
```
TraceLog /path/to/proftpd-trace.log
Trace ssh2:20
```
I suspect that, in that `TraceLog`, when your SFTP client connects, you will see messages:
```
omitting host key algorithm 'ecdsa-sha2-nistp256' due to lack of key
omitting host key algorithm 'ecdsa-sha2-nistp384' due to lack of key
omitting host key algorithm 'ecdsa-sha2-nistp521' due to lack of key
```
If you _do_ see these, then the remedy is to provide an EC host key:
```
SFTPHostKey /etc/ssh_host_ecdsa_key
```

**Comment by KratiBansal** [comment]
hey @Castaglia thanks for checking this one. Deeply sorry for the trouble. We checked and as pointed we were missing the SFTPHostKey for ecdsa. We populated it, and I still see the trace log complaining for -

```
2024-10-14 07:46:14,965 [29158] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp384' due to lack of key
2024-10-14 07:46:14,965 [29158] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp521' due to lack of key
```
Am I missing something here?

**Comment by KratiBansal** [comment]
I have added something like this -

```
    SFTPHostKey /etc/proftpd/sftp_host_rsa_key
    SFTPHostKey /etc/proftpd/sftp_host_dsa_key
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_256_key
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_384_key
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_521_key
```

```
trace log -

024-10-14 15:33:34,370 [19648] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_rsa_key'
2024-10-14 15:33:34,371 [19648] <ssh2:4>: using '/etc/proftpd/sftp_host_rsa_key' as RSA hostkey (2048 bits)
2024-10-14 15:33:34,371 [19648] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_dsa_key'
2024-10-14 15:33:34,371 [19648] <ssh2:4>: using '/etc/proftpd/sftp_host_dsa_key' as DSA hostkey (1024 bits)
2024-10-14 15:33:34,371 [19648] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_256_key'
2024-10-14 15:33:34,372 [19648] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_384_key'
2024-10-14 15:33:34,373 [19648] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_521_key'
2024-10-14 15:33:34,375 [19648] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp384' due to lack of key
2024-10-14 15:33:34,375 [19648] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp521' due to lack of key
2024-10-14 15:33:34,375 [19648] <ssh2:5>: digest 'hmac-ripemd160' is disabled in FIPS mode, skipping
2024-10-14 15:33:34,375 [19648] <ssh2:5>: digest 'umac-64@openssh.com' is disabled in FIPS mode, skipping
2024-10-14 15:33:34,375 [19648] <ssh2:9>: sending KEXINIT message to client
```

**Comment by KratiBansal** [comment]
The files are present for - /etc/proftpd/sftp_host_ecdsa_521_key and /etc/proftpd/sftp_host_ecdsa_384_key
still the issue seems to persist

**Comment by KratiBansal** [comment]
@Castaglia can you please check this? This is a little bit on priority for us.

**Comment by KratiBansal** [comment]
@Castaglia any update on this one?

**Comment by akshaysable2** [comment]
@Castaglia any updates ?

**Comment by Castaglia** [comment]
How did you generate these files?
```
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_256_key
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_384_key
    SFTPHostKey /etc/proftpd/sftp_host_ecdsa_521_key
```
mod_sftp double-checks that the key from the file matches the corresponding algorithm; the `ecdsa-sha2-nistp384` algorith requires an ECDSA 384-bit key, the `ecdsa-sha2-nistp521` algorithm requires an ECDSA 521-bit key.

**Comment by KratiBansal** [comment]
something like this -

ssh-keygen -t ecdsa -b 384
Generating public/private ecdsa key pair.
Enter file in which to save the key (/home/krati.bansal/.ssh/id_ecdsa): id_ecdsa_384
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in id_ecdsa_384.
Your public key has been saved in id_ecdsa_384.pub.
The key fingerprint is:
xxxxx
The key's randomart image is:
+---[ECDSA 384]---+
|          .o+    |
|         . E .   |
|   .  o + . o    |
|    *.o= = +     |
|   +.B..S + .    |
|  o..=+... o     |
| ...X ..o.=      |
|.. + =.o.+..     |
|.     ==+.oo     |
+----[SHA256]-----+

**Comment by KratiBansal** [comment]
Tried pem format keys too but still the issue -

```
ssh-keygen -f /etc/proftpd/ssh_host_ecdsa_key_521 -t ecdsa -b 521 -N '' -m PEM
Generating public/private ecdsa key pair.
Your identification has been saved in /etc/proftpd/ssh_host_ecdsa_key_521.
Your public key has been saved in /etc/proftpd/ssh_host_ecdsa_key_521.pub.
The key fingerprint is:
XXXXXXXX
The key's randomart image is:
+---[ECDSA 521]---+
|  ++BB+oo.       |
| . ====+         |
|  o E+. o        |
|.. o  ..         |
|..+  .  S        |
| o... +. .       |
|...o.+.=.        |
|o ..+.B o        |
|. .+oB++         |
+----[SHA256]-----+
```

**Comment by KratiBansal** [comment]
Supporting logs for more details -

```
sudo cat /var/log/proftpd/proftpd-trace.log | grep omitting -A10 -B10
2024-10-17 02:09:51,342 [4067] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_rsa_key'
2024-10-17 02:09:51,344 [4067] <ssh2:4>: using '/etc/proftpd/sftp_host_rsa_key' as RSA hostkey (2048 bits)
2024-10-17 02:09:51,344 [4067] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_dsa_key'
2024-10-17 02:09:51,345 [4067] <ssh2:4>: using '/etc/proftpd/sftp_host_dsa_key' as DSA hostkey (1024 bits)
2024-10-17 02:09:51,345 [4067] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_256_key'
2024-10-17 02:09:51,345 [4067] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_384_key'
2024-10-17 02:09:51,346 [4067] <ssh2:9>: loading host key from file '/etc/proftpd/sftp_host_ecdsa_521_key'
2024-10-17 02:09:51,348 [4067] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp384' due to lack of key
2024-10-17 02:09:51,348 [4067] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp521' due to lack of key
2024-10-17 02:09:51,348 [4067] <ssh2:5>: digest 'hmac-ripemd160' is disabled in FIPS mode, skipping
2024-10-17 02:09:51,348 [4067] <ssh2:5>: digest 'umac-64@openssh.com' is disabled in FIPS mode, skipping
2024-10-17 02:09:51,348 [4067] <ssh2:9>: sending KEXINIT message to client
2024-10-17 02:09:51,348 [4067] <ssh2:20>: sending 410 bytes of SSH_MSG_KEXINIT (20) payload
2024-10-17 02:09:51,348 [4067] <ssh2:19>: waiting for max of 120 secs while polling socket 1 for writing using select(2)
```

**Comment by Castaglia** [comment]
Do you have an `SFTPLog` configured?  I'm attempting to reproduce this behavior locally.  I do notice that, in an `SFTPLog`, on connect, I see messages like this logged:
```
2024-10-17 14:31:11,140 mod_sftp/1.2.0[86631]: using '/etc/proftpd/ssh_host_ecdsa256_key' as 256-bit ECDSA hostkey (521 bits)
2024-10-17 14:31:11,140 mod_sftp/1.2.0[86631]: using '/etc/proftpd/ssh_host_ecdsa384_key' as 384-bit ECDSA hostkey (521 bits)
2024-10-17 14:31:11,140 mod_sftp/1.2.0[86631]: using '/etc/proftpd/ssh_host_ecdsa521_key' as 521-bit ECDSA hostkey (521 bits)
```
and I'm wondering if you see similar.

I can confirm that I see this unexpected behavior of "omitting host key algorithm" locally as well, using the latest ProFTPD code from master:
```
2024-10-17 14:31:11,148 [86631] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp384' due to lack of key
2024-10-17 14:31:11,148 [86631] <ssh2:19>: omitting host key algorithm 'ecdsa-sha2-nistp521' due to lack of key
```
so I should hopefully have a fix soon.

**Comment by Castaglia** [comment]
This should fix the issue for you; I should have it committed shortly, and backported to the 1.3.8 branch: https://github.com/proftpd/proftpd/pull/1842

**Comment by Castaglia** [comment]
> Can you please let us know once you backport the fix.

This backport was done yesterday; see https://github.com/proftpd/proftpd/commit/4ca1c9ddf8a5acc59f2af3ec639b8547c14579cb
