### ISSUE TITLE
Test suite fails partially on risc64

### ISSUE THREAD

**Issue by hpreusse** [proftpd/proftpd#1848]
Another issue for the test suite. I'm using the 1.3.8.b+dfsg-3 from Debian and try to run the test suite on risc64. On the [Deb CI test page](https://ci.debian.net/packages/p/proftpd-dfsg/testing/riscv64/) one notices that a specific test fails:

```
1211s 99%: Checks: 881, Failures: 1, Errors: 0
1211s api/netaddr.c:194:F:base:netaddr_get_addr_test:0: Expected ENOENT (2) or EAGAIN (11), got Success (0)
1211s make[1]: Leaving directory '/tmp/autopkgtest-lxc.rzfhc3rb/downtmp/build.h5f/src/tests'
1211s make[1]: *** [Makefile:126: api-tests] Error 1
```
I logged in into one of the risc64 machines of Debian, but failed to reproduce the issue. I do not know yet, what is the difference between the machine running the Deb CI's and the box I used for testing. So currently I can't deliver more debug information. I'll try to find out what is the difference between the Deb CI box and my debug box.

For 1.3.8.b+dfsg-4 I've disabled the specific test.

**Comment by Castaglia** [comment]
Interesting.  The unit test in question is expected to fail, being unable to resolve via DNS a hostname that is (or _should be_) unresolvable: `foo.bar.castaglia.example.com` (see [here](https://github.com/proftpd/proftpd/blob/master/tests/api/netaddr.c#L190`)).  I wonder if there is something about the DNS setup of this CI host that somehow allows for resolving unknown names to some default/base IP address?

**Comment by hpreusse** [comment]
Many thanks for the comment. I informed the reponsible persons and hope for a reply.

**Comment by Castaglia** [comment]
@hpreusse Any update for this issue?  I'm wondering whether to close this ticket.  Thanks!

**Comment by hpreusse** [comment]
That ticket was mainly to find out, what the test does. Now that you explained I'm closing the issue. Many thanks!
