### ISSUE TITLE
can't get ProFTPD to serve up sftp

### ISSUE THREAD

**Issue by prescriptionlifeline** [proftpd/proftpd#1849]
### What I Did

I installed ProFTPD by doing `sudo apt install proftpd`, updated my .conf file (I have two - one at `/etc/proftpd/proftpd.conf` and one at `/usr/local/etc/proftpd.conf` - I tried both; my modifications are linked to, below) and then restarted ProFTPD by doing `sudo systemctl restart proftpd` and then this:

```
sftp -oPort=2222 prescriptionlifeline@localhost
```
That final `sftp` step gives me this error:

```
ssh: connect to host localhost port 2222: Connection refused
Connection closed.
Connection closed
```

### What I Expected/Wanted

I wanted to be able to connect to ProFTPD via SSH.

### ProFTPD Version and Configuration

`proftpd -V` output can be found here:

https://pastebin.com/4M0iwATc

The contents of my `/etc/proftpd/proftpd.conf` file (since a lot of online tutorials mention it) are as follows:

https://pastebin.com/izwUDyU4

The contents of my `/usr/local/etc/proftpd.conf` file (since that's what `proftpd -V` mentioned)

https://pastebin.com/SzjNd1ww

There isn't a `/etc/proftpd/authorized_keys/` directory.

My `/var/log/proftpd/sftp.log` is empty. `/etc/ssh/ssh_host_dsa_key` doesn't exist, however, `/etc/ssh/ssh_host_rsa_key` does and it starts off with `-----BEGIN OPENSSH PRIVATE KEY-----`. To view that file, however, I need to do sudo.

Any ideas?

**Comment by Castaglia** [comment]
What does `proftpd -l` (to list the statically compiled-in modules) show?

**Comment by prescriptionlifeline** [comment]
That appears to be the issue. I'm seeing this:

```
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
```

**Comment by Castaglia** [comment]
> It's a little annoying because all the online tutorials act as though mod_sftp is installed by default when you do `sudo apt install proftpd` but that does not appear to be the case.

This particular installation is on WSL, per your `proftpd -V` output:
```
Compile-time Settings:
  Version: 1.3.8 (stable)
  Platform: LINUX [Linux 5.15.167.4-microsoft-standard-WSL2 x86_64]
```
WSL is not exactly a common platform, so it's possible that the online tutorials assume a more common Linux-based installation, rather than via WSL.
