### ISSUE TITLE
Crash on logrotate

### ISSUE THREAD

**Issue by licaon-kter** [proftpd/proftpd#185]
Building from git.
This is from December 18 commit 82a2fe1.

[logrotate conf](https://gist.github.com/licaon-kter/00abe72fe84d21ae58e4)
[proftpd -V](https://gist.github.com/licaon-kter/7f65f59ad92ec440928e)
[proftpd -l](https://gist.github.com/licaon-kter/0092a93827a737769be2)
[proftpd -vv](https://gist.github.com/licaon-kter/a0dca62fb8d94314ddd5)
[proftpd -n --debug 10](https://gist.github.com/licaon-kter/58ae1bb7c448f68fd69c)
[readelf](https://gist.github.com/licaon-kter/6f9a190ce07947710b6e)

At this moment an old build of September 17 ( I guess commit aceca59 ) does *not* exhibit this, but the next build of October 13 ( I guess commit d6e7c99 ) *does* exhibit this.

I'll try to build some intermediaries to bisect this as time permits.

**Comment by Castaglia** [comment]
Could you also provide your full `proftpd.conf`, please?  That will help me see which _e.g._ DSO modules are loaded, and thus to help reproduce this locally.  Thanks!

**Comment by Castaglia** [comment]
I'm hoping that (79ee40)[https://github.com/proftpd/proftpd/commit/79ee407ad0c92f93c24efaa8b1758240532f3e1f] has fixed this (at least the segfault I saw when doing this).

**Comment by licaon-kter** [comment]
Looks like that fixed it, using forced HUP.

Config for reference:
[proftpd.conf](https://gist.github.com/licaon-kter/90758a19d0a0072f20c0)
[local1.conf](https://gist.github.com/licaon-kter/f6e4e608e85a15145ab0)

**Comment by Castaglia** [comment]
Excellent!  Thanks for the confirmation, and the configurations.

**Comment by licaon-kter** [comment]
Looks like 23582e4a425bd892cf3de1d5092760ac16e2d800 brought this back on my systems. :(

Config is above, I'll upload results of the other commands asap too.

**Comment by Castaglia** [comment]
I'm going to open a new, separate ticket, as this is a different root cause.  Otherwise, reports of the same symptom (which can have multiple causes) all get lumped together, which makes triage and historical accuracy confusing and hard.
