### ISSUE TITLE
how to install sftp module?

### ISSUE THREAD

**Issue by prescriptionlifeline** [proftpd/proftpd#1850]
### What I Did

```
git clone https://github.com/proftpd/proftpd.git
git checkout v1.3.8
./configure --enable-openssl --with-modules=mod_sftp
make
sudo make install
```

### What I Expected/Wanted

I expected `proftpd -l` to mention the SFTP module but it doesn't - it outputs this:

```
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
```

### ProFTPD Version and Configuration

`proftpd -V` returns this:

```
ProFTPD Version 1.3.8
```

**Comment by Castaglia** [comment]
Is it possible that there are multiple different `proftpd` executables now installed on your system?  The project-provided installation location for `proftpd` is `/usr/local/sbin/proftpd`.  Other package-provided installation locations may be `/usr/sbin/proftpd`, for example.

**Comment by prescriptionlifeline** [comment]
It's possible but rather then deal with that I just installed ProFTPD via apt-get on another system (a Raspberry Pi) and mod_sftp is working on that system so I'm satisfied.

Thanks!
