### ISSUE TITLE
mod_ban whitelisting doesn't work

### ISSUE THREAD

**Issue by pwnmagic** [proftpd/proftpd#211]
I am observing issues with mod_ban whitelisting (for clientconnectrate) using mod_ifsession. The whitelisting doesn't work. See config snippet for config details. In addition to the server config, I have tested **IfClass whitelist** within **IfModule mod_ban.c** and *_Global *_sections to rule out all possibilities but it doesn't help.

Config Snippet
https://gist.github.com/pwnmagic/70f0bee17f1d2973890a

ProFTPD Version
1.3.4c

Related Info
This could be related to the bugfixes made in 1.3.3 with respect to mod_ban and mod_ifsesion (http://sourceforge.net/p/proftp/mailman/message/24628031/)

**Comment by Castaglia** [comment]
Would it be possible for you try out your configuration using e.g. `proftpd-1.3.5a`?

**Comment by pwnmagic** [comment]
Ah, not possible at this time due to my test environment limitations but I'll see if I can setup something else. Any other ideas or workarounds for 1.3.4c?

**Comment by Castaglia** [comment]
Unfortunately, without the necessary code support, per-client whitelisting in `mod_ban` isn't really possible.

**Comment by Castaglia** [comment]
As there's been no movements/comments on this ticket in a while, I'm going to close it.  Please re-open if you feel it necessary.  Thanks!
