### ISSUE TITLE
Directory/File listing errors latest git

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#215]
Observing some odd log entries when users are listing dirs. Getting time outs or errors. I see the attached in the logs.
[logs-output.txt](https://github.com/proftpd/proftpd/files/133216/logs-output.txt)

**Comment by Castaglia** [comment]
Hrm.  Could you provide the `proftpd -V` output, and maybe a config that I could use to try to reproduce this locally?  Thanks!

**Comment by tspicer** [comment]
Hi,
I operate under the name "openbridge" in the forums. I think I sent you most of my configs in the past. I can resend if you do not have them anymore.

Transfers for larger files have been failing. I'm in the process of turning everything off to see any impacts. BTW, I use docker, so when ever I  build a new new docker image it pulls from source. This means changes are isolated to the build commands. In this case pulling from git for proftpd. I had not had this issue with an earlier clone


proftpd -V
Compile-time Settings:
  Version: 1.3.6rc2 (git)
  Platform: LINUX [Linux 4.1.13-19.31.amzn1.x86_64 x86_64]
  Built: Tue Feb 16 2016 22:51:16 UTC
  Built With:
    configure  'CFLAGS=-DBAN_LIST_MAXSZ=16384 -DPR_TUNABLE_GLOBBING_MAX_RECURSION=2 -DPR_TUNABLE_GLOBBING_MAX_MATCHES=500UL' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/var/run/proftpd' '--disable-auth-pam' '--disable-strip' '--enable-ctrls' '--enable-facl' '--disable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-autoshadow' '--enable-tunable-buffer-size' '--enable-sendfile' '--enable-dso' '--with-libraries=/usr/lib64/mysql:/usr/lib64' '--with-includes=/usr/include/mysql:/usr/include' '--with-modules=mod_readme:mod_tls:mod_dynmasq' '--with-shared=mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_sql:mod_sql_passwd:mod_sql_mysql:mod_quotatab:mod_quotatab_file:mod_quotatab_sql:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_ratio:mod_rewrite:mod_site_misc:mod_shaper:mod_geoip:mod_copy:mod_ifversion:mod_dnsbl:mod_qos:mod_tls_shmcache:mod_tls_memcache:mod_sftp:mod_sftp_sql:mod_ifsession:mod_exec:mod_charset:mod_clamav'

  CFLAGS: -DBAN_LIST_MAXSZ=16384 -DPR_TUNABLE_GLOBBING_MAX_RECURSION=2 -DPR_TUNABLE_GLOBBING_MAX_MATCHES=500UL -Wall
  LDFLAGS: -L$(top_srcdir)/lib  -L/usr/lib64 -L/usr/lib64/mysql -L/usr/lib64
  LIBS:  -lpcreposix -lpcre -lssl -lcrypto -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lmemcached -lmemcachedutil  -lssl -lcrypto -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/run/proftpd/proftpd.pid
    Scoreboard File:
      /var/run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    - IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (FIPS enabled)
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 500
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 2
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10




###################
# PROFTPD
###################

# Compile Proftpd to include ClamAV file stream scanner & mod_vroot
    cd /tmp ;\

# This pulls the latest source from Github.
    git clone https://github.com/proftpd/proftpd.git ;\
    cd proftpd* ;\
# This pulls the latest stable release.
    #wget -O proftpd.tar.gz https://github.com/proftpd/proftpd/archive/v1.3.5a.tar.gz ;\
    #tar -xf proftpd* && cd proftpd* ;\
    wget https://github.com/jbenden/mod_clamav/archive/master.zip ;\
    unzip master.zip ;\
    rm master.zip ;\
    #git clone https://github.com/Castaglia/proftpd-mod_vroot.git ;\
    wget https://github.com/Castaglia/proftpd-mod_charset/archive/master.zip ;\
    unzip master.zip ;\
    rm master.zip ;\
    #wget https://github.com/Castaglia/proftpd-mod_mime/archive/master.zip ;\
    #unzip master.zip ;\
    #rm master.zip ;\
    #wget https://github.com/Castaglia/proftpd-mod_tar/archive/master.zip ;\
    #unzip master.zip ;\
    #rm master.zip ;\
    #wget https://github.com/Castaglia/proftpd-mod_md5/archive/master.zip ;\
    #unzip master.zip ;\
    #rm master.zip ;\
    mv mod_clamav*/mod_clamav.c contrib/mod_clamav.c ;\
    mv mod_clamav*/mod_clamav.h contrib/mod_clamav.h ;\
    #mv proftpd-mod_vroot*/mod_vroot.c contrib/mod_vroot.c ;\
    #mv proftpd-mod_mime*/mod_mime.c contrib/mod_mime.c ;\
    mv proftpd-mod_charset*/mod_charset.c contrib/mod_charset.c ;\
    #mv proftpd-mod_md5*/mod_md5.c contrib/mod_md5.c ;\
    #mv proftpd-mod_tar*/mod_tar.c contrib/mod_tar.c ;\
    cd contrib/mod_dnsbl ;\
    ./configure ;\
    cd .. ;\
    cd .. ;\
    ./configure CFLAGS="-DBAN_LIST_MAXSZ=16384 -DPR_TUNABLE_GLOBBING_MAX_RECURSION=2 -DPR_TUNABLE_GLOBBING_MAX_MATCHES=500UL" '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/var/run/proftpd' '--disable-auth-pam' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--disable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-autoshadow' '--enable-tunable-buffer-size' '--enable-sendfile' '--enable-dso' '--with-libraries=/usr/lib64/mysql:/usr/lib64' '--with-includes=/usr/include/mysql:/usr/include' '--with-modules=mod_readme:mod_tls:mod_dynmasq' '--with-shared=mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_sql:mod_sql_passwd:mod_sql_mysql:mod_quotatab:mod_quotatab_file:mod_quotatab_sql:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_ratio:mod_rewrite:mod_site_misc:mod_shaper:mod_geoip:mod_copy:mod_ifversion:mod_dnsbl:mod_qos:mod_tls_shmcache:mod_tls_memcache:mod_sftp:mod_sftp_sql:mod_ifsession:mod_exec:mod_charset:mod_clamav' ;\
    make ;\
    make install ;\
    rm -rf /tmp/proftpd* ;\
    rm -rf /tmp/mod_* ;\

    echo "PROFTPD_OPTIONS=-DDYNAMIC_BAN_LISTS" > /etc/sysconfig/proftpd

**Comment by tspicer** [comment]
For example, I have a 450MB file, it starts to transfer, then fails early on in the process

{"time":"2016-02-16 23:03:43,891","cmd":"WRITE","full_path":"foo.txt","remote_user":"proftpdtestuser","remote_dns":"x.x.x.x","remote_ip":"x.x.x.x","local_ip":"172.17.0.2","local_dns":"172.17.0.2","protocol":"sftp","transfer_time":"891.325","transfer_size":"37191680","response_code":"0"}
{"time":"2016-02-16 23:03:44,566","cmd":"STOR","full_path":"/mnt/ebs/ftpd/proftpdtestuser/tests/.foo.txt","remote_user":"proftpdtestuser","remote_dns":"x.x.x.x","remote_ip":"x.x.x.x","local_ip":"172.17.0.2","local_dns":"172.17.0.2","protocol":"sftp","transfer_time":"892.000","transfer_size":"37208064","response_code":"-"}

**Comment by tspicer** [comment]
FYI, reverting to the build on or near Jan 25th has resolved the issue.

**Comment by Castaglia** [comment]
Hmm.  Would it be possible for you to test your `proftpd` _without_ the `mod_mime` module (or at least disabling it via config)?  I am wondering whether this could be caused by unexpected (read: "bad") interactions with that module (or with `mod_clamav`, or some of the other non-standard modules)?

**Comment by Castaglia** [comment]
Do these failures only seem to happen for SFTP requests, or for FTP commands, or both?  (The log excerpt above mentions "WRITE", which is an SFTP request, not an FTP command...)

**Comment by Castaglia** [comment]
Also, if you're on IRC, I am usually available on the `#proftpd` channel on irc.freenode.net, nick "castaglia".  In trying to reproduce this issue locally (and not having any luck so far), I'm thinking that a more interactive conversation might help to run this down.  And I would like to fix this soon, as it's the last issue before I release 1.3.6rc2 and 1.3.5b.  Thanks!

**Comment by tspicer** [comment]
Hi,
I can disable mod mime in the compile but was not using it in the config.

I'm thinking this might be related to the underlying filesystem (fuse/s3fs). From what I can tell is they introduced some code recently that may have broken s3fs. Once I reverted to an older commit the odd character issues in the log went away. However, the timeouts still persisted for SFTP.

**Comment by Castaglia** [comment]
OK, good to know about the odd characters (which looks like some type of memory buffer overrun/corruption to me).

**Comment by Castaglia** [comment]
The unexpected log message characters turned out to be caused by an issue in the underlying s3fs layer, not a proftpd issue.  Rolling back the s3fs version in question resulted in logging as expected.
