### ISSUE TITLE
Inconsistent results from XSHA1 

### ISSUE THREAD

**Issue by mrobe** [proftpd/proftpd#225]
Problem: using ProFTPD 1.3.5, my FTP client sends the XSHA1 command for an 8 GB file.

If the command is issued three times for the same file, XSHA1 returns three different hash values.

Is this a bug?

**Comment by Castaglia** [comment]
Are you using the `mod_digest` from smartftp.com?  If so, you might try the latest code from the master branch (where `mod_digest` is now part of the source distribution), and see if the issue still happens.

**Comment by mrobe** [comment]
Possibly. Will this be included in the next release of ProFTPD?

**Comment by Castaglia** [comment]
Yes, the `mod_digest` module is distributed with [proftpd-1.3.6rc2](https://github.com/proftpd/proftpd/releases/tag/v1.3.6rc2).

**Comment by Castaglia** [comment]
I'm going to assume that the `mod_digest` distributed with proftpd-1.3.6rc2 addresses this issue, and will close it.  Please reopen if that is not the case.  Thanks!

**Comment by mrobe** [comment]
Sorry, I cannot verify that the issue has been resolved.

It's not my box and the sysadmin is not going to install the release candidate because there are some local mods.

Is there any ETA on 1.3.6?

**Comment by Castaglia** [comment]
No ETA; it'll be ready when it's ready.  I can't really promise anything more than that.
