### ISSUE TITLE
Convert IDN domain to IDNA

### ISSUE THREAD

**Issue by Ninos** [proftpd/proftpd#231]
ATM our open-source project https://i-mscp.net/ need to store the idn-domain in database, because proftpd is not converting idn to idna. The correct way should be to store idna in database and automatically convert idn to idna (ascii), may if first auth will fail.
Example:
`test@exämple.tld -> test@xn--exmple-cua.tld`

ATM we need to use idn (`test@exämple.tld`), ascii-format will not work.

**Comment by nuxwin** [comment]
It must be mentionned that we use IDN as a part of the FTP usernames. It would be great to have an option that tells to ProFTPD to automatically convert any IDN to ASCII in username (before authentication attemp). This would allow to search username in one column only. We use MySQL, and we want store the usernames in ASCII form only.

Thanks you.

**Comment by Castaglia** [comment]
Hmm.  What if this could be done via the `mod_rewrite` module, such as a builtin [`RewriteMap`](http://www.proftpd.org/docs/contrib/mod_rewrite.html#RewriteMap) function such as `idnatrans`?  That way, you could configure `mod_rewrite` to translate the `USER` names as needed for your setup, and other sites could use the same functionality for any other commands, as needed?

**Comment by nuxwin** [comment]
@Castaglia 

Would be great ;)

**Comment by Castaglia** [comment]
Would the `USER` name be encoded as a sequence of UTF-8 bytes, or UCS-4?  Reason I ask is whether to use the `idna_to_ascii_8z()` or the `idna_to_ascii_4z()` libidn function...

**Comment by nuxwin** [comment]
@Castaglia 

We use UTF-8 but maybe you can add a switch for people which want to use  UCS-4 (just a suggestion).

Thank you for all your efforts to make this software always better.

**Comment by Castaglia** [comment]
With the above pull request, you _should_ be able to re-run your `make clean && ./configure ... && make && make install` command for proftpd.  And then in the `mod_rewrite` config, you might try:

    # Define a map that uses the internal "idnatrans" function
    RewriteMap idna int:idnatrans

    # Only for the USER command
    RewriteCondition %m USER

    RewriteRule ^(.*)@(.*)$ $1@${idna:$2}
  
I've not tested the above, but it gives you the idea.

**Comment by nuxwin** [comment]
@Castaglia 

I'll backport the PR on my Jessie ProFTPD debian package and process some tests.

**Comment by Castaglia** [comment]
Any luck/feedback/comment with this?

**Comment by nuxwin** [comment]
@Castaglia 

Sorry. We are in release period. I'll try to test that tomorrow.

**Comment by Castaglia** [comment]
OK, no worries.  Just thought I'd check in.  Good luck with the release!

**Comment by Castaglia** [comment]
Any luck/feedback/comment on this feature?  I'm asking because I'd like to consider merging it to the master branch, for inclusion in the next RC.

**Comment by nuxwin** [comment]
Oh.. Ok... Well I'll test it soon. I'm not at home till 12 may... I'm really sorry for that. I'll do that on 13 may. Right now, I've just a laptop on which my dev environment is not installed.

**Comment by Castaglia** [comment]
I'm looking to merge this into the master branch, unless there are reasons not to...?

**Comment by nuxwin** [comment]
@Castaglia 

This will be really more easy to for us to test and give feedback on that feature once merged in master.

**Comment by Castaglia** [comment]
Fixed in master.
