### ISSUE TITLE
Support extended attribute SFTP requests

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#241]
Consider enhancing `mod_sftp` to support SFTP requests related to extended attributes.  See, for example, [this OpenSSH feature request](https://bugzilla.mindrot.org/show_bug.cgi?id=1953).

And for an interesting read on why such a thing can be quite useful, read [this analysis of SSHFS](http://julio.meroh.net/blog/2016/02/17/sshfs-performance-analysis-for-builds.html).

**Comment by Castaglia** [comment]
The proposed changes for supporting SFTP operations on extended attributes in `mod_sftp` are based on the changes proposed for OpenSSH.  As OpenSSH has not shown desire to accept the proposed extensions, I'll be adapting them for ProFTPD's namespace.

In the response to the SFTP `INIT` request, `mod_sftp` anounces its support for the above extensions by including the string "xattr@proftpd.org" in the extension list.

- `getxattr@proftpd.org`

This request is implemented as an `SSH_FXP_EXTENDED` request with the following format:

    uint32          id
    string          "getxattr@proftpd.org"
    string          path
    string          name
    uint32          size

These `path`, `name`, `size` parameters correspond to those of the `getxattr(2)` system call.  On failure, the response will be an `SSH_FXP_STATUS` message.  On success, the response will be an `SSH_FXP_EXTENDED_REPLY`:

    uint32          id
    string          data

where `data` would be the value obtained via `getxattr(2)`.

- `listxattr@proftpd.org`

This request is implemented as an `SSH_FXP_EXTENDED` request with the following format:

    uint32          id
    string          "listxattr@proftpd.org"
    string          path
    uint32          size

These `path` and `size` parameters correspond to those of the `listxattr(2)` system call.  On failure, the response will be an `SSH_FXP_STATUS` message.    On success, the response will be an `SSH_FXP_EXTENDED_REPLY`:

    uint32          id
    string          data

- `removexattr@proftpd.org`

This request is implemented as an `SSH_FXP_EXTENDED` request with the following format:

    uint32          id
    string          "removexattr@proftpd.org"
    string          path
    string          name

These `path` and `name` parameters correspond to those of the `removexattr(2)` system call.  The response will be an `SSH_FXP_STATUS` message.

- `setxattr@proftpd.org`

This request is implemented as an `SSH_FXP_EXTENDED` request with the following format:

    uint32          id
    string          "setxattr@proftpd.org"
    string          path
    string          name
    string          value
    uint32          flags

These `path`, `name`, `value`, and `flags` parameters correspond to those of the `setxattr(2)` system call.  The response will be an `SSH_FXP_STATUS` message.

**Comment by Castaglia** [comment]
For the case where extended attributes should be included in `FXP_NAME` responses (_e.g._ for `READDIR`, `STAT`, and related requests), I'd recommend considering supporting the `SSH_FILEXFER_ATTR_EXTENDED` bits from [draft-ietf-secsh-filexfer-13, Section 7.14](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-7.14).  There are a growing number of SFTP clients which implement protocol version 6 of SFTP, and they too would benefit from extended attributes support *as documented in that draft*.

**Comment by Castaglia** [comment]
FYI, @martinprikyl @smartftp I think this branch/PR will be of interest to you.  Do your respective clients support extended attributes in SFTP protocol version 6?

**Comment by martinprikryl** [comment]
Thanks for your message. WinSCP does not support any extended file attributes. So far I'm not aware of any major SFTP server providing extended attributes that would be of any use in GUI SFTP client.

Regarding your specific implementation: I'm not really familiar with the xattr concept. What are the common x-attributes used in a wild that would be of use for a GUI client?

**Comment by Castaglia** [comment]
[Extended attributes](https://en.wikipedia.org/wiki/Extended_file_attributes) (commonly abbreviated as just "xattrs") are becoming more and more common, _e.g._:

- [Extended attributes and HDFS](https://blog.cloudera.com/blog/2014/06/why-extended-attributes-are-coming-to-hdfs/)
- [Tagging your files](http://vhanda.in/blog/2014/07/tagging-your-files/)

There's a [proposal](https://www.freedesktop.org/wiki/CommonExtendedAttributes/) to describe some common extended attribute names; the proposed names are being used in the some software for _e.g._ tagging (see file tagging link above).  Other common names are documented [here](http://linux-audit.com/using-xattrs-extended-attributes-on-linux/).  Some of these names might be of interest for GUI clients, I would think.

**Comment by martinprikryl** [comment]
I may display a list of attributes for a start.

**Comment by Castaglia** [comment]
Merged to master.

**Comment by gjaekel** [comment]
A connection problem was reported by a business customer that work with program using the Windows SFTP library "RebeX". On https://www.rebex.net/sftp.net/history.aspx , I found that this project

"Added workaround for ProFTPd 1.3.6's mod_sftp which sends broken response when CREATETIME attribute has been requested" 

within it's Release 2017-11-20 Version 2017 R6.1. This fits because our customer currently uses Rebex.Sftp 2017 R3

I want to ask if this is already know or fixed?

**Comment by Castaglia** [comment]
@gjaekel yes, I believe that issue should be addressed by https://github.com/proftpd/proftpd/commit/9c1381517c2e7dc794db3683686816a9d8a1779a#diff-8e15cf02b721b32801c4b1c8514556f4.
