### ISSUE TITLE
Signal 11 on client connection with malformed/crafted GeoIP.dat file.

### ISSUE THREAD

**Issue by dmilith** [proftpd/proftpd#299]
### What I Did

Got crashing proftpd each time client is connecting.
it's 100% reproductible on latest stable version of Proftpd, and here's stack trace (from prod build so no symbols ofc.):

    #0  0x00007fe572abd5f5 in _GeoIP_seek_record_gl () from /Software/Proftpd/lib/libGeoIP.so.1
    #1  0x00007fe572abe115 in GeoIP_id_by_addr_gl () from /Software/Proftpd/lib/libGeoIP.so.1
    #2  0x00007fe572ac097c in GeoIP_id_by_addr () from /Software/Proftpd/lib/libGeoIP.so.1

After re-downloading GeoIP.dat, Proftpd works as expected.

### What I Expected/Wanted

Error handling for crafted/wrong GeoIP.dat file on Proftpd side.

### ProFTPD Version and Configuration

Configuration is standard one + geoip module

    Compile-time Settings:
      Version: 1.3.5a (maint)
      Platform: LINUX [Linux 2.6.32-5-xen-amd64 x86_64]
      Built: Mon May 9 2016 16:54:34 CEST
      Built With:
        configure  '--enable-nls' '--with-includes=/Software/Proftpd/include' '--with-libraries=/Software/Proftpd/lib' '--enable-openssl' '--sysconfdir=/etc' '--localstatedir=/var/run' '--without-pam' '--disable-auth-pam' '--with-modules=mod_ifsession:mod_ratio:mod_readme:mod_tls:mod_geoip' '--prefix=/Software/Proftpd' 'CC=/usr/bin/gcc ' 'CFLAGS=-I/Software/Proftpd/include  -w -O2 -fPIC -mno-avx -fno-strict-overflow -fstack-protector-all -Wl,-rpath=/Software/Proftpd/lib,--enable-new-dtags' 'LDFLAGS=-L/Software/Proftpd/lib  -fPIC -fuse-ld=gold -Wl,-rpath=/Software/Proftpd/lib,--enable-new-dtags' 'CPP=/usr/bin/cpp' 'CXX=/usr/bin/g++ ' 'CXXFLAGS=-I/Software/Proftpd/include  -w -O2 -fPIC -mno-avx -fno-strict-overflow -fstack-protector-all -Wl,-rpath=/Software/Proftpd/lib,--enable-new-dtags'

      CFLAGS: -I/Software/Proftpd/include  -w -O2 -fPIC -mno-avx -fno-strict-overflow -fstack-protector-all -Wl,-rpath=/Software/Proftpd/lib,--enable-new-dtags -Wall
      LDFLAGS: -L$(top_srcdir)/lib -L/Software/Proftpd/lib  -fPIC -fuse-ld=gold -Wl,-rpath=/Software/Proftpd/lib,--enable-new-dtags -L/Software/Proftpd/lib
      LIBS:  -lssl -lcrypto -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lGeoIP  -lssl -lcrypto -lsupp -lcrypt -ldl

      Files:
        Configuration File:
          /etc/proftpd.conf
        Pid File:
          /var/run/proftpd.pid
        Scoreboard File:
          /var/run/proftpd.scoreboard

      Features:
        - Autoshadow support
        - Controls support
        + curses support
        - Developer support
        - DSO support
        + IPv6 support
        + Largefile support
        - Lastlog support
        - Memcache support
        + ncursesw support
        + NLS support
        + OpenSSL support
        - PCRE support
        - POSIX ACL support
        + Shadow file support
        + Sendfile support
        + Trace support

      Tunable Options:
        PR_TUNABLE_BUFFER_SIZE = 1024
        PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
        PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
        PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
        PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
        PR_TUNABLE_HASH_TABLE_SIZE = 40
        PR_TUNABLE_NEW_POOL_SIZE = 512
        PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
        PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
        PR_TUNABLE_SELECT_TIMEOUT = 30
        PR_TUNABLE_TIMEOUTIDENT = 10
        PR_TUNABLE_TIMEOUTIDLE = 600
        PR_TUNABLE_TIMEOUTLINGER = 30
        PR_TUNABLE_TIMEOUTLOGIN = 300
        PR_TUNABLE_TIMEOUTNOXFER = 300
        PR_TUNABLE_TIMEOUTSTALLED = 3600
        PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
Given that proftpd's `mod_geoip` uses MaxMind's provided library for reading those data files, it's more likely to be a bug in the MaxMind library.  The stacktrace definitely shows the MaxMInd library function names.  I'm not sure what `proftpd` itself could do to avoid this; we do not want to get into the habit of second-guessing the file formats for third-party libraries.  As such, I'm inclined to view this as a case of "don't do that" (_i.e._ using malformed/corrupted library input files), as from the ProFTPD point of view, this is configuration data, and is thus equivalent to a misconfiguration.

You might file this against the MaxMind library, via their [GitHub project for it](https://github.com/maxmind/geoip-api-c).

**Comment by Castaglia** [comment]
Unfortunately, as there's nothing that ProFTPD/`mod_geoip` can do to guard against this issue, I'm going to close this issue.  Please reopen if you feel differently.
