### ISSUE TITLE
High memory usage with long running sessions

### ISSUE THREAD

**Issue by lamiska** [proftpd/proftpd#330]
Hi, I am running proftpd 1.3.5 (official from Debian Jessie repo) together with sql module on my server to write big amount of small files in 2-5 min intervals by several users into their home directories ( my IDLE timeout is set to 20min )
After file is written to disk, memory usage of session process does not go down and keeps growing steadily. After few days usage grows to several gigabytes and process is killed by system.
Is this intentional and does the memory get freed only after session is closed?
### ProFTPD Version and Configuration

$ proftpd -V
Compile-time Settings:
  Version: 1.3.5 (stable)
  Platform: LINUX [Linux 3.16.0-4-amd64 x86_64]
  Built: Tue May 19 2015 11:09:58 UTC
  Built With:
    configure  'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'FCFLAGS=-g -O2 -fstack-protector-strong' 'FFLAGS=-g -O2 -fstack-protector-strong' 'GCJFLAGS=-g -O2 -fstack-protector-strong' 'LDFLAGS=-Wl,-z,relro' 'OBJCFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'OBJCXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--with-modules=mod_readme' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_tls_memcache:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession' 'build_alias=x86_64-linux-gnu'

  CFLAGS: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lpam -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncurses support
    + NLS support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
###### #########################################################

$proftpd -l
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_ident.c
  mod_auth_pam.c
  mod_readme.c
  mod_memcache.c
  mod_cap.c
  mod_ctrls.c
  mod_lang.c

**Comment by Castaglia** [comment]
It's certainly not _intentional_; ProFTPD uses a memory pool system, and tries to reuse those pools for as long as possible.  Memory growth like you are describing is *definitely* an issue.

Could you provide the `proftpd.conf` you're using, and perhaps the proftpd debug logging showing one of these sessions?

**Comment by lamiska** [comment]
Hi,

proftpd.conf - http://pastebin.com/ge0miGkV

Note that memory was also growing before rlimit was set (also it seems to not work properly, see below)


# ftpwho
standalone FTP daemon [3658], up for 18 hrs 33 min
 3676 ftpuser1 [18h33m]   0m1s idle
 3681 ftpuser2 [18h35m]  0m14s idle
......
......
Service class                      -  21 users

Process 3676 - 43MB RAM usage
Process 3681 - 109MB RAM usage


sftp.log:

sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session key exchange: diffie-hellman-group-exchange-sha256
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session server hostkey: ssh-rsa
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session client-to-server encryption: aes256-ctr
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session server-to-client encryption: aes256-ctr
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session client-to-server MAC: hmac-md5
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session server-to-client MAC: hmac-md5
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session client-to-server compression: none
sftp.log:2016-08-30 09:28:45,487 mod_sftp/0.9.9[3676]:  + Session server-to-client compression: none


proftpd.log:

2016-08-29 15:28:45,485 photon-ftp-1 proftpd[3676] SSH2 session opened.
2016-08-29 15:28:45,557 photon-ftp-1 proftpd[3676] USER  ftpuser1: Login successful
2016-08-29 15:28:45,563 photon-ftp-1 proftpd[3676] USER  ftpuser1: Login successful
.....
2016-08-30 09:15:01,321 photon-ftp-1 proftpd[29982]: USER  ftpuser1: Login successful
2016-08-30 09:15:01,325 photon-ftp-1 proftpd[29982]: USER  ftpuser1: Login successful.
2016-08-30 09:30:00,512 photon-ftp-1 proftpd[31439]: USER  ftpuser1: Login successful
2016-08-30 09:30:00,515 photon-ftp-1 proftpd[31439]: USER  ftpuser1: Login successful.
.....

**Comment by Castaglia** [comment]
I don't see any `mod_sql`-related configuration directives in your `proftpd.conf`; perhaps there are other config files in the `/etc/proftpd/conf.d/` directory that is included?

I'd like to get the full configuration, so that I can attempt to reproduce the issue locally.  Thanks!

**Comment by lamiska** [comment]
Hello,

conf.d/auth_sql.conf - http://pastebin.com/vsjE7Xaa
conf.d/ftp.conf - http://pastebin.com/Zz0YjxHj

Thank you

**Comment by Castaglia** [comment]
Thanks!  And just to clarify, you see these long-lived, memory-hogging sessions with **SFTP** connections, or **FTPS** connections -- or _both_?  I see that you have `<VirtualHost>` sections defined for both FTPS and SFTP...

**Comment by lamiska** [comment]
It is processes who have established connection on port 2222 which is SFTP

**Comment by Castaglia** [comment]
No, the memory leak commit is not (_yet_) in any released version.  I am hoping to do a release sometime soon, though.

**Comment by lamiska** [comment]
Hi, I compiled proftpd with the commit you linked, but there still seems to be memory leak.
I also commented out all unnecessary modules from modules.conf to rule out that leak is happening in one of the modules, my current modules.conf is:

LoadModule mod_tls.c
LoadModule mod_sql.c
LoadModule mod_sql_mysql.c
LoadModule mod_site_misc.c
LoadModule mod_sftp.c
LoadModule mod_sftp_sql.c
LoadModule mod_copy.c
LoadModule mod_ifsession.c

**Comment by Castaglia** [comment]
The pastebin.com links, for the `proftpd.conf`, `conf.d/auth_sql.conf`, and `conf.d/ftp.conf` files, have expired -- could you provide those configurations again, please?

**Comment by Castaglia** [comment]
It's quite possible that the issue you're seeing is related to the `mod_facl` module, even though it is not enabled; see [Bug#4278](http://bugs.proftpd.org/show_bug.cgi?id=4278).

**Comment by lamiska** [comment]
Hi, I tried compiling proftpd with the commit in file mod_facl.c you linked but memory leak is still happening.

Here are conf files:

proftpd.conf - http://pastebin.com/i0JQWJEe
auth_sql.conf - http://pastebin.com/42pgM0ZE
ftp.conf - http://pastebin.com/4dmX33De
modules.conf - http://pastebin.com/xF0kaXf8

This is how RAM usage looks like on server - https://i.imgur.com/EA44P0B.png - Yellow is used ram, orange is cached

Each connected user is running as own process, for example from ftpwho:

 6580 user_1 [ 26h4m]   0m0s idle
 6600 user_2 [ 26h5m]  0m15s idle
 6637 user_3 [ 26h5m]   0m2s idle
... + 150 other users

Linux processes 6580, 6600 and 6637 are using 90MB of RAM (per process), users with shorter connection time are using less RAM per process.

**Comment by Castaglia** [comment]
Thanks for the config files.  What tool are you using to obtain the memory values?

**Comment by Castaglia** [comment]
I should also point out the following bugfixes:

* [Bug#4166](http://bugs.proftpd.org/show_bug.cgi?id=4166): SSH Rekeying memory leak
* [Bug#4244](http://bugs.proftpd.org/show_bug.cgi?id=4244): Long-running sessions consume memory continuously

If you can, I'd recommend trying out the latest code from the master branch on GitHub, which has the above fixes in place; they are *not* slated to be backported to the 1.3.5 branch.

**Comment by Castaglia** [comment]
Now that 1.3.5c is released, you might try upgrading to that version, and see how it goes.

**Comment by lamiska** [comment]
Hi, I installed v1.3.5d and can confirm that I cannot reproduce memory leak anymore. You can probably close this issue and thank you for your help.

**Comment by Castaglia** [comment]
Excellent news, thanks!
