### ISSUE TITLE
UserOwner & GroupOwner not work with mod_sql

### ISSUE THREAD

**Issue by michalkolar** [proftpd/proftpd#346]
Hi, i want use parameter `UserOwner` & `GroupOwner`.

I want ftp as root (ownership of new file is www-data -> work with `AuthUserFile`) - but with `mod_sql` no... because when copy new file over ftp (`mod_sql` account - > ownership is 0 (root) but group is ok (33 gid -> www-data))

## Configuration

    Port            21
    AllowOverride           off
    AllowOverwrite          on
    AllowRetrieveRestart    on
    AllowStoreRestart       on
    CapabilitiesEngine      off

    VRootEngine             on
    DefaultRoot             ~
    DefaultServer           on
    DelayEngine             off
    #DirFakeGroup            on
    #DirFakeUser             on
    Group                   nogroup
    RootLogin               on
    IdentLookups            off
    MaxClients              20
    MaxInstances            20
    MaxLoginAttempts        2
    RequireValidShell       off
    ServerAdmin             support@wvg.cz
    ServerName              "FTP node2"
    ServerType              standalone
    Umask                   022
    UseFtpUsers             off
    UseReverseDNS           off
    User                    proftpd
    RootRevoke              off
    PersistentPasswd        on
    <Directory />
            GroupOwner      www-data
            UserOwner       www-data
    </Directory>

    SQLBackend                      mysql
    SQLAuthTypes                    MD5
    SQLPasswordEngine               on
    SQLPasswordEncoding             hex
    SQLAuthenticate                 users
    SQLConnectInfo                  ext@192.168.50.100 ftp
    SQLNamedQuery                   userinfo SELECT "`username`, `password`, 0 as `uid`, 0 as `gid`, `path` AS `homedir`, '/bin/false' as `shell` FROM `ftp` WHERE `username`='%U'"
    SQLUserInfo                     custom:/userinfo
    SQLMinUserGID   0
    SQLMinUserUID   0
    SQLDefaultUID   0
    SQLDefaultGID   0
    SQLMinID        0

## Compile-time Settings

    Compile-time Settings:
      Version: 1.3.6rc3 (git)
      Platform: LINUX [Linux 4.8.4-wvgsolution x86_64]
      Built: Sun Oct 30 2016 10:04:43 CDT
      Built With:
        configure  '--with-modules=mod_tls:mod_sql:mod_sql_mysql:mod_sql_passwd:mod_vroot'

      CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
      LDFLAGS: -L$(top_srcdir)/lib  -rdynamic
      LIBS:  -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lm -lmysqlclient -lz  -lssl -lcrypto -lsupp -lcrypt -ldl

      Files:
        Configuration File:
          /usr/local/etc/proftpd.conf
        Pid File:
          /usr/local/var/proftpd.pid
        Scoreboard File:
          /usr/local/var/proftpd.scoreboard

      Info:
        + Max supported UID: 4294967295
        + Max supported GID: 4294967295

      Features:
        - Autoshadow support
        - Controls support
        - curses support
        - Developer support
        - DSO support
        + IPv6 support
        + Largefile support
        - Lastlog support
        - Memcache support
        - ncurses support
        - NLS support
        - Sodium support
        + OpenSSL support
        - PCRE support
        - POSIX ACL support
        + Shadow file support
        + Sendfile support
        + Trace support
        + xattr support

      Tunable Options:
        PR_TUNABLE_BUFFER_SIZE = 1024
        PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
        PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
        PR_TUNABLE_ENV_MAX = 2048
        PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
        PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
        PR_TUNABLE_HASH_TABLE_SIZE = 40
        PR_TUNABLE_LOGIN_MAX = 256
        PR_TUNABLE_NEW_POOL_SIZE = 512
        PR_TUNABLE_PATH_MAX = 4096
        PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
        PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
        PR_TUNABLE_SELECT_TIMEOUT = 30
        PR_TUNABLE_TIMEOUTIDENT = 10
        PR_TUNABLE_TIMEOUTIDLE = 600
        PR_TUNABLE_TIMEOUTLINGER = 10
        PR_TUNABLE_TIMEOUTLOGIN = 300
        PR_TUNABLE_TIMEOUTNOXFER = 300
        PR_TUNABLE_TIMEOUTSTALLED = 3600
        PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
When you say "copy new file over ftp", what do you mean, precisely?  Could you provide the ProFTPD debug logging, debug level 10, showing a session where `UserOwner` and/or `GroupOwner` are not working as you expect?

**Comment by michalkolar** [comment]
UserOwner was not applied to the new file on ftp... always is UID of new file 0 (root).

**Comment by Castaglia** [comment]
Please provide the requested debug logging...

**Comment by Castaglia** [comment]
If there's nothing more to add to this report, I'd like to close it.

**Comment by Castaglia** [comment]
No further contact with reporter; closing this.

**Comment by Castaglia** [comment]
For the record, the issue here, I think, is the *hardcoding* of UID 0, for *any* user that `mod_sql` would return:
```
SQLNamedQuery userinfo SELECT "`username`, `password`, 0 as `uid`, 0 as `gid`, `path` AS `homedir`, '/bin/false' as `shell` FROM `ftp` WHERE `username`='%U'"
SQLUserInfo custom:/userinfo
```
This means that when resolving the UID for user "www-data", per the `UserOwner` directive, `mod_sql` would be consulted, and (assuming that user "www-data" was in the `ftp` table) would provide a UID of zero.  And thus the UID of the uploaded file would be set to 0, per the `UserOwner` directive.  So it was working as configured, just not as expected.

And why would the GID of the uploaded file be different?  Why would the `GroupOwner` setting appear to work as expected?  This is because `mod_sql` was not configured to lookup/resolve group names to GIDs; it was only configured to lookup/resolve users:
```
SQLAuthenticate  users
```
So for the "www-data" group, the system files (_e.g._ `/etc/group`) would be consulted; they would return a non-zero GID.
