### ISSUE TITLE
Support user/group names in MLSD/MLST responses

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#347]
The [RFC 3659](https://tools.ietf.org/html/rfc3659) defines the `MLSD` and `MLST` commands, the various _facts_ that can be used in those responses.  One of the things that the RFC left out (perhaps by accident) in the mentioned facts were facts for conveying the user and group _names_.  By convention, many FTP implementations starting using `UNIX.owner` and `UNIX.group` fact names to provide the numeric _IDs_.  But the name strings corresponding to those numeric IDs, such as would be provided in the `LIST` responses, were lacking.

Fact names for these user/group strings have now been registered in the [IANA OS-Specific Facts Registry](https://tools.ietf.org/html/rfc3659): `UNIX.ownername` and `UNIX.groupname`.  The `mod_facts` module should implement support for these facts, and start using them by default.

This was occasioned by this [ServerFault post](http://serverfault.com/questions/806347/proftpd-how-to-show-virtual-user-name-in-listings).

**Comment by Castaglia** [comment]
This will be of interest to @smartftp, @martinprikryl, and possibly @codesquid.

**Comment by codesquid** [comment]
Thanks, I've added support for these new facts to FileZilla.

**Comment by smartftp** [comment]
We have added support for them as well. Thanks.

**Comment by Castaglia** [comment]
Now available in the master branch.

**Comment by martinprikryl** [comment]
I have added this to WinSCP too:
https://winscp.net/tracker/show_bug.cgi?id=1481
Thanks!

The IANA link in the original post, is wrong. It should be:
https://www.iana.org/assignments/os-specific-parameters/os-specific-parameters.xhtml
