### ISSUE TITLE
Support FTP RANG command

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#351]
Consider adding support for the FTP `RANG` command, as defined in this [IETF Draft](https://tools.ietf.org/html/draft-bryan-ftp-range-08).

This would better support use cases where FTP clients simply want to download a subset of the bytes for a file, _without_ needing to *abort* the data transfer; see the `libcurl` thread on this topic ([here](https://curl.haxx.se/mail/lib-2016-11/0045.html) and [here](https://curl.haxx.se/mail/lib-2016-11/0089.html); this feature might thus be of interest to @bagder, @codesquid, and @smartftp).

**Comment by smartftp** [comment]
Support for the RANGE command has been implemented in SmartFTP a while ago.

**Comment by bagder** [comment]
Yes, if servers actually start to implement this command I think it'll be interesting for curl to support it. And perhaps not by chance, the RANGE draft features my name as a co-author. =)

**Comment by Castaglia** [comment]
Fixed in master.
