### ISSUE TITLE
Support Redis for caching

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#354]
ProFTPD currently supports caching via `memcached`; various modules then make use of that caching API as they see fit (_e.g._ `mod_ban`, `mod_tls`, _etc_).  In addition to `memcached`, ProFTPD should also support other caching services such as Redis, using _e.g._ the [hiredis](https://github.com/redis/hiredis) C library.

**Comment by Castaglia** [comment]
In addition to acting as a _cache_, Redis could also be used for logging.  Imagine, for example, logging/writing records to Redis instead of (or in addition to) a SQL database.  Initially the record being written would be a stringified JSON object; further refinements would come along later.

**Comment by dup2** [comment]
+1, very interesting

**Comment by Castaglia** [comment]
And done; merged into master.
