### ISSUE TITLE
SFTP with LDAP users

### ISSUE THREAD

**Issue by heruan** [proftpd/proftpd#367]
I'm on 1.3.5 (Ubuntu 14.04) and I'm trying to set up a SFTP server. This is my config at `/etc/proftpd/conf.d/sftp.conf`:

```
<IfModule mod_sftp.c>
	<VirtualHost 82.193.38.167>
		SFTPEngine on
		SFTPLog /var/log/proftpd/sftp.log
		Port 2222
		SFTPHostKey /etc/ssh/ssh_host_rsa_key
		SFTPHostKey /etc/ssh/ssh_host_dsa_key
		SFTPAuthorizedUserKeys file:~/.sftp/authorized_keys
		SFTPCompression delayed
		MaxLoginAttempts 6
		DefaultRoot ~
	</VirtualHost>
</IfModule>
```

It works for local accounts, but for LDAP accounts I get:
```
mod_sftp/0.9.9[6440]: no account for user 'ldaptestuser' found
```

But I can successfully log on the machine via SSH with `ldaptestuser`.

**Comment by Castaglia** [comment]
When you say:

> I can successfully log on the machine via SSH with `ldaptestuser`

Do  you mean that you can use that user, defined in LDAP, to login via OpenSSH?  I'm not sure what you mean by "via SSH" there.

Also, do you have any `mod_ldap` configuration directives in the rest of your `proftpd.conf`?  Or are you assuming that something like LDAP integration via PAM  modules would be enough?

**Comment by heruan** [comment]
I meant that I can login via OpenSSH, or the machine local console. And no, I do not have any LDAP config in ProFTPd, since the users are already valid machine accounts.

But I think I have found how to make it work: it seems uncommenting `PersistentPasswd off` from the global config let LDAP users to login successfully. What does turning this off imply?

**Comment by Castaglia** [comment]
When a client authenticates, ProFTPD will open the `/etc/passwd` file to ensure that the client-requested user name exists.  That file becomes inaccessible _if_ the session is chrooted, but ProFTPD may still need access to it, after chroot, for mapping UIDs to names (_e.g._ for directory listings).  Thus ProFTPD will "persistently" keep that `/etc/passwd` file open.

However, on systems where NSS/PAM modules are used, the functions used to access `/etc/passwd` are delegated to other code (such as for accessing an LDAP directory); ProFTPD keeping that "persistently" open causes issues for such delegating configurations.  And that's probably why using

    PersistentPasswd off

works in your case.

Glad to hear that you got things working!
