### ISSUE TITLE
ClamAV & Proftpd behavior (Enhancement?)

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#382]
### What I Did

Use ClamAv with Proftpd

    <IfModule mod_clamav.c>
       ClamAV       on
       ClamServer   {{LOCALIPV4}}
       ClamPort     3310
       ClamStream   on
    </IfModule>

### What I Expected/Wanted

Everything works as documented. However, it would be ideal if in the event `clamd` has failed (crashed or other) that Proftpd would continue operation with the processing of files through `clamd`. If `clamd` fails then proftpd rejects file transfers. Ideally an option would exist to process files even though `clamd` is not available. While it creates risk, it does not create a hard dependency on `clamd` always running.

### ProFTPD Version and Configuration

The build is using the latest commit (as of 01/06/2016)

**Comment by Castaglia** [comment]
This is probably something for @jbenden to take a look at.  Perhaps the `ClamFailsafe` directive in the current [`mod_clamav`](https://github.com/jbenden/mod_clamav) is what is needed, _i.e._:

    ClamFailsafe off

**Comment by tspicer** [comment]
Ah, ok! I was not sure who was the lead in this context. I'm not using that directive so it should default to off. I guess this should (bypass) clamd as described. However, killing clamd will lock/block uploads. I send to @jbenden . Thanks!

**Comment by jbenden** [comment]
With the `ClamFailsafe off` option, the upload is suppose to succeed on upload; whether or not `Clamd` successfully scanned the file.

If the connection to `Clamd` was severed, `mod_clamav` must (and should) auto-reconnect.

If this behavior is not observed, please sent a complete transcript from `ProFTPd` running at debug level 10.  This will assist me in debugging any reported problems.

**Comment by tspicer** [comment]
Thanks for the reply. I will test that option. 

The use case is that clamd may exit/crash for an extended period of time. It will reconnect once it is back up. However, it is the period while it was down which is the concern. It could mean that transfers fail for that window that clamd is not running. If ClamFailsafe off solves for that, I will test that and report back. Thanks for clarifying!

**Comment by jbenden** [comment]
*Side note*: It really is not ideal that `Clamd` is down for extended periods and using the option I mentioned. The reason is because viruses and other unwanted uploads ***WILL*** be accepted. So the option sort of defeats the use of `mod_clamav` altogether.

I **highly** recommend you configure a cluster of `Clamd` instances to survive any outages; although the setup of this is outside the scope of simple support of `mod_clamav`.

**Comment by tspicer** [comment]
Understood. This is about making sure this use case, however unlikely, is cared for. We have clamd under monitoring, so the chances of this happening should be low. Also, the files being uploaded have been pre-scanned on a local network prior to upload. The us of clamd with Proftpd provides an extra check for the data in transit. It is scanned again on the other side of the transfer too.

**Comment by tspicer** [comment]
@jbenden, I setup a test cluster as you described. There are 2 clamd instances sitting behind an ELB.   When I send a file > 9 Mb I will always get the following error:

```
mod_clamav/0.14rc2: Cannot stream file to Clamd socket: 2
```

This only occurs via SFTP, not via FTP. Here is my SFTP block:

```
<IfModule mod_sftp.c>
  <VirtualHost 0.0.0.0>

    Port                                2222
    SFTPEngine                   on
    CreateHome                  on 711 skel /etc/proftpd/skel dirmode 700 uid 2001 gid 2001
    SFTPAuthMethods        publickey password
    SFTPCryptoDevice        all
    WtmpLog                       off

    SFTPTrafficPolicy          low
    SFTPHostKey                 /etc/ssh/ssh_host_rsa_key
    SFTPHostKey                 /etc/ssh/ssh_host_dsa_key
    SFTPCompression         delayed
    SFTPClientAlive             3 60
    SFTPOptions                 IgnoreSFTPUploadPerms IgnoreSCPUploadPerms IgnoreSFTPSetPerms IgnoreSFTPSetOwners PessimisticKexinit

  </VirtualHost>
</IfModule>
```
When connecting with a file smaller, < 9 Mb via SFTP they will go through. 

I tested with Transmit on the Mac as a client.

**Comment by tspicer** [comment]
@jbenden This is the clam block. I also had tried using something other than the environment variable setting. As I said before, using the host name is will complain/error for all protocols. Using the IP it will work for FTP but seems to have the problems I referenced with SFTP 

```
<IfModule mod_clamav.c>
   ClamAV %{env:CLAMD_STATUS}
   ClamServer %{env:CLAMD_HOST}
   ClamPort 3310
   ClamStream on
   ClamFailsafe off
</IfModule>
```

**Comment by Castaglia** [comment]
Can/should this ticket be moved to [this `mod_clamav`](https://github.com/jbenden/mod_clamav) repo?

**Comment by tspicer** [comment]
I think it can

**Comment by Castaglia** [comment]
OK.  I'll close this ticket, and let @tspicer and @jbenden continue the discussion in the [`mod_clamav`](https://github.com/jbenden/mod_clamav) repo...
