### ISSUE TITLE
Build RPM using proftpd.spec as part of Travis build

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#390]
As part of the Travis build, we should try to build an RPM using the provided `proftpd.spec` file.

@pghmcfc, would you have any specific requests/guidance/suggestions on the `rpmbuild` options you'd like to see used here?

**Comment by pghmcfc** [comment]
I'm not that familiar with travis; which OS platform does/can the build run in?

I think the first thing to try would be to roll a distribution tarball and try to do "rpmbuild -ta proftpd-*.tar.gz" on it, which would use the spec file included in the distribution and try to build source and binary RPMs from it.

**Comment by Castaglia** [comment]
[Travis](https://travis-ci.org/) is a CI server.  You define a `.travis.yml` file in your project, which defines how Travis should run your build.  I think it runs containers (or VMs) for each build.

Installing `rpmbuild` and getting a tarball that looks release-like should be doable; are there any other `rpmbuild` commands (options, _etc_) that we'd want to do as a default?  The goal (right now, anyway) would be to include this `rpmbuild` step as part of the CI job, to ensure that the provided `.spec` file _does_ work.  Later, we'd add in steps that check that the built `.rpm` has what is expected/wanted.

**Comment by pghmcfc** [comment]
To keep things simple, I think you first want to check that a "default build" with no options works. After that, maybe move on to try ones with added functionality like LDAP/database support.

In addition to rpmbuild, you'll need to install:
 * pam-devel
 * ncurses-devel
 * zlib-devel
 * libacl-devel
 * libcap-devel                                                       
  * gcc

Those were all I needed to install to get "rpmbuild -ta proftpd-1.3.5d.tar.gz" to work on a clean CentOS7 box, though the versioning of the resulting packages (proftpd-1.3.5-0.1.d.el7.centos) could have been better (I'd think proftpd-1.3.5d-1.el7.centos would have been the desired version).

**Comment by Castaglia** [comment]
Hrm.  This may be a little more complicated than I'd expected at first; the Travis CI environment is Ubuntu-based.  This makes the issue I'd encountered harder to address:
```
$ sudo rpmbuild -ta proftpd-1.3.6rc5.tar.gz
error: Failed build dependencies:
	gettext is needed by proftpd-1.3.6-0.1.rc5.x86_64
	pkgconfig is needed by proftpd-1.3.6-0.1.rc5.x86_64
	pam-devel is needed by proftpd-1.3.6-0.1.rc5.x86_64
	ncurses-devel is needed by proftpd-1.3.6-0.1.rc5.x86_64
	zlib-devel is needed by proftpd-1.3.6-0.1.rc5.x86_64
	libacl-devel is needed by proftpd-1.3.6-0.1.rc5.x86_64
	libcap-devel is needed by proftpd-1.3.6-0.1.rc5.x86_64
```
However, it looks like it _might_ be still possible, by running _e.g._ [CentOS Docker containers on Travis](https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/) to do this build.

**Comment by pghmcfc** [comment]
Looks a bit convoluted but should work OK once it's set up.

**Comment by Castaglia** [comment]
This is now done, merged into master.
