### ISSUE TITLE
TLS session ticket rotation appears to cause issues via logrotate

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#404]
See [this closed issue](https://github.com/proftpd/proftpd/issues/185#issuecomment-276119979).

**Comment by Castaglia** [comment]
@licaon-kter, I'm attempting to reproduce the "crash" locally by compiling the latest ProFTPD code from the master branch, including the `mod_tls` module, and manually sending `SIGHUP` to simulate what `logrotate` does.  So far, no "crash" behavior noticed -- but perhaps I'm not looking at the same place/way you are?  What "crashy" behaviors are you noticing, specifically?

**Comment by Castaglia** [comment]
I've merged/committed the above change, @licaon-kter.  But I'll keep this issue open, until you can confirm whether that addresses the issue you saw?

**Comment by licaon-kter** [comment]
After the HUP netstat would not report proftpd listening on port 21, and it crashed with: https://gist.github.com/licaon-kter/25de0405f4d0bd0ae8147bfaf3790faa

Pulled 450d2dd7746186e05594d744379ec9d814807fb7 directly and looks like it's ok now.

Thanks for the quick fix

**Comment by Castaglia** [comment]
Great, thanks for the confirmation of the fix, and description of how it manifested for you.
