### ISSUE TITLE
SFTP not honouring MaxStoreFileSize properly

### ISSUE THREAD

**Issue by warpspeed6** [proftpd/proftpd#429]
### What I Did

MaxStoreFileSize	        2 Mb

### What I Expected/Wanted

ProFTPd to log below every time a 5M file is transferred, like below
mod_sftp/0.9.9[10969]: error writing 32768 bytes to '/gentoo_root.img5': File too large (MaxStoreFileSize 2097152 exceeded)

But It only honours for overwrites. The traces show it honours in expected.txt and then doesnt in unexpected.txt

anshu@warpy:~$ sftp anshusftp@anshu-sftp.syd.dev.xxxxx.com 
Connected to anshu-sftp.syd.dev.xxxxx
[conffile.txt](https://github.com/proftpd/proftpd/files/789062/conffile.txt)
[Expectedtrace.txt](https://github.com/proftpd/proftpd/files/789061/Expectedtrace.txt)
[UnExpectedtrace.txt](https://github.com/proftpd/proftpd/files/789063/UnExpectedtrace.txt)

.com.
sftp> rm gentoo_root.img5 
Removing /gentoo_root.img5
sftp> ls gen*
Can't ls: "/gen*" not found
sftp> put gentoo_root.img5
Uploading gentoo_root.img5 to /gentoo_root.img5
gentoo_root.img5                                                                                                                                           100% 5120KB   5.0MB/s   00:00          --->This should break
sftp> put gentoo_root.img5
Uploading gentoo_root.img5 to /gentoo_root.img5
gentoo_root.img5                                                                                                                                             0%   32KB  32.0KB/s   02:39 ETA
Couldn't write to remote file "/gentoo_root.img5": Failure     -> Breaks now (and at every second attempt if file not removed)
sftp> 

Remove the file and it uploads again
sftp> rm gentoo_root.img5
Removing /gentoo_root.img5
Couldn't delete file: No such file or directory
sftp> put gentoo_root.img5
Uploading gentoo_root.img5 to /gentoo_root.img5
gentoo_root.img5                                                                                                                                           100% 5120KB   5.0MB/s   00:01        ->Should break
sftp> 

### ProFTPD Version and Configuration

[root@fapisftp-i-xxxxx.dev log]# proftpd -V
Compile-time Settings:
  Version: 1.3.5d (maint)
  Platform: LINUX [Linux 4.4.19-29.55.amzn1.x86_64 x86_64]
  Built: Tue Feb 14 2017 00:23:40 UTC
  Built With:
    configure  '--host=x86_64-redhat-linux' '--build=x86_64-redhat-linux' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/var/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-nls' '--enable-openssl' '--enable-shadow' '--with-lastlog' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with-pkgconfig=lib64/pkgconfig' '--with-shared=mod_auth_pam:mod_ban:mod_ctrls_admin:mod_exec:mod_facl:mod_load:mod_quotatab:mod_quotatab_file:mod_quotatab_radius:mod_quotatab_sql:mod_radius:mod_ratio:mod_readme:mod_rewrite:mod_shaper:mod_site_misc:mod_sql:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_sql_passwd:mod_sql_postgres:mod_tls:mod_tls_shmcache:mod_proxy_protocol:mod_ifsession' 'build_alias=x86_64-redhat-linux' 'host_alias=x86_64-redhat-linux' 'CFLAGS=-O2 -g' 'CXXFLAGS=-O2 -g'

  CFLAGS: -O2 -g -Wall
  LDFLAGS: -L$(top_srcdir)/lib  -L/usr/lib64/mysql -L/usr/lib64/pgsql92
  LIBS: -lacl  -lssl -lcrypto -lssl -lcrypto -lcap -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/run/proftpd/proftpd.pid
    Scoreboard File:
      /var/run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (FIPS enabled)
    - PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by warpspeed6** [comment]
Environment is:
Ubuntu Client->EC2->S3FS<->S3  (with RDS Auth)

**Comment by Castaglia** [comment]
What does your `SFTPLog` file show?

**Comment by Castaglia** [comment]
See also [this forums post](https://forums.proftpd.org/smf/index.php/topic,11942.0.html) on the same topic.  Looks like I'll need to add this as a FAQ to the `mod_sftp` docs.

**Comment by warpspeed6** [comment]
Checked the post. Will get the SFTPLog today. From what I understand, STOR should be blocked if File size is bigger than MaxStoreSize but it happens in alternate events. :/  
The write at server shows more than allowed file size. Will get back to you soon.

**Comment by Castaglia** [comment]
Any updates/findings on this?

**Comment by warpspeed6** [comment]
FAQ was applicable. We decided not to go with this path.
Thanks again :)

Cheers!!
Anshu
