### ISSUE TITLE
Refactor mod_sftp for use as API

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#435]
The `mod_sftp` module provides an implementation for SSH2 and for the SFTP and SCP protocols.  Other modules (_e.g._ `mod_proxy`) could benefit from making more in-depth re-use of those implementations, for creating things like an SFTP _client_.

The work, then, is to modify the existing `mod_sftp` code to allow for modules to use the API directly (which involves [installing the `mod_sftp` headers](https://github.com/proftpd/proftpd/tree/sftp-install-headers)), and for using them as both client and server roles.

**Comment by aderumier** [comment]
Hi, any news ?

**Comment by Castaglia** [comment]
@aderumier no updates yet, unfortunately.  I've been concentrating on other features/issues of late.

**Comment by uid0gid0** [comment]
Have you had any chance to look at this? I'm looking forward to the opportunity to use mod_proxy for reverse proxying sftp/scp

**Comment by nikkonix** [comment]
Any news  ?

**Comment by Castaglia** [comment]
The next step, now that we install the `mod_sftp` headers, is to refactor the `mod_sftp` code into an installable library, that other modules (such as `mod_proxy`) may use.  Some bits of the `mod_sftp` code may not be suitable for use in this library, and other parts will need some refactoring to remove any assumptions, references to global variables, _etc_.

**Comment by Castaglia** [comment]
With https://github.com/Castaglia/proftpd-mod_proxy/issues/56 being addressed, using a different approach than I'd anticipated when I first opened _this_ ticket, I'm now going to close this.  The main use case (SSH/SFTP support in `mod_proxy`) has been accomplished.
