### ISSUE TITLE
Add configuration option to support scrypt derived keys that are not 32 bytes

### ISSUE THREAD

**Issue by btorellALTA** [proftpd/proftpd#454]
### What I Did

I was attempting to set up ProFTPD to authenticate against our MySQL database, delighted to see that ProFTPD supported passwords hashed via scrypt. After compiling ProFTPD and linking it with libsodium, I set all the relevant options, but authentication was still failing. After some investigation, I discovered that when generating scrypt keys to compare against the ciphertext, ProFTPD assumes the key is always going to be 32 bytes long. However, our keys in our database are 64 bytes long (Python default). RFC 7914 allows for scrypt derived keys to have an adjustable length, and libsodium's implementation supports this. I am uncertain as to why ProFTPD assumes and requires a derived key length of 32 bytes. Re-compiling ProFTPD and changing `SCRYPT_HASH_SIZE` in mod_sql_passwd.c to `64` fixes the issue.

### What I Expected/Wanted

I expected a SQLPassword configuration option available to specify what my key length is for ProFTPD to compare against, or a rationale provided as to why the 32-byte length is hard-coded/recommended.

### ProFTPD Version and Configuration

Compile-time Settings:
  Version: 1.3.6rc4 (devel)
  Platform: LINUX [Linux 4.4.0-31-generic x86_64]
  Built: Mon Mar 13 2017 17:28:21 EDT
  Built With:
    configure  '--enable-openssl' '--enable-dso' '--enable-ctrls' '--enable-nls' '--enable-sodium' '--sysconfdir=/etc/proftpd' '--with-modules=mod_ldap:mod_tls:mod_sql:mod_sql_mysql:mod_sql_passwd:mod_sftp' '--with-includes=/usr/include/sodium' '--with-libraries=/usr/lib/x86_64-linux-gnu'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib  -rdynamic -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS:  -lssl -lcrypto -lsodium -L$(top_srcdir)/lib/libcap -lcap  -lm -lmysqlclient -lz  -lssl  -lldap -llber  -lcrypto -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    + Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
Fair question.  Do you think it would be more admin-friendly if `mod_sql_passwd` supported only a small range of scrypt key lengths, _e.g._ 32-, 64-, 128 bytes in length, or was completely configurable?

**Comment by Castaglia** [comment]
This should now be fixed in master.  For your use case, you should now be able to use:

    <IfModule mod_sql_passwd.c>
      ...
      SQLPasswordScrypt 64
      ...
    </IfModule>

in your ProFTPD configuration, to produce/use 64-byte Scrypt hashes.  Thanks!

**Comment by btorellALTA** [comment]
Thanks!
