### ISSUE TITLE
Support the chacha20-poly1305@openssh.com SSH cipher

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#456]
The `mod_sftp` module should implement support for the ["chacha20-poly1305@openssh.com"](https://tools.ietf.org/html/draft-josefsson-ssh-chacha20-poly1305-openssh-00) cipher, for performance and interoperability.

**Comment by dak-csis** [comment]
Just a suggestion, it should (as far as is possible and practical) support all the ssh2 ciphers. Especially the hardware accelerated ones.

I'm seeing great performance differences between OpenSSH mod_sftp and proftpd sftp performance, not in favor of proftpd.

**Comment by Castaglia** [comment]
This has been implemented in the master branch now.
