### ISSUE TITLE
wish : timeoutlogin should possibly be used by mod_ban

### ISSUE THREAD

**Issue by jschvartz** [proftpd/proftpd#458]
### What I Expected/Wanted
I noticed numerous connections that just opens, then do nothing (no authentication)
These are finally killed after TimeoutLogin delay.
I would like to ban these adresses (using mod_ban) as i think this is a kind of threat (using as much ports as possible (DDOS?) )

### ProFTPD Version and Configuration
ProFTPD Version 1.3.6rc5

[proftpd.conf.txt](https://github.com/proftpd/proftpd/files/855503/proftpd.conf.txt)

**Comment by Castaglia** [comment]
Are you thinking something like this:

    <IfModule mod_ban.c>
      ...
      BanOnEvent TimeoutLogin ...
    </IfModule>

per the [`BanOnEvent`](http://www.proftpd.org/docs/contrib/mod_ban.html#BanOnEvent) docs?  Or instead are you thinking more of a module like [`mod_loiter`](https://github.com/Castaglia/proftpd-mod_loiter)?

**Comment by jschvartz** [comment]
I did not know **mod_loiter**, seems promising. I'll have a look asap. Thanks.

**Comment by Castaglia** [comment]
Hopefully [this `mod_loiter` feature request](https://github.com/Castaglia/proftpd-mod_loiter/issues/5), now implemented (and documented) can help provide what you want?

**Comment by jschvartz** [comment]
Many thanks, this is exactly what i needed !

**Comment by Castaglia** [comment]
Excellent, I'll consider this ticket as addressed/closed, then.
