### ISSUE TITLE
API Test Issues in 1.3.6

### ISSUE THREAD

**Issue by pghmcfc** [proftpd/proftpd#483]
Some of the API tests are failing for me in 1.3.6. I'll attach a full [build-log.txt](https://github.com/proftpd/proftpd/files/919983/build-log.txt) so you can see what's failing. This is with builds on Fedora/CentOS building in a chroot environment using the "mock" build tool, which I use for all my packaging.

I've already managed to patch around some of the issues, namely:

`fsio_sys_access_dir_test`: unexpectedly able to read files, because the `other` UID/GID used in the test is ''1000'', which on Fedora happens to be the UID for the first real user on the system, and in my case, that's me. I've changed these ids to 99 (`nobody` on Fedora) for my builds, which resolves the problem for me. I think a better fix might include checking that the chosen UID is different from the current UID.

`inet_connect_ipv4_test` and `inet_connect_ipv6_test`: unexpectedly able to connect to local port 80 because I happen to be running a web server. I changed the port to 180, which seems much less likely to be in use judging by the absence of any services listed for that port in my `/etc/services` file.

Other things I haven't patched yet:

Connecting to external services, such as the google nameserver at 8.8.8.8: 
```
api/inet.c:662:F:base:inet_connect_nowait_test:0: Failed to connect to 8.8.8.8#53: Bad file descriptor
```
Haven't figured that out yet but it will be necessary before I build for Fedora proper that I can disable tests that try to make connections to external services, because the Fedora build system blocks all such network access for reasons both of security and to ensure reproducible builds.
```
api/fsio.c:3350:E:base:fs_copy_file_test:0: (after this point) Received signal 11 (Segmentation fault)
api/fsio.c:3374:F:base:fs_copy_file2_test:0: Failed to open '/tmp/prt-fs-src.dat': File exists
```
I think the second of those is a consequence of the first, the file not getting cleaned up at the end of the test. 
```
api/data.c:316:F:base:data_sendfile_test:0: Expected ENOTSOCK (88), got Invalid argument (22)
```
Haven't figured that one out either.

And finally for now, a double-free or heap corruption in the pool test.
```
*** glibc detected *** ./api-tests: double free or corruption (out): 0x0000000000bef4e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75dee)[0x7fb608667dee]
/lib64/libc.so.6(+0x78c80)[0x7fb60866ac80]
./api-tests(free_pools+0x44)[0x40f8a4]
/usr/lib64/libcheck.so.0(+0x52b0)[0x7fb60a71c2b0]
/usr/lib64/libcheck.so.0(srunner_run_tagged+0x9fd)[0x7fb60a71d23d]
./api-tests(main+0xd1)[0x4c06b1]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7fb608610d1d]
./api-tests[0x40ed29]
```
I'm seeing all of these fails (except the sendfile one, which I don't see on CentOS 6) on both CentOS 6 and Fedora Rawhide, which are the oldest and newest builds I'm trying, so I don't think it's anything compiler-specific.

**Comment by Castaglia** [comment]
With [https://github.com/proftpd/proftpd/commit/389cc579bc8d5704f9dcc2fd01ffd6307aee6b2b] being merged to the 1.3.6 branch, does that address most of those issues?  I suspect there may be a few others hiding...

**Comment by pghmcfc** [comment]
The Rawhide build just has the segfaults in the fsio test now:
```
api/fsio.c:3359:E:base:fs_copy_file_test:0: (after this point) Received signal 11 (Segmentation fault)
api/fsio.c:3398:E:base:fs_copy_file2_test:0: (after this point) Received signal 11 (Segmentation fault)
 ```

The CentOS 6 build does the same.

**Comment by Castaglia** [comment]
Are all of these test issues now fixed?

**Comment by pghmcfc** [comment]
Fixed/worked around, yes.

**Comment by Castaglia** [comment]
Great, thanks.  Considering this addressed, then.
