### ISSUE TITLE
Writes to wtmpx are incorrect when compiled in 64bit mode on x86 Solaris

### ISSUE THREAD

**Issue by jiri-k** [proftpd/proftpd#485]
I've compiled proftpd as 64bit program on Solaris 11 (LDFLAGS=-m64;CFLAGS=-m64) and I've found out that the "last" command shows a user is still logged in (using ftp) after the user logs out:
\# last
john      ftp                           Tue Apr 18 16:31   still logged in
...

The problem is in function log_wtmp. Proftpd uses "struct utmpx" when writing to wtmpx, but the entries in the file are stores as "struct futmpx".
These two structures are the same when compiling a program in 32bit mode but differ in 64bit mode.
The problem is already corrected when building on SPARC, where futmpx is used.

**Comment by jiri-k** [comment]
I've created pull request #486 to address this issue.

**Comment by Castaglia** [comment]
Fix merged to master, and [backported to 1.3.6 branch](https://github.com/proftpd/proftpd/commit/105f7e33d9e9d695261ecfd0a7083eed50b99add).  Thanks!
