### ISSUE TITLE
proftpd.org down

### ISSUE THREAD

**Issue by clanstyles** [proftpd/proftpd#488]
Looks like proftpd.org is down, including ftp.proftpd.org

**Comment by Castaglia** [comment]
How are you checking?  Both `www.proftpd.org` and `ftp.proftpd.org` are accessible for me; also see http://downforeveryoneorjustme.com/proftpd.org.

**Comment by Castaglia** [comment]
Any luck/update on this?

**Comment by clanstyles** [comment]
Hey @Castaglia I had intended on responding earlier that day and spaced out. It was down for about an hour right when I posted that. I have an Ansible playbook that downloads ProFTP from the FTP server. All VMs were having connectivity issues during that period. I also verified the short outage with isitup.

It seems to be working right now. I don't have anything else to add.

Thank you and I love the Dexter icon!

**Comment by Castaglia** [comment]
Thanks!  And I'm glad to hear that things are working again for you.
