### ISSUE TITLE
Support syntax checks on AuthUserFiles, AuthGroupFiles on startup

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#490]
To help catch any possible syntax errors in configured `AuthUserFiles` and `AuthGroupFiles`, ProFTPD should perform, on startup/restart, a basic syntax check of each entry in these files.  This can help to debug/detect any badly formatted files early.

These files could possibly be large, so such syntax checks should be configurable via some `Option` directive.

**Comment by Castaglia** [comment]
If syntax errors *are* detected in the configured files, `mod_auth_file` should _log_ about them (_e.g._ at the `WARNING` log level), but *not* stop the server.  Consider the case where ProFTPD is regularly restarted via `SIGHUP`, by a program like `logrotate`.  It would be unexpected if the server died "randomly" due to such a syntax error.  So the best (and most appropriate behavior in this case, IMHO) is to detect and log the issue.

**Comment by Castaglia** [comment]
Part of this should involve refactoring the existing [lib/pwgrent.c](https://github.com/proftpd/proftpd/blob/master/lib/pwgrent.c) code into `mod_auth_file` proper; those routines are very similar to ones we'd want to use for performing such syntax checks, albeit with built-in error accumulators for logging.

**Comment by Castaglia** [comment]
See also this [forums thread](https://forums.proftpd.org/smf/index.php/topic,12270.0.html), where a syntax check of the `AuthGroupFile` on startup would have helped provide more specific info earlier in the debugging process.

**Comment by Castaglia** [comment]
What if the `-t/--configtest` command-line option functionality could be extended to perform these `AuthUserFile`, `AuthGroupFile` syntax checks?

**Comment by deba12** [comment]
Sounds really good. I like it.

**Comment by Castaglia** [comment]
I ended going with an `AuthFileOption` for this, given that `-t/--configtest` isn't easily conveyed to modules.

To perform a syntax check on the `AuthUserFile`, `AuthGroupFile`, then, one would use:
```
AuthFileOptions SyntaxCheck
AuthUserFile /path/to/ftpd.passwd
AuthGroupFile /path/to/ftpd.group
```
Any syntax issues found will cause ProFTPD to log the issues, and fail to start up.

**Comment by Castaglia** [comment]
Fixed in master.
