### ISSUE TITLE
mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

### ISSUE THREAD

**Issue by pghmcfc** [proftpd/proftpd#501]
I get this every time ProFTPD (1.3.6) starts:

proftpd: 2017-05-08 09:32:27,240 ftp.example.com proftpd[xxxx]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

Looks similar to an earlier report:
http://marc.info/?l=proftpd-devel&m=147330228924766&w=2

It doesn't seem to stop ftpdctl from working though:
```
# ftpdctl lsmod
ftpdctl: Loaded Modules:
ftpdctl:   mod_core.c
ftpdctl:   mod_xfer.c
ftpdctl:   mod_rlimit.c
ftpdctl:   mod_auth_unix.c
ftpdctl:   mod_auth_file.c
ftpdctl:   mod_auth.c
ftpdctl:   mod_ls.c
ftpdctl:   mod_log.c
ftpdctl:   mod_site.c
ftpdctl:   mod_delay.c
ftpdctl:   mod_facts.c
ftpdctl:   mod_dso.c
ftpdctl:   mod_ident.c
ftpdctl:   mod_readme.c
ftpdctl:   mod_auth_pam.c
ftpdctl:   mod_tls.c
ftpdctl:   mod_memcache.c
ftpdctl:   mod_cap.c
ftpdctl:   mod_ctrls.c
ftpdctl:   mod_lang.c
ftpdctl:   mod_ctrls_admin.c
ftpdctl:   mod_vroot.c
ftpdctl:   mod_ban.c
ftpdctl:   mod_qos.c
```

**Comment by pghmcfc** [comment]
And I don't get the error message if I manually remove `/run/proftpd/proftpd.sock` before starting ProFTPD.
Curiously, if I enable trace logging for `ctrls`, I see the "binding" message but not the error message that should also appear in the trace log. It's as if there's two calls to `ctrls_listen`, one before trace logging is enabled (and which fails), and another afterwards (which succeeds).

**Comment by pghmcfc** [comment]
Another point of interest: I get the same message if I do "proftpd --configtest".

**Comment by Castaglia** [comment]
Is this on an SELinux system?  I thought I'd seen some RedHat bug report about SELinux interfering with these Unix domain sockets...

**Comment by pghmcfc** [comment]
That was one of my first thoughts. However, I get the same message in permissive mode, and it's usual with SELinux denials to get "Operation not permitted" rather than "No such file or directory".

**Comment by pghmcfc** [comment]
Here's an strace:
```
# strace -e open,unlink,bind /usr/sbin/proftpd --configtest
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libattr.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libnsl.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libcrypt.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libacl.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libcap.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libmemcached.so.11", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libmemcachedutil.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libssl.so.10", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libcrypto.so.10", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libpam.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libfreebl3.so", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libsasl2.so.3", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libgssapi_krb5.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libkrb5.so.3", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libcom_err.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libk5crypto.so.3", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libaudit.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libkrb5support.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libcap-ng.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libselinux.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libpcre.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/etc/pki/tls/legacy-settings", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
Checking syntax of configuration file
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 3
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 4
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 4
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 4
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 3
open("/etc/services", O_RDONLY|O_CLOEXEC) = 3
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 3
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 4
bind(4, {sa_family=AF_UNIX, sun_path="/run/proftpd/test.sock"}, 110) = 0
unlink("/run/proftpd/test.sock")        = 0
open("/etc/pki/tls/openssl.cnf", O_RDONLY) = 4
bind(4, {sa_family=AF_UNIX, sun_path="/run/proftpd/proftpd.sock"}, 110) = -1 EADDRINUSE (Address already in use)
2017-05-09 19:32:30,619 ftp.example.com proftpd[32363]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
```
So there's two binds with an intervening unlink.

**Comment by pghmcfc** [comment]
OK, so I wasn't looking closely enough there and I think I can see what's going on now.

The first `bind()` is the run-time check in `src/ctrls.c` using `test.sock` to see if the platform identifies a `sockfd` as `S_ISFIFO` or `S_ISSOCK`, and is quite irrelevant to the problem.

What happens next is that `ctrls_init` is called as part of the module initialization. This does a `ctrls_listen` without doing `PRIVS_ROOT` and without requesting that the existing socket be unlinked. This is where the error comes from in the event that the socket already exists. `ctrls_init` then registers `ctrls_postparse_ev` as a callback for `core.postparse`.

When the `core.postparse` event is triggered after config parsing, `ctrls_postparse_ev` then does `PRIVS_ROOT` and calls `ctrls_listen` again, this time with the unlink flag set. This works, and is why `ftpdctl` still works despite the error message from the previous `bind` attempt.

I think the reason that this error message has only started showing up in the last year or so is that it was effectively only added in commit f2a7be92018dda20e260c37bfedaef2efe2ad3b5 in February 2016.

My question is now: what is the purpose of the call to `ctrls_listen` in `ctrls_init`? Possibly a hangover from a older approach that never got deleted?

**Comment by Castaglia** [comment]
That sounds right; I'll need to go back through the changelog when I have some time a little later.  But I seem to recall that the postparse handling code was, at some point, *not there*, and thus we wanted to ensure that the process listening even if `ControlsSocket` was not explicitly configured in the config file.

**Comment by Castaglia** [comment]
Yes, I think https://github.com/proftpd/proftpd/commit/c07da85d7d48c093dc1dea0eabf0569be42f2a57#diff-fbdaffa6c6b9aa7ebf0c666887dddd04 introduced this behavior, by adding this to the postparse event handler.

**Comment by pghmcfc** [comment]
Getting rid of the `ctrls_listen` in `ctrls_init` works for me. I can still use `ftpdctl` after starting the daemon, and again after a `kill -HUP`.

**Comment by Castaglia** [comment]
Merged to master, and backported to 1.3.6 branch.

**Comment by chrcoluk** [comment]
I confirm this problem and using the latest version of ProFTPD in the ports tree. OS FreeBSD.

Does not occur on pre 1.3.6.

**Comment by Sashan** [comment]
Solaris sees the same problem too.

**Comment by ZerooCool** [comment]
Hi, i use Debian SID, i have the same.
log from syslog :
mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

Or, with sudo proftpd --configtest

Checking syntax of configuration file
proftpd[32520]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
proftpd[32520]: processing configuration directory '/etc/proftpd/conf.d/'
Syntax check complete.

**Comment by adeleglise** [comment]
Can confirm issue is still here in FreeBSD 11.2, latest ports.

**Comment by tkalfaoglu** [comment]
The error still exists for me... 
# rpm -qa|grep proftp
psa-proftpd-1.3.6b-13.el7.art.x86_64

# tail -f messages|grep prof
Dec 23 16:07:04 proftpd[49918]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
Dec 23 16:09:56 proftpd[51302]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

**Comment by ZerooCool** [comment]
Same with debian buster 10

sudo dpkg -l| grep proftpd
ii  proftpd-basic        1.3.6-6       amd64        Versatile, virtual-hosting FTP daemon - binaries

More info :

I manage to connect to my FTP from my internet box from home.
I have an error from the wifi of my mobile phone (with the operator SFR)
The investigation brings me back to this issue:

# From FileZilla :
```
Statut :	Connexion à 139.99.173.195:21...
Statut :	Connexion établie, attente du message d'accueil...
Réponse :	220 ProFTPD Server (Debian) [::ffff:139.99.173.195]
Commande :	AUTH TLS
Réponse :	502 AUTH TLS exécuté avec succès
Commande :	AUTH SSL
Erreur :	Impossible de lire depuis le socket : ECONNRESET - Connexion réinitialisée par un pair
Erreur :	Impossible d'établir une connexion au serveur
```

# Erreur from log file :
```
2020-02-26 16:18:10,383 mod_tls/2.7[6537]: TLS/TLS-C requested, starting TLS handshake
2020-02-26 16:18:10,753 mod_tls/2.7[6537]: unable to accept TLS connection: system call error: [104] Connexion ré-initialisée par le correspondant
2020-02-26 16:18:10,753 mod_tls/2.7[6537]: TLS/TLS-C negotiation failed on control channel
```

```
# This socket error raised me to this previously reported error:
sudo proftpd --configtest
Checking syntax of configuration file
proftpd[16691]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
```

```
# The following folder is supposed to contain the proftpd.sock file according to the configuration of ProFTPd from the conf file.
# It is currently empty when I consult it.
# I manually create the file but that does not change this error:
cd
/var/run/proftpd
sudo touch proftpd.sock
# A proftpd.sock file already exists in the directory /run/
# A proftpd.sock file already exists in the directory /run/proftpd/
```

```
# I am trying to display the list of ProFTPd modules:
sudo ftpdctl lsmod
ftpdctl: error contacting server using '/run/proftpd.sock': Connection refused
```

```
# I am trying to trace the order for more information.
sudo apt install strace
strace -e open,unlink,bind,close /usr/sbin/proftpd --configtest

close(1022)                             = -1 EBADF (Mauvais descripteur de fichier)
close(1023)                             = -1 EBADF (Mauvais descripteur de fichier)
close(-1)                               = -1 EBADF (Mauvais descripteur de fichier)
Checking syntax of configuration file
close(-1)                               = -1 EBADF (Mauvais descripteur de fichier)
close(3)                                = 0
...
close(4)                                = 0
bind(4, {sa_family=AF_UNIX, sun_path="/run/test.sock"}, 110) = -1 EACCES (Permission non accordée)
close(4)                                = 0
unlink("/run/test.sock")                = -1 ENOENT (Aucun fichier ou dossier de ce type)
bind(4, {sa_family=AF_UNIX, sun_path="/run/proftpd.sock"}, 110) = -1 EADDRINUSE (Adresse déjà utilisée)
close(4)                                = 0
2020-02-26 22:51:48,094 vps178370 proftpd[22647]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
close(4)                                = 0
close(6)                                = 0
...
close(5)                                = 0
2020-02-26 22:51:48,231 vps178370 proftpd[22647]: mod_ctrls/0.9.5: unable to open ControlsLog '/var/log/proftpd/controls.log': Permission non accordée
2020-02-26 22:51:48,231 vps178370 proftpd[22647]: fatal: ControlsLog: unable to open '/var/log/proftpd/controls.log': Aucun fichier ou dossier de ce type on line 126 of '/etc/proftpd/proftpd.conf'
+++ exited with 1 +++
```

Still researching to figure out what's wrong.
