### ISSUE TITLE
Support MODE Z even for FTPS sessions

### ISSUE THREAD

**Issue by dup2** [proftpd/proftpd#505]
### What I Did

We enabled mod_deflate and see errors "Unable to handle MODE Z at this time" (from a error log handle configured via SQLLog) and "declining MODE Z (RFC 2228 mechanism 'TLS' in effect)" in the log configured via DeflateLog)

### What I Expected/Wanted

I've seen this already in the documentation where it says:

> Second, the internal ProFTPD APIs that mod_deflate uses are the same APIs that mod_tls uses; and that API does not currently handle chaining together of registered handlers

Any plans to support this chaining? 

### ProFTPD Version and Configuration

1.3.5d (maint) on Linux with mod_tls and mod_deflate.

**Comment by Castaglia** [comment]
Which FTPS client are you using?  I just tried this, on a patch I'm working on to enable this feature, using `lftp` -- but it failed:
```
---> MODE Z
<--- 200 OK
---> EPSV
<--- 229 Entering Extended Passive Mode (|||19683|)
---- Connecting data socket to (127.0.0.1) port 19683
---- Data connection established
---> LIST
<--- 150 Opening ASCII mode data connection for file list
**** SSL_connect: wrong version number
---- Closing data socket
<--- 226 Transfer complete
---- Closing control socket
ls: Fatal error: SSL_connect: wrong version number
```
This suggests that in the case of `lftp`, at least, _their_ support for `MODE Z` over TLS is not what you would expect, either...

**Comment by Castaglia** [comment]
Fixed in master.

**Comment by dup2** [comment]
Great, thanks for this implementation!
