### ISSUE TITLE
Error compiling mod_tls in master with Alpine 3.6 and libressl

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#530]
### What I Did

Compile with latest commit (master):

PROFTPD_COMMIT="cbd7acaccb2f62062a2c69626f89f700d5b7c272"

It will error on TLS. 

```
mod_tls.c: In function 'ocsp_stale_response':
mod_tls.c:4927:23: error: implicit declaration of function 'ASN1_TIME_diff' [-Werror=implicit-function-declaration]
                 res = ASN1_TIME_diff(&ndays, &nsecs, this_update, next_update);
                       ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [Makefile:31: mod_tls.o] Error 1
make[1]: Leaving directory '/usr/local/proftpd/modules'
make: *** [Makefile:39: modules] Error 2
```

I removed TLS from the build and it compiled ok

Since I'm only using SFTP, it is not a big issue. However, this had not occurred until recently as we are compiled earlier builds from late April/Early May without incident.

Happy to test further to troubleshoot.

**Comment by Castaglia** [comment]
Ah, libressl.  Such a support PITA.   _Sigh_.  I'll see what I can do.

**Comment by Castaglia** [comment]
Should now be fixed in master.
