### ISSUE TITLE
TLSECDHCurve multiple curves

### ISSUE THREAD

**Issue by graxlop** [proftpd/proftpd#534]
Hello,

I would like to request that the TLSECDHCurve directive be able to take multiple curves.

Thanks

**Comment by Castaglia** [comment]
What's the use case that having this feature would support?  What sort of configuration would you like to use, and why?

Providing details this like helps to ensure that the design meets real needs, and to provide a regression test for the requested behavior.

**Comment by graxlop** [comment]
The same as having the option to specify multiple cipher suites. With the current implementation, you're either stuck with a single curve or too many curves.

What happens if one or more of those curves has security issues in the future? Currently, there would be no proper way to mitigate it without relying on a single curve.

The TLSECDHCurve directive should allow something like:

TLSECDHCurve X25519:prime256v1

This allows for the more trusted X25519 curve to be prioritized over P-256, while still maintaining compatibility for those who don't support it.

**Comment by Castaglia** [comment]
Merged to master.
