### ISSUE TITLE
Implement LogFormat variable for data transfer average speed

### ISSUE THREAD

**Issue by graxlop** [proftpd/proftpd#535]
Hello,

I would like to request an additional variable for mod_log that would show the average transfer speed.

Maybe a format like KB/s, MB/s, etc.

Thanks

**Comment by Castaglia** [comment]
Average over what unit of time?  For the overall transfer?  If for the entire transfer, that can easily be computed, by a log post-processor, from the total number of bytes (`%b`) and the transfer time (`%T`).  I'm not sure what value would really be added in having ProFTPD do this...

**Comment by graxlop** [comment]
Yes, for the entire transfer. I find it useful for debugging purposes and it seems like most other FTP server software out there supports this functionality, so I'm sure others would appreciate it as well.

**Comment by Castaglia** [comment]
What other FTP servers have you seen do this, and how?  I admit I don't often see just what other features other FTP servers have...

**Comment by graxlop** [comment]
Pure-FTPd and vsftpd both have this functionality in their logs by default. A quick look at the vsftpd source code shows that they do it like you've described above, taking the transfer size and transfer time.

Here's an example of what vsftpd default transfer log looks like:

Fri Jul 14 06:26:14 2017 [pid 30373] [Username] OK DOWNLOAD: Client "5.5.5.5", "/Folder/Test.file", 537563631 bytes, 6118.22Kbyte/sec

**Comment by Castaglia** [comment]
Seems like a reasonable request.  This will not be added to the fixed `xferlog(5)` format, but I think we can log a message (at `INFO` level) on completion of a file transfer, and supply a `LogFormat` variable for it as well for `ExtendedLog` cases.

**Comment by Castaglia** [comment]
For my reference, pure-ftpd uses "KB/sec" (see [here](https://github.com/jedisct1/pure-ftpd/blob/master/src/ftpd.c#L2753)), whereas vsftpd uses "Kbyte/sec" (see [here](https://github.com/richardcochran/vsftpd/blob/master/logging.c#L369)).  I think ProFTPD uses "KB" elsewhere, so I'll use "KB/sec".

**Comment by Castaglia** [comment]
Implemented in master now.  Thanks!
