### ISSUE TITLE
Support TLSv1.3

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#536]
Start working on updating `mod_tls` to support configurations that want to use TLSv1.3.

**Comment by Castaglia** [comment]
I tested this branch by downloading a snapshot of the OpenSSL code, and building it:

    $ ./config enable-tls1_3

And then building `mod_tls` using that local installation.  I then configured `mod_tls` to _only allow_ TLSv1.3, using:

    TLSProtocol TLSv1.3

And used `openssl s_client` to verify:

    $ openssl s_client -connect 127.0.0.1:2121 -starttls ftp -tls1_3

**Comment by Castaglia** [comment]
Merged to master.

**Comment by gene1wood** [comment]
This was released in version [`1.3.7rc1`](https://github.com/proftpd/proftpd/releases/tag/v1.3.7rc1)
