### ISSUE TITLE
Add LDAPRequireGroup to mod_ldap

### ISSUE THREAD

**Issue by ws0w** [proftpd/proftpd#545]
This is not a problem ,but an enhancement:

I need the ability to a) use LDAP to authenticate users, and b) restrict access to specific directories based on where a user is in a specific LDAP group.

I modified mod_ldap and added a new directive, LDAPRequireGroup. This enabled me to restrict access to specific directories by checking whether the LDAP-authenticated user is in the requiremend LDAP group.

I forked proftpd, and made my modification in the forked repository here:

https://github.com/ws0w/proftpd

**Comment by ws0w** [comment]
Looks like  forked 1.3.5 branch instead of 1.3.6.

**Comment by Castaglia** [comment]
Does access to the directory, in your use case, require that the group come from _LDAP_ specifically_?  If so, why LDAP versus some other authentication data provider/source?  I'm wondering whether this functionality would also apply to groups from SQL databases, Auth files, RADIUS servers, _etc_...

**Comment by ws0w** [comment]
Yes, in my use case the group must come specifically from LDAP. The requirement is to control access to directories based on groups in an existing LDAP ldap database that has been used for this purpose in web applications for many years. LDAP is what is available.

For my current use case, the users must be authenticated from the existing LDAP service and access must be restricted based on memebership in groups defined in that same existing LDAP service.

**Comment by Castaglia** [comment]
OK.  That's a very specific requirement; as such, I am wary of it being used to a broader number of sites.  I.e. would it be worth adding to `mod_ldap`.

Alternatively, it should be possible to achieve this same functionality by having this done as a new module, that you could add to any current (and future) ProFTPD versions.  Would you be interested in writing (or helping write) such a module?

**Comment by ws0w** [comment]
I started to break this function out into a new module, but went with the easier route.

The LDAP Group requirement has a dependency on the LDAP authentication that mod_ldap already does. In order for a new module to use mod_ldap's authentication, mod_ldap would need to be modified to make "ld" and "ldap_authbind_dn" accessible to the new module. Any concerns with that?

Another option would be for the new module to re-implement the LDAP authentication. Then the new module would not depend on mod_ldap at all.

Which sounds better to you? Or perhaps other options?

**Comment by ws0w** [comment]
If we could add a mod_ldap.h file containing these lines:

extern LDAP *ld;
extern char *ldap_authbind_dn;

and modify mod_ldap.c to remove "static" from the declaration of those two variables, I could add the function I need in a separate module without having to re-implement the LDAP authentication.

If you're not willing to accept that, I'll suppose I could copy mod_ldap to a new module and add what I need there.

**Comment by ws0w** [comment]
Can you proved any feedback?

**Comment by ws0w** [comment]
Satisfied requirements with a new module.
