### ISSUE TITLE
Support Redis SELECT for multiple databases

### ISSUE THREAD

**Issue by lon9man** [proftpd/proftpd#550]
### What I Did

we are trying to use mod_redis for gathering info about STOR-ed files onto our FTP-server. 
we have 2 environments: dev and prod. each environment uses different database in Redis-server. 1 - prod, 2 - dev. Redis-server from the box supports command SELECT to choose database (https://redis.io/commands/select).

### What I Expected/Wanted

we saw that mod_redis unable to choose concrete database with command "RedisServer IP[:port] [password]" in config, but it will be very useful to have such functionality. Otherwise we should have multiple Redis-servers, 1 per each environment. But it is more simple to have only 1 Redis-server with several databases in it.

### ProFTPD Version and Configuration

    $ proftpd -V
1.3.7

**Comment by Castaglia** [comment]
I quite agree; an excellent idea!  I'll add this support.

**Comment by oleg-moseyko** [comment]
Very useful option for me

**Comment by Castaglia** [comment]
Fixed in master.  The `mod_redis` docs for the `RedisServer` directive have been updated to show how to configure the database index to select.
