### ISSUE TITLE
Documentation on `mod_sftp_sql` is extremely out of date!

### ISSUE THREAD

**Issue by jmvbxx** [proftpd/proftpd#564]
Every single line of sql code for the MySQL generates an error and I'd like to know if you'd be open to a PR with updated code that works.

Thank you!

**Comment by Castaglia** [comment]
What do you mean by "out of date" exactly?  What're the errors generated?  What version of MySQL are you using?

**Comment by jmvbxx** [comment]
There are two SQL commands for MySQL and neither works on version 5.7. I can happily do a PR with two updated commands that work (the ones I had to use, in fact).

For the first command, `key` is a reserved word and needs to be handled differently and in the second command there's no length associated with `name`.

**Comment by Castaglia** [comment]
I think some of the issues were due to my copy/pasting from my SQLite example (using `TEXT`, for example, rather than `VARCHAR`); that part should be fixed.  Thanks for letting know about about `key` being a keyword.  Hopefully the text is better now?  If so, I'll publish these updates on the ProFTPD website.  Thanks!

**Comment by jmvbxx** [comment]
Thanks @Castaglia! Have you pushed a documentation change, yet?

I'm checking here http://www.proftpd.org/docs/contrib/mod_sftp_sql.html or is there a better place to look?

**Comment by jmvbxx** [comment]
Thanks @Castaglia! Have you pushed a documentation change, yet?

I'm checking here http://www.proftpd.org/docs/contrib/mod_sftp_sql.html or is there a better place to look?

**Comment by Castaglia** [comment]
All of the docs are distributed with the source; see [mod_sftp_sql.html](https://github.com/proftpd/proftpd/blob/master/doc/contrib/mod_sftp_sql.html).  Once the docs look OK there, they might be published to www.proftpd.org, depending on whether the change in question pertains to released features/code or not.

**Comment by Castaglia** [comment]
Ah, got it.  Thanks!  I've just updated the example schema, for MySQL, to use `VARCHAR(256)` for those name columns; that should be small enough for the index, yes?

**Comment by jmvbxx** [comment]
Looks great! I'm going to implement in our infrastructure.

Thanks so much!

**Comment by Castaglia** [comment]
Awesome! I've updated the website version as well now; see [mod_sftp_sql.html](http://www.proftpd.org/docs/contrib/mod_sftp_sql.html).
