### ISSUE TITLE
Dynamic prefix and filter for Redis

### ISSUE THREAD

**Issue by lon9man** [proftpd/proftpd#573]
### What I Did

Hello!

We successfully use mod_redis for saving data about uploaded files into Redis. nextly this data will be processed by several php-workers.

our config partly:
```
RedisEngine on    
RedisLog /var/log/proftpd/redis.log    
RedisServer 127.0.0.1:6379    
LogFormat ftplog "%h %l %u %t \"%r\" %s %b %m %J %f"    
RedisLogOnCommand STOR ftplog
```
### What I Expected/Wanted

Potentially needed enhancement:
1. Key's prefix for saving can be dynamic saying using LogFormat-variables. it can be useful for grouping data by some variables. 
For example (using our config), we want to save data saying using prefix: 
   - "ftplog:%u" for grouping data by username (user1, user2, ...);
   - "ftplog:%m:%u" for grouping data by ftp-command (STOR, DELETE, ...) and username;
   - in any similar way using other variables combinations;

2. Some filter's clauses, which can help to prevent putting into Redis some unneeded events. 
For example, we don't want to save events:
    - where username equals John_Doe;
    - where filename/directory match regex-expression;
    - where bytes_sent more than N bytes;
          ...
    - abstractly saying some filter's boolean-clauses using LogFormat-variables;

Another point for good understanding:
using LogFormat we save logs into MySQL and Redis, nextly our worker use data from both data-storages. In which order do you save this data: 
1. MySql and then Redis
    or
2. Redis and then MySql.
What is the order? 
Simply saying our worker-logic wants to be sure that data already exists in both storages. 

### ProFTPD Version and Configuration

    $ proftpd -V

1.3.7rc1

**Comment by Castaglia** [comment]
Hmm.  These are good requests; I'll try to tackle them individually.  This work will need to wait until I finish Issue #392, as it is directly related.

I can address the last question, about the ordering.  ProFTPD dispatches any kind of event to its modules in "module load order"; last module listed, first module called.

Thus if you do `proftpd -l`, you will see the modules listed in the _reverse order_ of when they would be called.  (And if you are using the `LoadModule` directive to dynamically load modules in your config, then the _last_ module loaded will be the first one called.)  This means that if `mod_redis` appear after `mod_sql` in the `proftpd -l` output (or in your list of `LoadModule` directives), then the logging to Redis will happen _before_ the logging to SQL.  Does that help?

**Comment by Castaglia** [comment]
For the case where you do not want to write data to Redis based on the username, you should be using _e.g._ [`<IfUser>`](http://www.proftpd.org/docs/contrib/mod_ifsession.html#IfUser), like this:

    <IfUser !John_Doe>
      # Only log for users other than John_Doe
      RedisLogOnCommand STOR ftplog
    </IfUser>

However, full-fledge log processing/conditionals will probably not implemented; we do not support that sort of thing for file-based logging, either.  ProFTPD needs to focus on being a file transfer server; sophisticated log post-processing needs should be handled by separate tools/applications designed for that sort of task.

**Comment by lon9man** [comment]
@Castaglia,

> Does that help?
yes, that helps. thanks

**Comment by Castaglia** [comment]
Modules loaded with `LoadModule` will come _after_ the static modules (such as `mod_redis`) in the list; this means, in your case, that the data will probably be written to your SQL database _before_ it is written to Redis.

For your prefix request, does it matter to you if the additional data (via variables) are appended as a _suffix_ to the Redis key, or prepended as a prefix?  You say "prefix", but your example of `ftplog:%u` shows a suffix.  I think the suffix approach would be the most common, yes?

**Comment by lon9man** [comment]
@Castaglia, sorry for the delay.

>  I think the suffix approach would be the most common, yes?
little confused about suffix/prefix :). in our case my example (ftplog:%u) is full redis key's name, which works using mod_redis as LIST. so each json is added into it with the same key (https://drive.google.com/open?id=0B7YxJcgXibf5N1V2eUw5b01hcEU).

abstractly saying we want to create any dynamic redis key using available logformat-variables which looks like:
1. %u:%m:ftplog
2. ftplog:%u:%m
, where **ftplog** - some any static text string (can be another), **%m/%u** - example variables, value for each will be evaluated on runtime.

feel free to send us some another questions. thanks!

**Comment by Castaglia** [comment]
The latest merges to master should help you achieve some of your goals.  You should now be able to use:

    RedisLogOnCommand STOR ftplog ftp:%m:%u

The optional third parameter, now supported, is the Redis key to use, with `LogFormat` variables resolved.

You can also configure the `RedisLogOnCommand` directive within `<Directory>` sections, so that it logs only for files/actions within those directories:

    <Directory /path/to/upload/dir>
      RedisLogOnCommand STOR ftplog ftp:%m:%u
    </Directory>

Could you try out the latest code, see how it better meets your needs now?

**Comment by lon9man** [comment]
@Castaglia, will check!

**Comment by lon9man** [comment]
@Castaglia,
i have checked, it works as we requested! big thanks for your work!

P.S. have tried to use your example with `<Directory>` section, but i need slightly another thing:
we have directories:
```
/ftp/user1
/ftp/user2
...
/ftp/userN
/ftp/blitline
```
our task is to log into Redis all uploads from **userX**-directories EXCEPT **blitline**-directory. in result i have resolved it using  `<IfUser>` section:
```
<IfUser !blitline>
    RedisLogOnCommand STOR redis ftp:%m:%u
</IfUser>
```
but for the deeper understanding tried to resolve it using:

1. some `<Directory>`-section clause, but didn't find applicable way. does exists any?

2. Define/IfDefine section. didn't find workable solution. example:
```
<Directory /ftp/blitline>
    Define DISABLE_LOG
</Directory>

<IfDefine !DISABLE_LOG>
    RedisLogOnCommand STOR redis ftp:%m:%u
</IfDefine>
```
it looks like **Define/IfDefine** can be used only on config-loading and unable to work as runtime-solution.. is it correct?

thanks one more time

**Comment by Castaglia** [comment]
Excellent point.  Let me work on a PR to add a way of explicitly disabling `RedisLogOnCommand`, _e.g._ something like:

    <Directory /path/to/some/dir>
        RedisLogOnCommand none
    </Directory>

Hopefully I can add this today/tomorrow.

**Comment by Castaglia** [comment]
With the latest code in master, you should be able to use something like this:

    <Directory /ftp/user*>
      RedisLogOnCommand STOR redis ftp:%m:%u
    </Directory>

    <Directory /ftp/blitline>
      RedisLogOnCommand none
    </Directory>

Does that work properly as you need now?

**Comment by lon9man** [comment]
Strange, but it doesn't work.
my config:
```
<Directory /home/ftp>
    RedisLogOnCommand STOR redis ftp:%m:%u
</Directory>

<Directory /home/ftp/blitline>
    RedisLogOnCommand none
</Directory>

```
i am testing upload into directories:
```
1. /home/ftp/lon9man    (should be logged)
2. /home/ftp/blitline   (should NOT be logged)
```

in result i see both logged jsons in Redis:
```
1.
{
    "remote_dns": "xx.xx.xx.xx",
    "user": "lon9man",
    "local_time": "2017-09-25 08:11:05 +0000",
    "raw_command": "STOR IMG_20161219_223349.jpg",
    "response_code": 226,
    "bytes_sent": 182521,
    "command": "STOR",
    "command_params": "IMG_20161219_223349.jpg",
    "file": "/home/ftp/lon9man/IMG_20161219_223349.jpg"
}

2.
{
    "remote_dns": "xx.xx.xx.xx",
    "user": "blitline",
    "local_time": "2017-09-25 07:47:37 +0000",
    "raw_command": "STOR IMG_20161219_222629.jpg",
    "response_code": 226,
    "bytes_sent": 695394,
    "command": "STOR",
    "command_params": "IMG_20161219_222629.jpg",
    "file": "/home/ftp/blitline/IMG_20161219_222629.jpg"
}
```
what i can do for you for understanding the reason?

**Comment by Castaglia** [comment]
Well, the configuration you used is _different_ than the one you'd provided as an example.  Specifically, you have the `/home/ftp/blitline` directory as a _subdirectory_ of `/home/ftp`; your earlier examples did *not* show this.  It makes a difference, as configuration directives in `<Directory>` sections are inherited, and that also changes how configuration directives of the same name but different parameters are merged down/handled.

Let me work on this.  Note, however, that I will be on holiday for the next 2 weeks, so it may be a little while before I get back to this.

**Comment by lon9man** [comment]
1. My early config was the same, there I simply removed /home-directory from path for simplicity.
2. Also I used “userX”-names for simplification, in reality this names are different (as saying **lon9man** or **blitline**). But in any case all user-directories are located in /ftp-directory.
3. Also I checked your example in last commit, which is fully similar to my example:

```
Your:
<strong>Module:</strong> mod_redis<br>
 <Directory /path/to/pub>
       RedisLogOnCommand RETR file-transfers
 </Directory>
 
 # ...but prevent Redis logging in this subdirectory
 <Directory /path/to/pub/subdir>
      RedisLogOnCommand none
 </Directory


My:
<Directory /home/ftp>
    RedisLogOnCommand STOR redis ftp:%m:%u
</Directory>

<Directory /home/ftp/blitline>
    RedisLogOnCommand none
</Directory>

```

What is the difference between my example and your? Thanks!

P.S. Feel free to take the vacation next weeks, we will be happy to wait you)!

**Comment by Castaglia** [comment]
Can you test the latest master branch, see if the recent changes have addressed the functionality properly?

**Comment by lon9man** [comment]
@Castaglia, sorry for the delay. 
i have tested your last changes and it works as expected. thanks for the help, very fast and reliable!

P.S. for those interested:
minimally needed config for this functionality:
```
<IfModule mod_redis.c>
    # Enable mod_redis
    RedisEngine on

    # Tell mod_redis where to log its messages
    RedisLog /etc/proftpd/redis.log

    # Tell mod_redis where to find the Redis server
    RedisServer 127.0.0.1:6379

    LogFormat redis "%h %l %u %t \"%r\" %s %b %m %J %f"
</IfModule>

<Directory /home/ftp>
    RedisLogOnCommand STOR redis ftp:%m:%u
</Directory>

<Directory /home/ftp/blitline>
    RedisLogOnCommand none
</Directory>
```

**Comment by Castaglia** [comment]
Excellent news!  Thanks for the configuration.

**Comment by lon9man** [comment]
Hi @Castaglia 
have installed latest master (also tested some previous 1.3.7-versions, which i found on my desktop) and see that Directory-clauses doesn't work as expected. i am using [config](https://github.com/proftpd/proftpd/issues/573#issuecomment-336839336)
if i use 

    <Directory /home/ftp>
        RedisLogOnCommand STOR redis ftp:%m:%u
    </Directory>

i expect to see in redis (using key ftp:STOR:username) array with uploaded files, but i don't see any.
next part also doesn't work:

    <Directory /home/ftp/blitline>
        RedisLogOnCommand none
    </Directory>

so something strange happened. i remember that it worked when we closed this issue.
can you confirm such behaviour?
