### ISSUE TITLE
Implementation of check-file-name SFTP extension fails due to small buffers

### ISSUE THREAD

**Issue by mligor** [proftpd/proftpd#576]
Default buffer size is defined as FXP_RESPONSE_DATA_DEFAULT_SZ = 512 and in fxp_handle_ext_check_file() this is already multiplied by 2.

The problem is when many blocks are requested (e.g. 256), and in case of sha512 this is 64bytes each block will come to the summ of 16Kb. 256 blocks is not a limit anyway, but seams as reasonable value that should be accepted by mod_sftp.

I tried to increase the buffer and still I get one one block with the correct value - only the first one. I'm not so familiar with openssl BIO, therefore I could't find what the problem could be there.

**Comment by Castaglia** [comment]
What SFTP client are you using?  Is there an easy way I might reproduce the symptoms you're encountering, following some instructions you could provide?

**Comment by mligor** [comment]
Hi,

I'm member of the bitvise team and I got the info that denis bider already wrote you about the problem. 

Actually there is no client that does use that currently. We have in Bitvise SSH Client support for it, but it is active only for our server. When I tried to activate it with proftpd we got a terminated connection when multiple blocks should be calculated in the same request. Allocated response is then much larger then 1024 allocated bytes.

Even after increasing the buffer, I got always the same hash value for all blocks.

You can try to build SSH_FXP_EXTENDED request with: 
"check-file-name"
"testfile.dat"
"sha1"
0
2048
1024

This should return 2 SHA1 hashes, but it always returns the same hashes. Even if the file is 1024bytes 2 hashes will be returned.

I guess BIO_Reset() will reset position pointer to 0 and then always the same hash will be generated.

Best Regards,
Igor

**Comment by mligor** [comment]
Small update, bitvise released new version last night where you can test if file hashing works as expected. File hashish is used to synchronise files on server and client, by transferring only file differences (based on block hashes). 

We do request maximum 256 blocks, 64Kb for each block - which mean you will get the largest hash request for files over 16MB. 

You can download the new version of client on bitvise website:
https://www.bitvise.com/ssh-client-download

But you will need to change server identifier to enable SFTPv6 protocol, because we drop it to version 3 in case of mod_sftp. Simple setting 'ServerIdent on "MyServer 1.0"' does help.

Please check also notes in Bitvise Client version history, especially SFTP compatibility issues:
https://www.bitvise.com/ssh-client-version-history

At the end I have to say that proftpd is the linux server that currently the best support SFTPv6 protocol. And I believe that 1.3.7 version will be even better :) 

If I can give you some support, just let me know.

**Comment by Castaglia** [comment]
PR merged to master.  Thanks!
