### ISSUE TITLE
Successful logins aren't logged anymore

### ISSUE THREAD

**Issue by tomsommer** [proftpd/proftpd#595]
Proftpd stopped logging "Login successful" and "FTP session opened." messages from 1.3.5e to 1.3.6

Using `SystemLog`

**Comment by Castaglia** [comment]
I suspect this is due to the change of the default log level; see [Bug#3983](http://bugs.proftpd.org/show_bug.cgi?id=3983).  Does your _e.g._ `/etc/syslog.con` configuration filter out DEBUG-level messages for your FTP facility log files?

**Comment by tomsommer** [comment]
I don't use Syslog.

**Comment by Castaglia** [comment]
Well, if you use the `SystemLog` directive, then ProFTPD logs to the systems syslog-like facility, whatever that happens to be (syslog, syslog-ng, rsyslog, whatever).  One question is whether there is any "client" side filtering occurring in your system.

[Here](https://github.com/proftpd/proftpd/blob/master/modules/mod_auth.c#L394) you can see that ProFTPD _does_ log its "Login successful" messages at the `INFO` level.

**Comment by tomsommer** [comment]
Well, you changed the default to NOTICE here: https://github.com/proftpd/proftpd/commit/5fbe2f2ba7ba9d30ab59cd133cf33fb14134d889

Setting `SyslogLevel info` in the conf, works (odd name for a variable that controls the loglevel of files as well)

However, it seems ridiculous that an FTP server doesn't log logins per default.

**Comment by Castaglia** [comment]
It seems wrong _to you_; not all sites have the same/needs opinion.  Some sites only wish to know about _failed_ logins (which are logged at `NOTICE`).  And per the [Log Level howto](http://www.proftpd.org/docs/howto/LogLevels.html), the `INFO` level is for "normal operating conditions", which should apply to successful logins.

Thanks for pointing out the stale docs on www.proftpd.org; I'll update them accordingly.

**Comment by tomsommer** [comment]
No I agree, I'm saying the default should be changed to INFO. But mystery solved, perhaps this Issue will help someone else in the future.

**Comment by Castaglia** [comment]
Good point.  Definitely worthy of a FAQ entry, if nothing else.  I'll close this ticket once I've update the docs with this.

**Comment by Castaglia** [comment]
The website docs, and those distributed with the code, have been updated; see:

  http://www.proftpd.org/docs/modules/mod_log.html#FAQ

Thanks!
