### ISSUE TITLE
Multiple ProFTPD daemons unexpectedly running concurrently

### ISSUE THREAD

**Issue by xvkdev** [proftpd/proftpd#622]
### What I Did

Launching ProFTPd several times creates several instances each of them overwriting the previous PID file.
```
root# /usr/local/sbin/proftpd && ps -ef |grep proftp && cat /var/run/proftpd.pid
nobody   16639     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
root     16641 16558  0 06:19 pts/3    00:00:00 grep proftp
16639
root# /usr/local/sbin/proftpd && ps -ef |grep proftp && cat /var/run/proftpd.pid
nobody   16639     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16644     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
root     16646 16558  0 06:19 pts/3    00:00:00 grep proftp
16644
root# /usr/local/sbin/proftpd && ps -ef |grep proftp && cat /var/run/proftpd.pid
nobody   16639     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16644     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16651     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
root     16653 16558  0 06:19 pts/3    00:00:00 grep proftp
16651
root# /usr/local/sbin/proftpd && ps -ef |grep proftp && cat /var/run/proftpd.pid
nobody   16639     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16644     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16651     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
nobody   16657     1  0 06:19 ?        00:00:00 proftpd: (accepting connections)
root     16659 16558  0 06:19 pts/3    00:00:00 grep proftp
16657
```
### What I Expected/Wanted

Expectation would be to get an error about not being able to bind the 2nd time, no idea what's happening here to be honest. 
Better of course would be a message of "ProFTPd is already running, PID=xxx" if that's indeed true (i.e. check if PID file exists and if yes check if the process is still running), but never overwrite the PID file of a running instance as it makes it become untracked.

### ProFTPD Version and Configuration

Please help us reproduce the problem/issue you are encountering.  To do this,
we need to know which version of ProFTPD you are using, how it was built,
_etc_.  The following command is an easy way to get all of this information:
```
Compile-time Settings:
  Version: 1.3.7rc1 (git)
  Platform: LINUX [Linux 4.13.0-0.bpo.1-amd64 x86_64]
  Built: Mon Oct 30 2017 20:49:13 UTC
  Built With:
    configure  '--enable-nls' '--with-modules=mod_tls:mod_readme:mod_sftp:mod_ctrls_admin:mod_access_vroot:mod_digest:mod_geoip' '--enable-ctrls'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -L$(top_builddir)/lib/libcap -lcap  -lGeoIP  -lssl  -lpam  -lcrypto -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard
```
In addition, we need to see *all* of the ProFTPD configuration files you are
using (*minus* any sensitive information like passwords, of course).  Armed

Only relevant (to this part):
```
PidFile                         /var/run/proftpd.pid
```

**Comment by Castaglia** [comment]
Unfortunately using the `PidFile` as a determinator for whether another ProFTPD process is not terribly reliable.  Yes, we can check for the file's existence.  Yes, if present we can check whether that PID exists.  But we cannot assert that the PID in question refers to a _proftpd_ process; it can refer to another process which just happened to use a (recycled) PID.

Thus ProFTPD relies on the kernel's preventing of two different processes binding to the same socket as the determinator.

Now an argument can be made for _not_ overwriting the `PidFile` until _after_ the socket has been checked, but that then creates a time window where the PID of the current process is not tracked anywhere, which itself has consequences.

**Comment by xvkdev** [comment]
In linux you can see if the process is actually ProFTPd like this:

cat /var/run/proftpd.pid
16657
root@seedboxdev003:~# ls -l /proc/16657/exe
lrwxrwxrwx 1 root root 0 Oct 31 06:49 /proc/16657/exe ->
/usr/local/sbin/proftpd

**Comment by Castaglia** [comment]
And for the other platforms on which ProFTPD runs?  I *strongly* prefer non-platform-specific checks where possible, so that the behavior of ProFTPD is consistent across platforms and platform versions.

**Comment by xvkdev** [comment]
I don't have a solution I'm afraid.
Anyway I'd love to know why is linux allowing several processes to bind the
same IP and port now?

**Comment by Castaglia** [comment]
Looks like this behavior started with [this commit](https://github.com/proftpd/proftpd/commit/b69cf7483a78ec913db03d28c93517dc0fc6fe58), specifically the use of the `SO_REUSEPORT` socket option.

**Comment by Castaglia** [comment]
This should now be fixed in master.  Thanks!
