### ISSUE TITLE
mod_sftp: xferlog

### ISSUE THREAD

**Issue by pille** [proftpd/proftpd#633]
### What I Did

* configured proftpd to use ```mod_sftp```
* did file uploads/downloads

### What I Expected/Wanted

* see file uploads/downloads in ```xferlog```

### ProFTPD Version and Configuration

* version: 1.3.4a
* config: on demand
* "normal" FTP traffic is logged to ```xferlog```
* using ```mod_sftp``` log option to log into seperate file. (no filenames are logged)

**Comment by Castaglia** [comment]
ProFTPD 1.3.4a is quite old; please upgrade to the latest stable version, ProFTPD 1.3.6.  There have been many fixes and improvements since 1.3.4a.

**Comment by pille** [comment]
i can confirm, that this works as expected in 1.3.5a

**Comment by Castaglia** [comment]
Glad to hear that it's working now for you.  And thanks for following up!
