### ISSUE TITLE
Support overriding location of /etc/shutmsg

### ISSUE THREAD

**Issue by mcarbonneaux** [proftpd/proftpd#652]
In commit : https://github.com/proftpd/proftpd/commit/0d1f4b8bbdedd81a0fe4f9fbb165e40edaffd44d

you have made possible to override more of the default paths at configure/compile but not this one:
```
#define PR_SHUTMSG_PATH		"/etc/shutmsg"
```

can you make also overidable this last one ?

**Comment by Castaglia** [comment]
Could you elaborate on the desired use case/reasoning, please?  What's wrong with continued use of that hardcoded path (where only `root` can modify/set that file)?

**Comment by mcarbonneaux** [comment]
the idea is to compile proftpd in other directory tree than /, all part of proftpd can be placed in other place, but not /etc/shutmsg.

for different possible reason... the first in corporate rule the oblige installing product in specific corporate tree... the second is to instanciate multiple instance of proftpd...

**Comment by Castaglia** [comment]
I'll make it possible to override that location via custom `CFLAGS` value in your `configure` command, _e.g._:

    $ ./configure CFLAGS='-DPR_SHUTMSG_PATH=...' ...

but that's about it.  That location is not something that many people will want to change, which means, in my mind, that it does not warrant a special/new configure script option.

**Comment by Castaglia** [comment]
Fixed in master.
