### ISSUE TITLE
PROFTPD FORUM OUT : NET::ERR_CERT_REVOKED

### ISSUE THREAD

**Issue by stratege1401** [proftpd/proftpd#672]
Hello,

if an admin from proftpd.org read this, the starcom CA for the forum is revoked for chrome (no exception rules ) and looks with a SEC_ERROR_UNKNOWN_ISSUER error if access with firefox...

time to switch to a new CA ( letsencrypt !! )

**Comment by stratege1401** [comment]
Hope so, because forum access is simply dead for people using chrome. 

Dont' know who manage it, but it is a 45 secondes task with lestencrypt CA, and it is free !!!

This is giving a very bad look for proftpd community

**Comment by florian2833z** [comment]
Look, on september the 20th, I created a forum thread about this issue: 
https://forums.proftpd.org/smf/index.php/topic,12259.0.html

Still, no one cares about that issue ...

**Comment by stratege1401** [comment]
yes, i know, **but latest chrome update prohibit access** now... event to your post ( because, with no access, no read, logical )

  when CA is REVOKED, chrome gives no more option to bypass the warning by adding a exception.

So for the millions + users with chrome, no more forum, Unless to use firefox or opera or ...

Witch i am pretty sure, a lot of people will wont bother to test.

**Comment by florian2833z** [comment]
Lol I need to use internet explorer to be able to access the forum.

**Comment by stratege1401** [comment]
well, some people are not as savant as you are ...

I am able to bypass the revoke cert, but how many others people can't because they don't know...

your last comment is just saying to them that you dont care ... witch is your right. You should join some people building walls to keep those ignorant away.

**Comment by florian2833z** [comment]
Wait, you say, you switch FTP server? Just because of the forum or because of other reasons as well?

**Comment by stratege1401** [comment]
my goal is to have my students learning by testing and resolving faulty servers.
They have TD witch are like exam in real situation. And they also have TS witch are the same but done from home.
I wont direct them to any clue or help. They have to sort it out by themselfs.
During TS, they can use whatever software they want, including "internet explorer" if they want
But during TD, they use closed system within the school:
-They can mess with it, or install other stuff on it, because after reboot, the machine a set back to their original state. 
-The security suit use is pretty heavy to modify, and it take weeks to have an approval.

The proftpd forum is part of the package server. No access, no lessons.

Chrome is the main webrowser, proftpd forum can be open because of CA revoke...

See my point here.

Now, proftpd is out of the scope, i move to something reachable. In fact, the whole school just did.

**Comment by florian2833z** [comment]
I guess the forum will be dead forever ...

**Comment by stratege1401** [comment]
yeahhh, just started another years at school, with new students ...

I was just checking if the cert problem was fixed from feb last year.... witch is not.

Proftpd will be bared from our students for one more years.... what a pity.
In fact, proftpd is now blacklisted in our university.

this theat is now definitly closed.

Bye.

**Comment by Castaglia** [comment]
This issue has now been addressed.

**Comment by florian2833z** [comment]
https://dev.ssllabs.com/ssltest/analyze.html?d=forums.proftpd.org

The rest of the server config is still complete trash

**Comment by Castaglia** [comment]
That sort of "it's trash" feedback is not helpful.

Yes, I know that that host is out-of-date; it's been unmaintained for years, and I only found access to it today.  It was a fair amount of work just to get it to a state where I could issue a Let's Encrypt cert for it, let alone any other improvements.  It'd be great if others could help me maintain these things; I only have so much free time.

**Comment by ws0w** [comment]
I’d be happy to help.

**Comment by florian2833z** [comment]
> It'd be great if others could help me maintain these things; I only have so much free time.

If there's a job that anybody else could do, I'd be happy to help. But how can this be possible without giving away root access?

**Comment by stratege1401** [comment]
no root Access, no maintenance, or by sudoer !!!

Happy to see my 2018 post revitalized.
