### ISSUE TITLE
Perl syntax error in ftpasswd since last commit

### ISSUE THREAD

**Issue by eazrael** [proftpd/proftpd#679]
### What I Did

/usr/local/bin/ftpasswd --help
syntax error at /usr/local/bin/ftpasswd line 814, near "} split"
Global symbol "$names" requires explicit package name at /usr/local/bin/ftpasswd line 817.
Global symbol "$ftpasswd" requires explicit package name at /usr/local/bin/ftpasswd line 1102.
Execution of /usr/local/bin/ftpasswd aborted due to compilation errors.

Previous version of ftpasswd worked.

**Comment by Castaglia** [comment]
Thanks for reporting this!  Clearly I need to add some Perl syntax checking to the Travis CI builds for this project. :)

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!
