### ISSUE TITLE
Blocking out "NOOP" with Limit not working? 

### ISSUE THREAD

**Issue by drphlux** [proftpd/proftpd#684]
### What I Did

Placed within the only active Virtualhost for ftp, to deny server 
from accepting the NOOP command from clients:

```
<Directory /ftp/home>
  <Limit NOOP>
    DenyAll
  </Limit>
</Directory>
```

This does not affect the server from accepting the  NOOP command:
Server says: 200 'NOOP command successful'

Other commands like MLSD are blocked just fine within the same Limit 
when tested.

### ProFTPD Version and Configuration

    $ proftpd -V
ProFTPD Version 1.3.5e

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!

**Comment by drphlux** [comment]
Cool thanks. 
As to why I wanted to block NOOP? 
We want the clients to log in, transfer files and then log out. 
We don't want clients to linger.
I think the Ncftpd implemetation of "noop-delay" explains this perfectly:
[https://www.ncftp.com/ncftpd/doc/config/g/noop-delay.html](url)
