### ISSUE TITLE
proftpd forums using revoked certificate not accessible with chrome

### ISSUE THREAD

**Issue by chrcoluk** [proftpd/proftpd#688]
not a problem with proftpd itself, but basically proftpd forums website cannot be accessed via chrome as its using a revoked certificated from startssl.  Chrome does not allow the end user to override the warning ,its a full on hard block.

**Comment by chrcoluk** [comment]
yep, I had to install old build of firefox to browse the forum, not good.

**Comment by denisgrilliGMSL** [comment]
I don't understand how this can still the case. 
Who is managing the forum? Can we help in any way?

**Comment by Castaglia** [comment]
This should now be fixed/working.
