### ISSUE TITLE
mod_exec path issue in 1.3.6

### ISSUE THREAD

**Issue by tsmgeek** [proftpd/proftpd#691]
Since upgrade to 1.3.6 paths being passed in exec command using %f are not consistent with 1.3.5e
I am using mod_vroot.

For MKD commands the path is as seen by the FTP client ie '/foldera' but for STOR commands i see '/mnt/ftp/foldera/filea.jpg', it is including the whole path to the file.

When I downgrade back to 1.3.5e everything works as expected.

**Comment by Castaglia** [comment]
Could you provide the full `proftpd.conf` you're using, and the output from `proftpd -vv`, please?

**Comment by Castaglia** [comment]
Closing stale ticket.
