### ISSUE TITLE
Emulate FTP upload local files

### ISSUE THREAD

**Issue by lon9man** [proftpd/proftpd#700]
Hello

### What I Did
**Case 1:** we are using Proftpd for uploading by users files onto our server. then our background workers analyze upload logs (sql, redis) and process this files via putting into database and Amazon S3. sometimes our **workers #Type1** can be closed unexpectedly saying on exceptions or etc. and in result we want to process some files repeatedly. 

**Case 2:** i have some files, which **workers Type#2** download saying from Google Drive and save it locally. i want to put this files into Proftpd-uploadDirectory, nextly this files will be processed by **workers Type#1**. 

### What I Expected/Wanted
i want to emulate FTP upload files, which i already have in my server.. so this files will be parsed using Proftpd and nextly in the way described in **What I Did** section. 
want to prevent advices about **LFTP**, i don't want to use it, because:
- i don't have user passwords (only hashed), which LFTP needs to re-run own commands
- additional overhead on CPU and etc for such re-run FTP upload

**! Main question !**
so maybe Proftpd can potentially have some lightweight-way for such re-upload files/directories, which already exists locally?

### ProFTPD Version and Configuration
**$ proftpd -V**
Compile-time Settings:
  Version: 1.3.7rc1 (git)
  Platform: LINUX [Linux 4.4.0-121-generic x86_64]
  Built: Пнд Окт 16 2017 12:46:54 EEST

**Comment by Castaglia** [comment]
Honestly, this sounds like a feature request for a specific client for testing your specific server-side behaviors; it does not sound like a feature that ProFTPD, as a server, would implement.
