### ISSUE TITLE
forums.proftpd.org certificate has expired

### ISSUE THREAD

**Issue by martinprikryl** [proftpd/proftpd#729]
![prodftpd](https://user-images.githubusercontent.com/1632297/42303889-bf648186-8023-11e8-979a-90ebdeb4a5c2.png)

**Comment by florian2833z** [comment]
https://github.com/proftpd/proftpd/issues/688
https://github.com/proftpd/proftpd/issues/672

**Comment by Castaglia** [comment]
This issue has finally been addressed.
