### ISSUE TITLE
No CMD dispatch when using mod_sftp

### ISSUE THREAD

**Issue by pepi55** [proftpd/proftpd#734]
### What I Did

Created a custom module with a "cmdtable" containing functions of type "CMD".

### What I Expected/Wanted

When connecting with sftp to the proftpd server and sending a command like "ls" or "put", my custom module's "CMD" functions are not called.
What I expected to happen is that the custom "CMD" function defined in the "cmdtable" in my custom module to be called.

"PRE_CMD" and "POST_CMD" are all working fine and mod_sftp is also working correctly. The only thing is that it hijacks the "CMD" event and it is never evoked.

### ProFTPD Version and Configuration

```
Compile-time Settings:
  Version: 1.3.5b (maint)
  Platform: LINUX [Linux 4.17.6-1-ARCH x86_64]
  Built: Mon Jul 30 2018 09:27:22 UTC
  Built With:
    configure  '--enable-facl' '--prefix=/opt/proftpd' '--enable-openssl' '--sysconfdir=/etc' '--localstatedir=/var/log/proftpd' '--libexecdir=/usr/libexec/proftpd' '--with-modules=mod_sftp:mod_facl' '--enable-dso' '--with-shared=mod_tls:mod_auth_file:mod_auth_pam' '--enable-ctrls' '--enable-ltdl-convenience' '--cache-file=/dev/null' '--srcdir=./' '--enable-devel=nodaemon:nofork'

  CFLAGS:  -Wall -DPR_DEVEL_NO_FORK -DPR_DEVEL_NO_DAEMON -g -O0 -Wcast-align -Wchar-subscripts -Winline -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -Wpointer-arith -Wshadow -Wundef -Wfloat-equal -Wformat -Wimplicit-function-declaration -Wmaybe-uninitialized -Wpointer-to-int-cast -Wstack-protector -Wunreachable-code -fstack-protector-all
  LDFLAGS: -L$(top_srcdir)/lib  
  LIBS: -lacl  -lssl -lcrypto -lssl -lcrypto -lcap  -lcrypto -lz -lsupp -lcrypt -ldl  

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/log/proftpd/proftpd.pid
    Scoreboard File:
      /var/log/proftpd/proftpd.scoreboard
    Header Directory:
      /opt/proftpd/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    + Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncurses support
    - NLS support
    + OpenSSL support (FIPS enabled)
    - PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment]
No, `mod_sftp` deliberately does not dispatch the `CMD` phase.  That phase is for the callbacks which actually _implement_ the command in question; in the case of `mod_sftp`, it already implements the commands in question itself.  The nature/formatting of SFTP requests is such that a generic "run this command" for other modules does not make sense.

The question I have is: what `CMD` would you think you want to run, via SFTP, from your custom module?

**Comment by pepi55** [comment]
I want to implement AWS S3 support for sftp and ftp. This requires me to handle the read/write with the AWS SDK. Unless I am misunderstanding something, I think handling these with the CMD command is my best bet?

I want to keep away from modifying the source code so I don't have to patch + recompile with every update. That is why I want to implement it as a module.

**Comment by Castaglia** [comment]
When I've thought about implementing this functionality (S3 support, specifically), I've thought about using the pluggable FSIO API, rather than overriding custom commands.  That way, it'd automagically work with FTP and SFTP, by registering your own callbacks for the `pr_fsio_read()` and `pr_fsio_write()` _et al_ functions.   You might look into using that API for S3 support...?

**Comment by pepi55** [comment]
Yes, that is an option. I have to say, it was very difficult to find out about that option. I couldn't find readily available documentation about the FSIO API (as in, documentation mentioning it exists).

However, there is one issue with the FSIO API, it works with read/write but the AWS SDK does not support such functionality directly. To execute an upload/download call, you have to create a `PutObjectRequest`/`GetObjectRequest` which is then used to make a request to S3, which then gets you a filestream.

The issue here is that the FSIO API handles writes and read directly on the disk, while the AWS SDK needs to know whether you are downloading or uploading and it handles the writes to S3 internally.

Is there a more convenient option or is my only option to try and hack something together using FSIO?

**Comment by pepi55** [comment]
Nevermind I just realized that the FSIO API handles the remote filesystem only. Which means that `pr_fsio_read()` = `GetObjectRequest` and `pr_fsio_write()` = `PutObjectRequest`.

I think this issue can be closed now. If I have any other problems setting things up, I will just open a new issue.

Thanks for the help!
