### ISSUE TITLE
How does ProFTPD calculate the filesize to transfer?

### ISSUE THREAD

**Issue by pepi55** [proftpd/proftpd#749]
### What I Did

Scoured the source code for potential locations where the length and/or amount of upload/download cycles are defined.

### What I Expected/Wanted

I wanted to find a location where ProFTPD calculates what the total size of a file is before transferring it. How does it know how many upload/download cycles it needs to transfer the file? I want to know this for both mod_sftp and default ftp transfers.

### ProFTPD Version and Configuration

```
Compile-time Settings:
  Version: 1.3.5b (maint)
  Platform: LINUX [Linux 4.17.6-1-ARCH x86_64]
  Built: Mon Jul 30 2018 09:27:22 UTC
  Built With:
    configure  '--enable-facl' '--prefix=/opt/proftpd' '--enable-openssl' '--sysconfdir=/etc' '--localstatedir=/var/log/proftpd' '--libexecdir=/usr/libexec/proftpd' '--with-modules=mod_sftp:mod_facl' '--enable-dso' '--with-shared=mod_tls:mod_auth_file:mod_auth_pam' '--enable-ctrls' '--enable-ltdl-convenience' '--cache-file=/dev/null' '--srcdir=./' '--enable-devel=nodaemon:nofork'

  CFLAGS:  -Wall -DPR_DEVEL_NO_FORK -DPR_DEVEL_NO_DAEMON -g -O0 -Wcast-align -Wchar-subscripts -Winline -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -Wpointer-arith -Wshadow -Wundef -Wfloat-equal -Wformat -Wimplicit-function-declaration -Wmaybe-uninitialized -Wpointer-to-int-cast -Wstack-protector -Wunreachable-code -fstack-protector-all
  LDFLAGS: -L$(top_srcdir)/lib  
  LIBS: -lacl  -lssl -lcrypto -lssl -lcrypto -lcap  -lcrypto -lz -lsupp -lcrypt -ldl  

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/log/proftpd/proftpd.pid
    Scoreboard File:
      /var/log/proftpd/proftpd.scoreboard
    Header Directory:
      /opt/proftpd/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    + Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncurses support
    - NLS support
    + OpenSSL support (FIPS enabled)
    - PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment]
For FTP uploads, ProFTPD _cannot_ know, in advance, how large the file to be uploaded by the client will be.  And unless the FTP client in question uses the new `RANG` FTP command, the client does not inform the server of how large of a file will be uploaded.

For SFTP uploads, the protocol says that the client _may_ send a size field in the initial SFTP `OPEN` request.  However, `mod_sftp` largely ignores that, as a client may not send it, _or_ may send a different number of bytes than indicated.

For both FTP and SFTP downloads, the size of the file to be transferred is take from the `st.st_size` field, obtained via the `stat(2)` system call on the file in question.

I'm not sure what you mean by "amount of upload/download cycles".

**Comment by pepi55** [comment]
What I meant with upload/download cycles is the amount of times the `pr_fsio_write()` and `pr_fsio_read()` commands are called. I noticed that they are called multiple times with a certain amount of bytes to read/write.

Download makes sense now, but how does ProFTPD know when the upload is over?

**Comment by Castaglia** [comment]
ProFTPD knows the upload is "over" once the data transfer connection is closed.  It's a horrible way to indicate "end of data", but that's how FTP, as a protocol, works.

You can tune the buffer size used for transfers via a compile/build time `configure` option:
```
  --enable-transfer-buffer-size
                          tune the the size (in bytes) of data transfer
                          buffers (default=OS dependent)
```

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.

**Comment by pepi55** [comment]
Sorry for the delay, I had to take a break from the project that needed this. I think the ticket can be closed, you have stated everything that there is to it.
