### ISSUE TITLE
Inconsistent error string: "SECURITY VIOLATION: Root login attempted"

### ISSUE THREAD

**Issue by shaneforsythe** [proftpd/proftpd#751]
### What I Did

Trying to integrate fail2ban and proftpd I stumbled upon an issue try to monitor and block for both ftp and sftp connections. Fail2ban relies on regex expressions to match the log file and block ip addresses based on logs.  

Based on whether connection is sftp or ftp , the log is slightly different.

in contrib/mod_sftp/auth.c , line 343
`pr_log_auth(PR_LOG_NOTICE, "SECURITY VIOLATION: Root login attempted.");`
  
In modules/mod_auth.c , line 1049
`pr_log_auth(PR_LOG_NOTICE, "SECURITY VIOLATION: Root login attempted");`

Neither actually matches the reference here
In doc/modules/mod_auth.html, line 779
`SECURITY VIOLATION: root login attempted.`

The common fail2ban regex ( in filter.d/proftpd.conf ) which I believe is fairly widely distributed is
```
failregex = 
^%(__prefix_line)s%(__hostname)s \(\S+\[<HOST>\]\)[: -]+ USER .*: no such user found from \S+ \[\S+\] to \S+:\S+ *$

^%(__prefix_line)s%(__hostname)s \(\S+\[<HOST>\]\)[: -]+ USER .* \(Login failed\): %(__suffix_failed_login)s\s*$

^%(__prefix_line)s%(__hostname)s \(\S+\[<HOST>\]\)[: -]+ SECURITY VIOLATION: .* login attempted\. *$

^%(__prefix_line)s%(__hostname)s \(\S+\[<HOST>\]\)[: -]+ Maximum login attempts \(\d+\) exceeded *$
```

The sftp code path uses a period at the end, normal ftp does not.  the doc/modules has a period at end, but the 'r' in root is not capitalized.

I can file matching correction with author of that filter for fail2ban , but may or may not get updated to all distributions that package that.

### What I Expected/Wanted

Change error log to be consistent on different code paths (sftp vs ftp )

### ProFTPD Version and Configuration
# proftpd -V
Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 3.10.0-862.11.6.el7.x86_64 x86_64]

Installed from Centos7 RPM

**Comment by Castaglia** [comment]
This should now be fixed (and consistent!) in `master`.  Thanks!
