### ISSUE TITLE
QUESTION: Does mod_quotatab_sql support SFTP transfers?

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#752]
Was starting the process of integrating support of mod_quotatab_sql for SFTP transfers. However, looking at the docs it was not clear if SFTP (vs FTP) is supported. If not, it will save the effort of trying to get it running. Thanks!

**Comment by Castaglia** [comment]
Yes, it should be supported; the `mod_quotatab_sql` module works by hooking into the filesystem IO abstraction (FSIO API), which is independent of the protocol used to transport the bytes to/from the filesystem.
