### ISSUE TITLE
Does proftpd provides a FUSE-compatible File System Abstraction Layer to access user-space filesystems?

### ISSUE THREAD

**Issue by sepia-liu** [proftpd/proftpd#757]
Hello

### What I Expected/Wanted

With the number of user-space filesystems being developed and deployed, there was a huge performance hit when the user-space filesystems were exported the FTP service via the kernel-FTP. If  FTP server with a moduel which provides a FUSE(Filesystem in Userspace)-compatible File System Abstraction Layer(FSAL) to allow the file-system developers to plug in their own storage mechanism and access it from any FTP client, this will greatly enhance the response times。
### Main question !

I want to directly connect proftpd server with user-space filesystems (such as CephFS),the filesystem is already compatible with POSIX.  Does proftpd has such module that can access the FUSE filesystems directly through its File System Abstraction Layer without copying any data to or from the kernel? Of course the network streams themselves (TCP/UDP) will still be handled by the Linux kernel. In other words, is there such a feasibility?

I have tried to google it, but there is very little information about this, could anyone please help me with it or give me some ideas?

Thanks in advance.

**Comment by tspicer** [comment]
Greetings, we use Proftpd with Fuse based S3FS without incident. I'm not sure this is exactly what you are asking, but it does work.

**Comment by Castaglia** [comment]
@sepia-liu The short answer to your question is no, ProFTPD does not currently have a module that allows/implements FUSE access.  There is nothing preventing developers for writing such a module; the core ProFTPD developers have not written such a thing.

As @tspicer points out, ProFTPD can use other FUSE-based filesystems without issue.

**Comment by sepia-liu** [comment]
> @sepia-liu The short answer to your question is no, ProFTPD does not currently have a module that allows/implements FUSE access. There is nothing preventing developers for writing such a module; the core ProFTPD developers have not written such a thing.
> 
> As @tspicer points out, ProFTPD can use other FUSE-based filesystems without issue.
