### ISSUE TITLE
UseImplicitSSL connection immediately close on data channel

### ISSUE THREAD

**Issue by pol2095** [proftpd/proftpd#759]
Hello,

I use "TLSOptions UseImplicitSSL" to connect on the control channel in TLS, ftp command "PASV" return the data port, I connect on this port and I send "MLSD" in the control channel, I get the listing of directories and after the connection close on data channel ?

In the tls log
> 2018-11-13 21:37:27,331 mod_tls/2.6[13442]: [msg] sent TLSv1.2 warning 'close_notify' Alert message (2 bytes)
> 2018-11-13 21:37:27,331 mod_tls/2.6[13442]: [info] writing: SSL/TLS alert warning: close notify

I use "TLSOptions UseImplicitSSL NoSessionReuseRequired"

"NoSessionReuseRequired" fix the loss of connection for the control channel but not for the data channel ?

Thanks

**Comment by ostus2011** [comment]
Did you manage to solve the problem? If so, what was your solution?

**Comment by pol2095** [comment]
I need to send a new ftp command "PASV" and reopen a data port.
