### ISSUE TITLE
Connection issue from sftp client SSH-2.0-XFB.Gateway Unix

### ISSUE THREAD

**Issue by Loganlu** [proftpd/proftpd#760]
### I encounter an issue when connecting to prodftpd server from Axway sftp client on AIX
I used Axway (SSH-2.0-XFB.Gateway Unix) sftp client connect to prodftpd server and i got following error on the client.

> sftp -vv -i /home/gateway/Xperience_prv_key.key -P8888 xxx@xxxx.com
   OpenSSH_6.0p1, OpenSSL 1.0.1o-fips 12 Jun 2015
   debug1: Reading configuration data /etc/ssh/ssh_config
   debug1: Failed dlopen: /usr/krb5/lib/libkrb5.a(libkrb5.a.so):   0509-022 Cannot load module 
    /usr/krb5/lib/libkrb5.a(libkrb5.a.so).
     0509-026 System error: A file or directory in the path name does not exist.
    debug1: Error loading Kerberos, disabling Kerberos auth.
    debug2: ssh_connect: needpriv 0
    debug1: Connecting to ***.com [***] port 8888.
    debug1: connect to address *** port 8888: Connection timed out
    ssh: connect to host ***.com port 8888: Connection timed out
    Connection closed

And i see following error on server side.

> 2018-11-14 10:20:33,632 mod_sftp/0.9.9[94755]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
   2018-11-14 10:20:33,632 mod_sftp/0.9.9[94755]: disconnecting client (received EOF)
   2018-11-14 10:21:03,653 mod_sftp/0.9.9[94784]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
   2018-11-14 10:21:03,653 mod_sftp/0.9.9[94784]: disconnecting client (received EOF)
   2018-11-14 10:21:33,685 mod_sftp/0.9.9[94813]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
   2018-11-14 10:21:33,685 mod_sftp/0.9.9[94813]: disconnecting client (received EOF)
   2018-11-14 10:21:42,068 mod_sftp/0.9.9[94828]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
   2018-11-14 10:21:42,092 mod_sftp/0.9.9[94828]: received client version 'SSH-2.0-XFB.Gateway Unix'
    2018-11-14 10:21:42,092 mod_sftp/0.9.9[94828]: handling connection from SSH2 client 'XFB.Gateway Unix'
    2018-11-14 10:21:42,185 mod_sftp/0.9.9[94828]:  + Session key exchange: diffie-hellman-group1-sha1
    2018-11-14 10:21:42,185 mod_sftp/0.9.9[94828]:  + Session server hostkey: ssh-rsa
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session client-to-server encryption: aes128-cbc
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session server-to-client encryption: aes128-cbc
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session client-to-server MAC: hmac-sha1
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session server-to-client MAC: hmac-sha1
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session client-to-server compression: none
    2018-11-14 10:21:42,186 mod_sftp/0.9.9[94828]:  + Session server-to-client compression: none
    2018-11-14 10:21:42,360 mod_sftp/0.9.9[94828]: sending acceptable userauth methods: publickey
    2018-11-14 10:21:42,422 mod_sftp/0.9.9[94828]: public key MD5 fingerprint: 59:16:1b:b7:3d:5b:26:3e:c9:b1:7e:a3:1f:e6:b8:77
    2018-11-14 10:21:42,424 mod_sftp/0.9.9[94828]: sending userauth success
    2018-11-14 10:21:42,424 mod_sftp/0.9.9[94828]: user '***' authenticated via 'publickey' method
    2018-11-14 10:21:42,473 mod_sftp/0.9.9[94828]: 'subsystem' channel request for 'sftp' subsystem
    2018-11-14 10:22:03,665 mod_sftp/0.9.9[94844]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
    2018-11-14 10:22:03,665 mod_sftp/0.9.9[94844]: disconnecting client (received EOF)
    2018-11-14 10:22:33,775 mod_sftp/0.9.9[94873]: sent server version 'SSH-2.0-mod_sftp/0.9.9'
    2018-11-14 10:22:33,775 mod_sftp/0.9.9[94873]: disconnecting client (received EOF)`

### ProFTPD Version and Configuration
> proftpd -V
   Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 3.10.0-862.3.2.el7.x86_64 x86_64]
  Built: Wed Jan 31 2018 16:32:29 UTC
  Built With:
    configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' 
    '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '-- 
    sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '-- 
    libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '-- 
    mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '-- 
    localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable- 
    ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-shadow' '-- 
    enable-tests' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with- 
    modules=mod_readme:mod_auth_pam:mod_tls' '--with- 
 

> shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_ifsession'
   'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe - 
   Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 
   -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 
   'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe - 
   Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 
   -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic'
    CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -- 
    param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall
    LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld - L/usr/lib64/mysql -L/usr/lib64/mysql -L/usr/lib64
    LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lssl -lcrypto  -lpam -lsupp -lcrypt -ldl
  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd
  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (FIPS enabled)
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

In addition, this is my server configuration:

> ServerName "sftp-dev"
    ServerType                      standalone
    DefaultServer                   on
 
     DefaultRoot                     ~ sftp   # ~ means home dir and sftp stands for user group
 
     AuthOrder                       mod_auth_file.c*
     AuthUserFile                    /etc/proftpd/proftpd.sftp.passwd
     AuthGroupFile                   /etc/proftpd/proftpd.sftp.group
 
     LoadModule mod_sftp.c
 
    <IfModule mod_sftp.c>
 
        SFTPEngine on
        Port 8888
        SFTPLog /var/log/proftpd/sftp.log
        TransferLog /var/log/proftpd/sftp-xferlog
 
        # Configure both the RSA and DSA host keys, using the same host key
        # files that OpenSSH uses.
        SFTPHostKey /etc/ssh/ssh_host_rsa_key
        SFTPAuthMethods publickey
        SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u
        # SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u
        # Enable compression
        SFTPCompression delayed
        RequireValidShell off
        CreateHome on 700 dirmode 700
        SFTPOptions IgnoreSFTPSetPerms
 
   </IfModule>
 
   # limit the access of hidden files
    <Directory /*>
        HideFiles (^\..*|\.sh$)
        <Limit ALL>
        IgnoreHidden On
        </Limit>
    </Directory>

**Comment by Loganlu** [comment]
[-.txt](https://github.com/proftpd/proftpd/files/2581262/-.txt)
My detailed server configuration

**Comment by RomanHargrave** [comment]
I manage a B2B dropbox based on ProFTPd. We support Axway, which seems to have only required the following two lines be added to the configuration -

```proftpd
SFTPClientMatch ".*XFB.*"    channelWindowSize 1GB 
SFTPClientMatch ".*XFB.*"    sftpUTF8ProtocolVersion 3
```

**Comment by Denoce773** [comment]
Hello RomanHargrave,

I have the same issue.
In which configuration file should we setup both parameters?

**Comment by Castaglia** [comment]
> I manage a B2B dropbox based on ProFTPd. We support Axway, which seems to have only required the following two lines be added to the configuration -
> 
> ```
> SFTPClientMatch ".*XFB.*"    channelWindowSize 1GB 
> SFTPClientMatch ".*XFB.*"    sftpUTF8ProtocolVersion 3
> ```

A minor suggestion -- these can be combined into a single directive:
```
SFTPClientMatch ".*XFB.*" channelWindowSize 1GB sftpUTF8ProtocolVersion 3
```
if it helps.

**Comment by Castaglia** [comment]
I've updated the `mod_sftp` docs with a section covering the `SFTPClientMatch` settings for this clients (and others); see:
* http://www.proftpd.org/docs/contrib/mod_sftp.html#ClientMatches

**Comment by martinprikryl** [comment]
Is there a reason for this? Are there any outstanding interoperability issues with WinSCP?
```
SFTPClientMatch ".*WinSCP.*" sftpProtocolVersion 3
```

**Comment by Castaglia** [comment]
@martinprikryl these settings were contributed by ProFTPD/mod_sftp users; I don't know exactly what issues they encountered, to provide the above.  Perhaps it is relevant, but for older WinSCP versions (in which case, is there a more specific regex that can/should be used instead)?

**Comment by martinprikryl** [comment]
@Castaglia I believe the last version-specific interoperability issue we were dealing with was the following one between WinSCP 5.7 and ProFTPD 1.3.5 in 2015:
https://winscp.net/tracker/1289
http://bugs.proftpd.org/show_bug.cgi?id=4160
