### ISSUE TITLE
Debug output when Include used in config

### ISSUE THREAD

**Issue by twouters** [proftpd/proftpd#766]
When using `SystemLog NONE` and `SyslogLevel EMERG` proftpd will throw a syslog formatted message to stderr while starting or checking config (-t) if the `Include` directive has been used.

```
# proftpd -d 0 -t
Checking syntax of configuration file
2018-11-29 12:02:00,467 localhost proftpd[4983]: processing configuration directory '/etc/proftpd/vhosts'
Syntax check complete.
# proftpd -d 0 -t 2>/dev/null
Checking syntax of configuration file
Syntax check complete.
```

Version: 1.3.6 (stable)

**Comment by Castaglia** [comment]
Can you provide an example config, that we can use to reproduce this behavior locally? Thanks!

**Comment by twouters** [comment]
I'd still like to know when there are syntax issues with the config file, so I don't think that's an option. Unless -q behaves differently in that case.

I've patched this for now using the following patch on 1.3.6:

```
--- a/src/parser.c
+++ b/src/parser.c
@@ -1267,7 +1267,7 @@
     }
   }
 
-  pr_log_pri(PR_LOG_DEBUG, "processing configuration directory '%s'", dup_path);
+  pr_trace_msg(trace_channel, 3, "processing configuration directory '%s'", dup_path);
 
   dirh = pr_fsio_opendir(dup_path);
   if (dirh == NULL) {
```

It's probably not the correct solution but it works for me :D

**Comment by Castaglia** [comment]
Seems like a suitable change to me; if you submit that as a PR, I'll merge it.
