### ISSUE TITLE
Compile error on make.. warning unused variable 'md_ctx'

### ISSUE THREAD

**Issue by Baraganne** [proftpd/proftpd#771]
### What I Did

I was trying to add mod_proxy on my proftpd

### What I Expected/Wanted

Good compilation

### ProFTPD Version and Configuration

Here is my verison number : 

proftpd -v
ProFTPD Version 1.3.5b

Here is the error I get when compiling :
```
mod_sql.c:757:14: error: storage size of ‘md_ctx’ isn’t known
   EVP_MD_CTX md_ctx;
              ^~~~~~
mod_sql.c:757:14: warning: unused variable ‘md_ctx’ [-Wunused-variable]
```

**Comment by Castaglia** [comment]
Which version of OpenSSL do you have installed?  That is, what does `openssl version -a` show?

**Comment by Castaglia** [comment]
It looks like the `mod_sql.c` source has changed sufficiently since 1.3.5b, such that this is no longer a variable used in that code.  I'm thus closing this.
