### ISSUE TITLE
Emit an event when a user disconnect explicitly (QUIT)

### ISSUE THREAD

**Issue by Malizor** [proftpd/proftpd#777]
Currently, it does not seems possible for a module to hook into mod_core in order to differentiate explicit user disconnections from arbitrary disconnections.

This is a use case I have with one custom fsio module, which should only trigger some actions when the client disconnects explicitly (ie. full file upload) and not when the session is interrupted for external reasons.

**Comment by Malizor** [comment]
Thank you very much for your answer @Castaglia.

What do you think of the approach in my PR?
Do you think it has any value or do you recommend I go with your suggestion?

**Comment by Malizor** [comment]
@Castaglia : Your idea of using `session.disconnect_reason` works like a charm.
I successfully tested it in my module with FTP, FTPS and SFTP. It provides the same feature I implemented via my PR.

I'm going to use it, as it prevents me from patching my ProFTPD.
Feel free to close my PR if you think it's not useful.


As a side note, I noticed clients like Filezilla do not send a proper QUIT when they disconnect (the disconnect reason is always `Read EOF from client`). LFTP works fine.
It's not a problem in my use case, but I was wondering if you knew of any way around these client disparities?

Thanks again.

**Comment by Castaglia** [comment]
Unfortunately no, I don't know how to get clients like FileZilla to properly send a `QUIT` command; I wish I did.

I like the idea of your PR, but want to ponder on the event naming, specifically.  This issue demonstrates the difference between a "quit" (i.e. specifically requested by the client), and a disconnect for _other_ reasons (bad client behavior, server policy, _etc_).  I'm not sure if a single event can convey these differences -- and most modules probably won't care, only that the session ended, which is already covered by the existing `core.exit` event.  At the very least, I will see if there's a place in the developer docs for the above trick, of looking at `session.disconnect_reason` in an exit event handler.

**Comment by Castaglia** [comment]
I've now added this to the ProFTPD Developer Guide; see:
* https://github.com/proftpd/devel-guide/blob/master/devel/disconnects.md

With that, I'll consider this ticket closed.  Thanks!
