### ISSUE TITLE
It downloads a "download" file on login cancel

### ISSUE THREAD

**Issue by Hampusm** [proftpd/proftpd#788]
### What I Did

When i press the cancel button in the login menu for my ftp server in the browser it starts downloading a file called "download". 
This applies for all browsers.

### What I Expected/Wanted

For it too not download something.

### ProFTPD Version and Configuration

ProFTPD version 1.3.5b

[proftpd.conf.txt](https://github.com/proftpd/proftpd/files/2906760/proftpd.conf.txt)

**Comment by Castaglia** [comment]
ProFTPD does not create any sort of automatic filename on download; I believe the behavior you are seeing is implemented in the browser, not in ProFTPD.
