### ISSUE TITLE
add ProFTPD icon to font awesome

### ISSUE THREAD

**Issue by SlrG** [proftpd/proftpd#794]
I would like to place an icon request for ProFTPD to the [FontAwesome](https://github.com/FortAwesome/Font-Awesome) project.

The icon would look like this and is a modified version of the original from the ProFTPD homepage:

![105x105_t](https://user-images.githubusercontent.com/978967/54596764-9d0b5b00-4a35-11e9-9272-01681f189299.png)

Would this be okay?

**Comment by SlrG** [comment]
I'm sorry, I probably should have posted the issue for the website and not the source code.

**Comment by Castaglia** [comment]
I think this would be OK with us, yes.  Thanks!

**Comment by SlrG** [comment]
Great! Thank you very much.
