### ISSUE TITLE
libdir is hard-coded in proftpd.pc

### ISSUE THREAD

**Issue by orbea** [proftpd/proftpd#797]
### What I Did

In `proftpd.pc` I see that the `libdir` variable is hardcoded.
```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/proftpd
includedir=${prefix}/include/proftpd

Name: ProFTPD
Description: Professional FTP Daemon
Version: 1.3.6
Requires: 
Libs: -L${libdir}
Cflags: -I${includedir}
```
On my 64-bit system my `proftpd` lib directory is `/usr/lib64/proftpd` and the package is built with `--libdir=/usr/lib64`.

This seems to come from `Makefile.in`.

https://github.com/proftpd/proftpd/blob/bdeaae7e0e1b92cff3f86e4aeffb47a11422bddf/Makefile.in#L130

### What I Expected/Wanted

The created `proftpd.pc` file should set `libdir` according to the configure argument `--libdir`.

### ProFTPD Version and Configuration

```
$ proftpd -v
ProFTPD Version 1.3.6
```
This is on `Slackware64-current` with the default `proftpd` package.

**Comment by Castaglia** [comment]
Can you see if this [PR](https://github.com/proftpd/proftpd/pull/798) fixes this properly for you?
