### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pauldraper** [proftpd/proftpd#806]
It's been over two years from the latest ProFTPD release, with critical fixes since then.

Perhaps one is in order?

**Comment by AliceWonderMiscreations** [comment]
I'll have to look in the git as maybe it is fixed there, but a new release if made should include losing the DH parameters < 2048.

**Comment by GoodMirek** [comment]
New release from 1.3.6 branch (e.g. 1.3.6a) will help a lot for sure. All distributions currently deliver tag 1.3.6 and they seem to deliver fixes only once a new release is created.

**Comment by GoodMirek** [comment]
@Castaglia Please do you see any chance to create a new tag `1.3.6a` on 1.3.6 branch and make it a release?

**Comment by joshk0** [comment]
Mildly interested in a short-lived hostile fork if the maintainer does not answer. If I get 25 positive emojis I'll do it (feel free to suggest names to distinguish the two projects.) Also let me know if you'd be interested in being a maintainer / committer.

**Comment by GoodMirek** [comment]
@joshk0 I do not think a short-lived fork would help anyhow, because it will not be possible to convince Linux distributions to distribute it.
There is no change in code base needed, the major issue is that without a new release the distributions are distributing the old 1.3.6 release dated Apr 10, 2017.

**Comment by Castaglia** [comment]
ProFTPD 1.3.6a and 1.3.7rc1 have now been released.

**Comment by GoodMirek** [comment]
@Castaglia Thanks!
