### ISSUE TITLE
Support adding custom key/values to RedisLogOnCommand

### ISSUE THREAD

**Issue by lon9man** [proftpd/proftpd#811]
### What I Did
i am trying to use **RedisLogOnCommand**. all works fine, 
BUT i get JSON, property-name in which is **FIXED** (or i don't see how to change it using LogFormat-pattern).

my pattern:
`LogFormat user "%u %s"`
resulted JSON:
```
{
    "user": "xxxx", 
    "status": "nnn"
}
```

### What I Expected/Wanted
i want to get message with **custom properties names**, including variables as values OR completely custom values (not variable):
```
{
    "customProperty1": "%u", 
    "customProperty2": "%t", 
    "customProperty3": "customValue"
}
```

### ProFTPD Version and Configuration
**OS:** Ubuntu 18.10
```
    $ proftpd -V

Compile-time Settings:
  Version: 1.3.7rc1 (git)
  Platform: LINUX [Linux 4.18.0-17-generic x86_64]
  Built: чт бер 7 2019 17:07:19 EET
  Built With:
    configure  '--enable-redis' '--enable-dso' '--enable-ctrls' '--enable-nls' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/var/run' '--libexecdir=/usr/lib/proftpd' '--with-shared=mod_sql:mod_sql_mysql:mod_quotatab:mod_quotatab_sql:mod_sql_passwd:mod_ifsession' '--with-includes=/usr/local/include/hiredis' '--with-libraries=/usr/local/lib'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu
  LIBS:  -lssl -lcrypto -L$(top_builddir)/lib/libcap -lcap -lsupp -lnsl -lresolv -lresolv -lcrypt -ldl -lhiredis  -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    + Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment]
Ah, I see the issue.  The `LogFormat` directive allows the admin to configure any _free-form string_.  However, in order to emit well-formed JSON objects, the `RedisLog` directives need to have knowledge about the specific keys/values.  I'll try to find a way to give "hints" to the JSON logger, with regard to custom `LogFormat` fields, for this feature request.

**Comment by Castaglia** [comment]
For this feature, I'm starting to think that it might be done using a new configuration directive for the `mod_redis` module, _e.g._ `RedisJotOnCommand` (for the verb _jot_, meaning "to write down quickly").  This directive would take a redis key, optional expiry/TTL value, and the string to be written as the value.  Any formatting of the string, JSON or otherwise, would be done in configuration.

For example:
```
RedisJotOnCommand APPE,RETR,STOR my_key "{\"customProperty1\":\"%u\"}" TTL 5s
```

**Comment by lon9man** [comment]
@Castaglia it looks like an applicable way. 
_mykey_ - should be dynamic (users:%u:uploads:ftp:xxx). 
AFAIR RedisLogOnCommand can have such dynamic keys.

So it seems abstractly saying:
Class RedisJotOnCommand extends RedisLogOnCommand

**Comment by Castaglia** [comment]
Roughly, yes.  There would be some subtle but important other differences: `RedisLogOnCommand` appends to a Redis list.  The proposed `RedisJotOnCommand` would insert a Redis key (not hash, not list, not set), with optional expiry.

**Comment by lon9man** [comment]
Is it very important (restricted by something) that LIST will be absent in RedisJotOnCommand?
We most often use LIST than other types, very useful approach.

**Comment by Castaglia** [comment]
I'm looking at this again, and thinking about making a different new directive.  That is, rather than a `RedisJotOnCommand`, what if we had a `RedisLogAppend`, for _appending_ extra data to the logged data.  Thus, for your case:
```
LogFormat user "%u %s"
RedisLogOnCommand LIST user ...
RedisLogAppend '{"customProperty1":"%u","customProperty2":"%t","customProperty3": "customValue"}'
```

With this, the keys from the `RedisLogAppend` JSON object would be added to any `RedisLogOnCommand` (and `RedisLogOnEvent`) data.  Any variables in the keys (and values) would be resolved.  Any keys which duplicate data from the `LogFormat` data would be ignored.

**Comment by lon9man** [comment]
@Castaglia, i have 2 questions about implementation.

1. what means `LIST` here -> `RedisLogOnCommand LIST user ...` ?
2. for example i have such logic:
```
    RedisLogOnCommand STOR user upload:ftp
    RedisLogOnCommand STOR file upload:ftp:%u
```
so i save **different** data into **different** redis-keys (redis data type is **LIST**). 
in general way i will want to append some **different** custom-properties to each of them, but i am not sure that your concept about `RedisLogAppend` allows to make it (surely, maybe i didn't understand something important).

as i see it from my side: 
`RedisLogAppend` should have parameter, which will say which concrete log format we want to extend/append using custom-properties. 

for example:
```
    LogFormat user "%u %s"
    LogFormat file "%u %s %f"

    RedisLogOnCommand STOR user upload:ftp
    RedisLogAppend user '{"customProperty1": "%u"}'

    RedisLogOnCommand STOR file upload:ftp:%u
    RedisLogAppend file '{"customProperty2": "%f"}'
```

in this way we can customize all things we have

**Comment by Castaglia** [comment]
Ah, yes, excellent point.  I've also been thinking that "append" isn't quite the right name/concept here.  How about this, then:
```
LogFormat user "%u %s"
LogFormat file "%u %s %f"

# Extra data to include/log with these log formats
RedisLogFormatExtra user '{"customProperty1":"%u"}'
RedisLogFormatExtra file '{"customProperty2":"%f"}'

RedisLogOnCommand STOR user upload:ftp
RedisLogOnCommand STOR file upload:ftp:%u
```

**Comment by lon9man** [comment]
Yes, i think it will work as needed :)!

**Comment by Castaglia** [comment]
This should now be working in master.

**Comment by lon9man** [comment]
I will try it next week.
Thanks!
