### ISSUE TITLE
Proftpd server as c library

### ISSUE THREAD

**Issue by Rohit2387** [proftpd/proftpd#815]
Hi,

Whether proftpd server provide C based library support?
that can be start stop from C program through API?

Br
Rohit

**Comment by Castaglia** [comment]
I think it would be rather difficult to create a C library that provides all of the ProFTPD functionality.  What features/functionality are you specifically looking for?

**Comment by Castaglia** [comment]
I'm going to close this issue for now.

I think the idea is interesting, but would require a lot more discussion of intended use cases, thought about how such a library could/would be embedded, etc.
