### ISSUE TITLE
mod_sql message: 'Unknown character set: 'utf8mb4''

### ISSUE THREAD

**Issue by svoon** [proftpd/proftpd#835]
having mysql server on older version 4.x than the client 8.x causing error during connection:
message: 'Unknown character set: 'utf8mb4''

it is because proftpd is trying to use utf8mb4, which is not supported on older servers. The source code has already condition which charset to use, unfortunately it is checking version of the client, not version of the server.
All the mysql clients are backward compatible, but with this implementation in proftpd mod_sql the backward compatibility is broken.
ondrej

**Comment by Castaglia** [comment]
Where are you seeing "Unknown character set: 'utf8mb4'" being logged?  In the [mod_sql_mysql.c source](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sql_mysql.c#L624), we _attempt_ to set "utf8mb4", but if that fails, it does not cause a fatal error.  So I'm not sure how backward compatibility is broken in this way.  Causing an unnecessary log message, perhaps, but does this cause other issues?

**Comment by svoon** [comment]
Hi
I'm looking into your link, and you are actually right. I'm using debian package proftpd-dfsg-1.3.5b , where the behaviour is implemented differently:
line 547:
    if (mysql_set_character_set(conn->mysql, encoding) != 0) {
      sql_log(DEBUG_FUNC, "%s", "exiting \tmysql cmd_open");
      return _build_error(cmd, conn);
    }

**Comment by Castaglia** [comment]
Looks like that particular code changed in https://github.com/proftpd/proftpd/commit/13446d7c3fab4209376e8f4917338c0141cefcb0, as part of the 1.3.6 development cycle.

I'd like to thus close this ticket, if there are no objections.

**Comment by svoon** [comment]
Hi, agree, thanks a lot.
Ondrej
