### ISSUE TITLE
Proftpd 1.3.6a rpm package related questions

### ISSUE THREAD

**Issue by snjain** [proftpd/proftpd#844]
### What I Did

I have CentOS ( with Linux release 7.7.1908) and tried installing proftpd through epel repo.

Questions  - 
1) When I ran the command 'yum -y install proftpd', it installed the proftpd v 1.3.5e. How can I get proftpd v1.3.6a ? Is this version only available for centos v8 ?

2) Is proftpd 1.3.6a available as a rpm package (and source rpm) in epel repo ? 

3) I could see a source for proftpd v 1.3.6a at this location - ftp://ftp.proftpd.org/distrib/source/ . However if I want to build a rpm package, where can I find the SPECS for proftpd v 1.3.6a ?

4) Currently I am using proftpd v 1.3.3g and if I want to upgrade it to v 1.3.6a, can I use the steps given in this link http://www.proftpd.org/docs/howto/Upgrade.html (regardless of centos version 7 or 8)

### What I Expected/Wanted

1. Expected yum to get the latest stable proftpd release v 1.3.6a

2. Expected to find proftpd v1.3.6a rpm package in epel repo.

3. Expected to find SPEC file in proftpd 1.3.6a source tar ball.

4. Can I try upgrading proftpd v1.3.3g to any higher version regardless of red hat release ?

### ProFTPD Version and Configuration

    $ proftpd -V
    1.3.3g

 I am using proftpd.conf with default directives.

**Comment by Castaglia** [comment]
The ProFTPD Project only provides source code; it does not provide RPMs.  You will have to wait until your distro's package repositories offer the ProFTPD 1.3.6a RPM.  You can find the `.spec` file distributed with the ProFTPD source, and on GitHub, _e.g._ [here](https://github.com/proftpd/proftpd/blob/1.3.6/contrib/dist/rpm/proftpd.spec).

**Comment by snjain** [comment]
Thanks for your quick response.

Usually how long does it take for proftpd new releases to be updated in epel repositories? Looks like for epel6, the proftpd version found is 1.3.3g and epel7, the proftpd version found is 1.3.5e. 

Does this also mean that the proftpd version 1.3.6a would only be available in epel8 ?

If I make a custom build for proftpd version 1.3.6a, will it be compatible with rhel-6 and rhel-7 ?

Thanks,
Shailendra

**Comment by Castaglia** [comment]
I don't know; you would have to find the maintainers of the ProFTPD RPMs, and ask them.  We don't usually keep track of the timelines/schedules for packages.

**Comment by snjain** [comment]
Thanks for the information 

-shailendra
