### ISSUE TITLE
Proftpd - postgres related questions

### ISSUE THREAD

**Issue by snjain** [proftpd/proftpd#845]
### What I Did

I am using red hat release 6.10 and proftpd v1.3.3g with mysql version 5.6  I would like to switch from using mysql v5.6 to latest version of postgres 

Questions  - 

1. Is latest version of postgres supported for proftpd v 1.3.3g ? If not what is the postgres version that proftpd v1.3.3g supports ?
2. Is latest version of postgres supported for proftpd v 1.3.6a ?
3. Can proftpd connect to postgres database remotely ? My understanding is that I need to compile proftpd with the mod_sql SQL module with the libraries and header files (ibpq-fe.h and libpq.a) of a Postgres in a build machine. Once built, I can deploy proftpd to target machine and connect to postgres db remotely.

### What I Expected/Wanted

1. Latest version of postgres is supported for proftpd v1.3.3g

2. Latest version of postgres is supported for proftpd v1.3.6a

3. Please confirm if Proftpd v1.3.3g / 1.3.6a can connect to postgres db remotely. What changes do I need to make in proftpd.conf to make this work ?

### ProFTPD Version and Configuration

    $ proftpd -V
    1.3.3g

    Using proftpd.conf with default directives.

**Comment by Castaglia** [comment]
ProFTPD's `mod_sql_postgres` module uses the [libpq](https://www.postgresql.org/docs/9.5/libpq.html) Postgres client library, so ProFTPD can connect to any version of Postgres supported by that `libpq` library.

Yes, ProFTPD can absolutely connect to remote databases, including Postgres.

In your ProFTPD configuration, you might have something like the following for your MySQL connection:
```
SQLBackend mysql

# Include the info for connecting to MySQL
SQLConnectInfo ...
```
To use Postgres instead, your ProFTPD will need to have the `mod_sql` and `mod_sql_postgres` modules compiled and loaded, and then your configuration would be:
```
SQLBackend postgres

# Include the info for connecting to Postgres
SQLConnectInfo ...
```
Changing the [`SQLBackend`](http://www.proftpd.org/docs/contrib/mod_sql.html#SQLBackend) directive should be all that you need.

**Comment by Castaglia** [comment]
Closing this ticket as there's been no additional commentary/feedback for a few months.
