### ISSUE TITLE
mod_tls should honor SNI in TLS handshake

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#850]
ProFTPD currently supports name-based virtual hosts via the `HOST` command, as defined in [RFC 7151](https://tools.ietf.org/html/rfc7151).  However, it would be nice if name-based virtual hosts were also supported via TLS [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) _as well_.  That way, FTPS clients using/providing SNI can be used for name-based virtual hosts, without necessarily requiring that the `HOST` command be used.

**Comment by Castaglia** [comment]
We should also provide a `TLSOption` for ignoring/not using any SNI for these purposes, for backward compatibility/configurability.

**Comment by Castaglia** [comment]
Merged to master.

**Comment by Castaglia** [comment]
Re-opening this, as the implementation works for selecting a name-based vhost based on SNI, but *not* for selecting the proper server certificates from that named vhost during the TLS handshake.

**Comment by e-fik123** [comment]
Hi good news to hear that.
But i would need you to help me out with my configuration. As i use mod_proxy to fwd all FTP connections to backend servers.
For mod_proxy to determine which backend server to use i use mod_sql.
Using SNI in mod_tls requires to use for each domain extra <virtualhost> which is not the best way as i would just specify tls certificate based on domain and use again mod_proxy and mod_sql
Can you pls let me know how to contact you with my config.
Regards

**Comment by Castaglia** [comment]
@e-fik123 sure, send me details about your mod_proxy/mod_sql/SNI configuration directly via email, please.

**Comment by Castaglia** [comment]
Fixed in master.
