### ISSUE TITLE
SFTP Not Logging all Commands to ExtendedLog 

### ISSUE THREAD

**Issue by jpfinger** [proftpd/proftpd#862]
### Environment

  ProFTPd: 1.3.6c, git 4fedb39
  OS: CentOS Linux release 7.7.1908 (Core)
  proftpd-mod_vroot-master-dc2d63b

### What I Did

  I Updated ProFTPd from 1.3.5d to 1.3.6c-4fedb39.
  
  SFTP transfers no longer add "RETR" (and possibly other) commands in customized/extended logs.

  In our proftpd.conf, we have customized logging:
  ```
  Top-level
    ...
    LogFormat ourlog "%u||%m||%{transfer-status}||%f"
    ...

  <Global>
    ...
    ExtendedLog /opt/proftpd/logs/proftpext.log
    ExtendedLog /opt/proftpd/logs/xferlog-our.log READ,WRITE ourlog
    ...

  <IfModule mod_sftp.c>
    ...
    SFTPLog /opt/proftpd/logs/sftp.log
    ...
```
  
  Our "xferlog-our.log" lines now look like this on a file pull:
```
    account||LSTAT||-||-
    account||STAT||-||-
    account||OPEN||-||/outgoing/test.txt
    account||READ||-||/outgoing/test.txt
    account||READ||-||/outgoing/test.txt
    account||CLOSE||-||/outgoing/test.txt
```  
  Adding the 'ExtendedLog ... ourlog' line to the mod_sftp.c section has no affect.  Changing the %f to $F also did not help.

  Traditional outgoing FTP transfers show the RETR commands.  While testing this, I noticed that scp transfers logged nothing to the custom log.

### What I Expected/Wanted

  In our previous versions including 1.3.5d, we saw extended log activity including RETR on SFTP transfers:
```
    account||LSTAT||-||-
    account||STAT||-||-
    account||OPEN||-||/outgoing/test.txt
    account||READ||-||/outgoing/test.txt
    account||READ||-||/outgoing/test.txt
    account||RETR||success||/foo/bar/account/outgoing/test.txt
    account||CLOSE||-||/outgoing/test.txt
```
### ProFTPD Version and Configuration
```
Compile-time Settings:
  Version: 1.3.6c (git)
  Platform: LINUX [Linux 3.10.0-1062.4.1.el7.x86_64 x86_64]
  Built: Mon Nov 4 2019 20:29:12 GMT
  Built With:
    configure  '--prefix=/opt/proftpd-1.3.6c-4fedb39' '--enable-ctrls' '--with-modules=mod_sftp:mod_tls:mod_ifsession:mod_ban:mod_auth_pam:mod_vroot'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lpam  -lssl  -lcrypto -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /opt/proftpd-1.3.6c-4fedb39/etc/proftpd.conf
    Pid File:
      /opt/proftpd-1.3.6c-4fedb39/var/proftpd.pid
    Scoreboard File:
      /opt/proftpd-1.3.6c-4fedb39/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    - Redis support
    - Sodium support
    + OpenSSL support (FIPS enabled)
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment]
I believe this is fallout from [Bug#4067](http://bugs.proftpd.org/show_bug.cgi?id=4067).  To see the SFTP requests in your `ExtendedLog`, you might trying:
```
ExtendedLog /opt/proftpd/logs/xferlog-our.log SFTP,READ,WRITE ourlog
```

**Comment by jpfinger** [comment]
Thanks for the quick response.  Unfortunately adding SFTP to ExtendedLog doesn't fix the issue.  I tried adding it in addition to the existing ExtendedLog line, and to a SFTP-specific ExtendedLog in the mod_sftp section.  For the mod_sftp specific tests, I tried with both the same xferlog-our.log and a separate log file.

**Comment by jpfinger** [comment]
If I compile without mod_vroot (git revision dc2d63b), the RETR lines return to the custom log.  

This is without the 'SFTP' parameter in the ExtendedLog line.

**Comment by Castaglia** [comment]
Ah, interesting find!  Thanks for that.  I'll see if I can reproduce this behavior locally, with that information.

**Comment by Castaglia** [comment]
Which version of `mod_vroot` are you using?

**Comment by jpfinger** [comment]
The latest git revision from https://github.com/Castaglia/proftpd-mod_vroot, dc2d63b .

**Comment by Castaglia** [comment]
What happens if you put `mod_vroot` before `mod_sftp` in your `--with-modules` build command?  I'll try the same locally; I suspect the issue is related to https://github.com/Castaglia/proftpd-mod_vroot/commit/e60afa7be9c594d41f7d3088f781ead8a41de2cb#diff-8325f2fe6198771a8d71bf54cceee927, and to module load order/command dispatch order.

**Comment by Castaglia** [comment]
Nope, not related to that commit; I'm reproducing the behavior locally now.

**Comment by Castaglia** [comment]
Ah, found the problem -- it _is_ the `CMD` phase handlers in `mod_vroot`.  This should now be fixed by https://github.com/Castaglia/proftpd-mod_vroot/commit/3ea9ea41dd5b20d6b4e6b5c644f9389de5130116.

**Comment by jpfinger** [comment]
After updating mod_vroot, the RETR lines are there.  Hooray!

Unfortunately, it is not honoring the %f versus %F of LogFormat.  Both meta sequences are reporting the chrooted filename.  Previously, and without mod_vroot, %f gave us the full non-chrooted path.

**Comment by Castaglia** [comment]
Hrm.  Sounds similar to https://github.com/Castaglia/proftpd-mod_vroot/issues/16, put perhaps there's a regression?  Will check.

**Comment by jpfinger** [comment]
The issue is filed.  Thanks for your help on this.

**Comment by Castaglia** [comment]
@jpfinger I think this ticket can be closed now.  Any objections?

**Comment by jpfinger** [comment]
No objections.  After the recent commit and the most-recent mod_vroot, it looks good.  Thank you!
