### ISSUE TITLE
ExecOnCommand error with /dev/null for stdin

### ISSUE THREAD

**Issue by matrixise** [proftpd/proftpd#864]
I have an issue with ExecOnCommand with 1.3.6, I didn't check with another version.

```
mod_exec/0.9.16[29096]: preparing to execute '/tmp/ftp-logger.py' with uid 1000 (euid 1000), gid 1000 (egid 1000)
mod_exec/0.9.16[29096]:  + '/tmp/ftp-logger.py': argv[1] = --user
mod_exec/0.9.16[29096]:  + '/tmp/ftp-logger.py': argv[2] = ftp
mod_exec/0.9.16[29096]:  + '/tmp/ftp-logger.py': argv[3] = --file
mod_exec/0.9.16[29096]:  + '/tmp/ftp-logger.py': argv[4] = /home/ftp/test-ftp-demo.py
mod_exec/0.9.16[29096]:  + '/tmp/ftp-logger.py': argv[5] = 172.17.0.1
mod_exec/0.9.16[29096]: error: unable to open /dev/null for stdin: No such file or directory
mod_exec/0.9.16[29095]: '/tmp/ftp-logger.py' terminated normally, with exit status 2
mod_exec/0.9.16[29095]: STOR ExecOnCommand '/tmp/ftp-logger.py' failed: No such file or directory
```
[Dockerfile-debug.txt](https://github.com/proftpd/proftpd/files/3814556/Dockerfile-debug.txt)
Content of `ftp-logger.py`
```python
#!/usr/bin/env python
from __future__ import print_function
import time
import sys


```

and the command:

```
./proftpd -n -d 10 -c /srv/proftpd.conf -X
```

You can find my proftpd.conf file [proftpd.conf.txt](https://github.com/proftpd/proftpd/files/3814572/proftpd.conf.txt)

**Comment by matrixise** [comment]
[Dockerfile-debug.txt](https://github.com/proftpd/proftpd/files/3814556/Dockerfile-debug.txt)
Content of `ftp-logger.py`
```python
#!/usr/bin/env python
from __future__ import print_function
import time
import sys


```

**Comment by matrixise** [comment]
No idea?

**Comment by Castaglia** [comment]
I haven't had time to look into this yet.

**Comment by matrixise** [comment]
@Castaglia I could help you with this issue, What do you need? a complete dockerfile and makefile? I could create a repository for this issue.

**Comment by Castaglia** [comment]
Ah, I have an idea.  Your `proftpd.conf` uses:
```
# To cause every FTP user to be "jailed" (chrooted) into their home
# directory, uncomment this line.
DefaultRoot /home/ftp
```
Which means that the session process will be chrooted into `/home/ftp`.  Then later, when `mod_exec` tries to execute your Python script, it tries to find the Python interpreter to run, via the `#!/usr/bin/env python` line.  But _within the chroot_, that `/usr/bin/env` path probably doesn't exist -- nor does a Python interpreter.  Hence the "no such file or directory" error.

This is an unfortunate complication when using `mod_exec` scripts in combination with `DefaultRoot`.  A workaround is to use the `mod_vroot` module, which does not actually use the `chroot(2)` system call.

**Comment by matrixise** [comment]
Thanks, I will try on tomorrow.

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.   Assuming the above properly explains the behavior you see, I add it to the `mod_exec` docs, for future readers.
