### ISSUE TITLE
Leaking PAM handler and data in case of unsuccessful authentication

### ISSUE THREAD

**Issue by polter-rnd** [proftpd/proftpd#870]
### What I Did

1. Wrote a simple PAM module and used `pam_set_data()` for storing some data for the PAM  transaction;
1. Added data cleanup callback, so after PAM  transaction ends, memory releases.
1. Added log message from cleanup callback to ensure that is was called.

### What I Expected/Wanted

Expected behavior should meet [PAM documentation (paragraph 3.1.2)](http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html): 

>  The pam_end function terminates the PAM transaction and is the last function an application should call in the PAM context. Upon return the handle pamh is no longer valid and all memory associated with it will be invalid.
> The pam_status argument should be set to the value returned to the application by the last PAM library call.
> The value taken by pam_status is used as an argument to the module specific callback function, cleanup()

So we expect that `pam_end()` have to be called after any PAM transaction, PAM handler memory will be released and module's cleanup function will be called.

### What actually happens

ProFTPD does not call pam_end() for unsuccessul transactions, so PAM handler leaks as well as all data stored in transaction using `pam_set_data()`.

### Steps to reproduce

Affects all versions, tested on v1.6.3 and master.

- Create proftpd_test.c file with the following code (sample PAM module):

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>

#include <security/pam_modules.h>
#include <security/pam_ext.h>

#define PAM_DATA_NAME "our_test_data"
#define PAM_DATA_SIZE 1024

static void data_cleanup(pam_handle_t *pamh, void *data_arg, int error_status) {
    char *data = (char *) data_arg;
    pam_syslog(pamh, LOG_ERR, "pam_end() has been called, data=\"%s\", status=%d",
               data, error_status);
    free(data);
}

PAM_EXTERN int pam_sm_setcred(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SUCCESS;
}


PAM_EXTERN int pam_sm_authenticate(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    char *data = NULL;
    int rv = pam_get_data(pamh, PAM_DATA_NAME, (const void **) &data);
    if (rv != PAM_SUCCESS) {
        data = calloc(1, PAM_DATA_SIZE);
        if (data == NULL) {
                return PAM_ABORT;
        }

        strncpy(data, "Hello from pam_sm_authenticate!", PAM_DATA_SIZE);
        rv = pam_set_data(pamh, PAM_DATA_NAME, data, data_cleanup);
        if (rv != PAM_SUCCESS) {
            free(data);
        } else {
            pam_syslog(pamh, LOG_ERR, "pam_set_data() has been called, data=\"%s\"", data);
        }
    }

    return PAM_IGNORE;
}
```

- Compile module with `gcc proftpd_test.c -Werror -fPIC -shared -o pam_proftpd_test.so` 
- Put `pam_proftpd_test.so` to the directory with PAM modules (`/lib64/security` on RedHat/CentOS)
- Create file `/etc/pam.d/proftpd` with following content:

```
#%PAM-1.0
auth       required     pam_proftpd_test.so
auth       sufficient   pam_unix.so nullok try_first_pass
auth       required     pam_deny.so
account    required     pam_permit.so
session    required     pam_permit.so
```

- Change ProFTPD configuration by commenting out `AuthPAM off` if any and adding following lines:

```
AuthOrder mod_auth_pam.c* mod_auth_unix.c
AuthPAM on
AuthPAMConfig proftpd
```

- Open system log and wait for messages (`journalctl -f -u proftpd` for RedHat/CentOS 7+)
- Connect to ProFTPD server with right credentials and immediately disconnect
- See following lines in log:

```
proftpd[...]: pam_proftpd_test(proftpd:auth): pam_set_data() has been called, data="Hello from pam_sm_authenticate!"
proftpd[...]: ... USER user1: Login successful.
proftpd[...]: PAM pam_end() has been called, data="Hello from pam_sm_authenticate!", status=0
```

This is okay, since `status=0` means `PAM_SUCCESS`.

- Connect to ProFTPD server with existing user but wrong password, then disconnect
- See following lines in log:

```
proftpd[...]: pam_set_data() has been called, data="Hello from pam_sm_authenticate!"
proftpd[...]: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd21531 ruser=user1 rhost=::1  user=user1
proftpd[...]: ... USER user1 (Login failed): Incorrect password
```

This is **BUG** and memory leak, since FTP session ended but PAM handler as well as our data are still not released (`pam_end()` not called).

**Comment by Castaglia** [comment]
Merged and backported.  Thanks!
