### ISSUE TITLE
Fatal: SFTPKeyExchanges: unsupported key exchange algorithm: ecdh-sha2-nistp256

### ISSUE THREAD

**Issue by CameronGo** [proftpd/proftpd#881]
### What I Did
With this entry in my sftp.conf file:
```SFTPKeyExchanges ecdh-sha2-nistp256```

On startup I get this error:
```proftpd[1]: Fatal: SFTPKeyExchanges: unsupported key exchange algorithm: ecdh-sha2-nistp256 on line 32 of '/etc/proftpd/conf.d/sftp.conf'```

I get the same with ecdh-sha2-nistp384 and ecdh-sha2-nistp521 as well.

If I change it to:
```SFTPKeyExchanges diffie-hellman-group-exchange-sha256```

The application starts up fine and support is limited to just the expected key exchange algorithm.

If I remove that line from the config entirely and then check the supported key exchange algorithms, I see support for several algorithms including the ecdh-sha2-nistp256 ecdh-sha2-nistp384 and ecdh-sha2-nistp521.

### What I Expected/Wanted
I want to specify the list of key exchange algorithms and include 
```SFTPKeyExchanges diffie-hellman-group-exchange-sha256 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521```

### ProFTPD Version and Configuration
I'm running this inside a Docker container from the Ubuntu 14.04 base image with 
ProFTPD 1.3.5rc3 and OpenSSL 1.0.1f 

A redacted copy of my sftp.conf file:
```
<IfModule mod_sftp.c>
    ServerName xxxxx
    
    DisplayConnect /etc/proftpd/welcome.msg

    SFTPEngine on
    Port 2222
    DefaultRoot ~
    RequireValidShell off
    Umask 007 007 #Needs to be in the main config file

    # Configure both the RSA and DSA host keys, using the same host key
    # files that OpenSSH uses.
    SFTPHostKey /etc/ssh/ssh_host_rsa_key
    SFTPHostKey /etc/ssh/ssh_host_dsa_key

    #SFTPAuthMethods publickey keyboard-interactive

    SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u

    # Enable compression
    SFTPCompression delayed

    # Supported encryption algorithms
    SFTPCiphers aes256-ctr aes192-ctr aes128-ctr aes256-cbc aes192-cbc aes128-cbc

    # Supported MAC algorithms
    SFTPDigests hmac-sha2-256 hmac-sha2-512 hmac-ripemd160

    # Supported Key Exchange algorithms
    SFTPKeyExchanges diffie-hellman-group-exchange-sha256 ecdh-sha2-nistp256
</IfModule>
```

**Comment by Castaglia** [comment]
Interesting. I am wondering if it is related the algorithms enabled in your OpenSSL installation.  What does `openssl version -a` show?

**Comment by CameronGo** [comment]
Here you go:
```
OpenSSL 1.0.1f 6 Jan 2014
built on: Tue Dec  4 20:09:18 UTC 2018
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"

**Comment by Castaglia** [comment]
Got it.  Thanks!  The command to run, to see _its_ output, is `openssl ecparam -list_curves` -- can you show that command provides for you?

**Comment by CameronGo** [comment]
Sure - here is the full list
```
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  sect113r1 : SECG curve over a 113 bit binary field
  sect113r2 : SECG curve over a 113 bit binary field
  sect131r1 : SECG/WTLS curve over a 131 bit binary field
  sect131r2 : SECG curve over a 131 bit binary field
  sect163k1 : NIST/SECG/WTLS curve over a 163 bit binary field
  sect163r1 : SECG curve over a 163 bit binary field
  sect163r2 : NIST/SECG curve over a 163 bit binary field
  sect193r1 : SECG curve over a 193 bit binary field
  sect193r2 : SECG curve over a 193 bit binary field
  sect233k1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect233r1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect239k1 : SECG curve over a 239 bit binary field
  sect283k1 : NIST/SECG curve over a 283 bit binary field
  sect283r1 : NIST/SECG curve over a 283 bit binary field
  sect409k1 : NIST/SECG curve over a 409 bit binary field
  sect409r1 : NIST/SECG curve over a 409 bit binary field
  sect571k1 : NIST/SECG curve over a 571 bit binary field
  sect571r1 : NIST/SECG curve over a 571 bit binary field
  c2pnb163v1: X9.62 curve over a 163 bit binary field
  c2pnb163v2: X9.62 curve over a 163 bit binary field
  c2pnb163v3: X9.62 curve over a 163 bit binary field
  c2pnb176v1: X9.62 curve over a 176 bit binary field
  c2tnb191v1: X9.62 curve over a 191 bit binary field
  c2tnb191v2: X9.62 curve over a 191 bit binary field
  c2tnb191v3: X9.62 curve over a 191 bit binary field
  c2pnb208w1: X9.62 curve over a 208 bit binary field
  c2tnb239v1: X9.62 curve over a 239 bit binary field
  c2tnb239v2: X9.62 curve over a 239 bit binary field
  c2tnb239v3: X9.62 curve over a 239 bit binary field
  c2pnb272w1: X9.62 curve over a 272 bit binary field
  c2pnb304w1: X9.62 curve over a 304 bit binary field
  c2tnb359v1: X9.62 curve over a 359 bit binary field
  c2pnb368w1: X9.62 curve over a 368 bit binary field
  c2tnb431r1: X9.62 curve over a 431 bit binary field
  wap-wsg-idm-ecid-wtls1: WTLS curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls3: NIST/SECG/WTLS curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls4: SECG curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls5: X9.62 curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls10: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls11: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls12: WTLS curvs over a 224 bit prime field
  Oakley-EC2N-3:
        IPSec/IKE/Oakley curve #3 over a 155 bit binary field.
        Not suitable for ECDSA.
        Questionable extension field!
  Oakley-EC2N-4:
        IPSec/IKE/Oakley curve #4 over a 185 bit binary field.
        Not suitable for ECDSA.
        Questionable extension field!

**Comment by Castaglia** [comment]
Interesting.  According to the `openssl ecparam` output, you _should_ be able to use that ECDH algorithm.  Hmm.  I wonder if the `proftpd` executable you installed was compiled with a _different_ OpenSSL?  The reason being that the error you are encountering occurs when ProFTPD thinks that OpenSSL doesn't have support for EC curves; that support is detected at build time.

Would you happen to have a Dockerfile for this container, so that I can attempt to reproduce this locally?

**Comment by Castaglia** [comment]
Another way to check is for you to include the `include/proftpd/config.h` file, from where your installed ProFTPD lives, _e.g._ `/usr/local/proftpd/include/proftpd/config.h`.  That file contains a lot of the build-time test results; for purposes of this ticket, the relevant line will contain `PR_USE_OPENSSL_ECC`.

**Comment by CameronGo** [comment]
Below is a copy of my Dockerfile as requested.  I've done a search in the resulting container for the config.h file you mentioned and I don't see one anywhere.

```
FROM ubuntu:14.04

RUN apt-get update && \
    apt-get -y install cryptsetup proftpd openssh-server python-pip && \
    pip install awscli && \ 
    apt-get -y autoremove && apt-get -y autoclean && \
    /bin/sed -i "s/Umask*/#Umask/" /etc/proftpd/proftpd.conf && \
    rm /etc/update-motd.d/* && rm /run/motd.dynamic && rm /etc/legal && \
    addgroup sftpaccess && addgroup sftpowners
    
COPY ./etc /etc

RUN /usr/sbin/proftpd --configtest

COPY ./launch.sh /
    
EXPOSE 2222

ENTRYPOINT ["/bin/bash","launch.sh"]

**Comment by Castaglia** [comment]
Thanks!  Using that Docker image, I was able to find the necessary `config.h` file, using:
```
# apt-get install -y proftpd-dev
```
And see:
```
# grep _ECC /usr/include/proftpd/config.h 
#define PR_USE_OPENSSL_ECC 1
```
Very confusing.

So then I modified the `/etc/apt/source.list` file to include source packages, and installed the source for the proftpd package installed:
```
$ apt-get -y source proftpd-basic
```
And then:
```
$ cd proftpd-dfsg-1.3.5~rc3/
$ view contrib/mod_sftp/mod_sftp.c
```
and looked at the source code for handling of the `SFTPKeyExchanges` directive.  And _that_, in turn, led me to [this commit](https://github.com/proftpd/proftpd/commit/c9099e4915189e46ad47ef84bcf729fd71b5b4e9), which is where support for setting those via config directive was added: 1.3.5a.  Which is _after_ the 1.3.5rc3 version of the proftpd packaged installed for that Ubuntu 14.04 version.  Unfortunately.

**Comment by CameronGo** [comment]
Well, that is good detective work.  that is not sounding promising for a resolution on Ubuntu 14.04 then I take it.

Wondering if it might go that way, I started tinkering with other Ubuntu versions in the docker image.  16.04 unfortunately has a weird install quirk that prompts for standalone or not during apt-get install.  So then I went to 18.04 and starting running into this: https://github.com/proftpd/proftpd/issues/789.

Seems like there aren't any super great options in front of me as it stands.

**Comment by Castaglia** [comment]
There _is_ a way to automate the install of `proftpd-basic`, on Ubuntu 16 (or other versions).

This gives us the following Dockerfile:
```
FROM ubuntu:16.04

COPY proftpd.debconf .

RUN apt-get update && \
  apt-get install -y debconf-utils && \
  debconf-set-selections --verbose ./proftpd.debconf && \
  apt-get install -y proftpd-basic

CMD ["bash"]
```
And accompanying `proftpd.debconf`, to be in the same directory:
```
# debconf-get-selections | grep proftpd-basic
proftpd-basic	shared/proftpd/inetd_or_standalone	select	standalone
```
This [StackOverflow question](https://serverfault.com/questions/138067/automate-proftpd-basic-install-on-ubuntu-using-apt-get) helped with this.  I started with Ubuntu 16.04, ran:
```
$ sudo apt-get install -y proftpd-basic
```
manually selected "standalone", then ran:
```
$ debconf-get-selections | grep proftpd-basic
```
to discover the contents for that file, to feed into `debconf-set-selections` in the resulting Dockerfile.

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.

**Comment by CameronGo** [comment]
Thanks for the help.  Sure you can close it.  I haven't updated my prod deployment yet, but I have a test instance up and running on Ubuntu 18 right now and am just disabling PAM for now, which doesn't _appear_ to negatively impact my deployment.  After I've tested more if I run into issues I may circle back to using Ubuntu 16.  For reference here is my Dockerfile in my test deployment:

```
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get -y install proftpd openssh-server && \
    apt-get -y autoremove && apt-get -y autoclean

RUN /bin/sed -i "s/Umask*/#Umask/" /etc/proftpd/proftpd.conf && \
    /bin/sed -i "s/LoadModule mod_sftp_pam.c/#LoadModule mod_sftp_pam.c/" /etc/proftpd/modules.conf && \
    rm /etc/update-motd.d/* && rm /usr/share/base-files/motd && rm /etc/legal 
    
COPY ./etc /etc

RUN /usr/sbin/proftpd --configtest

COPY ./launch.sh /
    
EXPOSE 2222

ENTRYPOINT ["/bin/bash","launch.sh"]
```
