### ISSUE TITLE
HTTP configuration source

### ISSUE THREAD

**Issue by wasabii** [proftpd/proftpd#895]
This is an enhancement request for a HTTP-based configuration delivery module. Much like `mod_conf_sql` and `mod_conf_ldap`. I'd sort of expect the delivery from HTTP to just be a standard ProFTPd configuration file format.

**Comment by Castaglia** [comment]
Why not have an external script which reads from the HTTP server, writes out the ProFTPD config file, and tells ProFTPD to read from the file as normal?

**Comment by wasabii** [comment]
I want to give you a good answer, but the answer I have sucks. I am doing some work getting ProFTPD running inside of an orchestration framework. Where configuration is auto generated based on containers or other things moving around inside the cluster. It changes a lot. ProFTPD serves as an ingress controller in here, using mod_proxy. And pointing to dynamic backend services that come and go.

So, lots of configuration changes.

Also, I'm going to be running it on Windows. I'd like to get a MINGW build going. But, I don't know how much success I'll have with that. And, if I do, it's SIGHUP support is pretty bad. A Cygwin build might work better, since I could rewrite configuration and SIGHUP it with some specially created utilities.

All that said, it would be quite a bit nicer, if it just yanked configuration at runtime from another internal side-car service in the cluster. Probably by downloading it through HTTP.

**Comment by Castaglia** [comment]
I just finished writing a `mod_conf_url` module, which should be able to do what you want; see:
  https://github.com/Castaglia/proftpd-mod_conf_url

**Comment by wasabii** [comment]
Wow. Dude. That was fast. I'll take a look at it and see if I can make it work in my situation.

Gotta get over this "build it for Win32" thing first. Heh.

**Comment by Castaglia** [comment]
No worries.  I'll close this ticket, then -- any issues/requests for that module can be tracked in that module's project separately.  Thanks!
