### ISSUE TITLE
How can I log the KeyExchange algorithms used

### ISSUE THREAD

**Issue by CameronGo** [proftpd/proftpd#896]
### What I Did

I am running profptd with debug 10 and I get log data from stderr and stdout

### What I Expected/Wanted

I want to see the KeyExchange altorithms used with each connection, ideally also the encryption and MAC algorithms, so that I can confirm no one is using the less secure algorithms before I disable them.

### ProFTPD Version and Configuration

I am running ProFTPD Version 1.3.5e in Ubunut 18.04, which was installed from apt-get into a docker image.

Here is my conf file:
```
<IfModule mod_sftp.c>
    ServerName sftp.xxxxx.com 
  
    SFTPEngine on
    Port 2222
    DefaultRoot ~
    RequireValidShell off
    Umask 007 007 #Needs to be in the main config file

    # Configure both the RSA and DSA host keys, using the same host key
    # files that OpenSSH uses.
    SFTPHostKey /etc/ssh/ssh_host_rsa_key

    SFTPAuthorizedUserKeys file:/etc/proftpd/authorized_keys/%u

    # Enable compression
    SFTPCompression delayed

    # Supported encryption algorithms
    SFTPCiphers aes256-ctr aes192-ctr aes128-ctr

    # Supported MAC algorithms
    SFTPDigests hmac-sha2-256 hmac-sha2-512 hmac-ripemd160

    # Supported Key Exchange algorithms
    # SFTPKeyExchanges diffie-hellman-group-exchange-sha256 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521
</IfModule>
```
And attached are the logs I see after establishing a test connection, but see no mention of algorithms in use.

[sftpserver.log](https://github.com/proftpd/proftpd/files/4194585/sftpserver.log)

**Comment by Castaglia** [comment]
The [`SFTPLog`](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPLog), when configured, will contain this information.

**Comment by CameronGo** [comment]
OK - that is definitely the config option I was missing, though unfortunately it looks like I won't be able to quite get what I need as I'm in the same boat as described here https://github.com/proftpd/proftpd/issues/724.

I will follow that issue and close this one out.  And thank you for the quick response!
