### ISSUE TITLE
Segfault running LIST or NLST on Mac

### ISSUE THREAD

**Issue by muirmanders** [proftpd/proftpd#90]
I also submitted this here http://bugs.proftpd.org/show_bug.cgi?id=4156, not sure if you still use that bug tracking system.

LIST and NLST are crashing proftpd for me. In fsio.c pr_fsio_opendir calls
pr_fs_setcwd(pr_fs_getcwd()). That ends up effectively calling strlcpy(cwd,
cwd, sizeof(cwd)), which segfaults.

OS X 10.10

I'm running proftpd as non-root. "users.txt" has a single user with my pid/gid
and a home directory owned by me as well.

ServerType standalone
Port 2123
DefaultAddress 127.0.0.1

AuthUserFile /tmp/proftpd/users.txt
AuthOrder mod_auth_file.c

PidFile /tmp/proftpd/proftpd.pid
ScoreboardFile /tmp/proftpd/proftpd.scoreboard
TransferLog /tmp/proftpd/transfer.log

User muir
Group staff

**Comment by Castaglia** [comment]
In general, we prefer to use the ProFTPD Bugzilla instance for tracking, since that's where our historical bulk of bug reports are filed.  But filing an issue here works just as well.

Per Bug#4156, there's a PR to hopefully fix this issue; see:

  https://github.com/proftpd/proftpd/pull/91

**Comment by Castaglia** [comment]
The PR has been merged; this issue should now be fixed.  Please reopen if that is not the case.  Thanks!
