### ISSUE TITLE
error: unable to bind to local socket: Address already in use

### ISSUE THREAD

**Issue by ZerooCool** [proftpd/proftpd#914]
With debian buster 10

sudo dpkg -l| grep proftpd
ii  proftpd-basic        1.3.6-6       amd64        Versatile, virtual-hosting FTP daemon - binaries

More info :
I manage to connect to my FTP from my internet box from home.
I have an error from the wifi of my mobile phone (with the operator SFR)
The investigation brings me back to this issue:

#501 #508

# From FileZilla :
```
Statut :	Connexion à 139.99.173.195:21...
Statut :	Connexion établie, attente du message d'accueil...
Réponse :	220 ProFTPD Server (Debian) [::ffff:139.99.173.195]
Commande :	AUTH TLS
Réponse :	502 AUTH TLS exécuté avec succès
Commande :	AUTH SSL
Erreur :	Impossible de lire depuis le socket : ECONNRESET - Connexion réinitialisée par un pair
Erreur :	Impossible d'établir une connexion au serveur
```

**Impossible de lire depuis le socket : ECONNRESET**

# Erreur from log file :
```
2020-02-26 16:18:10,383 mod_tls/2.7[6537]: TLS/TLS-C requested, starting TLS handshake
2020-02-26 16:18:10,753 mod_tls/2.7[6537]: unable to accept TLS connection: system call error: [104] Connexion ré-initialisée par le correspondant
2020-02-26 16:18:10,753 mod_tls/2.7[6537]: TLS/TLS-C negotiation failed on control channel
```

```
# This socket error raised me to this previously reported error:
sudo proftpd --configtest
Checking syntax of configuration file
proftpd[16691]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
```

**mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use**

```
# The following folder is supposed to contain the proftpd.sock file according to the configuration of ProFTPd from the conf file.
# It is currently empty when I consult it.
# A proftpd.sock file already exists in the directory /run/
```

```
# I am trying to display the list of ProFTPd modules:
sudo ftpdctl lsmod
ftpdctl: error contacting server using '/run/proftpd.sock': Connection refused
```

**sudo ftpdctl lsmod
ftpdctl: error contacting server using '/run/proftpd.sock': Connection refused**

```
# I am trying to trace the order for more information.
sudo apt install strace
strace -e open,unlink,bind,close /usr/sbin/proftpd --configtest

close(1022)                             = -1 EBADF (Mauvais descripteur de fichier)
close(1023)                             = -1 EBADF (Mauvais descripteur de fichier)
close(-1)                               = -1 EBADF (Mauvais descripteur de fichier)
Checking syntax of configuration file
close(-1)                               = -1 EBADF (Mauvais descripteur de fichier)
close(3)                                = 0
...
close(4)                                = 0
bind(4, {sa_family=AF_UNIX, sun_path="/run/test.sock"}, 110) = -1 EACCES (Permission non accordée)
close(4)                                = 0
unlink("/run/test.sock")                = -1 ENOENT (Aucun fichier ou dossier de ce type)
bind(4, {sa_family=AF_UNIX, sun_path="/run/proftpd.sock"}, 110) = -1 EADDRINUSE (Adresse déjà utilisée)
close(4)                                = 0
2020-02-26 22:51:48,094 vps178370 proftpd[22647]: mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use
close(4)                                = 0
close(6)                                = 0
...
close(5)                                = 0
2020-02-26 22:51:48,231 vps178370 proftpd[22647]: mod_ctrls/0.9.5: unable to open ControlsLog '/var/log/proftpd/controls.log': Permission non accordée
2020-02-26 22:51:48,231 vps178370 proftpd[22647]: fatal: ControlsLog: unable to open '/var/log/proftpd/controls.log': Aucun fichier ou dossier de ce type on line 126 of '/etc/proftpd/proftpd.conf'
+++ exited with 1 +++
```

Still researching to figure out what's wrong.

**Comment by Castaglia** [comment]
@ZerooCool please provide the output from `proftpd -V`.

Also, it's usually considered rude to just re-open an existing ticket.  Best is to open a _completely new_ ticket, with your details; the tickets can be associated later if needed.  But overloading/reusing a ticket causes too many different behaviors/symptoms to be conflated together that may not actually be related.

**Comment by ZerooCool** [comment]
Ok, that's why I actually reopened.
I misspoke, (French -> English) the idea being to mention the issue, which I did despite everything with the hashtag.

I wanted to say "follow-up" or "even problematic" while bearing well on the fact that this error which seems known, does not seem to find an answer on the referenced exchanges, on google.

From my readings, this problem is mentioned in many places on the web, arch, fedora, debian, ubuntu, sourceforge, and, nobody seems to offer any answer.

I indicated reopen because it seemed to me that the problem had not been fixed in issue 501 (I can be wrong because I have not read the code modifications) in any case, it is not not mentioned a solution in discussion 501.

I can rename the title, without the reopen.

If you need additional information, I remain available to follow this issue.

**Comment by Castaglia** [comment]
The important information needed is the `proftpd -V` output.  Many different distributions provide different versions of ProFTPD; it is possible that you are running a version which does *not* have the fix.  That's why the `proftpd -V` output, _for your case_, is important.

**Comment by ZerooCool** [comment]
Ok -> https://pastebin.com/SNzb6ZsW

I notice in my research that I wanted to create a socket file like a text file but that it is not possible thus. I read i need use socat package but i don't understand if it's the good way.

I notice that in my configuration, the url which points to the socket does not exist :
`/var/run/proftpd/proftpd.sock`

In the end, I only have one file with  proftpd.socket 
`/run/proftpd.sock`

**Comment by Castaglia** [comment]
Can you also provide the `proftpd.conf` you're using?   This will help me reproduce the behavior locally.

**Comment by Castaglia** [comment]
ProFTPD 1.3.6 was released on April 9, 2017.  However, the _fix_ for the issue was not [merged to the 1.3.6 branch](https://github.com/proftpd/proftpd/commit/a3824adef09354e028bfcc4af28b30e3ae2ca924#diff-fbdaffa6c6b9aa7ebf0c666887dddd04) until May 14, 2017, _after_ 1.3.6 was released.

It is mentioned as being fixed in the [1.3.6a NEWS](http://www.proftpd.org/docs/NEWS-1.3.6a).  Thus, if possible, you might try using a newer version of ProFTPD 1.3.6.

**Comment by ZerooCool** [comment]
I tried to investigate a little further by reading many resources related to this error message.

I learned little, even see, learned nothing and discovered nothing.

On the other hand, I discover for myself by observing the structure of ProFTPd, which I know very little.

I think I just discovered something interesting!
I think I don't have this famous module! " mod_ctrls "

But, if i don't have this module, the warning is not correct, first, i need a " mod_ctrls not exist ? "

mod_ctrls/0.9.5: error: unable to bind to local socket: Address already in use

You can see here my modules :
https://wiki.visionduweb.fr/index.php?title=Installer_et_utiliser_un_serveur_proFTPd_pureFTPd_vsFTPd#Gestion_des_modules_de_ProFTPd

I come back, 5 minutes, with my config.

**Comment by ZerooCool** [comment]
How to use the new version ?
Would the debian buster package take care of the latest fixes ? ( I think not )
Or, I need to make compile from source ? ( Not really my priority )

**Comment by Castaglia** [comment]
I don't know when/how different distributions decide to provide updated versions of ProFTPD packages; that is outside the scope of the ProFTPD Project.

**Comment by ZerooCool** [comment]
Ofcourse.

I have add my config before.

Important question for me, can you confirm, please :

Have you a file.sock here ? I don't have any !
 /var/run/proftpd/proftpd.sock

Have you a mod_ctrls in cd /usr/lib/proftpd
Have you a mod_ctrls ?
I have only a mod_ctrls_admin.so

**Comment by ZerooCool** [comment]
mod_ctrls is not present for my current version of ProFTPD 1.3.6 installed on Debian Buster 10.

Still the same problem, so I can't use SFTP.
I still don't know how to use mod_ctrls which is not present when installing Debian proftpd-basic package.

**Comment by Castaglia** [comment]
I'm not sure how this "unable to bind to local socket" message prevents use of SFTP?

Can you install ProFTPD from source, rather than using the package?  @hpreusse does this happen for you?

**Comment by hpreusse** [comment]
> mod_ctrls is not present for my current version of ProFTPD 1.3.6 installed on Debian Buster 10.
> 
> Still the same problem, so I can't use SFTP.
> I still don't know how to use mod_ctrls which is not present when installing Debian proftpd-basic package.
> 
If you look at the [build log](https://buildd.debian.org/status/fetch.php?pkg=proftpd-dfsg&arch=arm64&ver=1.3.6-4%2Bdeb10u5&stamp=1588365907&raw=0) you'll notice that the module is compiled, but statically linked into the proftpd binary. So theer is no need to search for the module: it is already activated.

**Comment by ZerooCool** [comment]
Anyway, the module does not appear in the list of modules.
I do not know more, I will soon share the next error that I would encounter, following my experiments.

**Comment by Castaglia** [comment]
What does `proftpd -l` show?

**Comment by ZerooCool** [comment]
sudo proftpd -l
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_ident.c
  mod_auth_pam.c
  mod_cap.c
  mod_ctrls.c
  mod_lang.c

**Comment by hpreusse** [comment]
> I'm not sure how this "unable to bind to local socket" message prevents use of SFTP?
> 
> Can you install ProFTPD from source, rather than using the package? @hpreusse does this happen for you?
> 
Sorry, late response! I configured SFTP acoording to [this manual](https://www.digitalocean.com/community/tutorials/how-to-configure-proftpd-to-use-sftp-instead-of-ftp) and it worked like a charm. This is an Raspberry Pi using Raspbian, but the proftp version is the same as on Debian stable. I don't have an /var/run/proftpd/proftpd.sock, if that hurts you. I don't have an mod_ctrls as it is compiled into the binary. Hope this helps.

**Comment by Castaglia** [comment]
If there's no further details/reports of this issue with more recent releases, I'd like to close it.
