### ISSUE TITLE
Password issues with auth file from older version?

### ISSUE THREAD

**Issue by badbob001** [proftpd/proftpd#982]
I'm moving proftpd settings to a new server using the old auth file (mod_auth) but some users can not login.

Old version: 1.3.2d
New version: 1.3.6c

I think a clue is with the password hash for the users:

1. works: $1$<8-char-string>$<22-char-string>
2. not work: $1<11-char-string>
3. not work: <13-char-string>

From my research:

1. Looks to be md5-based + salt. These are recent users and the hash should be generated by ftpasswd.
2. Seems like md5 but not sure how they were generated.
3. 13-character length seems to indicate des hash. Not sure how it was generated.

How would I get the new system to accept logins using the older-style hashes? I know there may be security issues with the older hash types but the old server is going away very soon and that is a more pressing concern.

Thanks!

**Comment by Castaglia** [comment]
The `mod_auth_unix` module uses the platform-provided [`crypt(3)`](https://linux.die.net/man/3/crypt) library function.  Is it possible that the new server's `crypt(3)` function no longer supports the older format?

**Comment by badbob001** [comment]
Left out some details:
auth used: AuthOrder mod_auth_file.c
old proftpd version: 1.3.2d
new proftpd version: 1.3.6c
/proc/sys/crypto/fips_enabled is set to 0

Any suggestions on how to test what is supported by the system's crypt(3)?

**Comment by Castaglia** [comment]
In this case, it's not the ProFTPD versions that matter, so much the Unix distribution/platform versions on the old and new server, _i.e._:
```
$ uname -a
$ cat /etc/redhat-release
$ cat /etc/lsb-release
```
or whatever, can be used to identify the Unix versions.  _That_ is what will help inform just what the capabilities of the system-provided `crypt(3)` function are.

**Comment by badbob001** [comment]
old server:
> cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"

new server:
> cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

**Comment by badbob001** [comment]
I've gotten more insight on the issue. The hashes that are $1<11-char-string> are actually des hashes using '$1' as the salt. I was able to recreate the hash with: openssl passwd -crypt -salt '$1'.

Maybe the starting '$' character is making the mod_auth_file not think it's a des hash?

**Comment by Castaglia** [comment]
The `mod_auth_file` module does not introspect the hash or values (unless FIPS is enabled, and then only to log warnings for admins); it simply gives the field as-is from the `AuthUserFile`, and the user-provided password, to `crypt(3)`, and compares the results.

What is the specific ProFTPD [debug logging](http://www.proftpd.org/docs/howto/Debugging.html) generated for one of these failed logins?

**Comment by badbob001** [comment]
Created account des hashed password and two-letter salt: works. With same password des hashed but using '$1' instead for salt: can't login.

Ran with debug: proftpd -nd10 2>&1 >& /path/to/debug/file and the login attempt only shows only this:

> 2020-04-16 18:00:17,817 xxxxxxxx proftpd[64744] xxxxxxxx (yy.yy.yy.yy[yy.yy.yy.yy]): FTP session opened.
> 2020-04-16 18:00:18,594 xxxxxxxx proftpd[64738] xxxxxxxx: ROOT PRIVS at mod_ctrls.c:727
> 2020-04-16 18:00:18,594 xxxxxxxx proftpd[64738] xxxxxxxx: RELINQUISH PRIVS at mod_ctrls.c:733
> 2020-04-16 18:00:23,805 xxxxxxxx proftpd[64744] xxxxxxxx (yy.yy.yy.yy[yy.yy.yy.yy]): USER brokenuser (Login failed): Incorrect password
> 
Full debug log attached.
[proftpd_debuglog_20200416.txt](https://github.com/proftpd/proftpd/files/4489094/proftpd_debuglog_20200416.txt)

There is also a separate log for AUTH, but it only shows:
> xxxxxxxx Global Extranet FTP Server [64744] xx.xx.xx.xx [16/Apr/2020:18:00:20 +0000] "USER brokenuser" 331
> xxxxxxxx Global Extranet FTP Server [64744] xx.xx.xx.xx [16/Apr/2020:18:00:23 +0000] "PASS (hidden)" 530

Could somewhere the $1 portion of the password hash be incorrectly interpreted as a variable instead of a string? I certainly need to use single quotes when using '$1' as a salt in openssl commands.

**Comment by Castaglia** [comment]
No, ProFTPD is not an interpreter; it handles the strings as-is.

Do you have Perl installed on the newer host?  I can provide some Perl commands, if so, to help demonstrate where the issue might be.

**Comment by badbob001** [comment]
I see Perl 5.26.1 installed. Thank you for taking some of your time for this.

**Comment by Castaglia** [comment]
No, as I said, ProFTPD is not an interpreter.  It does not treat `$` as a special character; it's just a character like any other one.  Thus quoting, escapes, _etc_ will not change the behavior.

The behavior of `crypt(3)` has changed over time, as various libraries and parties have sought to enable new algorithms (newer than DES), _e.g._ MD5, SHA1, SHA256, Argon2, _ etc etc_ into the same interface:
```
char *crypt(const char *password, const char *salt);
```
And the only way they found to do so was by fiddling with the "format" of the `salt` string.  Like using `$` as a delimiter, so that `salt` could contain multiple fields.

A `$1$` prefix of the `salt` value thus helped differentiate an MD5-hashed value from the traditional (archaic) DES; for DES, the `$` character in the `salt` value is _invalid_.  Similarly, a `$5$` prefix indicated SHA256, `$6$` indicated SHA512, and `$2$` (and `$2a$`, `$2b$`, and `$2y$`) all [indicated bcrypt](https://github.com/proftpd/proftpd/blob/master/lib/openbsd-bcrypt.c#L86).  You can see some of this in `ftpasswd`'s [`get_salt`](https://github.com/proftpd/proftpd/blob/master/contrib/ftpasswd#L468) function.

**Comment by badbob001** [comment]
When someone logs in and enters their username and password, does the os then ask proftpd to provide the hash string of the user,  the os looks at the provided hash string to determine the hash info (type, salt, hash), the os hashes the password the same way, and then send back the hash-comparison/login result to proftpd?

Would there be an alternative mod_auth module that hashes the login passwords itself? Then maybe it'll handle illegal salt characters differently or can be adjusted to do so.

**Comment by Castaglia** [comment]
When a user attempts to log in, `mod_auth_file` looks up the fields in the `AuthUserFile` for the given username.  One of those fields is the password hash (from _e.g._ `ftpasswd`).  The module then calls `crypt(3)` with the client-provided password, _and_ the hash value.  The `crypt(3)` function will _assume_ that the given hash is the _salt_ to use (including algorithm identifier); it will return a password hash using the indicated algorithm and salt values.  If the returned password hash matches exactly what was in the `AuthUserFile` field for that user, login succeeds.

All of the above is done by ProFTPD; the OS is not involved.  The "platform" involvement is all in that `crypt(3)` function call.

**Comment by Castaglia** [comment]
From the two non-working cases you have:
> not work: $1<11-char-string>
> not work: <13-char-string>

It sounds like the `crypt(3)` function, on your new server, no longer supports the archaic DES format.  (Note, that the `$1` prefixed strings are *not* valid MD5 password hashes, _nor_ are they valid DES passwords hashes; I wonder where they came from?)

How many of these non-working password hashes do you have?  Would it be easier if those users generated new passwords (which is not a bad idea, to rotate/update new passwords periodically), and in doing so, use newer password hashing algorithms?

**Comment by Castaglia** [comment]
@badbob001 there might be a way to auto-generate new password hashes, but it would require a custom module, and building ProFTPD from source.  If you think you may need to explore this route, please contact me directly via email.

**Comment by Castaglia** [comment]
See Issue #1228 for a similar request; I've been working on https://github.com/Castaglia/proftpd-mod_passwd_update to implement this feature.
