### ISSUE TITLE
Do not send EXT_INFO to SSH clients which did not signal "ext-info-c"

### ISSUE THREAD

**Issue by ppazera** [proftpd/proftpd#984]
### What I Did

After upgrading proftpd to the latest sources SexureBlackBox library stopped working because it does not recognize EXT_INFO (7) packets and disconnects. I found NoExtensionNegotiation mod_sftp option and it helped, but that doesn't sound like correct solution because other clients may want to use extension negotiation

### What I Expected/Wanted

I think server should not send EXT_INFO when client does not signal "ext-info-c". I found couple related places in RFC8308:

> 
> 2.1.  Signaling of Extension Negotiation in SSH_MSG_KEXINIT
> 
>    Applications implementing this mechanism MUST add one of the
>    following indicator names to the field kex_algorithms in the
>    SSH_MSG_KEXINIT message sent by the application in the first key
>    exchange:
> 
>    o  When acting as server: "ext-info-s"
> 
>    o  When acting as client: "ext-info-c"

and

> 2.2.  Enabling Criteria
> 
>    If a client or server offers "ext-info-c" or "ext-info-s"
>    respectively, it MUST be prepared to accept an SSH_MSG_EXT_INFO
>    message from the peer.
> 
>    A server only needs to send "ext-info-s" if it intends to process
>    SSH_MSG_EXT_INFO from the client.  A client only needs to send
>    "ext-info-c" if it plans to process SSH_MSG_EXT_INFO from the server.
> 
>    If a server receives an "ext-info-c", or a client receives an
>    "ext-info-s", it MAY send an SSH_MSG_EXT_INFO message but is not
>    required to do so.

### ProFTPD Version and Configuration

    $ proftpd -V

```
Compile-time Settings:
  Version: 1.3.7rc4 (git)
  Platform: LINUX [Linux 4.12.14-197.34-default x86_64]
  Built: Wed Apr 15 2020 00:15:44 PDT
  Built With:
    configure  '--enable-dso' '--enable-ctrls' '--enable-facl' '--disable-ident' '--enable-nls' '--with-lastlog' '--with-shared=mod_auth_otp:mod_ban:mod_copy:mod_ctrls_admin:mod_deflate:mod_digest:mod_dnsbl:mod_dynmasq:mod_exec:mod_ifsession:mod_ifversion:mod_ldap:mod_load:mod_log_forensic:mod_qos:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_radius:mod_ratio:mod_readme:mod_rewrite:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_site_misc:mod_snmp:mod_sql:mod_sql_mysql:mod_sql_odbc:mod_sql_passwd:mod_sql_postgres:mod_sql_sqlite:mod_statcache:mod_tls:mod_tls_fscache:mod_tls_memcache:mod_tls_redis:mod_tls_shmcache:mod_unique_id:mod_wrap2:mod_wrap2_file:mod_wrap2_redis:mod_wrap2_sql'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic  -L/usr/lib64 -L/usr/lib/postgresql10/lib64
  LIBS: -lacl  -lssl -lcrypto -lcap  -lpam -lsupp -lattr -lresolv -lresolv -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    + OpenSSL support (OpenSSL 1.1.0i  14 Aug 2018, FIPS enabled)
    - PCRE support
    + POSIX ACL support
    - Redis support
    + Shadow file support
    + Sendfile support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

In addition, we need to see *all* of the ProFTPD configuration files you are
using (*minus* any sensitive information like passwords, of course).  Armed
with the version and configuration data, then, we can set up ProFTPD locally
using the same configuration, and see what happens.

**Comment by Castaglia** [comment]
For reference, the use of `EXT_INFO` messages was added in Issue #907 , so this is very recent, not yet released behavior.

**Comment by Castaglia** [comment]
@ppazera can you verify that https://github.com/proftpd/proftpd/pull/985 addresses the issue for your client/use case?

**Comment by ppazera** [comment]
@Castaglia yes, now it works without NoExtensionNegotiation option. Thanks again for promptly addressing this
